### ISSUE TITLE
TTS Rate on Mac OS client only does not update

### ISSUE THREAD

**Issue by masonasons** [BearWare/TeamTalk5#1004]
Ever since TeamTalk 5.8 which has added TTS support for all platforms, the Mac OS version has a bug where the rate slider does not change the TTS rate at all. Volume slider works fine. This problem does not happen on Linux or Windows. It would be great if this could be fixed.

**Comment by bear101** [comment]
When I change "Voice Rate" in TeamTalk v5.8.2 BETA1 I don't see this issue.

**Comment by masonasons** [comment]
still have this issue on the beta with both macs, intel and M1

**Comment by pitermach** [comment]
I can also still confirm this in 5.8.2 on my M1 Mac with Monterey.

A potential workaround that could be used here is sending an embedded speech command to the synthesizer to force the rate to change. You can send `[[rate xxx]]` to the synthesizer, where xxx is a number to specify the rate in words per minute (a minimum of 150 and a max of 800 should give everyone something they're happy with). You can already test this, if someone chats a message with such a command it'll change TeamTalk's rate for the session.

**Comment by TheQuinbox** [comment]
So, update. This only happens with Macintalk voices (e.g. Alex). Vocalizer voices (e.g. Samantha), work fine.
