### ISSUE TITLE
Inconsistent behaviour with tt-files and tt-URLs

### ISSUE THREAD

**Issue by Michael1972** [BearWare/TeamTalk5#1005]
When opening a tt-file or URL on PC or mac, teamtalk 5.8 QT, teamtalk correctly enters the channel, that the file or url is pointing to. After closing the application, when the conference is finished, and reopening manually  later via desktop or quick launch icon, teamtalk  obviously overwrites the settings, configured in the preferences, and  always returns to the  tt-file / url channel. We are running a server with many blind users and provide tt-files and urls, making it easier for them to enter special channels. The teamtalk clients are configured to always connect to the last server, joining its main-channel. So, users enter special channels for special topics via tt-file, but expect to return to the main-channel for normal conversation after  later normal reboot, and get confused, because they always land in the channel from the last used tt-file / url. Entering the main-channel, configured in the preferences, only is possible by manual navigation, tha can be overwhelming for beginners. Is that normal behaviour or a bug? Thanks.

**Comment by bear101** [comment]
The checkbox in "Preferences->Connection" states to "Reconnect to latest host". It would be very confusing if "latest host" was everything except tt-files and tt-URLs. This would create at least the same amount of cunfusion as the scenario that you describe.

I would suggest you send two TT-files to users. One with main-channel and another TT-file for your other channel. Then users should use these as entry points and not some automatic setting.
