### ISSUE TITLE
NVDA being silent when pressing tab after the chat edit field

### ISSUE THREAD

**Issue by StormProductionsMusic** [BearWare/TeamTalk5#1006]
Hi,

Everytime when pressing TAB after the message edit field, NVDA goes silent instead of focusing on a specific channel like it did on the Classic client. Arrows do announce the channels, but it would be easier if NVDA would just focus on the latest focused channel everytime you tab after the message field.

**Comment by ChrisDuffley** [comment]
Unfortunately, @bear101 can't solve this issue directly. It's a Qt issue.

**Comment by bear101** [comment]
@Oreonan I've created a new label named "Qt accessibility" for issues that are caused by issues with Qt. Can this issue be closed with that label?

**Comment by Oreonan** [comment]
Yes, we can't solve it ourself.
