### ISSUE TITLE
Closing main window with a private chat open doesn't quit TeamTalk

### ISSUE THREAD

**Issue by pitermach** [BearWare/TeamTalk5#1037]
QT TeamTalk 5.8.1. on both Windows and Mac.

Steps to reproduce:

- Connect to a server
- - Initiate a private chat with another person
- - With their chat window still open, return to the main TeamTalk window and press Alt+F4/COmmand+Q to quit
Expected behavior: Both the main and chat windows close and Teamtalk quits. This is how the classic client behaves.
Actual result: While the main window closes, the private chat remains open. As long as this is the case, you are still connected to the server, so if you were transmitting sound you'll continue to do so. Additionally, although on Windows pressing Alt+F4 in a chat causes it to close, pressing command+Q on a Mac while a chat window is focused does absolutely nothing and the only way to close it is to press the "Cancel" button.

This issue is rather serious and could unintentionally lead to dangerous situations where someone might not be aware they are actually still connected to a server.

**Comment by bear101** [comment]
I've fixed this issue. I also found it annoying that you had to go through all TeamTalk windows before closing.
