### ISSUE TITLE
TT Server Api: cannot list user accounts, channels and files

### ISSUE THREAD

**Issue by beqabeqa473** [BearWare/TeamTalk5#1051]
hello.

I started to experiment of server part TeamTalk5 development.

could you tell me, how it is possible to send out information of online users, useraccounts, channels and files to clients on request?

i didn't find methods in api for that.
or maybe uthese objects should be added somehow otherwise?

note that i am trying to use dotnet example for now.

thanks.

**Comment by beqabeqa473** [comment]
Yes, i already read documentation and tried an example.

there is no way what i read to send response back on list accounts,
list channels, files etc.

maybe i missed some parts?

could you please give me a right direction?

thanks.

On 10/10/21, Bjørn Damstedt Rasmussen ***@***.***> wrote:
> Hi Beqa
>
> You can read the server API documentation
> [here](https://bearware.dk/teamtalksdk/v5.8b/docs/NET/group__serverapi.html).
>
> A .NET server example is available here:
> https://github.com/BearWare/TeamTalk5/tree/master/Server/TeamTalkServer.NET
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/BearWare/TeamTalk5/issues/1051#issuecomment-939524031


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by bear101** [comment]
Currently there's not a way to send accounts list back to the client.

The current list of channels is one you maintain yourself by handling OnChannelCreated-event. Likewise for files: OnFileUploaded-event.

**Comment by bear101** [comment]
I'm closing this issue for now.
