### ISSUE TITLE
Problem opening tt-files and URLs on android-devices

### ISSUE THREAD

**Issue by Michael1972** [BearWare/TeamTalk5#1062]
On android-devices, tt-files only can be opened by importing them into TeamTalk. TT-URLs have to be opened from within a browser. Could it be made possible, to open tt-files and tt-URLs, placed into an e-mail directly from within the  android-mail-client-window. So, users, receiving tt-URLs or files  via e-mail would have an easier access. On all other platforms,  (Windows, Mac OS, IOS), TT-URLs and tt-files can be opened directly within an e-mail-message or instant messenger window.

**Comment by xingkong013** [comment]
hi @CoBC 
Is this issue currently being addressed?
thanks

**Comment by beqabeqa473** [comment]
related to #1182

**Comment by bear101** [comment]
Duplicate #1182
