### ISSUE TITLE
teamtalk have a problem on windos 11

### ISSUE THREAD

**Issue by alireza1385mamani** [BearWare/TeamTalk5#1077]
Hi every one. How are you? I hope you will be good. actually I wanted to say thanks to the diveloper for making this good application. but it has a problem on windos 11 on the 5.8.1 release of teamtalk.
the problem is that when you open the application on windos 11 you will see this error.
Server Busy  dialog  This action cannot be completed because the other program is busy. Choose 'Switch To' to activate the busy program and correct the problem.
and there is a switch to and retry butten there but when you press on each of them you will see that nothing works right. and even if you run it with an administrater permition you will see that it has this error. the version of my teamtalk as I said is 5.8.1 and my windos is Windows 11 21H2 (x64) build 22000.258. I hope it'll be fixed soone.

**Comment by Oreonan** [comment]
Can't reproduce here with Win11 21H2 and TT 5.8.2

**Comment by bear101** [comment]
Please try with v5.8.2 and provide error information, like Event Viewer's Windows Logs. Then reopen issue.
