### ISSUE TITLE
Channel editing for channel creator operators only

### ISSUE THREAD

**Issue by alessio0292** [BearWare/TeamTalk5#1086]
Dear Bjoern, and all,
As I said in a previous message, the team talk program allows through an option that can be activated in the servers for users that allows users or administrators to create and modify all channels while, I propose and suggest another option that allows it is up to only the operators who create the channels to modify the channels created by the operators who create that channel. In this way the operator can create permanent channels, he can name other operators if he wants, he can change the number of users allowed in the channel, he can change the disk quota, he can change for example the properties of the audio decoder encoder and he can also change the transmission range for the audio encoder.
This option could be useful to those operators who, through an optional or definitive operator keyword, can modify their own channel instead of modifying all the other channels of other operators.
regards,
Alessio from Italy

**Comment by bear101** [comment]
Creating permanent channels is limited to users with ability to create/modify all channels.

**Comment by alessio0292** [comment]
pleas did you close this issue was a important suggestion!

Da: Bjørn Damstedt Rasmussen 
Data: lunedì 1 novembre 2021 17:26
A: BearWare/TeamTalk5 
Cc: alessio0292 ; Author 
Oggetto: Re: [BearWare/TeamTalk5] Channel editing for channel creator operators only (Issue #1086)

Closed #1086.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by alessio0292** [comment]
please delete or increase this limit only for operators creators of channels!

Da: Bjørn Damstedt Rasmussen 
Data: lunedì 1 novembre 2021 17:26
A: BearWare/TeamTalk5 
Cc: alessio0292 ; Author 
Oggetto: Re: [BearWare/TeamTalk5] Channel editing for channel creator operators only (Issue #1086)

Creating permanent channels is limited to users with ability to create/modify all channels.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by alessio0292** [comment]
please remove this limit. I have written two discussions regarding this thing with the ideas category.
