### ISSUE TITLE
in windows seven isn't possible to transmit media file in last versions i think from 5.5 but i'm not sure

### ISSUE THREAD

**Issue by alessio0292** [BearWare/TeamTalk5#1087]
Dear Bjoern and all,
In this moment I don’t want to update from seven to windows 10 and for this reason I’d like to transmit media files but since any versions isn’t possible. Who is the last version for windows seven where is possible to transmit media files?
For me now updating the versions is a problem now that I have got windows seven yet.
regards,
Alessio from Italy.

**Comment by bear101** [comment]
Windows 7 issues will not be fixed. It's obsolete

**Comment by alessio0292** [comment]
for me is not obsolete because I use windows 7 please I don’t like Your thing that You speak.

Da: Bjørn Damstedt Rasmussen 
Data: lunedì 1 novembre 2021 17:21
A: BearWare/TeamTalk5 
Cc: alessio0292 ; Author 
Oggetto: Re: [BearWare/TeamTalk5] in windows seven isn't possible to transmit media file in last versions i think from 5.5 but i'm not sure (Issue #1087)

Windows 7 issues will not be fixed. It's obsolete

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
