### ISSUE TITLE
media file link also in windows seven

### ISSUE THREAD

**Issue by alessio0292** [BearWare/TeamTalk5#1088]
Dear Bjoern and all,
In this moment i have got a computer with windows seven 64 bit. In team talk for windows 7 isn’t possible to transmit media file links for example radio links stream urls. Dear Bjoern and all, please put also transmission media files links in windows seven so if I’d like transmit links for example stream urls i can transmit also in windows 7.
regards,
Alessio from Italy.
p.s.: I written this message without a translator.

**Comment by bear101** [comment]
Windows 7 is obsolete and no longer supported by Microsoft. TeamTalk developers will not use extra time supporting an obsolete platform.
