### ISSUE TITLE
Voice activation feature for Android client

### ISSUE THREAD

**Issue by bear101** [BearWare/TeamTalk5#109]
http://www.bearware.dk/phorum/read.php?1,4331,4331#msg-4331

**Comment by beqabeqa473** [comment]
hi bjoern.

i've tried to implement this functionality however something went wrong.

why this piece of code doesn't work.

	ttclient.enableVoiceActivation(true);
ttclient.setVoiceActivationLevel(2);

for testing purposes i am trying to turn it on on event connectSuccess.

**Comment by bear101** [comment]
If I remember correctly then in order to save battery the sound input device is only active when we press push-to-talk button. If you want to use voice activation then the sound input device must be active all the time.

**Comment by bear101** [comment]
Check out method enableVoiceTransmission() in TeamTalkService.java

**Comment by beqabeqa473** [comment]
ok, a basic voice activation has been implemented.
it is a checkbox in preferences off by default.
one more setting should be added to configure activation level.

**Comment by beqabeqa473** [comment]
should go for now, i've pushed an initial implementation.

**Comment by beqabeqa473** [comment]
hi.

it seems i've accidentally made voice activation value to true.
i think it should be off by default.
also i think slider should be added to controll voice activation level.

i've updated to latest win10 and my git installation is now crashing.

bjoern, if you are planning to update tt on playstore, please change setting to false in xml, i'm very sorry, i can't push.
