### ISSUE TITLE
I report an error in team talk please, fix this error.

### ISSUE THREAD

**Issue by alessio0292** [BearWare/TeamTalk5#1090]
Dear Bjoern and all,
I report an error that I noticed in team talk as well in the classic version. Basically when I go to record a conversation or my voice in a channel on a server even if it is not allowed to record I can record the same. I also tried to activate the option that says in the channel that it is not allowed to store on the disc but I still keep recording on the disc as if it is possible to record. Usually if it is not allowed to record in the channel one cannot record instead, everyone can record the same. The setting of the server for users regarding the recording of conversations on the disk the same if it is disabled the user can always record conversations in the channels so it does not work.
please resolve this error and send you many greetings.
Alessio from Italy.

**Comment by bear101** [comment]
You can record but the recording will be silent. Reopen if this is not the case.

**Comment by alessio0292** [comment]
No Bjoern, is always possible to record because I don’t record others participants but my microphone I listen in a record with this option that i said in a message.

Da: Bjørn Damstedt Rasmussen 
Data: lunedì 1 novembre 2021 17:21
A: BearWare/TeamTalk5 
Cc: alessio0292 ; Author 
Oggetto: Re: [BearWare/TeamTalk5] I report an error in team talk please, fix this error. (Issue #1090)

You can record but the recording will be silent. Reopen if this is not the case.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by alessio0292** [comment]
No Bjoern, I can always record because even if I don't record the voice of the participants, I record my voice and my microphone.
