### ISSUE TITLE
transmission interval in opus codec from 0 ms

### ISSUE THREAD

**Issue by alessio0292** [BearWare/TeamTalk5#1092]
I'd like all that in team talk the interval trasmission is 0 ms and no 20 ms because I'd like to experiment to speak with people and my friends on team talk with a minimum value interval of 0 millisecond because I don't like transmit with minimum value of 20 ms.

**Comment by bear101** [comment]
20 msec interval is minimum in TeamTalk, since lower values may cause problems on some platforms.

**Comment by alessio0292** [comment]
Pleas You can’t decide all of team talk like you want! Dear Bjoern, transform the rogram in open source so We dedcided as You want team talk! Id like to try from 0 ms!

Da: Bjørn Damstedt Rasmussen 
Data: lunedì 1 novembre 2021 17:24
A: BearWare/TeamTalk5 
Cc: alessio0292 ; Author 
Oggetto: Re: [BearWare/TeamTalk5] transmission interval in opus codec from 0 ms (Issue #1092)

20 msec interval is minimum in TeamTalk, since lower values may cause problems on some platforms.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by alessio0292** [comment]
Please You can’t decide all of team talk like you want! Dear Bjoern, transform the program in open source so We decide as We want team talk!
