### ISSUE TITLE
I suggest team talk opensource program.

### ISSUE THREAD

**Issue by alessio0292** [BearWare/TeamTalk5#1093]
Dear All,
I'm very worried for team talk and the creator Bjoern because many things of team talk for example many problems that i reported, Bjoern decide always many things of this program and I don't like this thing is my opinion. Me for this thing i suggest team talk a open source program so many programmers can modify the program like the person wants and the programmers can put the things that a person wants.

**Comment by bear101** [comment]
Please keep discussions in https://github.com/BearWare/TeamTalk5/discussions
