### ISSUE TITLE
TeamTalk client announce both stable and beta update for 5.8.2

### ISSUE THREAD

**Issue by Nardol** [BearWare/TeamTalk5#1107]
Since TeamTalk 5.8.2 is stable, when launching TeamTalk, both stable and beta updates are notified, with the same version.
I have checked both stable and beta checkboxes but I should only had a notification for a stable update, not a beta one.
Of course when the stable version is installed, no update are presented as I now have the latest version.

**Comment by bear101** [comment]
Hm, I've modified the beta-check. If you use the v5.8.2.5053 (beta) then you shouldn't get a beta notification.

**Comment by bear101** [comment]
Does it work as expect now?

**Comment by Nardol** [comment]
> Does it work as expect now?

Yes, it works as expected now. Thanks!
