### ISSUE TITLE
problem in windows 10 from classic team talk version 5.7 and later. 

### ISSUE THREAD

**Issue by alessio0292** [BearWare/TeamTalk5#1108]
The problem I report is the following:
From the classic version of team talk5.7 when a person uploads a file, after the file is uploaded, it happens that the person drops off the server. This problem was not present in versions prior to 5.7. I believe that the problem does not occur in windows 10 home but certainly either in the professional or in some update.

**Comment by bear101** [comment]
I just uploaded to the TeamTalk 5 Official UK  server using Classic v5.8.2 64-bit. No issues.
