### ISSUE TITLE
Teamtalk QT treat right alt as ctrl+left alt

### ISSUE THREAD

**Issue by djgraco** [BearWare/TeamTalk5#1115]
Hello,
I'd like to report another bug. Version 5.8.2 client QT used, Windows 10 Pro 64 bit.
I don't know if this patch is possible to implement at all.
The point is that in the Classic teamtalk I could enter Polish diacritics in the chat with the right alt "ś" "ą"
I know that ctrl + alt + S in teamtalk turns on events for speech, but in Classic it was done so that you pressed left ctrl, left alt and S.
Namely, in QT, the right alt is treated as pressing ctrl + left alt and it is correct, but the operation of this function in Classic was different and I was able to enter Polish diacritics in the chat, because the right alt was treated as a different key.

**Comment by bear101** [comment]
Probably related to this issue: https://bugreports.qt.io/browse/QTBUG-69317?attachmentOrder=asc
Seems there's a plugin which can be enabled to fix it

**Comment by bear101** [comment]
Also: https://bugreports.qt.io/browse/QTBUG-83032

> As a workaround you can use the -platform windows:altgr command line argument to detect AltGr key. See documentation: https://doc.qt.io/qt-5/qguiapplication.html#QGuiApplication at Platform-Specific Arguments.

Does this fix the issue?

**Comment by djgraco** [comment]
Unfortunately, while I tried the run teamtalk5.exe with the argument i see it
Startup arguments  dialog  Program argument "-altgr" is unrecognized.

**Comment by djgraco** [comment]
Ohh, I maked a mistake. Argument is "-platform windows:altgr". With this right alt seems to be working well.
Thank you very much @bear101
Best Regards
DJ Graco

**Comment by bear101** [comment]
Ok, sounds good. I'll see how we can make this the default property on startup, so you don't need to pass the arguments.
