### ISSUE TITLE
teamtalk 5.8.2 for ubuntu 18 problem with downloaded archive

### ISSUE THREAD

**Issue by xogium** [BearWare/TeamTalk5#1120]
Hi,
the teamtalk 5.8.2 archive for ubuntu 18 has a small problem, where the languages directory is itself contained in a directory named languages, leaving all the languages unusable, until you move the content of the second languages directory into the first one.

**Comment by bear101** [comment]
Can you download the archive here and see if it also crashes? https://github.com/BearWare/TeamTalk5/actions/runs/1425552219
