### ISSUE TITLE
Bad container for recorded files ogg

### ISSUE THREAD

**Issue by djgraco** [BearWare/TeamTalk5#1129]
Hello,
the problem is with teamtalk QT 5.8.2, but it was also present in earlier versions.
Namely, when we record a conversation in the ogg format, the finished file is in the wrong container. It looks like we have an opus stream in an ogg container which is wrong and not all players will recognize such a file.
This should be done in an opus container. Below is a link to an example file recorded in this format
https://www.dropbox.com/s/dq4157gk70qa3nt/20211112-191306%20Conference.ogg?dl=1
Regards

**Comment by djgraco** [comment]
I forgot to add it, I am using Windows 10 PRO. I don't know about other platforms.

**Comment by bear101** [comment]
What wrong with the file? It looks fine and plays in VLC as well:
```
@ ffmpeg -i 20211112-191306\ Conference.ogg 
ffmpeg version 4.4.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with Apple clang version 13.0.0 (clang-1300.0.29.3)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.4.1_2 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-avresample --enable-videotoolbox
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, ogg, from '20211112-191306 Conference.ogg':
  Duration: 00:00:26.92, start: 0.000000, bitrate: 110 kb/s
  Stream #0:0: Audio: opus, 48000 Hz, stereo, fltp
At least one output file must be specified
```

**Comment by djgraco** [comment]
OK, the problem seems to be solved. The file seems to be created with the wrong extension because my player (Winamp) treated it as an ogg worbis and not an opus, but the file itself actually looks okay and is in a good container.
After changing the extension to opus, everything plays fine. It would be possible to create a patch for the next version that would replace the extension from ogg to opus so that all players would recognize the file correctly, as there is no ogg worbis stream there.

**Comment by bear101** [comment]
This is a bug in WinAMP. You should take it up with them
