### ISSUE TITLE
Headset TX toggle doesn't work in iTeamTalk

### ISSUE THREAD

**Issue by bear101** [BearWare/TeamTalk5#1136]
Seems TX toggle using headset is no longer working on iOS 15.

**Comment by ChrisDuffley** [comment]
It did with 5.8.1/2 and earlier. What you'd do is use the Play/Pause function for turning off Push-to-Talk, then the Next Track function to re-enable it. That's how I've done it. So, a single press for off and double press for on.

Christopher Duffley

Host of Mission Possible Podcast <http://www.missionpossiblepodcast.com/>

LINKS TO SUBSCRIBE:

iTunes <https://itunes.apple.com/us/podcast/mission-possible-christopher/id1103092109?mt=2> | Stitcher <http://www.stitcher.com/s?fid=88094&refid=stpr> | Google Play <https://goo.gl/app/playmusic?ibi=com.google.PlayMusic&isi=691797987&ius=googleplaymusic&link=https://play.google.com/music/m/Ik76dexklcprwnpuxbdr2s6bm3y?t=Mission_Possible_with_Christopher_Duffley> | Follow Podcast On TuneIn And Listen To Latest Episode <http://tunein.com/radio/Mission-Possible-With-Christopher-Duffley-p892505/>

LIKE/FOLLOW Me:

Facebook <http://facebook.com/christopherduffley> | Twitter <http://twitter.com/chrisduffley> | YouTube <http://youtube.com/christopherduffley> | Instagram <http://instagram.com/christopherduffley>

On Nov 15, 2021, at 14:20, Bjørn Damstedt Rasmussen ***@***.***> wrote:


Seems TX toggle using headset is no longer working on iOS 15.

**Comment by bear101** [comment]
When TT is mixing its sound with other apps (see #977) then the headset cannot send play/pause events to TT. This makes sense since mixed audio doesn't have an "owner".

**Comment by beqabeqa473** [comment]
Hi Bjoern.

Could you try to play a silence as it was done in android client to
identify teamtalk as an audio player?

maybe this will help.

On 11/18/21, Bjørn Damstedt Rasmussen ***@***.***> wrote:
> When TT is mixing its sound with other apps (see #977) then the headset
> cannot send play/pause events to TT. This makes sense since mixed audio
> doesn't have an "owner".
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/BearWare/TeamTalk5/issues/1136#issuecomment-972025038


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by bear101** [comment]
The problem that several apps share playback. So if you press "pause" then which app should pause?

**Comment by bear101** [comment]
Ability to use headset for TX toggle is now possible again in version v5.8.3 build 4. Note, however, when headset for TX toggle is enabled then audio cannot be mixed with other apps.
