### ISSUE TITLE
Problem opening a new instance on Teamtalk 5.8.3

### ISSUE THREAD

**Issue by math65** [BearWare/TeamTalk5#1144]
Hi !

In the beta TeamTalk v. 5.8.3.5062, when you open a second instance, a bug report appears, here is the detail 👍
[Bug report.txt](https://github.com/BearWare/TeamTalk5/files/7610678/Bug.report.txt)

**Comment by bear101** [comment]
Is it an Apple M1? If so check out #1067

**Comment by math65** [comment]
Yes, it's an Apple M1 :)

**Comment by ChrisDuffley** [comment]
I have a separate problem relating to configs and things...a separate issue will be open soon on this. I can't do anything with my own INI anymore, see next issue for details.
