### ISSUE TITLE
Bugs audio in TT 5.8.3 Beta 3 iOS

### ISSUE THREAD

**Issue by math65** [BearWare/TeamTalk5#1146]
Hi,

I noticed several audio bugs in the latest Teamtalk Beta for iOS.

* When you connect a bluetooth headset to the iPhone and the preprocessing is disabled, the sound comes out on the iPhone.
* When listening to the sound on the iPhone earpiece, (top speaker), Preprocessing does not work.

Tell me if you need more details :)

**Comment by RichBeardsley2001** [comment]
It also doesn't save your mic settings. So if you select stereo, it will be in stereo, but then it will turn off when you close the app.

**Comment by RichBeardsley2001** [comment]
I'm still having the problem with the bluetooth headphones in the latest update.

**Comment by bear101** [comment]
@math65 Have you enabled Speaker Output? This will override your Bluetooth headset

**Comment by math65** [comment]
Yes, I have.
But before this problem did not occur

**Comment by RichBeardsley2001** [comment]
I tried disabling speaker output with no luck. It stopped playing through the headphones and went to my earpiece.
And would it be possible to give us a setting that lets us choose not to use the mic on our headphones? I know that Android devices have that option for when you're using bluetooth headphones. The only way I can get bluetooth headphones to work is if I don't choose stereo. The app uses the mic on my headphones, and then the audio is compressed and everything is in mono.

**Comment by math65** [comment]
Yes, that it would be a great function! Currently with a Bluetooth headset it's in Mono...

**Comment by bear101** [comment]
v5.8.3 Build 4 is out which modifies the behaviour of preprocessing. Please create new issue if behaviour is not as expected.
