### ISSUE TITLE
Move users from the online users dialog to a specific channel

### ISSUE THREAD

**Issue by StormProductionsMusic** [BearWare/TeamTalk5#1167]
### Description

Hi,

In the classic version of TeamTalk, there was a feature that lets you move an user that is just online and not in any channel (online users dialog) to a specific channel. You had the move option both in the context menu, and by using the ctrl+alt+x and ctrl+alt+v shortcuts.
For now, this option seems to be unavailable in the QTClient.
Please do let me know if it's planned to be added or maybe it's not a priority now.

Thanks.

### Application

- [X] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkServer

**Comment by ChrisDuffley** [comment]
Actually it's already there. The Alt Ctrl X keystroke was not added to that, which is actually a bad idea to keep out of the Online Users dialog. It's of course fine with the main channels list.

Christopher Duffley
Host of Mission Possible Podcast: http://www.missionpossiblepodcast.com
Cell: +1 (603) 851-6971

Sent from my iPhone 12 Pro Max

On Dec 13, 2021, at 07:28, StormProductionsMusic ***@***.***> wrote:

﻿
Description

Hi,

In the classic version of TeamTalk, there was a feature that lets you move an user that is just online and not in any channel (online users dialog) to a specific channel. You had the move option both in the context menu, and by using the ctrl+alt+x and ctrl+alt+v shortcuts.
For now, this option seems to be unavailable in the QTClient.
Please do let me know if it's planned to be added or maybe it's not a priority now.

Thanks.

Application

 qtTeamTalk
 TeamTalkAndroid
 iTeamTalk
 TeamTalkServer

**Comment by StormProductionsMusic** [comment]
Okay, so what’s you’re saying is that the feature I’m requesting is already there? Ifs so, how do I move an user that’s not on any channel?
I know that you can do this from the channels list, but my suggestion is that you could do it from the Online Users dialog as well.
Thanks.

**Comment by CoBC** [comment]
This feature was introduced in TT 5.8.2. Now the context menu of users in "Online users" dialog has an option "Select for move". You have to open the context menu and use this item to select people to move, after that close "Online users" dialog and press CTRL-Alt-V in wanted channel. The CTRL-Alt-X shortcut isn't implemented in "Online users" dialog.

**Comment by StormProductionsMusic** [comment]
Hi,

It's weird how I didn't notice that until now. I mean, I did press the context menu on an user before and I didn't notice it for some reason, Sorry, and thanks anyway.
