### ISSUE TITLE
Discord-like Deafen Feature

### ISSUE THREAD

**Issue by StormProductionsMusic** [BearWare/TeamTalk5#1168]
### Description

Hi,

We recently had one such case where a person we were talking to on the server went somewhere away from their phone, but forgot to turn off their Master volume, and we could be heard all over their house because they didn't have headphones plugged in. 
That's where I got the idea to have a feature where a server admin can turn off someone's Master volume without them doing anything. In Discord, this feature has been implemented for a very long time and has been very successful, making it used quite often there.

How I see it implemented? Well, near each user, where all those checkboxes are, a new one could appear with something like "Master Volume", which would let you toggle users' master volumes. Same could be applied to the ctrl+alt+something shortcuts, where this one could be ctrl+alt+w for example as it's more related to the first one where you can mute the users' microphone.

What do you think about this type of function?

Thank you.

### Application

- [X] qtTeamTalk
- [X] TeamTalkAndroid
- [X] iTeamTalk
- [X] TeamTalkServer

**Comment by bear101** [comment]
You can use Transmit Control to stop someone from transmitting to the 
channel.

--
Kind regards

Bjørn Damstedt Rasmussen
www.bearware.dk

**Comment by CoBC** [comment]
If I understand correctly, the idea isn't to disallow an user to transmit, but an option to mute master volume for a specific user, basically simulate a CTRL-M in user side, but by an admin.

**Comment by bear101** [comment]
Ok, well, I don't think an admin should be able to take control of 
another person's computer.

--
Kind regards

Bjørn Damstedt Rasmussen
www.bearware.dk

**Comment by StormProductionsMusic** [comment]
Hi,The idea is not to let someone control another user’s computer, the thing is to simulate a ctrl+M keypress when someone is AFK and we want to make this person not hear us when it returns. Of course this could be added as a permission as well like “The user can deafen other users”, which would be a checkbox.

**Comment by bear101** [comment]
Simulating key press on another computer is taking control.

I would never enable this option on my computer because I don't want people to modify my client application's settings. This would create a flood of support emails because people cannot figure out why they cannot hear other people.

**Comment by StormProductionsMusic** [comment]
I can’t agree with you here. Discord has this feature for years and they never had trouble with it. If you don’t want to simulate keypresses, you can do like Discord and do it server-side same as the transmission toggle, so that you can simply stop the transmitting of sounds to the recipient. Other ways also are ok – I’d love to see this implemented.
