### ISSUE TITLE
Channel editing for channel creator operators only

### ISSUE THREAD

**Issue by alessio0292** [BearWare/TeamTalk5#1169]
### Description

Dear Bjoern, and all,
As I said in a previous message, the team talk program allows through an option that can be activated in the servers for users that allows users or administrators to create and modify all channels while, I propose and suggest another option that allows it is up to only the operators who create the channels to modify the channels created by the operators who create that channel. In this way the operator can create permanent channels, he can name other operators if he wants, he can change the number of users allowed in the channel, he can change the disk quota, he can change for example the properties of the audio decoder encoder and he can also change the transmission range for the audio encoder.
This option could be useful to those operators who, through an optional or definitive operator keyword, can modify their own channel instead of modifying all the other channels of other operators.
regards,
Alessio from Italy.
Is a message that i written in a e-mail old e-mail and i did many discussions for this thing that i suggest many times.
please, is a important suggestion!
please delete or increase this limit only for operators creators of channels!
please remove this limit. I have written two discussions regarding this thing with the ideas category.

### Application

- [ ] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkServer

**Comment by alessio0292** [comment]
i'd like this thing in team talk classic because the qt for me that I'm blind is inaccessible with nvda and classic is the best version.

**Comment by alessio0292** [comment]
excuse me, also in team talk classic.

**Comment by CoBC** [comment]
1. Firstly, I think you can simply keep this subject in discussion #1102, this issue is a duplicate.
2. The Qt client is perfectly usable with NVDA screenreader, I'm also blind and I use this version without any issue with NVDA.

**Comment by alessio0292** [comment]
hey did you close this issue? You didn’t have to close or you mustn’t close this issue.

Da: Corentin Bacqué-Cazenave 
Data: venerdì 17 dicembre 2021 16:10
A: BearWare/TeamTalk5 
Cc: alessio0292 ; Author 
Oggetto: Re: [BearWare/TeamTalk5] Channel editing for channel creator operators only (Issue #1169)

Closed #1169.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
