### ISSUE TITLE
Problem latest stable version of team talk qt client in windows 7.

### ISSUE THREAD

**Issue by alessio0292** [BearWare/TeamTalk5#1173]
### Description

Dear Bjoern, and all, 
I wanted to try on my pc with windows seven home premium 64 bit the new version of team talk in the normal qt version only that I have an error that tells me that microsoft win core winrt 1.0 is not present in the computer so I can only open the classic version but not I like it in this latest version because there are no features that I had reported in previous messages.
Best regards,
Also me, Alessio from Italy. 

### Application

- [X] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkClassic
- [ ] TeamTalkServer

### Platform

- [X] Windows
- [ ] macOS
- [ ] Android
- [ ] iOS
- [ ] Linux

### Expected behavior

the program doesn't open.

### Actual behavior

doesn't open.

### Steps to reproduce problem

The program doesn't open.

**Comment by bear101** [comment]
Duplicate #1139

**Comment by bear101** [comment]
I've changed a couple of things in the build process so it should now run on Windows 7:
Please try this version: http://bearware.dk/beta/TeamTalk_v5.9.2.5082_Setup.exe
