### ISSUE TITLE
QTTeamTalk: generalize updateTitle to use also in trayIcon

### ISSUE THREAD

**Issue by beqabeqa473** [BearWare/TeamTalk5#1174]
### Description

What do you think about generalizing updateTitle functionality to use also for trayIcon?
I am talking about that because user may have several instances of TT opened and in this case it is not a trivial task to identify which instance they want to be restored.

### Application

- [X] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkServer

**Comment by bear101** [comment]
Sounds like a good idea. You're welcome to add the feature. Please do a pull request so we can review the changes.

**Comment by beqabeqa473** [comment]
@bear101 done.
