### ISSUE TITLE
Use github actions cache for faster builds

### ISSUE THREAD

**Issue by beqabeqa473** [BearWare/TeamTalk5#1175]
### Description

Hello.

What do you think about using gh actions cache for faster builds?
For example instead of rebuilding qt framework everytime, we can cache it and build parts which were changed.

### Application

- [ ] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkServer

**Comment by bear101** [comment]
It would be a good idea to use a cache. Currently Qt is only built on version changes because it takes too long to build Qt.

**Comment by bear101** [comment]
Closing issue. Provide pull request instead.
