### ISSUE TITLE
Phone call-like transmission mode

### ISSUE THREAD

**Issue by Piciok** [BearWare/TeamTalk5#118]
MY idea is to work around the problem of what to do when the speaker is active and one would like to talk without echoing the channel sound back to everyone else. One way of overcoming this issue is to create a mode where placing the phone by the ear switches audio output to the earpiece just like with a regular phone call and enables TX.

**Comment by tech10** [comment]
Good idea, though such things can interfere with the screen reader's use of the proximity sensor.

**Comment by Piciok** [comment]
Unfortunately in this scenario screenreader can't be used but I suggest it as a workaround for when no headphones 
  are available and one just wants to talk so I assume this will be used just for short periods of time.

  ----- Original Message -----

**Comment by tech10** [comment]
Depending on the device used, turning the screen reader off and on again can be somewhat complex. From an accessibility standpoint, the option doesn't seem to be the best idea from my perspective. Perhaps a warning that interference with a screen reader is possible might be included with this option, if it's going to be added.

**Comment by Piciok** [comment]
As far as I know all it does to Talkback is silence it while it speaks. I don't think that should cause a lot of inconvenience.
  ----- Original Message -----

**Comment by tech10** [comment]
If TalkBack is using the proximity sensor to silence itself by you waving your hand over it, then another application uses the proximity sensor for something like what you're suggesting, the other app will take priority, leading to TalkBack speaking in your ear and possible activation of some items if you're not careful. It's happened to me before when using an application to automatically put the phone on speaker when pulled away from the ear. It's rather inconvenient and bothersome, so I'd guess TeamTalk doing as you suggest would have similar results.

**Comment by Piciok** [comment]
I use Whatsapp like that sometimes. The only drawback is Talkback going rather talkative when you touch the screen with your face.


  ----- Original Message -----

**Comment by tech10** [comment]
Yep, that's right, hence the warning about interference with TalkBack.

**Comment by beqabeqa473** [comment]
hi, i've done such thing in one of my apps called ventdroid, you can view it on playstore.
if you can look at it, i can do similar thing in teamtalk too

**Comment by Piciok** [comment]
Hello!

I have had a look at your app. This is pretty much what I've imagined it would be except it would also switch the audio to the earpiece apart from turning on TX, unless it already does that. I visited the public Ventrilo server and I didn't seem to be hearing anyone so couldn't check and the TX sounds as well as Talkback were coming out of my speaker.
  ----- Original Message -----

**Comment by beqabeqa473** [comment]
yes, ventdroid switches audio output to earpiece.
bjoern, does tt android sdk have possibility to select earpiece?

**Comment by bear101** [comment]
HAve you tried to toggle the AudioManager? I don't know if earpiece is a global setting or per audio stream. I would think it's a global setting

http://developer.android.com/reference/android/media/AudioManager.html

**Comment by beqabeqa473** [comment]
it is audiostream voicecall.
route_earpiece doesn't work from my tryings to make something.
only switching stream to voice_call works.

**Comment by beqabeqa473** [comment]
hi bjoern.

for this to work i was using audioTrack android api.
i didn't use native code to achieve this.
where streams can be switched here?

**Comment by bear101** [comment]
@beqabeqa473 Another developer told me that we can use the device's built-in echo cancellation by calling Audiomanager.setMode with the AudioManager.MODE_IN_COMMUNICATION argument.

**Comment by beqabeqa473** [comment]
yes, maybe this helps.

unfortunately, as i understand we don't have possibility to interract
with audio code.

On 6/10/16, Bjoern D. Rasmussen <notifications@github.com> wrote:
> @beqabeqa473 Another developer told me that we can use the device's built-in
> echo cancellation by calling Audiomanager.setMode with the
> AudioManager.MODE_IN_COMMUNICATION argument.
>
> ---
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/BearWare/TeamTalk5/issues/118#issuecomment-225012145


-- 
with best regards beqa

**Comment by beqabeqa473** [comment]
hi @Piciok 
i've just pushed what you said in this issue.

@bear101 could you review it?

**Comment by beqabeqa473** [comment]
it is at sensors branch

On 5/23/18, Bjoern D. Rasmussen <notifications@github.com> wrote:
> @beqabeqa473 where did you push it? Which commit?
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/BearWare/TeamTalk5/issues/118#issuecomment-391128563


-- 
with best regards beqa

**Comment by beqabeqa473** [comment]
hi bjoern.

so, what you will say, can it be merged to master, or it is something
to be done with it.

On 5/23/18, Beqa Gozalishvili <beqaprogger@gmail.com> wrote:
> it is at sensors branch
>
> On 5/23/18, Bjoern D. Rasmussen <notifications@github.com> wrote:
>> @beqabeqa473 where did you push it? Which commit?
>>
>> --
>> You are receiving this because you were mentioned.
>> Reply to this email directly or view it on GitHub:
>> https://github.com/BearWare/TeamTalk5/issues/118#issuecomment-391128563
>
>
> --
> with best regards beqa
>


-- 
with best regards beqa

**Comment by bear101** [comment]
@beqabeqa473 shouldn't it also dim the screen so touch is inactive? Otherwise your ear might touch buttons.

**Comment by bear101** [comment]
Sensors branch merged to TeamTalk v5.3.3 release

**Comment by beqabeqa473** [comment]
hi @bear101 

i cannot find a checkbox to control this feature.

maybe it has lost somewhere.

**Comment by bear101** [comment]
@beqabeqa473 You mean the Proximity Sensor?

**Comment by beqabeqa473** [comment]
yes

On 6/8/19, Bjørn Damstedt Rasmussen <notifications@github.com> wrote:
> @beqabeqa473 You mean the Proximity Sensor?
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/BearWare/TeamTalk5/issues/118#issuecomment-500028326


-- 
with best regards beqa

**Comment by bear101** [comment]
AFAIK this feature is supported now
