### ISSUE TITLE
QTTeamTalk: possibility to use convenience helpers for QInputDialog

### ISSUE THREAD

**Issue by beqabeqa473** [BearWare/TeamTalk5#1180]
### Description

Hello.

I don't know QTTeamTalk in details yet and am asking, is there any reason to use QInputDialogs as they are used now?

If not, maybe we can use convenience helper functions to cleanup code a bit, like this.
    bool ok = false;
    QString s = QInputDialog::getText(this, MENUTEXT(ui.actionChangeNickname->text()), TT_GetFlags(ttInst) & CLIENT_AUTHORIZED ? tr("Specify new nickname for current server") : tr("Specify new nickname"), QLineEdit::Normal, nick, &ok);

### Application

- [X] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkServer

**Comment by bear101** [comment]
What code are you referring to? QInputDialog is used many places.

**Comment by beqabeqa473** [comment]
I mean using helper functions instead of constructing dialogs by hand.

**Comment by bear101** [comment]
QInputDialog::getText() is a static function so it is in itself a helper function. It takes many arguments that could have been put in local variables but there's no need for it.
