### ISSUE TITLE
TeamTalk for Android crashes when uploading a file

### ISSUE THREAD

**Issue by Ramon-Salazar** [BearWare/TeamTalk5#1182]
### Description

Hi @bear101 When uploading a file no matter if it's an immage, an audio or video it immediately crashes, for the first time I thought it's an issue with my device but it appeared that it's the teamtalk issue, just tested in many android devices, same result.

Regards

### Application

- [ ] qtTeamTalk
- [X] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkClassic
- [ ] TeamTalkServer

### Platform

- [ ] Windows
- [ ] macOS
- [X] Android
- [ ] iOS
- [ ] Linux

### Expected behavior

it should upload a file but suddenly it crashes.

### Actual behavior

it crashes and the app dissappears.

### Steps to reproduce problem

1: selecting a file, 2, when uploading.

**Comment by bear101** [comment]
Phew, seems Google has once again changed their API... :(

**Comment by Ramon-Salazar** [comment]
Oh OK, though this happened since 3 weeks ago, before even the update 5.8.2

**Comment by beqabeqa473** [comment]
hi @bear101.

I think we should try to fix this issue, as it is practically impossible to work with files like streaming files and uploading/downloading files on android 11 and up.

I think the easiest way would be to declare ourselves as manageExternalStorage, but in this case we need to explain to google play why we are using that way or we should find another way to do that.

**Comment by bear101** [comment]
I'm not really familiar with Google's handling of file access. So if you think manageExternalStorage is the way to go then I would support it.

**Comment by lbk2907** [comment]
Hey @beqabeqa473 & @bear101, any update on this? Thanks.

**Comment by beqabeqa473** [comment]
Unfortunately, i don't have enough time to work on this.

On 5/20/23, lbk2907 ***@***.***> wrote:
> Hey @beqabeqa473 & @bear101, any update on this? Thanks.
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/BearWare/TeamTalk5/issues/1182#issuecomment-1555359662
> You are receiving this because you were mentioned.
>
> Message ID: ***@***.***>


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by Muamalaljanahi** [comment]
It is sad that we still unable to upload files despite this bug seemingly existing for a long time.

**Comment by poretsky** [comment]
I think, it may be closed, since #2184 fixes it as well.
