### ISSUE TITLE
suggestions of new features for the program.

### ISSUE THREAD

**Issue by alessio0292** [BearWare/TeamTalk5#1183]
### Description

Hi everyone,
I suggest some new features for the team talk program.
1. The ability to write texts with infinite font sizes as in the notepad program.
2. The ability to edit channels for channel creators only without editing all other channels created by other people.
3. The possibility, again for those who use windows seven even if obsolete, to transmit multimedia files and in addition also transmit url streams for example web radio.
4. The possibility of configuring the audio decoder encoder when the person is inside the channel, when configuring an initial channel with the possibility of eliminating interruptions when there are low connections and with the possibility of transmitting with a minimum interval of 0 milliseconds because it is arriving on 5g.
5. The possibility, again in windows seven, to record conversations also in mp3.
6. The ability to disable also in the history or history of messages the alert that the person is intercepting the other user who is in another channel and also allow users to intercept other users who are in other channels.
7. Put the program license into open source program.
note: The person creating the channel clearly has to set a admin or operator password if she wants to edit that channel she created again. 

### Application

- [ ] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkServer

**Comment by bear101** [comment]
This issue describes many issues. An issue should only describe one issue. Also it appears more like a discussion.
