### ISSUE TITLE
Implement AppleScript as alternative to QTextToSpeech on MacOS

### ISSUE THREAD

**Issue by CoBC** [BearWare/TeamTalk5#1185]
### Description

QTextToSpeech is currently the only one TTS engine available on MacOS. The "say" function of AppleScript can allow us to offer an alternative, to directly output text with VoiceOver, or any installed voice if VoiceOver is disable.
Last time we tried, an error due to strings concatenation was happened, so we have to retry and see if we can find a solution.
More, adding this can probably allow us to switch to Qt6 which don't include QTextToSpeech for now

### Application

- [X] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkServer

**Comment by CoBC** [comment]
We should also considere two other alternatives
1. Use OSXAccessibilityWraper, implemented on the following project, maybe it can be helpful:
https://github.com/jcsteh/osara
2. According to the official Qt documentation, seems we can try to manually import QTextToSpeech in Qt6
https://www.qt.io/product/qt6/qt-5-15-vs-6-2-feature-comparison

**Comment by bear101** [comment]
@CoBC Is this issue still relevant now that we use Qt 6 with QtSpeech?

**Comment by CoBC** [comment]
No, I'll close.
