### ISSUE TITLE
Ability to choose audio inputs on Android

### ISSUE THREAD

**Issue by Piciok** [BearWare/TeamTalk5#119]
With some Android devices a different mode than the default one seem to provide better performance because of software bugs or other unexpected behaviour. In this case it would be good to make it possible to choose the audio input mode for the Teamtalk Android app such as Cam, Mic or Voice.

**Comment by beqabeqa473** [comment]
hi bjoern.
as i know there is now api currently to retrieve audiosource.
if i am wrong please tell me how it could be done.

**Comment by Piciok** [comment]
Any progress on this one? It is affecting a greater number of devices now including flagships. The default microphone mode does not always allow to broadcast stereo audio (most Samsung phones, Xiaomi A1 etc.). Moreover, on certain non-standard configurations such as custom roms on older Samsung devices the enforced stereo combined with default mode results in the sender being able to broadcast from one channel only. I believe such an implementation exists for example in Open Camera, maybe this could help?

**Comment by bear101** [comment]
Duplicate #437
