### ISSUE TITLE
Disable audio input and output when on a call

### ISSUE THREAD

**Issue by Piciok** [BearWare/TeamTalk5#120]
Currently the Teamtalk app operates still while a phone call is in place. My suggestion is to block both audio input and output for the Teamtalk app so that neither a part of our conversation is overheard nor to disturb the person talking with Teamtalk audio coming over the call audio.

**Comment by tech10** [comment]
I like this idea. If transmitting, the app should stop transmission as well, and while I do believe the audio input should be blocked, perhaps the output could optionally be reduced in volume by a specific amount or muted, as I like hearing the TeamTalk conversation while on a phone call, though I can understand why some may not.

**Comment by beqabeqa473** [comment]
this was also fixed by igor, so i think this should be closed as well.
