### ISSUE TITLE
Bug when changing the microphone

### ISSUE THREAD

**Issue by math65** [BearWare/TeamTalk5#1205]
### Description

Hi!

In Teamtalk 5.8.35, when changing the microphone (mono / stereo) or disabling preprocessing, you must restart TeamTalk so that the changes are taken effect.

### Application

- [ ] qtTeamTalk
- [ ] TeamTalkAndroid
- [X] iTeamTalk
- [ ] TeamTalkClassic
- [ ] TeamTalkServer

### Platform

- [ ] Windows
- [ ] macOS
- [ ] Android
- [X] iOS
- [ ] Linux

### Expected behavior

The microphone must change or the preprocessing must be disabled

### Actual behavior

The sound goes mono or preprocessing does not deactivate.

### Steps to reproduce problem

* Open TeamTalk
* Connect to a server
* Go to the settings
* Disable preprocessing or change microphones

**Comment by bear101** [comment]
Duplicate #1256
