### ISSUE TITLE
TTS announcements not working while screen locked; sounds not working at all

### ISSUE THREAD

**Issue by Piciok** [BearWare/TeamTalk5#121]
Currently the TTS announcements only come through if the screen is unlocked and the sounds aren;t heard at all.
Tested on Samsung Galaxy S4 running Android 5.0.2 as well as Huawei Honor 7 running the same version.

**Comment by tech10** [comment]
I have encountered this as well on a Google Play addition of the Samsung Galaxy S4 running the latest software updates.

**Comment by beqabeqa473** [comment]
hi.

i think this was fixed in some of igor's commits, so it should be closed.
