### ISSUE TITLE
Android 11: Microphone is not working in channels with bitrate higher than 32000

### ISSUE THREAD

**Issue by cyrmax** [BearWare/TeamTalk5#1211]
### Description

On Android 11 users cannot speak in channels with mono bitrate higher than 32000 or stereo bitrate higher than 16000.
Bug detected on:
Xiaomi redmi note 8 t (MIUI 12.5);
Samsung Galaxy a02s (OneUI 3.1).

Sometimes, if user activates microphone in low bitrate channel and joins high bitrate channel, user can speak and can be heard normaly. But if user disables microphone and reenables it, no sound is transmited.

On some AOSP ROMs this bug is reproducible, on others  all works normaly.

### Application

- [ ] qtTeamTalk
- [x] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkClassic
- [ ] TeamTalkServer

### Platform

- [ ] Windows
- [ ] macOS
- [x] Android
- [ ] iOS
- [ ] Linux

### Expected behavior

User enables microphone and can speak in any channel.

### Actual behavior

In channels with stereo and bitrate higher than 16000 or mono and bitrate higher than 32000 user enables microphone and no sound is transmited.

### Steps to reproduce problem

Install latest TeamTalk5 for Android;
Connect to any server;
Join any channel with following audio settings:
channels: mono, bitrate higher than 32000;
channels: stereo, bitrate higher than 16000.
Try to enable microphone by holding button or enable voice activation.

**Comment by bear101** [comment]
I tried OPUS mono at 223 KBit on my Samsung A10 with Android 11 and it's able to record.

**Comment by amirmahdifard** [comment]
guys, please close this, i tryed everything with my phone, i'm android 11, there is no problem,
