### ISSUE TITLE
Problem receiving and sending files

### ISSUE THREAD

**Issue by mkpeed** [BearWare/TeamTalk5#1219]
### Description

It is not possible to download the file and upload the file. In Android version 5.8.3 when downloading or uploading files
 The application closes automatically

### Application

- [ ] qtTeamTalk
- [X] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkClassic
- [ ] TeamTalkServer

### Platform

- [X] Windows
- [ ] macOS
- [X] Android
- [ ] iOS
- [ ] Linux

### Steps to reproduce problem

It is not possible to download the file and upload the file. In Android version 5.8.3 when downloading or uploading files
 The application closes automatically

**Comment by bear101** [comment]
#1182
