### ISSUE TITLE
Creating homescreen shortcuts to TT servers

### ISSUE THREAD

**Issue by Piciok** [BearWare/TeamTalk5#122]
The ability to generate a shortcut placed on the homescreen that once clicked would connect directly to the server it points to along with the ability to intercept these shortcut through apps such as Tasker, Shortcut Launcher etc.

**Comment by bear101** [comment]
@beqabeqa473 do you know how to associate .tt files with an app on Android? I managed to do it on iOS, so I guess it should also be possible on Android somehow.

**Comment by beqabeqa473** [comment]
hi brjoern.

no, i don't know yet, but i will search.
how implementation works on ios?

**Comment by beqabeqa473** [comment]
ok, it seems, intent filter does the job.

e.g.

<data android:scheme="file"  android:host="*" android:pathPattern=".*\\.EXT" android:mimeType="*/*"  />

**Comment by bear101** [comment]
@beqabeqa473 is this issue still relevant?

**Comment by beqabeqa473** [comment]
i think it some type of enhancement which will be good t obe done in the feature, but i don't think it is important at this point.
