### ISSUE TITLE
Increase character limit in text messages

### ISSUE THREAD

**Issue by dgleks** [BearWare/TeamTalk5#1236]
### Description

Hello!

Over the years, something that has never failed to frustrate me about TeamTalk is it's hardcode-enforced character limit for user/channel messages. While such a limit may be useful on public servers where potentially-shady people may be connecting to send messages containing 1048575 characters, this limitation is impractical and rather inconvenient on private servers, where activities such as writing projects and the like may be taking place. With that being said, I would like to suggest the following:

* The ability to raise the message character limit (or disable it entirely) at configuration time.
* Messages sent to a channel that contain newlines should be treated as 1 message, similar to how user messages operate. Currently, any message containing newlines that gets pasted into the channel message edit box splits each line up into separate messages, which ends up creating for some potentially-spammy situations as far as sounds and screen readers are concerned.
* When logging of user messages is enabled, user messages fail to log properly. Instead of retaining the format of a timestamp (if enabled) and name on 1 line and the message on another line, the logfile ends up writing out user messages with the nickname, followed by the message (no timestamps, spaces or newlines between the nickname and message are included). This has only been tested with the classic client, so I am not sure if the issue persists in the QT version as well or not.

Thank you for reading, and I look forward to hopefully having these issues addressed ASAP!

### Application

- [ ] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkServer

**Comment by alessio0292** [comment]
for me is a good request. I proposed same this request.
