### ISSUE TITLE
I suggest the possibility in the team talk program to broadcast without internet or with very low and almost absent connections.

### ISSUE THREAD

**Issue by alessio0292** [BearWare/TeamTalk5#1238]
### Description

Dear Bjoern and all,
I suggest the possibility of broadcasting offline for example in an offline channel so, in this way, there will be no annoying delays or interruptions that are the cause of the internet connections and people would not worry about these problems.
I don't know but I think such a thing can be done.
Greetings,
Alessio from Italy.
p.s .: The possibility of creating a server can also be useful and also the possibility of creating servers that work even without internet. 

### Application

- [X] qtTeamTalk
- [X] TeamTalkAndroid
- [X] iTeamTalk
- [X] TeamTalkServer

**Comment by ChrisDuffley** [comment]
How can this be done, if at all? I don't see this as possible to implement.

Thanks,

Christopher Duffley
Host of Mission Possible Podcast: http://www.missionpossiblepodcast.com
Cell: +1 (603) 851-6971

Sent from my iPhone 12 Pro Max

On Feb 17, 2022, at 12:18, alessio0292 ***@***.***> wrote:

﻿
Description

Dear Bjoern and all,
I suggest the possibility of broadcasting offline for example in an offline channel so, in this way, there will be no annoying delays or interruptions that are the cause of the internet connections and people would not worry about these problems.
I don't know but I think such a thing can be done.
Greetings,
Alessio from Italy.
p.s .: The possibility of creating a server can also be useful and also the possibility of creating servers that work even without internet.

Application

 qtTeamTalk
 TeamTalkAndroid
 iTeamTalk
 TeamTalkServer

**Comment by alessio0292** [comment]
in practice, example, a person with only a sound card that have the program 
can use me also, without a internet connection I can have a connection but 
if a connection is very low or doesn’t run or work, I can same use a program 
and i can broadcast and transmit same very well using only a sound card or 
for mobile users, the cards of phones.

Da: Christopher Duffley
Data: giovedì 17 febbraio 2022 19:00
A: BearWare/TeamTalk5
Cc: alessio0292 ; Author
Oggetto: Re: [BearWare/TeamTalk5] I suggest the possibility in the team talk 
program to broadcast without internet or with very low and almost absent 
connections. (Issue #1238)

How can this be done, if at all? I don't see this as possible to implement.

Thanks,

Christopher Duffley
Host of Mission Possible Podcast: http://www.missionpossiblepodcast.com
Cell: +1 (603) 851-6971

Sent from my iPhone 12 Pro Max

On Feb 17, 2022, at 12:18, alessio0292 ***@***.***> wrote:

﻿
Description

Dear Bjoern and all,
I suggest the possibility of broadcasting offline for example in an offline 
channel so, in this way, there will be no annoying delays or interruptions 
that are the cause of the internet connections and people would not worry 
about these problems.
I don't know but I think such a thing can be done.
Greetings,
Alessio from Italy.
p.s .: The possibility of creating a server can also be useful and also the 
possibility of creating servers that work even without internet.

Application

qtTeamTalk
TeamTalkAndroid
iTeamTalk
TeamTalkServer
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you are subscribed to this thread.
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you authored the thread.Message ID: 
***@***.***>

**Comment by bear101** [comment]
I don't understand this issue description. Please rephrase issue and then reopen.

**Comment by bear101** [comment]
It appears more like a discussion instead of an issue.
