### ISSUE TITLE
Allow setting to close to tray with shortcut to show/hide window

### ISSUE THREAD

**Issue by smoke-j** [BearWare/TeamTalk5#1243]
### Description

Using TeamTalk v. 5.8.3 on Windows 10 21H2
Could we get the ability to close to tray, and have a shortcut in the shortcuts options of TeamTalk to re show the window?
currently if you close the window it actually closes it, there is no option to close to tray. With a screen reader this is a touch annoying, especially without the shortcut to show and hide the window. previously on TeamTalk classic you could close to tray, but that feature is missing in the non classic version on Windows.
There is also no shortcut you can set to show/hide the TeamTalk window. This was also an option on Classic, but it is missing from the standard version.
Having these two features would be nice in standard since classic is done with.

### Application

- [X] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkServer

**Comment by bear101** [comment]
Is this the same issue as #1141?

**Comment by smoke-j** [comment]
partially, but also the ability to close to tray instead of just minimize to tray.

**Comment by bear101** [comment]
Show/hide shortcut is now in v5.9.
The Close-window-to-tray is one I would like to keep as it is. I think Close should mean Close.
