### ISSUE TITLE
Support arm64 for Raspberry Pi

### ISSUE THREAD

**Issue by tech10** [BearWare/TeamTalk5#1251]
### Description

Since there have been strictly arm64 versions of Raspberry Pi OS for some time now, some may choose to use this version of the operating system. As it is, to my knowledge, the 32 bit arm version of the TeamTalk client and server can't be run on the 64 bit arm version of the operating system, unless someone knows something I don't. It would be useful to have a version compiled for arm64 as well.

### Application

- [X] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [X] TeamTalkServer

**Comment by bear101** [comment]
Can you build it yourself? Go to [Build](https://github.com/BearWare/TeamTalk5/tree/master/Build) folder and type ```make depend-rasp rasp```

**Comment by tech10** [comment]
I'm not currently running a 64 bit arm version of the operating system on my Pi, so I won't be able to build it for arm64 yet. I'll either have to set up a chroot or use another SD card to see if I can build it. If I make the attempt, I'll update this.

**Comment by bear101** [comment]
Reopen if there's issues

**Comment by tech10** [comment]
After installing build-essential on Debian 11, which is the 64 bit arm base for the latest Raspberry Pi OS, this is the output received. The build failed.

```console
# make depend-rasp rasp
apt install qt5-default libqt5x11extras5-dev qtmultimedia5-dev \
                    libqt5texttospeech5-dev qttools5-dev-tools qttools5-dev doxygen \
                    openjdk-8-jdk ninja-build libpcap-dev junit4 cmake \
                    libssl-dev autoconf libtool pkg-config \
                    libasound2-dev wget python
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'python-is-python2' instead of 'python'
Package qt5-default is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'qt5-default' has no installation candidate
E: Unable to locate package openjdk-8-jdk
make: *** [Makefile:192: depend-rasp] Error 100
```

**Comment by tech10** [comment]
@bear101 I have recently attempted to build this on the 64 bit version of Raspberry Pi OS with no success, same errors as above. I am also unable to reopen this issue for you, but it currently will not build for me, because the needed software can't be installed.

**Comment by bear101** [comment]
Unfortunately I don't have a Raspberry Pi with latest Debian/Raspberry OS. I also searched for Docker images of latest Raspberry Pi OS but I cannot find anyone that is working.

**Comment by tech10** [comment]
You could either chroot into the image or use systemd-nspawn as an alternative to Docker. Since you'd only be doing a build, you probably wouldn't need a docker image, per say. Downloading the latest image shouldn't be too difficult, and if you're able to boot from a 64 bit kernel, you should be able to run the 64 bit version of Raspberry Pi OS in a chroot at minimum.
