### ISSUE TITLE
Change the User count bot to be constantly logged in

### ISSUE THREAD

**Issue by Urh2006** [BearWare/TeamTalk5#1254]
### Description

I'd like to see so the User count bot would be constantly logged in the servers and that it could dynamicly update the number of users. It is so annoying that it keeps relogging in every 5 minutes. Plus this means that the number of users on the server is not completely true. I dout this would be heart.

### Application

- [X] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkServer

**Comment by StormProductionsMusic** [comment]
Agreed. Sometimes it can be disturbing to see this Stats bot logging on and off over and over. It would be a great thing to have it always online.

**Comment by bear101** [comment]
Put #teamtalkskip# in the server name to have have the TeamTalk service to not log on to your server. See #1247

**Comment by bear101** [comment]
There's too many TeamTalk servers for the bot to be connected to all of them.
