### ISSUE TITLE
Unable to record a user you muted.

### ISSUE THREAD

**Issue by TheQuinbox** [BearWare/TeamTalk5#1258]
### Description

If you unsubscribe from a user's voice, you're unable to record them for the rest of the session, no matter if you resubscribe to them or not.

### Application

- [X] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkClassic
- [ ] TeamTalkServer

### Platform

- [X] Windows
- [X] macOS
- [ ] Android
- [ ] iOS
- [X] Linux

### Expected behavior

If I re-subscribe to a user's voice, TT should be able to record them.

### Actual behavior

Unsubscribing from a user's voice, then re-subscribing to it, should allow you to record them.

### Steps to reproduce problem

1. Start recording
2. Press control 4 on a user
3. Press control 4 on them again.

**Comment by bear101** [comment]
In earlier TeamTalk releases a muted user was recorded as well, but by user request this was changed, so muted users are not recorded.

Current behaviour is that unsubscribed and muted users will not be part of a recording.

**Comment by ChrisDuffley** [comment]
This is correct behavior, however I think they're referring to when they're re-subscribing to a user. Strangely, I don't think I can reproduce what you're trying to do, but I can take a look when I see more users later on.

Christopher Duffley

Host of Mission Possible Podcast <http://www.missionpossiblepodcast.com/>

LINKS TO SUBSCRIBE:

iTunes <https://itunes.apple.com/us/podcast/mission-possible-christopher/id1103092109?mt=2> | Stitcher <http://www.stitcher.com/s?fid=88094&refid=stpr> | Google Play <https://goo.gl/app/playmusic?ibi=com.google.PlayMusic&isi=691797987&ius=googleplaymusic&link=https://play.google.com/music/m/Ik76dexklcprwnpuxbdr2s6bm3y?t=Mission_Possible_with_Christopher_Duffley> | Follow Podcast On TuneIn And Listen To Latest Episode <http://tunein.com/radio/Mission-Possible-With-Christopher-Duffley-p892505/>

LIKE/FOLLOW Me:

Facebook <http://facebook.com/christopherduffley> | Twitter <http://twitter.com/chrisduffley> | YouTube <http://youtube.com/christopherduffley> | Instagram <http://instagram.com/christopherduffley>

On Mar 5, 2022, at 23:19, Bjørn Damstedt Rasmussen ***@***.***> wrote:


In earlier TeamTalk releases a muted user was recorded as well, but by user request this was changed, so muted users are not recorded.

Current behaviour is that unsubscribed and muted users will not be part of a recording.

**Comment by bear101** [comment]
@TheQuinbox Is it single recording or separate?

**Comment by TheQuinbox** [comment]
I have both boxes checked, and it doesn't pick them up as a new user when I resubscribe and start recording

**Comment by ChrisDuffley** [comment]
In terms of resubscribing to people, I've had no problems with this when it comes to recordings. That's at least as far as I know with over 20,000 recordings in my list, lol!

Christopher Duffley
Host of Mission Possible Podcast: http://www.missionpossiblepodcast.com
Cell: +1 (603) 851-6971

Sent from my iPhone 12 Pro Max

On Mar 6, 2022, at 15:35, Quin ***@***.***> wrote:

﻿
I have both boxes checked, and it doesn't pick them up as a new user when I resubscribe and start recording

**Comment by bear101** [comment]
I've tried again to reproduce the issue using the steps described but cannot.
