### ISSUE TITLE
Teamtalk5 droid drains too much battery power

### ISSUE THREAD

**Issue by Ramon-Salazar** [BearWare/TeamTalk5#1262]
### Description

Hi @bear101!

I've noticed when running teamtalk on my phone for a long time, like for one hour or more I've noticed that it drains too much battery power, every few minutes it loses one percent which is somehow weird since all apps which I have except Teamtalk don't eat up that much power.

I think it's a bug because that's the only app which drains too much battery power.

### Application

- [ ] qtTeamTalk
- [X] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkClassic
- [ ] TeamTalkServer

### Platform

- [ ] Windows
- [ ] macOS
- [X] Android
- [ ] iOS
- [ ] Linux

### Expected behavior

it shouldn't drain too much power, like every 30 minutes or even more it should take only one to two percent of battery power.

### Actual behavior

Every 2 to 5 minutes it takes one percent of battery power which is really unbelievable according to my experience on apps which I mostly used Yeamtalk 5 droid is the only app which drains too much battery power.

### Steps to reproduce problem

1: when leaving teamtalk opened for a long time and connected to a server.

2: after leaving it opened and connected then tirned on voice activation you'll notice every 2 to 5 minutes it takes one percent of battery power.

**Comment by bear101** [comment]
If you disable voice activation then TeamTalk will only process audio input when you transmit. This will help conserve battery.

If you need voice activation then disable audio preprocessing to use less battery.
