### ISSUE TITLE
message output is not showing after sending private message in QT client.

### ISSUE THREAD

**Issue by rexya2017** [BearWare/TeamTalk5#1281]
### Description

If I send a private message to person B, the message I send does not appear in the private message history section.

### Application

- [X] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkClassic
- [ ] TeamTalkServer

### Platform

- [X] Windows
- [ ] macOS
- [ ] Android
- [ ] iOS
- [ ] Linux

### Expected behavior

Supposedly after sending a private message, the message should appear in the history section.

### Actual behavior

Private messages that I sent do not appear in the history section.

### Steps to reproduce problem

1. Press enter on the name of the person to whom you want to send a private message.
2. type a message on the tex area.
3. hit enter to send your message.

**Comment by rexya2017** [comment]
I'm using QT TeamTalk v. 5.9.0.5078 - Unreleased

**Comment by CoBC** [comment]
Fixed in this commit: 2d1a2b0
