### ISSUE TITLE
no return tts after sending a private message

### ISSUE THREAD

**Issue by jeremyp3** [BearWare/TeamTalk5#1283]
Since the last modification, we no longer receive the content of our private messages in the notification when we send a message. it's like the message is empty

it is displayed well in the history, so there must be a problem with a tts variable

use QT TeamTalk version in linux

**Comment by ChrisDuffley** [comment]
@CoBC, you mentioned this on a build, correct? I've noticed this on Qt in Windows as well using TTS. Doesn't show up in history either on Windows though, and I think you mentioned that as well.
