### ISSUE TITLE
Send one notification even for long messages

### ISSUE THREAD

**Issue by Nardol** [BearWare/TeamTalk5#1293]
### Description

When receiving a long message, we have one notification for each piece of message.
It is the case when sending or receiving public messages, Receiving private message and maybe for broadcast messages.

### Application

- [X] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkClassic
- [ ] TeamTalkServer

### Platform

- [X] Windows
- [X] macOS
- [ ] Android
- [ ] iOS
- [X] Linux

### Expected behavior

We should have only one notification for all the message

### Actual behavior

There is one notification for each part of the message so for a very long message, we have numerous notifications instead of only one

### Steps to reproduce problem

1. With TTS enabled, receive a long message

**Comment by Nardol** [comment]
@bear101 could you take a look please? It is a very annoying bug, more when notifications arrive in a random time as the message is not correct when all pieces are not placed in the right order.

**Comment by bear101** [comment]
This has been fixed for channel and broadcast text messages in v5.10

**Comment by Nardol** [comment]
@bear101  There is a remaining issues in the fix: the sender name is pronounced in the message. And for users who have enabled displaying the date, the notification also contains the date of the message.
The date is not necessary and the nickname is a redundant information.
Could it be possible to have only the message?
In fact:
"Notification TeamTalk5: Message from User: message"
Instead of:
"Notification TeamTalk5: Message from user: <User> message"
