### ISSUE TITLE
Screen reader don't read messages by lines when pressing up and down arrows

### ISSUE THREAD

**Issue by grishakonzalaev** [BearWare/TeamTalk5#1296]
### Description

When I read messages in private windows or in channels, I can't read it by lines when I press up and down arrows. Object navigator of NVDA  helps me to read by lines, but it's not comfortable.

### Application

- [X] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkClassic
- [ ] TeamTalkServer

### Platform

- [X] Windows
- [ ] macOS
- [ ] Android
- [ ] iOS
- [ ] Linux

### Expected behavior

I can read messages by lines when press up and down arrow.

### Actual behavior

When I press up and down arrows in focus of message history, screenreader reads me whole message.

### Steps to reproduce problem

1. Go to any Teamtalk server.
2. focusing to message list of channel or write private message and focus to this message in private window.

**Comment by TheQuinbox** [comment]
This is a problem with QT, not TeamTalk.
