### ISSUE TITLE
Unable to join channel without a password

### ISSUE THREAD

**Issue by tspivey** [BearWare/TeamTalk5#1300]
### Description

After disconnecting from a server, passwords to channels are remembered. As a result of this, I can't join a channel with the same name as one I've already joined with a password, because TeamTalk tries to send the already-remembered password to the server.

### Application

- [X] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkClassic
- [ ] TeamTalkServer

### Platform

- [X] Windows
- [ ] macOS
- [ ] Android
- [ ] iOS
- [ ] Linux

### Expected behavior

I can join the channel

### Actual behavior

The password prompt appears

### Steps to reproduce problem

1. Join a server with a password-protected channel. Enter the password when asked, and join the channel.
2. Press f2 to disconnect, and f2 again. Connect to another server.
3. Join a channel with the same name as the first one, without a password.

**Comment by amirmahdifard** [comment]
bear101? how even you want to fix this? the only way that i can think to fix this, is  save channel passwords for each server difrently: do you have any other  ideas to fix this bug?

**Comment by bear101** [comment]
Please try build artifacts from this workflow to see if it fixes the problem:
https://github.com/BearWare/TeamTalk5/actions/runs/3141892561

**Comment by tspivey** [comment]
Thanks, that fixed it.
