### ISSUE TITLE
Server: Send passwords of auto-operator channels to users on login

### ISSUE THREAD

**Issue by Simon818** [BearWare/TeamTalk5#1301]
### Description

Admins and users with access to all channels are automatically sent the passwords to channels. These appear on the iPhone when joining and when viewing / editing channel info on Desktop. Despite being automatically assigned as operator, it is possible for users to change their main channel password and lose access to it. Ideally, this should not require admin intervention since the user has already been assigned as operator of their own channel. It seems like the best solution to this problem is to send the passwords of auto-operator channels to regular users in the same way the passwords of all channels are sent to admins.

Edit: One alternative solution is to just assign the user's channel as the "Initial Channel" in their user account, but this only works when there is a single auto-operator channel.

### Application

- [ ] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [x] TeamTalkServer

**Comment by amirmahdifard** [comment]
i agree with this one, because if we making someone as an oprator, they shouldn't need admin power anymore.
