### ISSUE TITLE
redesigning the server list/connect dialog of the QT client

### ISSUE THREAD

**Issue by saphir29000** [BearWare/TeamTalk5#1309]
Lighten the connection dialog by putting only the list of servers and the buttons add, edit, delete and connect.
In the add/edit dialog, we can enter/edit the server's infos, as is the case on android/iOS

**Comment by bear101** [comment]
I find it quite convenient to be able to see IP-address, initial channel, etc. when selecting a server. So I'd rather keep it as it is.
