### ISSUE TITLE
Teamtalk is crashing when trying to open it on Mac OS 11.6.2

### ISSUE THREAD

**Issue by danutzmd** [BearWare/TeamTalk5#1314]
### Description

![image](https://user-images.githubusercontent.com/67736306/167363170-4ee3d872-4b63-458f-a0d4-fed8718812e2.jpg)

### Application

- [x] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkClassic
- [ ] TeamTalkServer

### Platform

- [ ] Windows
- [x] macOS
- [ ] Android
- [ ] iOS
- [ ] Linux

### Expected behavior

The app should open normally without crashing

### Actual behavior

When I'm opening the app it just crashes

### Steps to reproduce problem

I'm just trying to open the app and it just crashes

**Comment by bear101** [comment]
Write in Discussions until we know there is an issue
