### ISSUE TITLE
server: channel operators can't change they channel name

### ISSUE THREAD

**Issue by amirmahdifard** [BearWare/TeamTalk5#1320]
### Description

when someone is a channel operator in a channel, when they going to inside they channel so they can edit they channel infomations, but i don't know y? they can't change the channel name, but they can change other stuf like password and topik and other stuf. so i don't know how and  y? but please fix this bug also.

### Application

- [ ] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [X] TeamTalkServer

**Comment by bear101** [comment]
To change the name of a channel requires the user right "Modify all Channels" in User Accounts dialog

**Comment by amirmahdifard** [comment]
but what about if we don't want someone to edit another channels name, just we want them to bee able to edit only one channel name and other stuf?
