### ISSUE TITLE
libssl1.1 is deprecated in Ubuntu 22.04LTS

### ISSUE THREAD

**Issue by Nick6489** [BearWare/TeamTalk5#1323]
### Description

TeamTalk Pro will not run on this platform, as libssl.so.1.1 cannot be found. I suspect you already know this, for which I apologize, but just in case...

### Application

- [ ] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkClassic
- [X] TeamTalkServer

### Platform

- [ ] Windows
- [ ] macOS
- [ ] Android
- [ ] iOS
- [X] Linux

### Expected behavior

The server runs.

### Actual behavior

The server errors, as it cannot find that file.

### Steps to reproduce problem

Run the server.

**Comment by bear101** [comment]
For now Ubuntu 22 binaries are available as artifacts in [GitHub Actions](https://github.com/BearWare/TeamTalk5/actions)

**Comment by Nick6489** [comment]
This error still exhibits in the stable version. Error while loading shared libraries: libssl.so.1.1: Cannot open shared Object File: No such file or directory

**Comment by bear101** [comment]
$ ldd teamtalk-v5.10-ubuntu22-x86_64/server/tt5srv 
	linux-vdso.so.1 (0x00007fffc3561000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fc4162a2000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fc41607a000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fc41672a000)

I don't see the dependency to libssl.so
