### ISSUE TITLE
Video in TeamTalk5 does not work

### ISSUE THREAD

**Issue by Urh2006** [BearWare/TeamTalk5#1331]
### Description

So basically I can't start video no matter what I do. As far as my friends tell me it worked still in TeamTalk version 5.3 and in the Beta version for 5.4 and then it stopped working. When I press Ctrl+Shift+V to start video it just won't do anything and it will say that the video capture device hasn't been configured properly and then I should check prefferences. I checked everything and everything is fine. I'm not sure if this effects IOs or Android as I haven't tested those, but I know it also effects classic and not just the QT client.

### Application

- [X] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [X] TeamTalkClassic
- [ ] TeamTalkServer

### Platform

- [X] Windows
- [ ] macOS
- [ ] Android
- [ ] iOS
- [ ] Linux

### Expected behavior

When you press Ctrl+Shift+V, it should start the video transmition.

### Actual behavior

When I press Ctrl+Shift+V it just says that the video capture device hasn't been configured properly and that I need to check settings in prefferences.

### Steps to reproduce problem

Press Ctrl+Shift+V or go to start video in the menu.

**Comment by bear101** [comment]
What Windows version do you use?
