### ISSUE TITLE
error while loading shared libraries on ubuntu

### ISSUE THREAD

**Issue by vlad-a-c** [BearWare/TeamTalk5#1337]
### Description

i've tried to run  tt5srv the version for ubuntu18 and above and i get error loading shared library libssl.so.1 or something like that. how do i fix that?

### Application

- [ ] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkClassic
- [X] TeamTalkServer

### Platform

- [ ] Windows
- [ ] macOS
- [ ] Android
- [ ] iOS
- [X] Linux

### Expected behavior

run normaly

### Actual behavior

throws me that error

### Steps to reproduce problem

type ./tt5srv -wd folder -d

**Comment by bear101** [comment]
If you use the server from this archive then the dependency to libssl.so should be gone:
https://github.com/BearWare/TeamTalk5/suites/6603494511/artifacts/248148586

**Comment by vlad-a-c** [comment]
yes it is gone. it works fine now.

**Comment by vlad-a-c** [comment]
hello. i'm having again the same issue with the loading libraries. can you please help me again? it's the same issue with the same error.
