### ISSUE TITLE
Cannot authenticate BearWare account on TeamTalk 5.9.2.5083 - Unreleased

### ISSUE THREAD

**Issue by lbk2907** [BearWare/TeamTalk5#1351]
### Description

Cannot log in to server that uses BearWare account.

### Application

- [X] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkClassic
- [x] TeamTalkServer

### Platform

- [X] Windows
- [ ] macOS
- [ ] Android
- [ ] iOS
- [x] Linux

### Actual behavior

When I try to authenticate the BearWare account, it said that "Activate BearWare.dk Web Login  dialog  Failed to authenticate".
I have try both (with and without @bearware.dk) and the result is same.
When I try with older release client (5.9), it works fine.
For the TeamTalkProServer has no problem. I realise that TeamTalkProServer didn't ask for authenticate account anymore when we have BearWare account configured. Is nice feature. 😊

### Steps to reproduce problem

After update to TeamTalk 5.9.2.5083 - Unreleased

**Comment by lbk2907** [comment]
a little update here. I not sure how it happend.
Just now I have said that I realise that the TeamTalkProServer didn't ask for to authenticate the BearWare account when we creating a new server and have BearWare account configured. But now I realise that some of the XML still ask to authenticate the BearWare account.
If you ask how I know that, the answer is I remove the BearWare user token stored in the XML ffile. One of the server is working fine and the 2 other didn't work. The working server is the smaller one. It only contain the root channel and 1 subchannel on it.

**Comment by lbk2907** [comment]
Woops. The account also have only 2. One is an administrator account and one is BearWare account.

**Comment by lbk2907** [comment]
I figured out the steps to reproduce this issue. I mean the server that didn't ask for authentication when have BearWare account configured.
Simple, the "bearware" account need to be on the top of the user account section in the XML file.
It should be like follow:
    <users>
        <user>
            <username>bearware</username>
            <password />
            <user-type>1</user-type>
            <user-rights>521735</user-rights>
            <note />
            <userdata>0</userdata>
            <init-channel />
            <modified-time>2022/05/04 20:42</modified-time>
            <audiocodec-bps-limit>0</audiocodec-bps-limit>
            <abuse-prevention>
                <commands-limit>0</commands-limit>
                <commands-interval-msec>0</commands-interval-msec>
            </abuse-prevention>
            <channel-operator />
        </user>
        <user>
            <username>testing123</username>
            <password>thisisatest</password>
            <user-type>2</user-type>
            <user-rights>0</user-rights>
            <note />
            <userdata>0</userdata>
            <init-channel />
            <modified-time>2022/05/05 17:46</modified-time>
            <audiocodec-bps-limit>0</audiocodec-bps-limit>
            <abuse-prevention>
                <commands-limit>0</commands-limit>
                <commands-interval-msec>0</commands-interval-msec>
            </abuse-prevention>
            <channel-operator />
        </user>
    </users>

**Comment by lbk2907** [comment]
I figured out the steps to reproduce this issue. I mean the issue about the server that didn't ask for authentication when have BearWare account configured.
Simple, the "bearware" account need to be on the top of the user account section in the XML file.
It should looks like follows:
https://www.dropbox.com/s/redoqpz5xcqcaab/UserAccountList.txt?dl=1
If the BearWare account in your XML file same like an example above (I mean the the arangement) and you run the TeamTalkProServer, it will not ask for authentication.
This also happend on TeamTalk Professional Server 5.9.0.5080 (release).

**Comment by lbk2907** [comment]
I forgot to mension that I'm running the TeamTalkProServer on Ubuntu 20.04.4LTS using the TeamTalkProServer for Ubuntu 18.

**Comment by bear101** [comment]
I can confirm that the BearWare WebLogin is failing in the latest Windows release v5.9.2.5083. The problem is that DLLs libcrypto-1_1.dll and libssl-1_1.dll are missing. It seems I need to deploy these manually.

**Comment by lbk2907** [comment]
Are user need to do anything or just wait for the next update?

**Comment by bear101** [comment]
Wait for next update.

**Comment by lbk2907** [comment]
Ok thanks.
