### ISSUE TITLE
Problem from classic version 5.7 in windows 10.

### ISSUE THREAD

**Issue by alessio0292** [BearWare/TeamTalk5#1357]
### Description

Problem from classic version 5.7 in windows 10.
Dear Bjoern and all,
Many people from Brazil have a problem that if any person uploads a file, any person on the server who already has those versions disconnects from the server. The problem is only in brazil, only in the latest versions of classic team talk. The normal qt team talk program, the brazilians told me it doesn't have this problem.
Best regards,
Alessio from Italy.

### Application

- [ ] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [X] TeamTalkClassic
- [ ] TeamTalkServer

### Platform

- [X] Windows
- [ ] macOS
- [ ] Android
- [ ] iOS
- [ ] Linux

### Expected behavior

all brazilian people with windows 10 if someone uploads a file, the person from brazil with version of team talk 5.7 classic only automatically disconnects from the server.

### Actual behavior

a brazilian disconnect from the server.

### Steps to reproduce problem

a person upload a file and the brazilian with this version that i said disconnects automatically.

**Comment by bear101** [comment]
Does switching language to English fix the issue?

**Comment by bear101** [comment]
Cannot reproduce
