### ISSUE TITLE
Voice activation is always enabled after idle

### ISSUE THREAD

**Issue by bear101** [BearWare/TeamTalk5#1380]
### Description

When "Disable voice activation during idle" is checked then voice activation is always enabled even though the user has never enabled voice activation.

### Application

- [X] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkClassic
- [ ] TeamTalkServer

### Platform

- [X] Windows
- [X] macOS
- [ ] Android
- [ ] iOS
- [X] Linux

### Expected behavior

If VOX is disabled and "Disable voice activation during idle" is enabled/checked then after idle VOX should remain disabled.

### Actual behavior

If VOX is disabled and "Disable voice activation during idle" is enabled/checked then after idle VOX will be enabled.

### Steps to reproduce problem

1. Connect to server and join channel
2. Set idle timeout to say 5 seconds in Preferences
3. Check "Disable voice activation during idle" in Preferences
4. Disable VOX
5. Wait for idle
6. Become active again, i.e. come out of idle
7. VOX is now enabled

The problem is in mainwindow.cpp:2383

**Comment by CoBC** [comment]
@bear101 2383? Is it not the line 2391 which cause this issue?

**Comment by bear101** [comment]
Yes, line 2391. I guess it should extract SETTINGS_GENERAL_VOICEACTIVATED and set that instead of true/false.

**Comment by CoBC** [comment]
Yes, it's also what I thought, but it seems to not work better :(
