### ISSUE TITLE
Message Of The Sender Didn't Show Up After Closing the Private Message And Re-Open It

### ISSUE THREAD

**Issue by lbk2907** [BearWare/TeamTalk5#1381]
### Description

When I send the private message to someone, I can't read back what I just wrote to him/her after pressing escape to close the private message window and press enter again on that person name to re-open it.

### Application

- [X] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkClassic
- [ ] TeamTalkServer

### Platform

- [X] Windows
- [ ] macOS
- [ ] Android
- [ ] iOS
- [ ] Linux

### Expected behavior

It suppose to show up the sender message even after closing the private message window and re-open it just in case they need it.

### Actual behavior

Message of the sender didn't show up after closing private message window and re-open it.

### Steps to reproduce problem

Happend on version 5.10.0.5087.

**Comment by bear101** [comment]
@lbk2907 Please try artifacts from this build: https://github.com/BearWare/TeamTalk5/actions/runs/2643654360

**Comment by lbk2907** [comment]
@bear101 May you guide me how can I test that? Thanks.

**Comment by lbk2907** [comment]
@bear101 May you help me to compile it and send it to my email so that I can test it. Or maybe you can guide me how can I set it up. Thanks.

**Comment by bear101** [comment]
When the workflow has finished compiling you can download the TeamTalk 5 Portable:
https://github.com/BearWare/TeamTalk5/actions/runs/2643654360

**Comment by lbk2907** [comment]
@bear101 Thanks.

**Comment by bear101** [comment]
Hm, please wait for build #1385 to land on issue 1381 branch.

**Comment by bear101** [comment]
There's a bug in the artifacts that is being fixed by #1385 

> @bear101 Thanks.

**Comment by lbk2907** [comment]
@bear101 All right.

**Comment by bear101** [comment]
Please try artifacts from this workflow: https://github.com/BearWare/TeamTalk5/actions/runs/2644234312

**Comment by lbk2907** [comment]
@bearware101 Is fixed.
