### ISSUE TITLE
server: intercepting isn't saved in the log

### ISSUE THREAD

**Issue by amirmahdifard** [BearWare/TeamTalk5#1387]
### Description

when an admin intercepts someone in the teamtalk, doesn't matter wich one, intercept user messages, channel messages, voice or all  of them, it doesn't save that in the tt5srv.log. so we can't understand anything from this. if we read the log: also this one is also not save anything if an user mutes or unmutes  someone's messages or whatever,  with controle pluss number: it is a bug, because this informations are needed in the log: server version: 5.9.1: i tryed to explane as good as i can, but let me know if something is needed

### Application

- [ ] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkClassic
- [X] TeamTalkServer

### Platform

- [X] Windows
- [ ] macOS
- [ ] Android
- [ ] iOS
- [ ] Linux

### Expected behavior

the subscriptions of turning off or on peoples messages or voice or all of them, also subscriptions for intercepts should bee saved in the server log.

### Actual behavior

the subscriptions of turning off or on peoples messages or voice or all of them, also subscriptions for intercepts are not saving in the logs.

### Steps to reproduce problem

1: go to the teamtalk and in  the server: 2: intercept someone, doesnt matter wich intercept, because it's happen with all of them. or change a subscription for a user, wich is controle pluss number ros, because its happening with this one too: 3: go to the server folder and open tt5srv.log, and then good luck trying to find them.

**Comment by ChrisDuffley** [comment]
Why do you think this should be saved in the log? I have no reason to save it there because it's client-specific and I personally would disable this if that setting is there.

**Comment by amirmahdifard** [comment]
for example, lets say a fight happened on the server. between 2 people, about intercepting, or whatever, and you are the one who have to prove that this one happened or not, because you have the server. and anyway, its something that happening between client and server, not only client, so i know its a bug. and anyway, thats not only you, someone may bee need this.

**Comment by bear101** [comment]
Please try server artifacts from this workflow: https://github.com/BearWare/TeamTalk5/actions?query=branch%3Aissue-1387

Subscriptions that intercept are written in capital letters.
