### ISSUE TITLE
Generate .tt-file name from 'Server Name' instead of autogenerated

### ISSUE THREAD

**Issue by djgraco** [BearWare/TeamTalk5#1388]
### Description

Hello,
I believe I have reported this once, but I cannot find this issue in either open or closed.
I would like to report bad writing information to .tt file by qt client on windows. There is no such problem in the classic.

I have such an entry on the server list
Name: my best server
Host: myserver.com
Ports: 10333
Username: graco
Password: pass123
Something like this appears in the value of name in the generated .tt file
   <name>graco@myserver.com:10333</name>
And it should be
   <name>my best server</name>
Client version used
TeamTalk v. 5.10.0.5086
Windows 10 PRO 21h2 x64
Greetings

### Application

- [X] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkClassic
- [ ] TeamTalkServer

### Platform

- [X] Windows
- [ ] macOS
- [ ] Android
- [ ] iOS
- [ ] Linux

### Steps to reproduce problem

1. Create a entry on server list:
Name: my best server
Host: myserver.com
Ports: 10333
Username: graco
Password: pass123
2. Click Generate TT file button.
Something like this appears in the value of name in the generated .tt file
`<name>graco@myserver.com:10333</name>`
And it should be
`<name>my best server</name>`

**Comment by bear101** [comment]
Please try artifacts from this workflow: https://github.com/BearWare/TeamTalk5/actions/runs/2787788293

**Comment by djgraco** [comment]
I tested the portable version and unfortunately it doesn't work for me.
Besides, I discovered that when I generate a tt file, I enter a different username and password than the one saved in the server list, then the old settings will be found in the generated file.

**Comment by CoBC** [comment]
If I understand correctly, it's the name in the file (name field in XML) which is incorrect, not only the file name.

**Comment by bear101** [comment]
What is written in "Connect to a Server" dialog's "Entry Name" will appear in <name> tag. With the changes on this branch the "Entry name" will be used as file name. Also username/password had no effect in "Generate .tt File" dialog has been fixed.

**Comment by CoBC** [comment]
The problem is that when you select a server in host list, entry name is 
reset to ***@***.***:port, instead of the name define in host entry. 
So, when you generate a TT file, the name with ***@***.***:port, is 
used as server name.
