### ISSUE TITLE
Disabled Text To Speech event still talking in latest beta

### ISSUE THREAD

**Issue by adns44** [BearWare/TeamTalk5#1397]
### Description

I turned off the sounds and text to speech events when an user logs in or out from the server, or joins / lefts from a channel. But I am the admin of my server, so I still keep it turned on to chat message status events to see the user traffic if it is neccessary.
The problem is that JAWS auto reads if an user leaves from a parent channel or from another channel in the same level with my current channel. It seems to be that the event sent to tolk and ignores the disabled state

### Application

- [X] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkClassic
- [ ] TeamTalkServer

### Platform

- [X] Windows
- [ ] macOS
- [ ] Android
- [ ] iOS
- [ ] Linux

### Expected behavior

Do not say this info when it is turned off

### Actual behavior

The event talked when it turned off

### Steps to reproduce problem

Turn on TTS events. Turn off user logged in, logged ouf, join channel and left channel, and try to login to the server with another device, moving between channels.

**Comment by CoBC** [comment]
Can't reproduce here. Are you using the 32 or 64 bits version?

**Comment by adns44** [comment]
I use 64-bit version. I updated a few days ago to 5.10 and the problem still ocurs.
To reproduce start a JAWS screen reader, create a channel (e.g. example) and in the example an example1 and example2 channels. Join to the example1 or example 2, turn of announcing user join and left from a channel in text-to-speech, turn on Window > configure events, turn on user join and left from a channel. Finaly from an other client, log in to example1 or example, and left from there. The screen reader will announce this event on the first client.
