### ISSUE TITLE
Support for socks5 proxy servers

### ISSUE THREAD

**Issue by jmdaweb** [BearWare/TeamTalk5#1407]
### Description

Currently, socks5 proxies are the only ones that can relay both TCP and UDP traffic. Having this feature implemented would allow users connecting to servers outside corporate environments whose networks are behind a proxy.

### Application

- [X] qtTeamTalk
- [X] TeamTalkAndroid
- [X] iTeamTalk
- [ ] TeamTalkServer

**Comment by bear101** [comment]
Sorry, this is out of scope. Time required to implement it exceeds the benefit.
