### ISSUE TITLE
Teamtalk doesn't connect to tt-URL when autoconnect-settings are active

### ISSUE THREAD

**Issue by Michael1972** [BearWare/TeamTalk5#1411]
### Description

In usage of teamtalk, it can be easy to define auto-connect-settings (connect to latest host, reconnect on connection dropped and join root channel upon connection). When the first of these options is set, connecting to an tt-URL is impossible and results in error-messages.

### Application

- [X] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [X] TeamTalkClassic
- [ ] TeamTalkServer

### Platform

- [X] Windows
- [X] macOS
- [ ] Android
- [ ] iOS
- [ ] Linux

### Expected behavior

TT-URLs should always work, independent from auto-connect-Settings, because beginners don't care about settings, they just want to connect to a server, and TT-URLs are the easiest way.

### Actual behavior

With configured settings described above, activating the tt-URL of a teamtalk-server displays "Invalid user-account"., including an edit-field to type in a username. The error-messages are different. Sometimes, with my own server, after clicking the tt-URL brings "the server reported an error, cannot perform action, because client is currently not logged in".
 After deactivating the connect to last host setting, TT-URLs work as expected.

### Steps to reproduce problem

* activate the above described settings, connect to a server and close the teamtalk-application.
* click on a TT-URl
* the error-message appears.

Could you please fix this?

Thank you

**Comment by bear101** [comment]
I cannot reproduce this problem in TeamTalk v5.10.

1. Check "connect to latest host"
2. Connect to a server
3. Quit TeamTalk
4. Open .tt file
5. TeamTalk connects to the server in the tt-file.

**Comment by Michael1972** [comment]
Thank you for the steps and your reply. But I'M afraid, we have to reopen the issue. The behaviour of teamtalk in this case is very curious. So, here again the steps to reproduce the problem:
* check connect to last host on startup
* connect to a server
* quit teamtalk and reconnect via tt-file or tt-URL
* Teamtalk connects as expected
* quit teamtalk in order to come back later
* connect again via tt-file or tt-URL
* this second connection  fails  and results in error-message: "The server reported an error, command flooding prevented by server".

Please check this again.
Thank you
