### ISSUE TITLE
A request

### ISSUE THREAD

**Issue by alessio0292** [BearWare/TeamTalk5#1434]
### Description

Dear Bjoern and collaborators,
I suggest a possibility in a next version of team talk to join servers or channels in total anonimity or in invisible mode and for this thing in activity state create a state called invisible that this state is present in applications like skype or in a facebook website where people can use messenger without to shou the activity state. This invisible mode can be util for people that want to show the activity in team talk only if people speak or write but don't want show the presence in a channel or a server and don't want to be away or online in that moment.
regards,
Alessio from Italy and please Bjoern unbann me in discussion because i didn't understood your bann.
Alessio italian in github alessio0292.

### Application

- [X] qtTeamTalk
- [X] TeamTalkAndroid
- [X] iTeamTalk
- [X] TeamTalkServer

**Comment by amirmahdifard** [comment]
friend, i'm sorry, but your so annoying for everyone as i saw all your ishoos and stuf
