### ISSUE TITLE
    A tip for users on the server.

### ISSUE THREAD

**Issue by alessio0292** [BearWare/TeamTalk5#1435]
### Description

Dear Bjoern and all,
I suggest a new possibility for users of servers and who are on servers. At this moment it is only possible to create and edit all channels while I propose an extra option that allows users who will enable that option to allow only that creator of that channel to edit only that channel that created that owner instead of modifying those channels that were created by another creator. There are two alternatives:
1. in the first alternative, if you enable that option for users that allows users to act as channel operators, no password would be needed.
2. in the second alternative instead if that person wants to become an administrator or operator, for example, the creator must set or configure an administrator password.
This new option could be useful for those people who have their own server and who want to allow one person to create a channel, even permanent, and repeat, without modifying other channels already created by other creators. This possibility, as I said, exists in another application called zello walkie talkie where permanent channels can be created and the administrator or owner of that channel can also put other administrators or moderators.
the password must be configured because otherwise you would not be able to hand over the administration to that person or I would not be able to modify the channel myself.
I'd like you to put this option on right away and it has to work in the classic version of TeamTalk as well.
I use windows seven as my operating system so this feature I have resubmitted must work in that operating system as well.
regards,
Alessio from Italy.

### Application

- [X] qtTeamTalk
- [X] TeamTalkAndroid
- [X] iTeamTalk
- [X] TeamTalkServer

**Comment by amirmahdifard** [comment]
and i suggest you to change your translater, i'm sure that the developers have to at leest first spend an hour to understand what you said, and then work on it.. i only understood a little sentens of your text, and i will open another ishoo for it, and will explane it in a bettar way.

**Comment by amirmahdifard** [comment]
guys, please close this, i will open another one.
