### ISSUE TITLE
Adding VoiceOver Custom actions to iTeamTalk views

### ISSUE THREAD

**Issue by tgeczy** [BearWare/TeamTalk5#146]
This seems relatively simple to do. VoiceOver users can swipe down with one finger to quickly invoke various functions of a table cell. For example, a blind person might swipe down with one finger inside the server list to quickly delete or edit the server information. In the users table cell, a blind person might swipe down to kick or mute that user.

    override var accessibilityCustomActions: [UIAccessibilityCustomAction]? {
        get {
            return accessibilityActionsSource?.accessibilityCustomActionsForView(self)
        }
        set {
            super.accessibilityCustomActions = newValue
        }
    }

also:
http://stackoverflow.com/questions/16316189/custom-voiceover-actions-in-uitableviewcell

**Comment by bear101** [comment]
@tgeczy, how do you actually manage to press "Edit" button on channel items using VoiceOver?

**Comment by tgeczy** [comment]
Actually there's an edit button next to each channel right now which
is in the list - the problem with that could be that even users who do
not have rights to edit a channel see the "edit button" next to each.
Normally you just touch the item and then double-tap on it, but with
custom actions a VoiceOver user would find the channel's name, flick
down and double tap. The nice thing about custom actions is that
flicking down with one finger on the item will reveal more than one
action, such as "edit", "delete," etc. In some places this is less
practical than others: For example, when focusing on the name of a
user, you could flick down with one finger to kick, ban, mute, or
kick-ban the person quickly, rather than having to open the user's
action pop-up.
Fortunately it looks like VoiceOver can query all of the actions on a
view and automatically figure out which custom actions are available.
At least, from when I read the code / class info, that's what I
understood. It's not well documented at all, but many apps use custom
actions so definitely doable and probably simpler to implement than we
know / think.

**Comment by bear101** [comment]
@tgeczy I've tried adding custom actions but I can't figure out how to access them with voiceover. The rotor says that actions are available but how do I get the actions listed? What is the gesture I have to do?

**Comment by bear101** [comment]
Apple's documentation says: "After you choose an option, flick your finger up or down on the screen to use it." What does it mean to "flick a finger"?

**Comment by tech10** [comment]
Hi,
Take your finger and when it's in contact with the screen, bend it at the first knuckle, so it's like a quick swipe down or up the screen. You want to do this quickly, though, at the moment your finger's in contact with the screen. I hope that helped.

Blake

**Comment by bear101** [comment]
Right now I've added two custom actions and I can make it navigate to "actions" in the rotor. But how do I make it speak the possible actions? And how do I select one?

**Comment by beqabeqa473** [comment]
i think you can just swipe through items with left/right  gestures and up/down through actions and double tap to select.

**Comment by tgeczy** [comment]
Hi Bjoern,
You swipe down with one finger when the element is under the VoiceOver
cursor. You know this when it says "actions available" - swiping down
is similar to how you might scroll but with less force. Take one
finger and slide it about 1-2 CM down the screen quickly, and it
should read the custom action you made. For example, "join". Then you
can double-tap to have it activate that action rather than doing the
"default" one which might be different. This way a clickable item can
have several "actions" for blind people to use. The default action
when you double-tap a channel name is to expand that channel cell -
VoiceOver will bypass this entirely and implement something else that
you added.
Hope this helps. If you commit those changes I can definitely let you
know if and how well they work.
Sincerely,
Tamas

**Comment by bear101** [comment]
Phew, I finally figured out how to enumerate accessible actions. I thought I should keep the finger on the screen when going through actions. Anyway I've commit an example of custom actions for connect to server and delete server.

Anyone who knows how to associate a value with a UIAccessibilityCustomAction? Right now I create a hash-map to maintain the association between action and table row. It seems a bit too complicated for something so simple.

**Comment by tgeczy** [comment]
I agree. Thanks for implementing it though, Bjoern. It seems to work well here.
I thought that there's a function which automatically grabs all
actions associated with the cell and places them as an accessible
action event. At least, from my research I recall reading about it and
how easy it is for devs to implement this because they can just grab
all actions to a table view and have it automatically place them in to
an actions aray.
I was surprised and quite dismayed at how little information exists on
this though besides Apple's class reference and maybe a few blogs that
mention it in passing.
I'm actually curious to see how this is implemented, so thanks for doing so.
-Tamas

**Comment by bear101** [comment]
Should we add more custom actions? E.g. on the channel list to mute and kick users?

**Comment by beqabeqa473** [comment]
yes, i think join/edit actions should be added for channels, message/kick/ban and other future possible actions should be added for users.

**Comment by beqabeqa473** [comment]
i think, all possible actions should be added depending on user rights.
and also i think for all clients, some checks should be added to show/hide actions depending on user rights.

**Comment by bear101** [comment]
I'm adding the custom actions now to the channel list. It should be ready in a day or two since I need to update the TeamTalk API.

**Comment by bear101** [comment]
38ac1b6769b00b886376d1103b281a7cc9b8df5b
78c891d3789657ceb1f368349bda4ccc53b30192
@tech10, @tgeczy  Can you think of more items that need custom actions?

**Comment by tech10** [comment]
Be sure the action to mute user will change to un-mute them when muted, if possible.

A few more I can think of.
Ban user, view user info, remove user's account. The remove user account action should depend on weather it's the anonymous user or not. If it is, you shouldn't remove that one from the list of users with a custom action, so it shouldn't show up if the user focused on by VoiceOver is the anonymous user.

That's about all I can think of for users. For channels, I'd add one to remove channel, but I'd recommend that be about it. We don't want too many custom actions.

**Comment by tgeczy** [comment]
Hi Bjoern and others,
Thanks for implementing this. I hope it wasn't too difficult, though
looking at the code it kind of sucks that it doesn't let you just
assign the custom actions to already-created functions. Still, the
implementation is pretty cool, and havinga global class defined makes
things a bit easier.
I agree about the mute user changing to unmute when it's toggled with
custom actions. I guess similar how "kick" shows up as one of them.
The problem I see with other things (like delete user, ban user) is
that they would be way too easy to trigger. Kick user is fine, it's
not a super severe action, but ban and others might be kind of easy to
do with just a custom one. Ultimately it's your decision Bjoern, but
just my thoughts are these.
-Tamas

**Comment by tech10** [comment]
Hi,
You'd want confirmation before such actions are completed when kicking or banning a user, removing a user account or a channel, etc. Otherwise, you could do so without quite realizing what you're doing if you aren't paying attention. That could be the solution to the problem of easy triggering.

Blake

**Comment by bear101** [comment]
I'll close this issue. When we add new features we'll just remember custom actions as well.
