### ISSUE TITLE
moving users to a difrent channel doesn't save up on server los / disconnection

### ISSUE THREAD

**Issue by amirmahdifard** [BearWare/TeamTalk5#1461]
### Description

if i'm in a channel and i was moved by another user or even i have access and i moved my self to another channel, now for any reezen  if i disconnected from the server and reconnected, it will spoarn me to the channell where i was joind my self, not the one where i was moved last time. this bug is so annoying for those who having important conversation  and moving people to a channel and someone have bad internet in there

### Application

- [ ] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkClassic
- [X] TeamTalkServer

### Platform

- [ ] Windows
- [ ] macOS
- [ ] Android
- [ ] iOS
- [ ] Linux

### Expected behavior

the channel where you have been moved should be saved and you should back to there.

### Actual behavior

thats doesn't save

### Steps to reproduce problem

go to a server: join a channel with name audio box for example: move your self to friends channel: los your internet and then reconnect again: your spoarned at audio box, not friends.

**Comment by bear101** [comment]
The server should not make any assumptions on what client should do. The clients must themselves restore the state they want. Also the server doesn't know if the connection was dropped or disconnected manually.
