### ISSUE TITLE
problems with accessability

### ISSUE THREAD

**Issue by artem59k** [BearWare/TeamTalk5#1490]
### Description

Hello. I found a problem. In the user rights settings, the NVDA screen reader program does not say whether the right is allowed or prohibited. For example: a user can log in several times, and after that it is not clear whether this right is enabled or not. Also, in translations, it is possible to pronounce selected items in lists in the text-to-speech settings, but this flag is not present in the interface.

### Application

- [X] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkClassic
- [ ] TeamTalkServer

### Platform

- [X] Windows
- [ ] macOS
- [ ] Android
- [ ] iOS
- [ ] Linux

### Expected behavior

It was assumed that the screen reader program would explicitly state which user rights are prohibited or allowed

### Actual behavior

The program speaks only the text in the list. For example, a user can log in several times, then it is not clear whether this right is allowed for the account, or prohibited.

### Steps to reproduce problem

1. You need to open a window with accounts. 2. Go to the tree list with user rights and check on different account rights by default, then it will be clear that using the screen reader program it is clearly not clear checked the checkbox, or not checked.

**Comment by bear101** [comment]
Do you have the same problems with TTS events in Preferences? Because it's designed the same way.

**Comment by artem59k** [comment]
All tts events work well, just doesn't say selected when ctrl space is pressed in the channel list and in the file list

**Comment by CoBC** [comment]
f9530ee should fix this
