### ISSUE TITLE
No beta version available for Ubuntu 18

### ISSUE THREAD

**Issue by Nardol** [BearWare/TeamTalk5#1491]
### Description

When checking for update, the new beta version is proposed but on the web page, there is TeamTalk and Teamtalk pro for Ubuntu 22 but no for Ubuntu 18 which is the only version usable with Debian

### Application

- [X] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkClassic
- [X] TeamTalkServer

### Platform

- [ ] Windows
- [ ] macOS
- [ ] Android
- [ ] iOS
- [X] Linux

### Expected behavior

On the web page the Ubuntu 18 versions should be available

### Actual behavior

Only Ubuntu 22 version are available

### Steps to reproduce problem

1. Activate checking for beta version update
2. Launch TeamTalk
3. The new update available dialog is showed
4. Click Yes
5. Look on the webpage, there is no Ubuntu 18 version

**Comment by bear101** [comment]
Now Ubuntu 18 is there.
