### ISSUE TITLE
the latest version of the server is not supported in the stable release of Debian 11

### ISSUE THREAD

**Issue by artem59k** [BearWare/TeamTalk5#1522]
### Description

Hello. The latest version 5.11 is not supported in stable releases of Debian 11. Of course, it is possible to build the required libraries from source code, but most users do not have enough experience to compile dependencies. Yes, it's not difficult, but when installing libraries from the latest releases of the testing branch, many libraries of a stable system need to be updated. If necessary, the libraries can be updated, but it would be nice if there is an alternative way to solve this issue.

### Application

- [ ] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkClassic
- [X] TeamTalkServer

### Platform

- [ ] Windows
- [ ] macOS
- [ ] Android
- [ ] iOS
- [X] Linux

### Expected behavior

When executing tt5srv, it was assumed that the server would work as usual

### Actual behavior

the console reports missing libraries
./tt5srv: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./tt5srv)
./tt5srv: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./tt5srv)
./tt5srv: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./tt5srv)

### Steps to reproduce problem

the problem appears when running a binary file in the stable version of Debian 11

**Comment by Nardol** [comment]
Which version have you installed on Debian Bullseye?
The Ubuntu 18 version should be fine.
I use the pro server, maybe it is only the free version which is not compatible?

**Comment by artem59k** [comment]
The fact is that in the latest release 5.11, the ubuntu 18 server download was removed

**Comment by CoBC** [comment]
It is just not listed on download page, but you can find it here:

http://bearware.dk/teamtalk/v5.11/

**Comment by artem59k** [comment]
Thank you
