### ISSUE TITLE
TeamTalk 5 default QT client, (accessibility bug report): "collapsed or expanded" word are not automatically announced by screen reader when navigating with left/right arrow key

### ISSUE THREAD

**Issue by shaghayegh1382** [BearWare/TeamTalk5#1528]
### Description

Hello. I use team talk 5, when I collapsed or expand a channel with left and right arro key, my screen reader  doesn't automatically say "collapsed" or "expanded" words like the classic version. Hope it gets solved soon.

### Application

- [X] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkClassic
- [ ] TeamTalkServer

### Platform

- [X] Windows
- [ ] macOS
- [ ] Android
- [ ] iOS
- [ ] Linux

### Expected behavior

Automatically saying collapsed and expanded by screen reader when you expand or collapsed a server or channel

### Actual behavior

Collapsed and expanded are not automatically announced by screen reader

### Steps to reproduce problem

step 1: I connect to a server.
step 2: I try to expand the server and its channels.
step 3: when I expand and collapsed channels, my screen reader does not specify collapsed or expanded state such as  classic version.

**Comment by amirmahdifard** [comment]
hi, please say wich version of teamtalk are you using? this problem is fixed in 5.11 last version aparrently as the developers mentioned it in the change log of that version.

**Comment by shaghayegh1382** [comment]
5.11
