### ISSUE TITLE
TeamTalk 5 default QT client, (Accessibility bug report): The exact member counts are not automatically announced by NVDA whenever you collapsed or expand a server

### ISSUE THREAD

**Issue by shaghayegh1382** [BearWare/TeamTalk5#1531]
### Description

Let me to describe my issue with an example:
Assuming the US team talk server, I enter the server and there are 10 people on the server. I navigate to the server name such as this: English US teamtalk server (10), well there are 10 users on the server, from these people, three of them are in root channel, when I press right and left arrow key, it doesn't say the member of server and root channel automatically, and I have to check it out with nvda+up arrow key, hope you understand what do I mean if you take a look to classic version.

### Application

- [X] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkClassic
- [ ] TeamTalkServer

### Platform

- [X] Windows
- [ ] macOS
- [ ] Android
- [ ] iOS
- [ ] Linux

### Expected behavior

I expect the exact member count for server and root channel is automatically announced by NVDA when you expand or collapsed a server, such as this: English US team talk 10, collapsed. I press right arrow key and expand it, there are 3 members in root channel so it must say: English US team talk server, 3, expanded. So we notice that there are 10 people on the server in total and 3 of them are in root channel, as we see in the classic version too.

### Actual behavior

Actually, the exact server members and root channel members are not automatically read by screen reader if you collapsed and expand a server

### Steps to reproduce problem

Step 1: I open team talk 5.
step 2: I enter to a server, e.g: Official US server.
Step 3: There are 10 people in english US server, and from these 10 people, 3 of them are in root channel.
Step 4: I expand and collapsed server with right and left arrow keys.
step 5: First: the "expanded" or "collapsed" word are not automatically announced by NVDA, second: The exact members for the entire server and the root channel are not also automatically announced when I expand or collapsed the server or even the channels.

**Comment by ChrisDuffley** [comment]
@CoBC or @bear101 - the expanded and collapsed problem must be a Qt issue as you don't get collapsed and expanded on macOS either. However, shouldn't it just announce how many are in the root at one time when expanded similar to Classic as mentioned?

**Comment by CoBC** [comment]
Related to Qt issue, reported here:
[QTBUG-105733](https://bugreports.qt.io/browse/QTBUG-105733)

**Comment by amirmahdifard** [comment]
@CoBC i emajjin that if Qt fixes the all accessibility problems, how nice this Qt client will become! really grate!
