### ISSUE TITLE
classic client: an option for client in server Properties

### ISSUE THREAD

**Issue by amirmahdifard** [BearWare/TeamTalk5#1550]
### Description

the (logging delay per IP adress is not in classic client's server propertis dialogue: Classic client vertion: 5.11

**Comment by bear101** [comment]
Isn't this "Login delay per IP-address"?

**Comment by amirmahdifard** [comment]
no, it is not in server propertis. just max logging per IP adress wich is difrent

**Comment by amirmahdifard** [comment]
that logging delay thing is only in config and not in server propertis

**Comment by amirmahdifard** [comment]
wich is bad because people canot change it from the client if they needed too, now the only way that we can change this one later after the config, is to edit the tt5srv.xml i think because there is no way to change this from the client wich is bad.

**Comment by amirmahdifard** [comment]
@bear101 please change the lables of my tikits. teamtalk server for the server one, and client lable for the client problem.

**Comment by amirmahdifard** [comment]
@bear101 i just chekked: this logging delay per IP adress is in QT Client Server propertis, so it is only not in classic client.
