### ISSUE TITLE
switch build system to gradle

### ISSUE THREAD

**Issue by beqabeqa473** [BearWare/TeamTalk5#156]
hello.

maybe it would be better to switch to gradle. with this we'll get more flexibility and eliminate need to worry about dependencies.
gradle will do it instead us.

**Comment by bear101** [comment]
@beqabeqa473 I've create a Android Studio project on this branch

**Comment by beqabeqa473** [comment]
that's great. will check.

**Comment by bear101** [comment]
also @poretsky please use the 'androidstudio' branch if you commit new code

**Comment by bear101** [comment]
Now on master

**Comment by beqabeqa473** [comment]
hi.

should we build a teamtalk5.jar file or where we can get it?

**Comment by bear101** [comment]
In the next SDK the TeamTalk5.jar file is included in the Android Studio project

**Comment by bear101** [comment]
5.1D

**Comment by beqabeqa473** [comment]
is it possible for other devs also to build this library?

is it teamtalkjni?

**Comment by bear101** [comment]
Yes. Run 'make Java' to build teamtalk5.jar
