### ISSUE TITLE
Qt Client: transmition toggles in the channels tree

### ISSUE THREAD

**Issue by amirmahdifard** [BearWare/TeamTalk5#1562]
### Description

if we're pressing the right arrow key on a user or channels, we're suddenly getting to all transmitions toggles that we can toggle them with the space barr key: but please remove  them from here, or please add an option to disable them from the settings, because it is something that can be so annoying for blind users: QT client vertion: 5.11

### Application

- [X] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkServer

**Comment by amirmahdifard** [comment]
this one is important

**Comment by CoBC** [comment]
I really don't see the issue for blind users here. This toggles are accessible for a long time with screenreaders and personally I find this very helpful to quickly see if we are right to transmit any stream type, or change transmission right if we are admin or operator. I suggest to open a discussion if it's really ennoying and see opinion of other users.

**Comment by ChrisDuffley** [comment]
I agree with this. Why would I not want them there? And yes they've been accessible since at least 5.7.1 or so.

**Comment by amirmahdifard** [comment]
@CoBC i didn't say remove them, i said add an option in display tab so we can disable them because of too meny things in the channels tree.
