### ISSUE TITLE
Sound events are played on default output audio device

### ISSUE THREAD

**Issue by CoBC** [BearWare/TeamTalk5#1565]
### Description

Following switch to Qt6 and QSoundEffect, sound events are played on default output audio device instead of device selected in TT preferences.

### Application

- [X] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkClassic
- [ ] TeamTalkServer

### Platform

- [X] Windows
- [X] macOS
- [ ] Android
- [ ] iOS
- [X] Linux

### Expected behavior

Sound events should be played on same device that all TT sounds (device selected in preferences)

### Actual behavior

Sound events are played on default output audio device

### Steps to reproduce problem

1. Start TT and select another output audio device than system default in preferences
2. Do something that play a sound

**Comment by bear101** [comment]
As far as I remember Qt TeamTalk never support TT_InitLocalPlayback(), so sound events have always been played by Qt. I assume Qt uses the default audio device.

**Comment by CoBC** [comment]
DO you think it's possible to retrieve QAudioDevice from id and uid of output device in settings, and force QSoundEffect to play to this device?

**Comment by bear101** [comment]
I think it would be better to switch to TT_InitLocalPlayback(). This could also fix the issue with overlapping sound events.

**Comment by CoBC** [comment]
This can also help to implement the option to choose playback mode, right?
Is it something you can look into?

**Comment by bear101** [comment]
I can look into it in a few days
