### ISSUE TITLE
QT Client: there are some useless information that screen reader shouldn't say them.

### ISSUE THREAD

**Issue by amirmahdifard** [BearWare/TeamTalk5#1566]
### Description

in some places for example again files list or user account list  or server list, screen reader is saying some useless information that you should remove at least some of them: for example, in files list, it is like this.
Name: nvda_2022.3.exe, Size: 26 M, Owner: amirmahdifard, Date: 2022/10/09 10:32  collapsed  row 10  Name  column 1  level 1
in server list, it is like this.
Public server, Name: Australian TeamTalk 5 Server (AU), Users: 0, Country: AU, MOTD: Hello and welcome.  collapsed  row 15  Name  column 1  level 1
in user accounts list, it is like this.
Username: amirmahdifard, Password: blaablaablaa, Type: Administrator, Note: , Initial channel: , Modified: 2022/07/02 11:36  row 1  Username  column 1  level 1
so in these case, at the end, screen reader is saying unrelated things: for example, it says clapst: but these informations are not something that is closed or expanded, it's items in a list: or after klapsed, it says username, or name, first i thort that it saying this one  because it is sorted by username or name, but then i chekked and understand that it's doesn't matter, even if i sort my files by size, it will stil say name at the end of each file: so please remove these information, or at least some of them. they are useless: QT Client vertion: 5.11

### Application

- [X] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkServer

**Comment by CoBC** [comment]
Information about rows and columns are reported because the component have multiple columns, you can disable report of table information for TT in your screenreader if you don't want to have this reported, but we can't remove this. The issue with collapsed state is a Qt issue and I've already reported this to Qt devs (waiting for a fix) ([QTBUG-105734](https://bugreports.qt.io/browse/QTBUG-105734))

**Comment by CoBC** [comment]
About "username" or "name" announce at the end of item, it's because this is the head of first olumn, so it's also related to table information report.
