### ISSUE TITLE
QT client: add TTS event for voice activation and push to talk toggles

### ISSUE THREAD

**Issue by amirmahdifard** [BearWare/TeamTalk5#1568]
### Description

we have sound event for voice activation when we toggle it with controle shift a, but lets say someone doesn't want to use sound event for this and use TTS event that says voice activation disabled or voice activation enabled: and about push to talk, we don't have any TTS event for it, and we don't have sound event for it too, so please add TTS event for this too when we press controle shift t to togle it, it should say push to talk enabled or push to talk disabled: and if you want, you can also add a section for adding a sound event for push to talk toggles in settings sound settings tab: anyway, you've added TTS event for allmoste everything including subscriptions even, so please add TTS event for voice activation and push to talk wich can be toggled using controle shift a and controle shift t or me menu: QT Client vertion: 5.11

### Application

- [X] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkServer

**Comment by CoBC** [comment]
@bear101 Should we add a specific TTS event for this in preferences (for example a new "Voice transmission mode toggle")?

**Comment by amirmahdifard** [comment]
i think that it should be normal tts events like others.

**Comment by bear101** [comment]
You're to add the TTS event
