### ISSUE TITLE
Migrate to Qt6 on Linux

### ISSUE THREAD

**Issue by CoBC** [BearWare/TeamTalk5#1585]
### Description

Currently, we migrated to Qt6.4 on MacOS and Windows with TT5.11. Linux users are still limited to Qt5.15. To allow migrating TT to Qt6 on Linux, we have to rewrite some code because Qt modules specific to X11 has been removed, replaced by native Qt features.
I think we have to look into it to allow Linux users benefit to Qt6 improvements and to align features on all platforms.

### Application

- [X] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkServer

**Comment by bear101** [comment]
Is Qt 6.4 available from Ubuntu 22 mirrors? I.e. can you install it from "apt install"?

**Comment by CoBC** [comment]
I don't know if it's available from mirors, but, at least for test, it's available from Qt installer.

**Comment by bear101** [comment]
I'll close this for now. As I see it we cannot expect users to manually install Qt 6.4. It's too complicated to explain how to use Qt installer/maintenance tool.

**Comment by CoBC** [comment]
@bear101 I see Qt6.4.2 packages available for Ubuntu 23.04. Not sure if you want to switch to Ubuntu 23 or not but I think packages for Ubuntu 22 will not be updated anymore.

**Comment by bear101** [comment]
@CoBC I only see an Ubuntu 23.10. It's not an LTS release. Do you know if Ubuntu 23 has changed to FFmpeg v4 or v5? It might be a big task to convert FFmpeg v3 to newer releases.

**Comment by CoBC** [comment]
23.04 seams to be Lunar, but however you're right it's not a LTS release, next LTS release will be 24.04.
For FFMPEG, 22.04 uses FFMPEG4 and 23.04 uses FFMPEG5

**Comment by CoBC** [comment]
@bear101 Ubuntu 24.04 LTS has been released on april 2024 included Qt 6.4.2.
So do you have any new plan for this issue? Should we now work on it? Or do we still have some reasons to continue using Qt5 for now, maybe related to migration of new FFMPEG releases?

**Comment by bear101** [comment]
Do you remember which Qt6 version introduced QtSpeech? I think it was Qt v6.5. Does it make sense to switch prior to QtSpeech was introduced?

**Comment by CoBC** [comment]
Nope, it was Qt6.4: Qt Speech coming to Qt 6.4 
<https://www.qt.io/blog/qt-speech-coming-to-qt-6.4>
