### ISSUE TITLE
Qt client: a problem with focus of connect to a server dialogue

### ISSUE THREAD

**Issue by amirmahdifard** [BearWare/TeamTalk5#1589]
### Description

so as normal, when i press f2 or select "connect" option from the client menu, i expect that i get the server list and walk between them by using my arrow keys: but moste of the times when i go to connect to a server dialogue, the focus is on host adress edit box, so i have to manully make it to focus on server list: but sometimes when i go to the connect to a server dialogue, it focus on server list, so i'm not sure when it happens, just i can say randomly for now: Qt client vertion: 5.11

### Application

- [X] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkServer

**Comment by CoBC** [comment]
"Connect to a server" dialog is configured to always offer to reconnect to latest host when you open it. So, if your last server isn't in your server list, focus will be move to host adress combobox, otherwise focus will be on server list. So, it's not a bug, but something wanted.
