### ISSUE TITLE
Qt client: a problem with edit box's in connect to a server dialogue

### ISSUE THREAD

**Issue by amirmahdifard** [BearWare/TeamTalk5#1590]
### Description

as you know, in the connect to a server dialogue, there are a fue edit box's that can be fild up: host, TCP UDP ports, user name and pasword and others: when you focus on these box's the NVDA says for example, Username  combo box  public  collapsed  Down and when your editing these box's it's strange: if you have your speak typed characters turned on, when your typing, it says the leters that you typed, but when you press backspace, it doesn't announce the leter as it's got deleted: i feel it;s Qt accessibility again LOL, because normally when this kind of bugs are reported, you said that it's Qt accessibility: i feel it's Qt accessibility because it doesn't focus on the edit box properly, so may be that's wy NVDA doesn't announce the deleted leters as other edit box's and like classic vertion: Qt client vertion: 5.11

### Application

- [X] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkClassic
- [ ] TeamTalkServer

### Platform

- [X] Windows
- [ ] macOS
- [ ] Android
- [ ] iOS
- [ ] Linux

### Expected behavior

when you focus on edit box's on connect to a server dialogue and typing a leter and deleting it, it should announce it as normal, and it should work like other edit box's

### Actual behavior

when you focus on the edit box's on connect to a server dialogue, may be the focus is not happening properly or something, that deleted leters are not announced

### Steps to reproduce problem

1: go to the "connect to a server dialogue
2: focus on one of the edit box's in there
3: type something in there, and then delete your text with backspace

**Comment by CoBC** [comment]
Already reported to Qt and fixed on the Qt side: [QTBUG-107572](https://bugreports.qt.io/browse/QTBUG-107572)
@bear101 This fix will be included on Qt 6.4.2 and 6.5 beta, we have to switch to one of this version when available.
