### ISSUE TITLE
Sound Event Doesn't Play When Using "Default" Mode in TeamTalk 5.12.0.5102 - Unreleased

### ISSUE THREAD

**Issue by lbk2907** [BearWare/TeamTalk5#1594]
### Description

The sound doesn't play when using "Default" mode. This doesn't happend when using "One by One" and "Overlapping" mode.

### Application

- [X] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkClassic
- [ ] TeamTalkServer

### Platform

- [X] Windows
- [ ] macOS
- [ ] Android
- [ ] iOS
- [ ] Linux

### Expected behavior

The sound should play when using "Default" mode.

### Actual behavior

Sound doesn't play when using "Default" mode.

### Steps to reproduce problem

Change the sound playback mode to "Default".

**Comment by lbk2907** [comment]
I just found 1 more situation which the sound event will not play that is when you press Control+M to mute the master volume. It doesn't matter which mode are you on. Whenever the master volume is muted, the sound event also will be muted.

**Comment by bear101** [comment]
@CoBC On Windows with Qt 6.4.1 I get the following error: "qt.multimedia.audiooutput: Failed to setup resampler". Do you see the same?

It works fine on macOS with Qt 6.4.1. I guess it's a bug introduced in Qt 6.4.1 for Windows.

**Comment by jeremyp3** [comment]
Hello,
@bear101 
as indicated in #1578
under linux, with qt5, the sound is cut when playing.

I think my comment was not seen before merger

**Comment by CoBC** [comment]
@bear101 Yes, same here, so maybe just stick on Qt6.4.0 (at least on Windows) for now.

**Comment by bear101** [comment]
https://bugreports.qt.io/browse/QTBUG-108383

**Comment by bear101** [comment]
@lbk2907 When playing "One by one" and "Overlapped" the sound events are played by TeamTalk client. "Default" is played by Windows' audio configuration. I guess we should change the naming to indicate this.

When TeamTalk client handles playback it obeys "master volume" and "mute all" settings.

**Comment by lbk2907** [comment]
Thanks.

**Comment by lbk2907** [comment]
@bearware101
May you explain? I not really get it. Thanks.

**Comment by bear101** [comment]
Should we change it to:
- Platform Sound Device
- TeamTalk Sound Device - One-by-One
- TeamTalk Sound Device - Overlapped

**Comment by lbk2907** [comment]
Maybe? I don’t know well about the coding. Sorry. 😊
The sound event suppose to be played even the master volume is muted. And the sound event volume should not follow the master volume.

**Comment by bear101** [comment]
The Windows playback issue is not present in Qt 6.5

**Comment by lbk2907** [comment]
Are you have plan to add an option to disable sound event? Or that option is already there? Just in case I miss it.

**Comment by CoBC** [comment]
You can press CTRL+Alt+Z or use "Me/Notifications/Enable sound 
events"Message ID: ***@***.***>

**Comment by lbk2907** [comment]
O that. You see? I just miss it. I always use that rofl. 😊
