### ISSUE TITLE
Small delay while playing Sound Events on Overlapping mode (5.12.0.5103 Unreleased)

### ISSUE THREAD

**Issue by StormProductionsMusic** [BearWare/TeamTalk5#1600]
### Description

On other playback modes, Sound Events work just fine. However, when I set the sound events to play on Overlapping mode, they take a small delay of around 250ms to actually play.

Note that i'm not using wireless headphones or any other source that can generate audio delay.

### Application

- [X] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkClassic
- [ ] TeamTalkServer

### Platform

- [X] Windows
- [ ] macOS
- [ ] Android
- [ ] iOS
- [ ] Linux

### Expected behavior

The Sound Events would play imediately, without having any sort of audio delay.

### Actual behavior

There's an estimated delay of around 250ms before playing any audio event on Overlapping mode.

### Steps to reproduce problem

1. Go to Preferences > Sound Events > Playback mode and set this to Overlapping.
2. Try to perform any action that requires a sound event to be played, and notice the small delay that occurs before playing the actual file.

**Comment by amirmahdifard** [comment]
hello, onnistly, i wanted to report this bug, but i thought that developers won't fix it: i agree that overlapping and one by one sounds has more delay, but even default one also has some delay for the sound to play: heh: if you don't notice it, or you don't agree with me, just enough if you compare it with sound events of classic: classic is really fast and has no delay at all. but qt client has some delay: i hope that they manage to fix it.

**Comment by amirmahdifard** [comment]
@CoBC @bear101 these delay of sound events caused some strange problems too: for example, if someone is sending 2 or 3 quick messages, in one by one, the channel messages sounds get a little chokky for me, but i don't have this problem in classic.

**Comment by amirmahdifard** [comment]
@bear101 @CoBC i just found a thing to try help you at least a little: in classic vertion, there is some delay for the all at once mode sound events, but there is no delay at all for others: and in Qt client, there is delay for all modes, but the delay for one by one and overlapping modes are so much, but the delay for the default mode is small

**Comment by amirmahdifard** [comment]
@bear101 @CoBC a fue days ago, i bort a new laptop wich is no longer hdd, it is ssd: and more cpu and ram: now, i don't have any delay for default mode, only one by one and overlapping has delay: also the delay that i had in some tts events wor also fixed.

**Comment by StormProductionsMusic** [comment]
Yes, I can confirm that the delay only occurs when other audio systems are checked.  On WASAPI this doesn’t happen.
