### ISSUE TITLE
Hello, can I use some command to send a broadcast to the online members of the server?

### ISSUE THREAD

**Issue by olsen-zhang** [BearWare/TeamTalk5#1606]
### Description

As stated in the title, I want to use some commands directly through the server to send broadcasts to online users on the server without logging into the administrator account. Is there such a function?

### Application

- [X] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [X] TeamTalkServer

**Comment by bear101** [comment]
There's a user-right called broadcast text messages in "User Accounts" dialog

**Comment by olsen-zhang** [comment]
Sorry, my description is wrong.&nbsp; I mean, I don't want to open the team talk client, but directly send broadcasts to online users on the server through commands.
This command may be done through the DOS command, but I do not know whether this command exists or whether this function does not exist.
&nbsp;


声声上：暗之曙光
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Bjørn Damstedt ***@***.***&gt;; 
发送时间: 2022年11月23日(星期三) 下午3:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [BearWare/TeamTalk5] Hello, can I use some command to send a broadcast to the online members of the server? (Issue #1606)





 
There's a user-right called broadcast text messages in "User Accounts" dialog
