### ISSUE TITLE
The ability to clear history in channel messages

### ISSUE THREAD

**Issue by Medusa5000** [BearWare/TeamTalk5#1610]
### Description

The ability to delete history in channel messages
To avoid the lag if there are  lot of messages on ITeamTalk
 Also, I can't delete the history on QT client

### Application

- [X] qtTeamTalk
- [ ] TeamTalkAndroid
- [X] iTeamTalk
- [ ] TeamTalkServer

**Comment by bear101** [comment]
Please try artifacts from this Action: #1648
