### ISSUE TITLE
Problem with cursor focus in server list using NVDA

### ISSUE THREAD

**Issue by Medusa5000** [BearWare/TeamTalk5#1611]
### Description

When I press f2, the nvda cursor goes to the host's IP address most of the time instead of the server list
So I have to use tab and shift+tab and pass through some unimportant items just to get to my server list which is annoying

### Application

- [X] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkClassic
- [ ] TeamTalkServer

### Platform

- [X] Windows
- [ ] macOS
- [ ] Android
- [ ] iOS
- [ ] Linux

### Expected behavior

When you press f2, the nvda cursor focus moves to the servers list

### Actual behavior

When you press f2, the cursor focuses on the host's IP address instead of server list

### Steps to reproduce problem

- press f2
- Browse some unimportant items using shift+tab to get to the server list

**Comment by CoBC** [comment]
Please see #1589. Duplicate.
