### ISSUE TITLE
teamtalk is not saving my microphone preferences

### ISSUE THREAD

**Issue by Medusa5000** [BearWare/TeamTalk5#1612]
### Description

In teamtalk on IPhone I have to set the default microphone every time I connect to a server
 if I receive a call it will change to the headphones microphone and I have to change it again
I suggest that the microphone preferences saved as is the case with my name and volume ETC. so i don't have to set it Each time I log in

### Application

- [ ] qtTeamTalk
- [ ] TeamTalkAndroid
- [X] iTeamTalk
- [ ] TeamTalkClassic
- [ ] TeamTalkServer

### Platform

- [ ] Windows
- [ ] macOS
- [ ] Android
- [X] iOS
- [ ] Linux

### Expected behavior

teamtalk will save the default microphone selection and no need to set it every time you open the App

### Actual behavior

Every time you open TeamTalk, connect to a server, or receive a call, you have to select the preferred microphone again

### Steps to reproduce problem

1. Open teamtalk
2. Connect to a server
3. Go to preferences and change the default microphone to bottom microphone
4. Disconnect
5. Connect to the same server or any other server
You will notice that the default microphone is changed to the headphone microphone if it is connected

**Comment by bear101** [comment]
Related to #1205
