### ISSUE TITLE
Volume is changed when screen is locked

### ISSUE THREAD

**Issue by bear101** [BearWare/TeamTalk5#162]
Hi there not sure if the forum for the I team talk app is being checked as
often as it used to be but I wanted to let you no about the same volume bug
I'm having when my screen is locked on my I phone 6 I cant adjust the volume
at all if I want to do so I have to unlock the screen completely I'm sorry
for bug reporting vier email but I wouldn't want the app to be submitted to
the app store with this bug unresolved many thanks for all your work martin
Rhodes

**Comment by greenstone1907** [comment]
Hi, also, on lock screen, when we press next song, transmit button is locked and can not be unlocked by the same way. We had to unlock the screen and press stop transmit button to stop ptt. İt should indeed be very nice to have a transmit button on the lock screen.
  ----- Original Message ----- 
  From: Bjoern D. Rasmussen 
  To: BearWare/TeamTalk5 
  Sent: Wednesday, February 3, 2016 8:52 AM
  Subject: [TeamTalk5] Volume is changed when screen is locked (#162)


  Hi there not sure if the forum for the I team talk app is being checked as
  often as it used to be but I wanted to let you no about the same volume bug
  I'm having when my screen is locked on my I phone 6 I cant adjust the volume
  at all if I want to do so I have to unlock the screen completely I'm sorry
  for bug reporting vier email but I wouldn't want the app to be submitted to
  the app store with this bug unresolved many thanks for all your work martin
  Rhodes

**Comment by bear101** [comment]
Duplicate of #218
