### ISSUE TITLE
please change some bat files in teamtalk's directory

### ISSUE THREAD

**Issue by amirmahdifard** [BearWare/TeamTalk5#1632]
### Description

currently, when we install client and server, in the teamtalk's folder, there is 2 files related to tt5svc.exe: one of them are tt5svc install.bat, and the other one is tt5svc uninstall.bat: the install file is installing the servis as you klick on it, and the uninstall one also uninstalls the servis: my suggestion is that to remove these 2 bat files, and make only one bat file instead, called tt5svc manager.bat or something, and when we open this bat file, it should say like, teamtalk nt servis mannager: 1 "install servis": 2 "uninstall servis" select an option: this would be more good if there will be only 1 bat file and can do both install and uninstal: i beleave that you can do this, because there are some projects that made only 1 servis mannager file and that file does both: even, you can add more options to that file if you want too: like, 3 "start servis": 4 "stop servis": 5 "set automatik servis start up": 6 "set manual start up": and as how as you want: i hope you accept my suggestion and i hope i see it in next feucher vertions of teamtalk: tt vertion: 5.11: thanks

### Application

- [ ] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [X] TeamTalkServer

**Comment by bear101** [comment]
I prefer to have separate .bat files. Alternatively you can use the .exe file directly.

**Comment by amirmahdifard** [comment]
please also do this with bat files of teamtalk pro server, wich is tt5prosvc install.bat and tt5prosvc uninstall.bat: thanks

**Comment by amirmahdifard** [comment]
@bear101 yes i know, i'm using that exe file directly, i just gave a suggestion for those who are using the bat files. but ok
