### ISSUE TITLE
No sound when disconnect/reconnect

### ISSUE THREAD

**Issue by CoBC** [BearWare/TeamTalk5#1650]
### Description

Since #1607, when you disconnect from a server and reconnect, no sound is emited and transmited.

### Application

- [X] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkClassic
- [ ] TeamTalkServer

### Platform

- [X] Windows
- [X] macOS
- [ ] Android
- [ ] iOS
- [X] Linux

### Expected behavior

Sound should work normally

### Actual behavior

No sound

### Steps to reproduce problem

Start TT and connect to a first server: sound is working
Now disconnect (F2) and reconnect without restart TT: you have no sound and you are forced to refresh devices.

**Comment by jeremyp3** [comment]
I confirm this bug.

**Comment by bear101** [comment]
@jeremyp3 please try artifacts from #1652

**Comment by jeremyp3** [comment]
thanks @bear101 is fixed ! :)
