### ISSUE TITLE
Add a "New" button on account and server list

### ISSUE THREAD

**Issue by CoBC** [BearWare/TeamTalk5#1657]
### Description

A "New" button must be add to allow clean all fields and recreate a new server or account with default settings. The current way to add a server or an account isn't intuitive for all.

### Application

- [X] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkServer

**Comment by bear101** [comment]
At the moment the button is called "Clear". I don't see why "New" is a more intuitive name.

"New" sounds like you're modifying something. "Clear" means go back to to default.

**Comment by CoBC** [comment]
Oh pff yes, you're right ! I'll have to check better next time.
