### ISSUE TITLE
Server crashes when a channel ban is applied to a user not in a channel

### ISSUE THREAD

**Issue by bear101** [BearWare/TeamTalk5#1659]
### Description

Thread 1 "tt5prosrv" received signal SIGSEGV, Segmentation fault.
0x000055555566f22b in ACE_String_Base<char> operator+<char>(ACE_String_Base<char> const&, ACE_String_Base<char> const&) ()
(gdb) bt
#0  0x000055555566f22b in ACE_String_Base<char> operator+<char>(ACE_String_Base<char> const&, ACE_String_Base<char> const&) ()
#1  0x00005555556da901 in teamtalk::Channel<teamtalk::ServerChannel, teamtalk::ServerUser>::GetChannelPath() const ()
#2  0x00005555556c6cce in teamtalk::ServerNode::UserBan(int, int, teamtalk::BannedUser) ()
#3  0x00005555556e6ee4 in teamtalk::ServerUser::HandleUserBan(std::map<ACE_String_Base<char>, ACE_String_Base<char>, std::less<ACE_String_Base<char> >, std::allocator<std::pair<ACE_String_Base<char> const, ACE_String_Base<char> > > > const&) ()
#4  0x00005555556f6697 in teamtalk::ServerUser::HandleCommand(ACE_String_Base<char> const&, std::map<ACE_String_Base<char>, ACE_String_Base<char>, std::less<ACE_String_Base<char> >, std::allocator<std::pair<ACE_String_Base<char> const, ACE_String_Base<char> > > > const&) ()
#5  0x00005555556f71e2 in teamtalk::ServerUser::ProcessCommand(ACE_String_Base<char> const&, bool) ()
#6  0x00005555556f766a in teamtalk::ServerUser::ProcessCommandQueue(bool) ()
#7  0x00005555556f7788 in teamtalk::ServerUser::ReceiveData(char const*, int) ()
#8  0x00005555556c3d15 in teamtalk::ServerNode::OnReceive(int, char const*, int) ()
#9  0x00005555556e2d2e in StreamHandler<ACE_SOCK_Stream>::handle_input(int) ()
#10 0x000055555573504f in ACE_Select_Reactor_T<ACE_Reactor_Token_T<ACE_Token> >::dispatch_io_set(int, int&, int, ACE_Handle_Set&, ACE_Handle_Set&, int (ACE_Event_Handler::*)(int)) ()
#11 0x00005555557310ba in ACE_Select_Reactor_T<ACE_Reactor_Token_T<ACE_Token> >::dispatch_io_handlers(ACE_Select_Reactor_Handle_Set&, int&, int&) ()
#12 0x0000555555732e16 in ACE_Select_Reactor_T<ACE_Reactor_Token_T<ACE_Token> >::dispatch(int, ACE_Select_Reactor_Handle_Set&) ()
#13 0x000055555573862e in ACE_Select_Reactor_T<ACE_Reactor_Token_T<ACE_Token> >::handle_events(ACE_Time_Value*) ()
#14 0x000055555572c7ed in RunEventLoop(ACE_Reactor*, ACE_Reactor*, ACE_String_Base<char> const&) ()
#15 0x00005555557302d1 in RunServer() ()
#16 0x000055555565f36d in main ()

### Application

- [ ] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkClassic
- [X] TeamTalkServer

### Platform

- [ ] Windows
- [ ] macOS
- [ ] Android
- [ ] iOS
- [X] Linux

### Expected behavior

Process should not crash

### Actual behavior

Crashes with SIGSEGV

### Steps to reproduce problem

Not sure yet :(

**Comment by bear101** [comment]
@CoBC This bug is quite severe, so are you ok that we push the v5.12 release ASAP?

**Comment by CoBC** [comment]
It's OK for me, I have no pending work for now.
