### ISSUE TITLE
Qt client: tts event for vidio transmition enable / disable using controle + shift + v or toggling throo me menu or vidio tab start webcam chek box

### ISSUE THREAD

**Issue by amirmahdifard** [BearWare/TeamTalk5#1666]
### Description

so before, i asked you to do this for voice transmition, so now it would be good if we have it for vidio transmition too since vidio transmition is also togglable using controle shift v or vidio tab or me menu: a new option should be added to text to speech events tab in settings, like vidio transmition mode chek box, and if it's turned on, whenever we press controle shift v toggle the vidio, we should get tts message like vidio transmition enabled and also vidio transmition disabled: qt client vertion: 5.12

### Application

- [X] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkServer

**Comment by amirmahdifard** [comment]
@CoBC yeay, you are good att adding tts, lets goooo open a pr for this! thanks!

**Comment by CoBC** [comment]
I've assigned the issue to myself, but no one here can process all requests as quickly as you would like. Please wait for the issue to go through its normal lifecycle until a contributor develops what you requested.

**Comment by amirmahdifard** [comment]
@CoBC i don't force you or anything, but i just suggest to add this tts: it can be an interesting new tts event for 5.13 change log: one of the interesting about Qt teamtalk is its so meny nice tts events: in text to speech tab, now we have voice transmition toggle, so it is good also if we have the vidio transmition toggle too: so i suggest that you work on this if you want too: thanks.

**Comment by CoBC** [comment]
@bear101 Should I add another TTS event specific to video transmission or just rename the one I added last time for voice activation and PTT from "Voice transmission toggled" to something like: "Transmission type toggled". I just just renaming the existing one can be better to avoid add a large number of events.

**Comment by bear101** [comment]
I think it's better to keep them separate.

**Comment by amirmahdifard** [comment]
@CoBC would you also add a tts event for when we press controle shift d for sharing or stop sharing desktops? so i don't open another tikit for that one again lol: also, when you press f10 in the main menu to show or hide chat history, that one also doesn't have a tts event

**Comment by CoBC** [comment]
I'll open a new PR more later to desktop hsaring. F10 to display or hide 
chat don't exist in Qt client.
