### ISSUE TITLE
Logitech 9000 USB camera no longer working as of 5.11

### ISSUE THREAD

**Issue by CrzyMiky** [BearWare/TeamTalk5#1672]
### Description

logitech 9000 camera no longer recognized, and only shows 'custom video format, and will not initialize.
it worked fine before v5.11. 

### Application

- [ ] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [X] TeamTalkClassic
- [ ] TeamTalkServer

### Platform

- [X] Windows
- [ ] macOS
- [ ] Android
- [ ] iOS
- [ ] Linux

### Expected behavior

I expected to turn on my logitech usb camera, and get video

### Actual behavior

the camera wont initialize

### Steps to reproduce problem

1 start Teamtalk, with logitech camera plugged in to usb port.
2 in preferences, enable logitech 9000 camera
3 select test, and see camera wont initialize

Note that logitech camera utility talks to the cam fine. 
The webcam also works fie in zoom sessions, and it DID work fine
in Teamtalk  also. Something has changed.

**Comment by bear101** [comment]
I looked through the logs from v5.10 to v5.11 and I don't see any changes that should affect video capture. Are you sure it's not this issue #581 you're experiencing?

**Comment by CrzyMiky** [comment]
camera works fine on zoom , and webcam software.
re-installed lastest logitech drivers, and no change.
re-installed TeamTalk, and also no change.
TeamTalk finds the Logitech 9000 pro webcam but no resolution settings
None of the manual ones that the cam supports will work.
The internal cam works fine, though is a lower resolution and higher noise
camera.
This camera DID work fine. something changed.
Thanks for your good work.
Michael Newman
