### ISSUE TITLE
Allow to replace an existing file on upload

### ISSUE THREAD

**Issue by CoBC** [BearWare/TeamTalk5#1684]
### Description

Currently, when we upload a file, if the file exists on the server, we get an error regarding existing file. I think it can be better to offer the ability to replace this existing file.

### Application

- [X] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [X] TeamTalkServer

**Comment by bear101** [comment]
Can't you call TT_DoDeleteFile() prior to TT_DoSendFile() ? This also ensures you don't overwrite someone else's file.

**Comment by amirmahdifard** [comment]
i think that this will need server side code too because uploading a file is interaction with the server

**Comment by amirmahdifard** [comment]
@bear101 but i have a question: wy @CoBC didn't poste this idea in discotions in there?

**Comment by bear101** [comment]
Because @CoBC will address the issue himself.

No one has decided to address the issues you've created or determined if they're relevant.

**Comment by amirmahdifard** [comment]
ok, no problem, so because i'm not a developer, my tikits will closed because the developers are not interested to add them: but really if you look, my suggestions are not bad, they are good for teamtalk softwhere: example: getting a tt file of your servers at once: or ability for stop and resume file upload and download: please tell me that do you see thees feechers bad or unwanted at some point? so what is the problem with them?

**Comment by amirmahdifard** [comment]
@bear101 seriously, you your self as a developer, do you see the ability for getting a .tt file contaning all your servers like android client or ability for poze and resume in upload or download, do you see them bad feechers oe unwanted?

**Comment by Nardol** [comment]
@amirmahdifard  If I understand correctly what @bear101 says, the process is as follow:
1. Open a discussion in ideas section about your desired feature (f e a t u r e)
2. If someone else is interested, you will have answers and it will be possible to have a better frame of development
3. If a developer can manage it, an issue can be created to precise more
4. Then a pull request could be opened to close the issue when it will be merged (m e r g e d)
As a note, you are polluting an issue being off-topic with your complains which is not fair at all. I am not a moderator but I am subscribed to all notifications in TeamTalk and I don't want to unsubscribe an issue I want to follow but want to have the choice to unsubscribe a special discussion where you will debate with @bear101 :slightly_smiling_face: so can you avoid off-topics please? Thank you very much in advance for your consideration about this polite ask.

**Comment by amirmahdifard** [comment]
@Nardol i understand what @bear101 is saying, i just talking to him because he said @CoBC adress his tikits him self, so i was talking about that: but may be if adding an ability to teamtalk project is interested for me, but it mite not be interested for others: thanks.

**Comment by bear101** [comment]
This should be fixed by first calling TT_DoDeleteFile() prior to TT_DoSendFile()
