### ISSUE TITLE
Classroom operator mode inaccessible to visually impaired people in both clients

### ISSUE THREAD

**Issue by atti01** [BearWare/TeamTalk5#169]
The Documentation writes: The checkboxes in front of each user are used to control who can transmit to the channel. 
However with both screen readers jaws 15.0 and nvda latest master build i am not able to find these checkboxes neither on screen nor the hirarchical object window list to control who's allowed to talk in a classroom channel type. Is there any Fix fot these Issues?

**Comment by bear101** [comment]
The menu options for this is under Users -> Advanced. Basically you use Ctrl+Alt+Q, Ctrl+Alt+W, Ctrl+Alt+E

**Comment by bear101** [comment]
Does the shortcuts solve the problem with class-rooms? Then I'll close the issue

**Comment by atti01** [comment]
/I don't know of any Shortcuts to give someone Rights to speak or send
text or whatever when in classroom channel./
The Documentation only speaks of checkboxes besides the usernames when
in this special type of channel, which aren't accessible to screen
readers. Do these checkboxes  only work in the qt client or in the
classic client as well?

Am 18.02.2016 um 22:01 schrieb Bjoern D. Rasmussen:

**Comment by bear101** [comment]
Only the Qt client has checkboxes. The tree control (CTreeCtrl) for the accessible client doesn't support multiple checkboxes.

You cannot control who can send text messages to a channel. Only voice, media file and webcam can be controlled. In the accessible client you do this with Ctrl+Alt + (Q W E).

**Comment by atti01** [comment]
Thanks björn for the reply.
I'll try this out and report it back to you.
btw. The teamtalk accessibility in NVDA using the qt client makes lots 
of progress. These days it makes hardly any difference to the classical 
mfc-client.
But i prefer the classical client anyway, because though very many if 
not nearly all control elements do give feedback in the qt-client i 
think the standard mfc-version of the client is more scriptable in its 
output and behaviour to us.
Might be nice to know if these checkboxes are reachable in tab order 
once the qt-client is open and someone enters a classroom.
Do the shortcuts work in both the clients?
So thanks for this great work again.



Am 21.02.2016 um 09:24 schrieb Bjoern D. Rasmussen:

**Comment by Piciok** [comment]
Hello,

Is there a way to tell with the accessible client who's currently asking for voice?

Last time I tried it there was no indication readable to screenreaders whatsoever.

  ----- Original Message -----

**Comment by bear101** [comment]
You mean "question mode"? You can press Ctrl+G on the user to hear what mode he is (in accessible client).

**Comment by atti01** [comment]
Thanks all is working fine.
You can close this ticket now.
Just couldn't find it in the docs.
Regards, Attila.
