### ISSUE TITLE
Qt client: stream media file to channel dialogue doesn't work normally as expected in some kases

### ISSUE THREAD

**Issue by amirmahdifard** [BearWare/TeamTalk5#1692]
### Description

see, i see this very annoying bug in some other random places, but i don't remember all of them at the moment, but i'm gonna explane it for the stream media file to channel dialogue bug, so you can understand what the bug is: so when you are focusing on a button, and you press enter, it activates another button instead of the current focused button: for example, go to stream media file dialogue, press tab until you reach to browse button: here, if you press enter key, it activates and press's ok button instead of browse button, so if you want to activate browse button, you need to press its shortcut wich is alt + b, or in some kases, you can also press space bar but you can't press enter: qt teamtalk vertion: 5.12

### Application

- [X] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkClassic
- [ ] TeamTalkServer

### Platform

- [X] Windows
- [ ] macOS
- [ ] Android
- [ ] iOS
- [ ] Linux

### Expected behavior

i expect that if you press enter or space or whatever on a focused button, i only get that button activated and not something else

### Actual behavior

if you are focus on a button and you press enter to activate that button, something else is activating

### Steps to reproduce problem

press controle + s or select stream media file option to open stream media file to channel dialogue: press tab until you find browse button, then press enter

**Comment by CoBC** [comment]
I guess we forced enter to browse button. I'll try to improve it.

**Comment by Nardol** [comment]
The key to activate a button is Space, not Enter.
Enter is the key to activate the default button, so to validate the dialog completely.
We sometimes use to press enter to activate a button but it is something we should not do.
Anyway having it fixed would avoid some mistakes from user who have bad habits :slightly_smiling_face:

**Comment by amirmahdifard** [comment]
@Nardol i don't know if you are correct in this kase, from start of my work with computer and windows, with all windows settings, in all aplications that i worked with, even in classic client, enter key is for activating a button that i'm focused on, so that is wy i reported this: this bug is annoying, sometimes i forget to pressed space and i pressed enter and streamed something that i didn't wanted too, and close the dialogue: this is annoying

**Comment by amirmahdifard** [comment]
@CoBC no, this bug should be fixed gemerally: i just exampled the browse button but this bug happens in some other random places, so not only this.

**Comment by amirmahdifard** [comment]
if @Nardol is correct about that, then i can close this: just i want to know what other people think about that.

**Comment by Nardol** [comment]
I am sure of what I say :slightly_smiling_face: 
And JAWS confirm me when tutorial messages are activated, the message is clearly to press space, not Enter.
An explanation: https://stackoverflow.com/questions/16090578/why-do-enter-and-space-keys-behave-differently-for-buttons

The problem is there is no norm about that so behaviors are different in some case.
So the real right answer is to find a consensus :wink:

**Comment by amirmahdifard** [comment]
@Nardol thank you for your answer: i just reported this because i normally got used to press enter for activating a button: so this is working correct and normally, closing as completed.
