### ISSUE TITLE
Qt TeamTalk: the voice activation and push to talk tts events doesn't work if you toggle voice activation and push to talk from general tab in settings

### ISSUE THREAD

**Issue by amirmahdifard** [BearWare/TeamTalk5#1708]
### Description

the tts events of voice activation and push to talk toggle works fine when you toggle them using the me menu or shortcut keys, but when you go to settings and general tab, there is a voice activated chek box, and push to talk chek box's: when you togle them from there and press ok button, their tts events doesn't work and doesn't announce: please make them to work and announce also when you toggle them from the general settings: vertion: 5.13 beta.

### Application

- [X] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkServer

**Comment by CoBC** [comment]
It's not in the habits to use TTS event when changing settings from settings dialog. So, I'm not in favor of this request.

**Comment by amirmahdifard** [comment]
right, closing as completed
