### ISSUE TITLE
Qt client: a problem came up after you did the notification when sound devices added / removed

### ISSUE THREAD

**Issue by amirmahdifard** [BearWare/TeamTalk5#1710]
### Description

so, in 5.13 beta, when i'm using wosappy, so windows audio setion or windows standard but not windows direct sound: and my sound events playback is set to one by one teamtalk sound device: when i play a sound event in my teamtalk, the sound events are cut while playing sometimes: just enough if you try it, you will notice the cutting sound events: vertion: 5.13 beta

### Application

- [X] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkClassic
- [ ] TeamTalkServer

### Platform

- [X] Windows
- [ ] macOS
- [ ] Android
- [ ] iOS
- [ ] Linux

### Expected behavior

the sound events should play with out cutting in wosappy

### Actual behavior

the sound events are cut while playing in wosappy due to the ability that you added.

### Steps to reproduce problem

1: in the 5.13 last out beta vertion, set your sound mode to windows audio setion, or windows standard so you use wosappy but not direct sound
2: play some dsound events in your teamtalk, you will see the cutting sound events problem.

**Comment by bear101** [comment]
I cannot reproduce the issue

**Comment by amirmahdifard** [comment]
@bear101 but when using wosappy and one by one as sound events,  while playing sound events, the sounds are cut a little bit while playing: i don't know how you can't reproduce the problem.
