### ISSUE TITLE
TeamTalk For Android Has No Notification

### ISSUE THREAD

**Issue by lbk2907** [BearWare/TeamTalk5#1714]
### Description

TeamTalk for Android has no notification. Let's say someone receive a private message from another user in the server with TTS event disabled, they will not able to know who sent the message to them. For now, user are rely on TTS event to read the private message to them. If they miss what TTS are saying, there has no way for them to know who sent the message to them. After user know who are messaging them, they need to go to the name who are sent the message to them and press the "message" button to read the message and reply to that message is necessary.

### Application

- [ ] qtTeamTalk
- [X] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkClassic
- [ ] TeamTalkServer

### Platform

- [ ] Windows
- [ ] macOS
- [X] Android
- [ ] iOS
- [ ] Linux

### Expected behavior

User should able to click on the notification icon to read the message sent by another user and reply to it if necessary.

### Actual behavior

TeamTalk notification icon are missing.

### Steps to reproduce problem

I not sure this happend since which version of TeamTalk and on which version of Android. Currently, I'm running Android 13.

**Comment by amirmahdifard** [comment]
for me works fine here

**Comment by lbk2907** [comment]
There has no notification here. I have uninstall and reinstall. The issue 
still same. I think the notification permition. Also doesn't exist.

**Comment by amirmahdifard** [comment]
when i allowed the app notification, it works fine for me

**Comment by lbk2907** [comment]
May I know which Android version you using?

**Comment by lbk2907** [comment]
Which version of Android that you are using? Anyway, I'll check back. Thanks.

**Comment by lbk2907** [comment]
I just try to turn on the TeamTalk notification from the notifications 
settings in the app info but the switch is disabled.

**Comment by beqabeqa473** [comment]
@lbk2907 is issue still reproduceable?

Describe which device model and android version you are using.

**Comment by lbk2907** [comment]
I got two devices here. One is Redmi Note 10 Pro running PixelExperience 
custom rom with Android 13 and the another one is Pixel 7 Pro running 
Android 14 Beta 2. This issue will happend on Android 13 and above. User 
are not able to turn on the notification switch.

**Comment by beqabeqa473** [comment]
I can confirm that it is broken and i've fixed it.
Fix will be available in the next beta.

**Comment by lbk2907** [comment]
Thanks. I'll wait for it!
