### ISSUE TITLE
Qt client: there are 2 unlabled buttons in settings>display>video window settings dialogue under Text Appearance grouping

### ISSUE THREAD

**Issue by amirmahdifard** [BearWare/TeamTalk5#1718]
### Description

in the settings display tab and video window dialogue, in the part where the NVDA screen reader says Text Appearance  grouping, there are 2 unlabled buttons next to each other, and NVDA just says button: may be i can see what is these 2 buttons are related to by using NVDA object navigation, but i'm not sure that if they are really related to these buttons, or they are something else: please lable these 2 buttons correctly: vertion: 5.12 stable.

### Application

- [X] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkServer

**Comment by CoBC** [comment]
@amirmahdifard I've assigned this issue to myself and added this to TeamTalk 5.13 milestone. So, in advance, please don't ping on this issue, I'll work on it.

**Comment by amirmahdifard** [comment]
@CoBC don't worry, wy should i do that, i'm just doing something that everyone would do for a open source project: i'm working with the app, and i'm reporting any bugs that i find, and give my ideas to improve the app, then it is in developers choice to add my idea or fix the bug: since i like this app, sometymes i suggest the developers to do something wich in my apinian can improve the app, but again at the end, it is completely on the developers choice: thank you for your work and the developments
