### ISSUE TITLE
Qt client: microphone emoji isn't reported by screen reader after your own nickname

### ISSUE THREAD

**Issue by ScottChesworth** [BearWare/TeamTalk5#1734]
### Description

Using TeamTalk 5.12 with NVDA 2022.4, it's not possible to tell from a quick check of the channel list whether you're broadcasting or muted, because the microphone emoji that indicates transmission isn't reported after your own nickname. Note that I'm not 100% sure whether it's not appearing visually or not being reported, but either way, it seems like illogical behaviour.

### Application

- [X] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkClassic
- [ ] TeamTalkServer

### Platform

- [X] Windows
- [ ] macOS
- [ ] Android
- [ ] iOS
- [ ] Linux

### Expected behavior

I hear a microphone emoji reported by NVDA after other people's nicknames when they're transmiting audio. I'd expect reporting around my own nickname to be consistent with that.

### Actual behavior

The microphone emoji isn't reported after my own nickname in the channel list when I'm transmitting. Several other users on the server confirmed this behaviour, in that they got the microphone emoji for others, but not after their own nicknames.

### Steps to reproduce problem

1. Load NVDA and join a TT server with at least one other user.
2. Have them hit Control+Shift+A a couple of times, notice how a microphone emoji is reported after their nickname in the channel list when they're transmitting audio, and that the emoji disappears when they're muted.
3. Now hit Control+Shift+A and observe your own nickname in the channel list. No emoji appears irrespective of your mute state.
4. Ask the other user to confirm whether a microphone is reported on their end whenever you're transmitting. You'll find that it is.

**Comment by amirmahdifard** [comment]
the microphone state is working fine for me and works as expected here.

**Comment by CoBC** [comment]
I cannot reproduce the issue.

**Comment by ChrisDuffley** [comment]
@ScottChesworth & @CoBC, I also could never repro at all. Are you sure you're not having audio issues on your end/are others not hearing you? Also, the reason why it could be going in and out is because your voice activation could be greater than 0 and with quieter backgrounds the mic could go back off. If it's at 0, it will not go off at all.

**Comment by ScottChesworth** [comment]
I think this was a local issue, or rather, two localized issues where both people involved in my test had an NVDA add-on set to strip emojis. Oops! Sorry about the false alarm. Closing this now.
