### ISSUE TITLE
TeamTalk sdk: use python sounddevice library to stream audio rather than input device.

### ISSUE THREAD

**Issue by denizsincar29** [BearWare/TeamTalk5#1737]
### Description

Hello. I wanted to stream a wav file that is prepared from tts engine, with teamtalk sdk. but I only have option to stream from an input device.
please give us an ability to stream from direct audio raw data using sounddevice library. (pip install sounddevice).

### Application

- [ ] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkServer

**Comment by beqabeqa473** [comment]
Streaming raw audio data is supported in TeamTalk sdk.
You can insert audio blocks to input audio data.
see [](http://www.bearware.dk/teamtalksdk/v5.12a/docs/C-API/group__transmission.html#gac3efce380265ba02123a5388b803be90)

**Comment by denizsincar29** [comment]
Beqa, I am not familiour with c or c++ so I want to have it directly in python. I know I'm so lazy but why python binding doesn't have all functions of sdk?

**Comment by denizsincar29** [comment]
Hah! if teamtalk sdk have ability to transmit raw data, than why does ttmediabot use virtual audio cable?

**Comment by beqabeqa473** [comment]
If high-level api of python bindings doesn't have functionality, it will likely be in low-level bindings

**Comment by beqabeqa473** [comment]
> Hah! if teamtalk sdk have ability to transmit raw data, than why does ttmediabot use virtual audio cable?

It is out of scope of this issue and this project.

If some project is not using functionality go ahead and ask there
