### ISSUE TITLE
Add few events in Teamtalk protocol

### ISSUE THREAD

**Issue by beqabeqa473** [BearWare/TeamTalk5#1743]
### Description

Hello.

While working on one project, i've discovered that i need to get a list of user accounts to check for an account availability before adding it.
But the probelm is that if server will have a large amount of user accounts and if will fetch them in every ajax call, we will faze with non-needed resource consume.

I am happy to cash user account on client start, but in this case if an admin will delete or create user account manually within the client, i won't be notified of that change.

So i suggest to add events for adding and removing user accounts, and while on it, maybe add events for connecting and disconnecting users, so we can do some stuff depending on these events.

@bear101 what do you think about that?

### Application

- [ ] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [X] TeamTalkServer

**Comment by bear101** [comment]
I don't really see the need for this feature

**Comment by beqabeqa473** [comment]
Maybe for last two events there is not so much need, but as for user account adding and removing i think i described an usecase.
If for example we are doing web registration system, it would be good to check for an account availability just before registering an user to not create an unnecesary entry in database.
To check for username, we need to fetch accounts list all the time, because we don't know if some of admins added or deleted an account during request.
If these events would be implemented, we could cache accounts on start of registration backend, and after dependeing on account addition or deletion adjust our cache.

**Comment by beqabeqa473** [comment]
I think i might be able to implement it myself.

Will try to come with pr later today

**Comment by beqabeqa473** [comment]
Sorry for some junk here. I accidentally pushed to wrong place.
