### ISSUE TITLE
Noise Reduction not working after connecting to a server

### ISSUE THREAD

**Issue by atti01** [BearWare/TeamTalk5#175]
Hello,
The noise reduction in the classic client isn't working after connecting to a server. After switching between channels back and ford it's working fine again. The qt-client doesn't have these issues. I am running 64 bit win7. Interestingly i have to connect from the root chjannel which is opus 32k mono to another opus channel for the noise rduction to kick in. If i switch to a speex-channel and back to the opus-rootchannel again, the noisereduction doesn't kick in. 2 other folks using the classic client had the same issue. Is there any way to find out what's causing the issue and report it back to you?

**Comment by bear101** [comment]
Please try this version and see if it fixes the problem:
http://bearware.dk/test/TeamTalkClassic_v5.1.3.4575_Portable.zip
