### ISSUE TITLE
iOS: Audio stops if switching from LTE to WiFi

### ISSUE THREAD

**Issue by Simon818** [BearWare/TeamTalk5#176]
The title pretty much says it all. I'm assuming iOS does some kind of smart network handling in order to make the connection remain in place after connecting to WiFi. TeamTalk stays connected to the server when this happens, but there's no audio whatsoever. I've found that restarting the server to cause the connection to break (and therefore an automatic reconnect attempt) can fix this, as well as the expected solution of reconnecting from iOS. This is frustrating because most people don't know it will happen, and one has to contact them some other way to tell them to reconnect in order to fix it. I should also preface this by saying that I've only seen this on one device, so I would be happy to test with other people if this isn't easily reproducible.

**Comment by stickbear2015** [comment]
I can reproduce this, and the reverse as well going from wifi to LTE, 
audio dies requiring a reconnect but the base connection to the server 
stays alive.

**Comment by Simon818** [comment]
This is still present in latest iTeamTalk and happens on every device I've tested. It seems to have something to do with the UDP connection not being re-established when the IP address changes, but I could be wrong. This is a huge problem for anyone who actually moves around with their phone though.

**Comment by bear101** [comment]
Apparently a TCP connection on 3G stays active although the device switches to wifi whereas the UDP connection seems to send packets on the wifi instead.

**Comment by bear101** [comment]
Fixed in 5.2.1.4773
