### ISSUE TITLE
Systemd unit file for server

### ISSUE THREAD

**Issue by leonardder** [BearWare/TeamTalk5#181]
The TT server distributions currently only contain a classic init script to run the server at startup. Since Debian 8+ and Centos 7 use systemd, it would be nice if at least the centos7 server distribution contains a systemd unit.
I'm using the current unit myself:

```
[Unit]
Description=TeamTalk 5 server daemon
After=network.target

[Service]
ExecStart=/usr/bin/tt5srv -nd -c /etc/teamtalk/tt5srv.xml -l /var/log/teamtalk/tt5srv.log
Type=simple
User=teamtalk
Group=teamtalk
StandardOutput=syslog
StandardError=syslog

[Install]
WantedBy=multi-user.target
```

**Comment by bear101** [comment]
Shouldn't it be "tt5srv -d" instead of "tt5srv -nd"? Otherwise the startup script will hang in the startup (not detaching).

**Comment by leonardder** [comment]
It workds properly with -nd with a service type of simple. -nd is also possible, but that requires service type forking and setting the pidfile in the service as well. I could rewrite the service to a forking one, if that's the prefered behavior. But the current one works as expected, I use it in production.

**Comment by bear101** [comment]
I think the -d option is the preferred. Otherwise you cannot stop/restart the service. There's a pid-file option for tt5srv and I guess it should point to /var/run/tt5srv.pid.

**Comment by leonardder** [comment]
Restarting the server also works without problems here. It's just how systemd works with simple services. However, since the init script also uses daemon mode, I guess it would be more in line with that as well as the standards to create a forking service. I'll dive into it today.

**Comment by leonardder** [comment]
The following also works as expected, as long as the teamtalk user has write access to /run/teamtalk

```
[Unit]
Description=TeamTalk 5 server daemon
After=network.target

[Service]
Type=forking
ExecStart=/usr/bin/tt5srv -d -c /etc/teamtalk/tt5srv.xml -l /var/log/teamtalk/tt5srv.log -pid-file /run/teamtalk/tt5srv.pid
PIDFile=/run/teamtalk/tt5srv.pid
User=teamtalk
Group=teamtalk

[Install]
WantedBy=multi-user.target
```

Furthermore, to get more in sync with the init script, do we want the binary to live in /usr/bin or in /home/tt/tt5? Do we want user teamtalk or user tt?

**Comment by bear101** [comment]
Probably location of binary, log file and configuration file should be user configurable, since there's no package installer with TeamTalk. Also user account should be configurable

```
BIN=/usr/bin/tt5srv
CFGFILE=/etc/teamtalk/tt5srv.xml
LOGFILE=/var/log/teamtalk/tt5srv.log
PIDFILE=/run/teamtalk/tt5srv.pid
USER=tt

[Service]
Type=forking
ExecStart=su $USER -c "$BIN -d -c $CFGFILE -l $LOGFILE -pid-file $PIDFILE"
...
```
Would that work? I'm not familiar with systemd

**Comment by leonardder** [comment]
That will not work out of the box. You can do two things

1. Set the variables in the systemd unit itself using Environment=variable=value
2. Use an environment variable file, like EnvironmentFile=/etc/conf.d/tt5srv and include that file in both the systemd unit as well as in the init script.

**Comment by bear101** [comment]
tt5srv is not in /usr/bin "out of the box". The user has to do the installation of the TeamTalk server manually anyway (by copying files).

**Comment by bear101** [comment]
I've added the first systemd setup file to the TeamTalk Linux package:
https://github.com/BearWare/TeamTalk5Setup/tree/master/Server/Linux
Thanks a lot! It will be included in the next release.
