### ISSUE TITLE
Use both microphones on stereo channels in all samsung phones

### ISSUE THREAD

**Issue by shaghayegh1382** [BearWare/TeamTalk5#1819]
### Description

Only right microphone is used in some samsung phones in stereo channels, such as galaxy a31, a32, and a22

### Application

- [ ] qtTeamTalk
- [X] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkClassic
- [ ] TeamTalkServer

### Platform

- [ ] Windows
- [ ] macOS
- [X] Android
- [ ] iOS
- [ ] Linux

### Expected behavior

Use both microphones in stereo channels in galaxy a31, a32, and a22

### Actual behavior

In stereo channels, Only right microphone is being used on some samsung phones, such as galaxy a31, a32, and a22

### Steps to reproduce problem

Step 1: Buy one of these samsung phones: Galaxy a31, Galacy a32, and galaxy a22.
step 2: Install latest version of the team talk from the play store.
Step 3: Enter to a private or public server.
Step 4: Create a stereo channel, bitrate 64000, and samplerate 48000.
Step 5: Give microphone permission for team talk on your phone and see that your audio is being transmited with the right microphone, so your audio is mono in a stereo channel.
Step 6: Install high q mp3 voice recorder or one recorder software which can record stereo files.
Step 7: Check the "stereo, use both microphones if available" option.
Step 8: Record your audio and hear it. You will see your voice is recorded with both microphones, so its stereo.
Step 9: Conclusion: This issue happens in team talk only.

**Comment by bear101** [comment]
#1762
