### ISSUE TITLE
Add Move users dialog to Qt client

### ISSUE THREAD

**Issue by CoBC** [BearWare/TeamTalk5#1833]
### Description

Currently, the only way to move users in Qt client is to select users on channel tree than move it to channel we wish.
In classic client, a dialog was present to allow moving users quickly. A similar dialog should be added to Qt client with a list of checkboxes to choose users to move, and a combobox to choose channel.

### Application

- [X] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkServer

**Comment by amirmahdifard** [comment]
in classic client, we could only move one person using that dialogue: but if you want to add this dialog to qt client, please let  us move as more people as we want to select, and not only one.
