### ISSUE TITLE
bug to import servers by a .tt file in android 11 and above

### ISSUE THREAD

**Issue by vrivri123** [BearWare/TeamTalk5#1836]
### Description

When trying to import a file, it returns to the main window with the servers, but the file I imported is not there.

### Application

- [ ] qtTeamTalk
- [X] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkClassic
- [ ] TeamTalkServer

### Platform

- [ ] Windows
- [ ] macOS
- [X] Android
- [ ] iOS
- [ ] Linux

### Expected behavior

It should import the file and show the server in the list, just like it does with clients for other platforms.

### Actual behavior

Cannot import files

### Steps to reproduce problem

1. Open the app. 2. Click on more options. 3. Click on import from a file and choose the file.

**Comment by bear101** [comment]
#1182
