### ISSUE TITLE
Bug uploading files to a channel, apparently on Android 11 and above

### ISSUE THREAD

**Issue by vrivri123** [BearWare/TeamTalk5#1837]
### Description

When selecting a file to be sent, absolutely nothing happens. I can wait for hours that the file won't. There is no progress bar or anything like that.

### Application

- [ ] qtTeamTalk
- [X] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkClassic
- [ ] TeamTalkServer

### Platform

- [ ] Windows
- [ ] macOS
- [X] Android
- [ ] iOS
- [ ] Linux

### Expected behavior

The file should be uploaded, and the file tab should show a progress bar to let the user know how the upload is going.

### Actual behavior

Nothing happens when trying to send a file

### Steps to reproduce problem

1. Join a channel with file upload enabled. 2. Click on send file and select the file to be sent.

**Comment by bear101** [comment]
#1182
