### ISSUE TITLE
QtTeamTalk Mainland China cannot publish its own server publicly### 

### ISSUE THREAD

**Issue by xyzs0000** [BearWare/TeamTalk5#1843]
### Description

Hello, I am a loyal user of QT from China. Feedback for the next question. I released my server publicly as required in the qtf2 menu. He said that the release was successful, but I can’t see it in the server list. After testing, as long as the server is in China The mainland, and the ip address, is not successful for mainland China. This problem started on January 15, 2023, and it has been like this until now. I hope it can be resolved. Thank you.

### Application

- [X] qtTeamTalk
- [X] TeamTalkAndroid
- [ ] iTeamTalk
- [X] TeamTalkServer

**Comment by xyzs0000** [comment]
### My server address is tt.xyzswd.net tcp port 20000 udp port 20000 username 0000 password 0000

**Comment by bear101** [comment]
The server seems to work fine

**Comment by xyzs0000** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "BearWare/TeamTalk5"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月22日(星期六) 凌晨2:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [BearWare/TeamTalk5] QtTeamTalk Mainland China cannot publish its own server publicly###  (Issue #1843)





 
The server seems to work fine
