### ISSUE TITLE
Suggestion to Automate TeamTalk Updates:

### ISSUE THREAD

**Issue by Muamalaljanahi** [BearWare/TeamTalk5#1853]
### Description

At present, updating TeamTalk requires a manual visit to the program page and downloading the update, which can be time-consuming and inconvenient. Most programs automatically update themselves with user approval, making the process seamless. It would be helpful to implement an automatic update feature in TeamTalk as well, which would save users time and effort.

### Application

- [X] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkServer

**Comment by bear101** [comment]
Duplicate #1739
