### ISSUE TITLE
Suggestion to improve the Connect to a Server dialog with Screen readers

### ISSUE THREAD

**Issue by Muamalaljanahi** [BearWare/TeamTalk5#1858]
### Description

Currently if the last connected server is not in the Saved Servers List focus will be placed on the Host Address field automatically. This is very annoying for screen reader users, especially those who often connect to public servers
I suggest adding a shortcut to move nvda focus to the Saved Servers List to avoid this problem

### Application

- [X] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkServer

**Comment by CoBC** [comment]
@bear101 This one is something we can easily do with the same way as did on mainwindow.ui for tabs but it will requires a new translation update so maybe wait for the next release?

**Comment by bear101** [comment]
I've tagged and pushed out v5.13, so just go ahead.

**Comment by Muamalaljanahi** [comment]
@CoBC  still waiting

**Comment by CoBC** [comment]
This is probably not requires anymore with new host manager.
