### ISSUE TITLE
server: a bug with the new argument -cleanfiles that you've added.

### ISSUE THREAD

**Issue by amirmahdifard** [BearWare/TeamTalk5#1862]
### Description

when you try run this argument, it's good when it says witch files it is skipping, but at the first, it says 2 times like this:
Skipping file .
Skipping file ..
so it's not the name of any files at the first 2 times when it talks about skipping, please fix this.

### Application

- [ ] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkClassic
- [X] TeamTalkServer

### Platform

- [X] Windows
- [ ] macOS
- [ ] Android
- [ ] iOS
- [ ] Linux

### Expected behavior

when you run the cleanfiles argument, it should only say skipping file and the files name that are in that folder.

### Actual behavior

when you run the cleanfiles argument, at the first, 2 times it says skipping file with 2 dots at the end, even tho that kind of file is not exist in my folder
Skipping file .
Skipping file ..
like this.

### Steps to reproduce problem

1: run the -cleanfiles aregument in the cmd of your windows, and look at the results it gives you, look at the 2 first skipping files result, the rest is ok, at least for me, it was the first 2 ones and that's all: vertion: 5.13

**Comment by bear101** [comment]
I don't see the "bug" in this.

**Comment by amirmahdifard** [comment]
@bear101 why it says skipping file 2 times with nothing at the end? you are just being unrisponcable

**Comment by ChrisDuffley** [comment]
@Nardol: I agree with you here. I, like @Bear101, also don't see a bug here based on what both of you said.

Thanks!
