### ISSUE TITLE
Whenever I try to install TeamTalk v5.13 Classic, the installer still reports it has v5.10 installed and hasn't seemed to have upgraded the program at all. 

### ISSUE THREAD

**Issue by trancer1994** [BearWare/TeamTalk5#1863]
### Description

Hi, 

I'd like to report a really, really annoying bug. 

I've just downloaded v5.13 to try on my Windows PC (I've installed the Classic client and server). When I try to install the client and server of the latest version and I launch it, it's as if it hasn't upgraded anything at all because it just says v5.10, which is the last version I had before I tried to upgrade. On the other hand I try to upgrade to v5.12 (or at least, that's the version it wants) of QT, but when I try to install that one it just brings me back to the same upgrade screen in an endless loop which caused me to try to install v5.12 of that client in the first place. 

So basically: 

Everytime I try to upgrade from v5.10 of Classic to v5.13 of Classic, it installs the new version but still reports that I have v5.10 installed.
When I upgrade from v5.10 of QT to v5.12 it installs something, but again reports v5.10 and asks me whether I want to upgrade to v5.12, which is how I apparently got v5.12 in the first place. 

Please fix this because it is really, really annoying. 

### Application

- [X] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [X] TeamTalkClassic
- [ ] TeamTalkServer

### Platform

- [X] Windows
- [ ] macOS
- [ ] Android
- [ ] iOS
- [ ] Linux

### Expected behavior

The installer should install the new version of TeamTalk, and run the new version of it upon clicking Finish. Same with QT.

### Actual behavior

The installer installs the new version of TeamTalk but runs the version I had installed before the upgrade. Same with QT, but it says there is a new version available, 5.12.

### Steps to reproduce problem

Please fix this issue.

**Comment by ChrisDuffley** [comment]
Can you try uninstalling TT and reinstalling just v5.13 and see if it returns the new one upon launch? I've never had this issue on any of my machines. I've noticed that the %appdata%\BearWare.dk folder doesn't get deleted in the process, but I'd still copy the XML and INI files before uninstalling so you don't lose them.

**Comment by bear101** [comment]
I cannot reproduce the issue
