### ISSUE TITLE
Teamtalk crash when you go to the text to speech preferences several times

### ISSUE THREAD

**Issue by jeremyp3** [BearWare/TeamTalk5#1866]
### Description

Hello, 

I post a special crash of teamtalk, with the parameter tts.

personally, I have only tested on linux

to get in condition.
1. open the teamtalk preferences, go to the speech to text tab, then select default and validate

real result :
teamtalk crashes
expected result :
display the text-to-speech preferences

### Application

- [x] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkClassic
- [ ] TeamTalkServer

### Platform

- [ ] Windows
- [ ] macOS
- [ ] Android
- [ ] iOS
- [x] Linux

### Expected behavior

open the preferences text-to-speech

### Actual behavior

teamtalk crashes

### Steps to reproduce problem

reproduce the crash
1. open the preferences then go to the text to speech tab. do not touch anything then do escape to close the preferences
2. reopen the preferences then try to go to the text-to-speech tab.

**Comment by Nardol** [comment]
I confirm the fix.
If TTS is set to default (so QT), if we open the preferences, go to Text to speech tab, close preferences without saving then go back to preferences->TTS tab, TeamTalk crashes instead of displaying preferences again.

**Comment by bear101** [comment]
I cannot reproduce this issue.

**Comment by bear101** [comment]
Ups, clicked wrong issue.

**Comment by jeremyp3** [comment]
no reproduce this issue with teamtalk 5.17
