### ISSUE TITLE
Implement the ability to ban mac addresses of undesirable people from servers

### ISSUE THREAD

**Issue by trancer1994** [BearWare/TeamTalk5#1867]
### Description

I would like to suggest that you implement the ability on all TeamTalk platforms to ban the mac addresses of undesirable people from servers, as well as their ip addresses and usernames, as an option in the list, or a standalone command, depending on what you wish to do, or what would be easier. Examples are certain people on public servers who spam a lot, or people who are genuinely causing trouble on other servers. The banning of all their mac addresses would ensure that they never came back to said server they were banned from. This would also bypass the need to implement an option to ban vpns, because vpns are only ips, and they are temporary, as in you can come back to the server on a new ip, whereas with a mac address being banned you wouldn't be able to come back again on said mac address, because a mac address is unique to every device, and no two devices have the same mac address. 

Perhaps you could implement this feature in the next version of the client, or maybe release an update to this one with that feature in it. 

### Application

- [X] qtTeamTalk
- [X] TeamTalkAndroid
- [X] iTeamTalk
- [X] TeamTalkServer

**Comment by bear101** [comment]
Your mac-address is not transmitted on the internet. Please read up on how [TCP/IP works](https://en.wikipedia.org/wiki/Internet_protocol_suite).
