### ISSUE TITLE
TCP and UDP Port Cursor Should at the End

### ISSUE THREAD

**Issue by lbk2907** [BearWare/TeamTalk5#1886]
### Description

For now, when you want to enter the TCP port and UDP port, the cursor is at the beginning of the edit box with the default port set which is 10333. That's mean the cursor at before the number 1. If user want to clear the number, they need to move the cursor to the end manually before they can delete the default port and enter the new one.

### Application

- [ ] qtTeamTalk
- [X] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkServer

**Comment by bear101** [comment]
Isn't this default behaviour on Android?

**Comment by lbk2907** [comment]
If I not mistaken, yes. I not sure this happened since which version of TeamTalk. It will be nice if the cursor put at the end when user want to edit the port. Some user complain to me that they cannot delete the default port but actually the cursor is at the beginning of the text box.

**Comment by CoBC** [comment]
Why not just move cursor to end before deleting text? If this is considere as accessibility problem, TalkBack has a way to move cursor to end easily. If is not accessibility, cursor can easily be move by touching place to place cursor.

**Comment by jeremyp3** [comment]
I'm also in favor of the cursor being at the end of the text zone. if it's possible to modify it on the teamtalk side, why not? it would be more practical for everyone. for example, if you want to modify the port from 10333 to 10335, with talkback you need to do a lot of manipulations, whereas here you'd just have to erase the last 3 to put a 5 to make 10335

**Comment by lbk2907** [comment]
But the cursor is at the end for other text box except TCP and UDP port.

**Comment by bear101** [comment]
Closing because no one has provided a way for how this should be solved.
