### ISSUE TITLE
Crash when opening TTS preferences

### ISSUE THREAD

**Issue by CoBC** [BearWare/TeamTalk5#1895]
### Description

It's probably related to a recent commit from @beqabeqa473
Config: Android 13, TT 5.14.0.5118 (build 121)

### Application

- [ ] qtTeamTalk
- [X] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkClassic
- [ ] TeamTalkServer

### Platform

- [ ] Windows
- [ ] macOS
- [X] Android
- [ ] iOS
- [ ] Linux

### Expected behavior

TTS preferences should open

### Actual behavior

TT crash

### Steps to reproduce problem

* Open the app
* GO to More options/Preferences
* Go to Text-To-Speech

**Comment by beqabeqa473** [comment]
Cannot confirm a bug.

Please, provide more information including logs

On 5/30/23, Corentin Bacqué-Cazenave ***@***.***> wrote:
> Assigned #1895 to @beqabeqa473.
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/BearWare/TeamTalk5/issues/1895#event-9377206758
> You are receiving this because you were assigned.
>
> Message ID:
> ***@***.***>


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by bear101** [comment]
I've tried on API 30, 31 and 33 but don't see any crashes.

**Comment by jeremyp3** [comment]
I confirm that I reproduce the crash under Android 10. 

I tried to put my phone in English, and the crash also occurs.

**Comment by bear101** [comment]
@beqabeqa473 should I revert the change and push a new release? I cannot figure out why its crashing.

**Comment by beqabeqa473** [comment]
Could you get crash from google play console or that folks who has
crash provide logs so we could identify the problem.

On 6/2/23, Bjørn Damstedt Rasmussen ***@***.***> wrote:
> @beqabeqa473 should I revert the change and push a new release? I cannot
> figure out why its crashing.
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/BearWare/TeamTalk5/issues/1895#issuecomment-1574158063
> You are receiving this because you were mentioned.
>
> Message ID: ***@***.***>


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by CoBC** [comment]
The logs I attached previously aren't sufficient? I don't know how to 
get more logs

**Comment by beqabeqa473** [comment]
You didn't atach anything

On 6/3/23, Corentin Bacqué-Cazenave ***@***.***> wrote:
> The logs I attached previously aren't sufficient? I don't know how to
> get more logs
>
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/BearWare/TeamTalk5/issues/1895#issuecomment-1574273666
> You are receiving this because you were mentioned.
>
> Message ID: ***@***.***>


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by beqabeqa473** [comment]
Aah, sorry, you've edited a comment. Will look at it.

**Comment by beqabeqa473** [comment]
Crash says that it is not possible to fetch list of engines.
This code was not changed.
Why you have that bug i have no idea.
You should have this bug also in earlier versions of teamtalk.
Unfortunately, i have no possibility for now to debug or write
something because i have no computer here.

On 6/3/23, Beqa Gozalishvili ***@***.***> wrote:
> You didn't atach anything
>
> On 6/3/23, Corentin Bacqué-Cazenave ***@***.***> wrote:
>> The logs I attached previously aren't sufficient? I don't know how to
>> get more logs
>>
>>
>> --
>> Reply to this email directly or view it on GitHub:
>> https://github.com/BearWare/TeamTalk5/issues/1895#issuecomment-1574273666
>> You are receiving this because you were mentioned.
>>
>> Message ID: ***@***.***>
>
>
> --
> with best regards Beqa Gozalishvili
> Tell: +995593454005
> Email: ***@***.***
> Web: https://gozaltech.org
> Skype: beqabeqa473
> Telegram: https://t.me/gozaltech
> facebook: https://facebook.com/gozaltech
> twitter: https://twitter.com/beqabeqa473
> Instagram: https://instagram.com/beqa.gozalishvili
>


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by bear101** [comment]
On Google Play I can only find crash reports on Production releases. I cannot find any on "Open Testing" track.

In TeamTalk v5.13 I see this crash report:
`Exception java.lang.NullPointerException:
  at dk.bearware.data.TTSWrapper.getEngines (TTSWrapper.java:69)
  at dk.bearware.gui.PreferencesActivity$TtsPreferenceFragment.onCreate (PreferencesActivity.java:402)
  at android.app.Fragment.performCreate (Fragment.java:2486)
  at android.app.FragmentManagerImpl.moveToState (FragmentManager.java:1261)
  at android.app.FragmentManagerImpl.addAddedFragments (FragmentManager.java:2431)
  at android.app.FragmentManagerImpl.executeOpsTogether (FragmentManager.java:2210)
  at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute (FragmentManager.java:2166)
  at android.app.FragmentManagerImpl.execPendingActions (FragmentManager.java:2067)
  at android.app.FragmentManagerImpl$1.run (FragmentManager.java:742)
  at android.os.Handler.handleCallback (Handler.java:938)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loopOnce (Looper.java:241)
  at android.os.Looper.loop (Looper.java:342)
  at android.app.ActivityThread.main (ActivityThread.java:8143)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:583)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1045)`

**Comment by beqabeqa473** [comment]
That is very strange.

Nothing was changed in this case when i was working on it.

I think 5.13 itself has this problem.
When you made refactorings you removed check on null and for some
reason, if tts is not initialising, npe is throwing.
If you can re-add these checks, i think exceptions won't happen anymore.
But why tts is not initializing on some devices that is a question.
Unfortunately i am not able to work on this for several days as i
don't have access.

On 6/3/23, Bjørn Damstedt Rasmussen ***@***.***> wrote:
> On Google Play I can only find crash reports on Production releases. I
> cannot find any on "Open Testing" track.
>
> In TeamTalk v5.13 I see this crash report:
> `Exception java.lang.NullPointerException:
>   at dk.bearware.data.TTSWrapper.getEngines (TTSWrapper.java:69)
>   at dk.bearware.gui.PreferencesActivity$TtsPreferenceFragment.onCreate
> (PreferencesActivity.java:402)
>   at android.app.Fragment.performCreate (Fragment.java:2486)
>   at android.app.FragmentManagerImpl.moveToState
> (FragmentManager.java:1261)
>   at android.app.FragmentManagerImpl.addAddedFragments
> (FragmentManager.java:2431)
>   at android.app.FragmentManagerImpl.executeOpsTogether
> (FragmentManager.java:2210)
>   at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute
> (FragmentManager.java:2166)
>   at android.app.FragmentManagerImpl.execPendingActions
> (FragmentManager.java:2067)
>   at android.app.FragmentManagerImpl$1.run (FragmentManager.java:742)
>   at android.os.Handler.handleCallback (Handler.java:938)
>   at android.os.Handler.dispatchMessage (Handler.java:99)
>   at android.os.Looper.loopOnce (Looper.java:241)
>   at android.os.Looper.loop (Looper.java:342)
>   at android.app.ActivityThread.main (ActivityThread.java:8143)
>   at java.lang.reflect.Method.invoke
>   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run
> (RuntimeInit.java:583)
>   at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1045)`
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/BearWare/TeamTalk5/issues/1895#issuecomment-1574689466
> You are receiving this because you were mentioned.
>
> Message ID: ***@***.***>


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by bear101** [comment]
@beqabeqa473 you're referring to "tts" in TTSWrapper? It is always assigned a value in the two constructors.

**Comment by CoBC** [comment]
Could this bug be related to TTS engines installed in the phone? For my 
part I have Google TTS, Samsung TTS, Vocalizer and Jieshuo TTS.

**Comment by beqabeqa473** [comment]
I mean it may be null and getEngines might throw an exception.

Is it working just speaking an event to them who has this problem?

On 6/3/23, Bjørn Damstedt Rasmussen ***@***.***> wrote:
> @beqabeqa473 you're referring to "tts" in TTSWrapper? It is always assigned
> a value in the two constructors.
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/BearWare/TeamTalk5/issues/1895#issuecomment-1574832205
> You are receiving this because you were mentioned.
>
> Message ID: ***@***.***>


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by CoBC** [comment]
Yes, I just tested and the event is speak using Google TTS.

**Comment by beqabeqa473** [comment]
I have no idea how it is related to tts. Ok, if manager becomes null,
then speak should not work with screenreaders but how it is related to
tts.

On 6/6/23, Bjørn Damstedt Rasmussen ***@***.***> wrote:
> @beqabeqa473 it's TTSWrapper.java:69 that is causing a
> NullPointerException.
>
> So 'manager' in this line becomes null:
> `AccessibilityManager manager = (AccessibilityManager)
> mContext.getSystemService(Context.ACCESSIBILITY_SERVICE);`
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/BearWare/TeamTalk5/issues/1895#issuecomment-1579250879
> You are receiving this because you were mentioned.
>
> Message ID: ***@***.***>


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by bear101** [comment]
Should we change TTSWrapper.speak() to this?

`
    public void speak(String text) {
            AccessibilityManager manager = (AccessibilityManager) mContext.getSystemService(Context.ACCESSIBILITY_SERVICE);
        if (this.useAnnouncements && manager != null && manager.isEnabled()) {
                AccessibilityEvent e = AccessibilityEvent.obtain();
                e.setEventType(AccessibilityEvent.TYPE_ANNOUNCEMENT);
                e.getText().add(text);
                manager.sendAccessibilityEvent(e);
        } else {
            tts.speak(text, TextToSpeech.QUEUE_ADD, null, null);
        }
    }`

**Comment by CoBC** [comment]
Unfortunately it's still crashing with latest beta.

**Comment by CoBC** [comment]
Note that this issue seams to be fixed with Android 14 update

**Comment by bear101** [comment]
In Google Play Console I still see many crashes but so far not any on Android 14.
```
Exception java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List android.speech.tts.TextToSpeech.getEngines()' on a null object reference
  at dk.bearware.data.TTSWrapper.getEngines (TTSWrapper.java:81)
  at dk.bearware.gui.PreferencesActivity$TtsPreferenceFragment.onCreate (PreferencesActivity.java:404)
  at android.app.Fragment.performCreate (Fragment.java:2486)
  at android.app.FragmentManagerImpl.moveToState (FragmentManager.java:1261)
  at android.app.FragmentManagerImpl.addAddedFragments (FragmentManager.java:2431)
  at android.app.FragmentManagerImpl.executeOpsTogether (FragmentManager.java:2210)
  at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute (FragmentManager.java:2166)
  at android.app.FragmentManagerImpl.execPendingActions (FragmentManager.java:2067)
  at android.app.FragmentManagerImpl$1.run (FragmentManager.java:742)
  at android.os.Handler.handleCallback (Handler.java:938)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loop (Looper.java:246)
  at android.app.ActivityThread.main (ActivityThread.java:8653)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:602)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1130)
```

**Comment by peter1384** [comment]
i have android 12 and have installed last build on my phone, it is only crashing when not connected. When connected to a server and opening tts settings works fine with out any crash
