### ISSUE TITLE
China cannot publicly share its own servers in the Unofficial Servers section.

### ISSUE THREAD

**Issue by xyzs0000** [BearWare/TeamTalk5#1897]
### Description

Contents of Zhengdu clipboard editor can edit text Hello, I am a loyal user of QT from China. Feedback The next question, I released my server publicly as required in the qtf2 menu, and he indicated that the release was successful, but it was not listed i 第4项,共4项

### Application

- [X] qtTeamTalk
- [X] TeamTalkAndroid
- [X] iTeamTalk
- [ ] TeamTalkClassic
- [X] TeamTalkServer

### Platform

- [X] Windows
- [X] macOS
- [X] Android
- [X] iOS
- [X] Linux

### Expected behavior

Contents of Zhengdu clipboard editor can edit text Hello, I am a loyal user of QT from China. Feedback The next question, I released my server publicly as required in the qtf2 menu, and he indicated that the release was successful, but it was not listed i 第4项,共4项

### Actual behavior

Contents of Zhengdu clipboard editor can edit text Hello, I am a loyal user of QT from China. Feedback The next question, I released my server publicly as required in the qtf2 menu, and he indicated that the release was successful, but it was not listed i 第4项,共4项

### Steps to reproduce problem

中国势障者人才基地
tt://tt.xyzswd.net?tcpport=20000&udpport=20000&encrypted=0&username=0000&password=0000&channel=%2F

**Comment by bear101** [comment]
It's there now.
