### ISSUE TITLE
Keyboard isn't closing

### ISSUE THREAD

**Issue by OzancanKaratas** [BearWare/TeamTalk5#190]
After sending a channel message, keyboard doesn't close in the iTeamTalk. Please place an option onto keyboard as tap to close.

**Comment by bear101** [comment]
To remove the keyboard you "swipe it away" like in Facebook messenger 
and Google Hangouts. Maybe you want to send several messages. Then it's 
annoying to reopen the text input every time.

--
Kind regards

Bjoern D. Rasmussen
www.bearware.dk

**Comment by tech10** [comment]
What is the VoiceOver jesture for this? I, too, cannot close the keyboard after sending a message, and thus, can't return to the channels tab.

**Comment by bear101** [comment]
Hm, how do you swipe away the Facebook messenger's keyboard?

--
Kind regards

Bjoern D. Rasmussen
www.bearware.dk

**Comment by OzancanKaratas** [comment]
Alright, the problem has been solved. The keyboard has being closed after tap and hold an blank area.

**Comment by tech10** [comment]
Could you explain this a bit further? I attempted double tap and hold in the edit field, but the keyboard still wouldn't close for me.

**Comment by OzancanKaratas** [comment]
No, please click a channel message or log. You can click your own message. Don't click edit field.

**Comment by tech10** [comment]
That worked, thanks! Although, it doesn't seem to be the most intuitive thing to figure out. A slight change to the app might be a good idea, perhaps a return to prior tab button, or something. Just a thought.

**Comment by bear101** [comment]
We can make it so that sending an empty message closes the keyboard. Would that work?

**Comment by tech10** [comment]
That would be better than what we've got now, I think, though if possible, there should probably be some kind of note or accessibility tip about it, however that works. Where it now says type text here, it could say type text here, send empty message to close keyboard. That way, people would know what to do.
