### ISSUE TITLE
when connecting to the encrypted server, certificate verification notoriously fails

### ISSUE THREAD

**Issue by zstanecic** [BearWare/TeamTalk5#1906]
### Description

The connection on every encripted server fails, in the latest beta version, with client verification feature. 
I get error code 1416

### Application

- [ ] qtTeamTalk
- [x] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkClassic
- [ ] TeamTalkServer

### Platform

- [ ] Windows
- [ ] macOS
- [x] Android
- [ ] iOS
- [ ] Linux

### Steps to reproduce problem

connect to the server

**Comment by zstanecic** [comment]
It cannot. 

Client verification fails.

**Comment by bear101** [comment]
Fixed in build 123
