### ISSUE TITLE
Qt client: when you are in vidio or desktop tab controle, stil the history and the message edit box is there.

### ISSUE THREAD

**Issue by amirmahdifard** [BearWare/TeamTalk5#1917]
### Description

in qt client when you are in vidio tab or desktop tab, you can still see history and message, but you should only see history and message edit box when you are in chat tab only.

### Application

- [X] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkServer

**Comment by CoBC** [comment]
Can you argument why? It's wanted that history and message are in all tabs

**Comment by amirmahdifard** [comment]
but it's unrelated, why the vidio and desktop tabs should have histury, chat should only be in its own tab, like others. @CoBC can you confurm and open a pr to fix this?

**Comment by amirmahdifard** [comment]
i don't think that is fare because why having chat history in all tabs but not having other tabs everywhere, also, if history should be everywhere, then why chat tab exists, i would raather having chat history only on chat tab, and everything else are in there own tabs. also, this is more standard user interface.

**Comment by bear101** [comment]
I also prefer history in all tabs.
