### ISSUE TITLE
Public Server Still Show Up

### ISSUE THREAD

**Issue by lbk2907** [BearWare/TeamTalk5#1921]
### Description

The public server still show up even the show public server list is not exists anymore.

### Application

- [ ] qtTeamTalk
- [X] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkClassic
- [ ] TeamTalkServer

### Platform

- [ ] Windows
- [ ] macOS
- [X] Android
- [ ] iOS
- [ ] Linux

### Expected behavior

The public server should not show up anymore.

### Actual behavior

The public server still show up even the show public server is not exist anymore.

### Steps to reproduce problem

Happend on TeamTalk 5.14 build 122.

**Comment by amirmahdifard** [comment]
i think that @bear101 should remove them from bearwhere website

**Comment by lbk2907** [comment]
But the Windows version works fine.

**Comment by bear101** [comment]
The public servers will not be removed until v5.14 is released.
