### ISSUE TITLE
Enable/disable TTS events in Classic client

### ISSUE THREAD

**Issue by bear101** [BearWare/TeamTalk5#193]
1. I think that the possibility to join a channel by pressing Enter besides the shortcut CTRL+J would be practical.
2. If you added TTS for private and channel messages, it would be good to select what the TTS should or shouldn’t read. Sometimes it could be disturbing when TTS reads everything including messages.

**Comment by tech10** [comment]
I agree with point two, I think all TTS events should be toggled in settings, including client connects and disconnects, along with reading of channel and private messages.
