### ISSUE TITLE
An ancient bug with android client which causes incompatibility with the microphone of some Samsung phones

### ISSUE THREAD

**Issue by shaghayegh1382** [BearWare/TeamTalk5#1932]
### Description

If you set the Microphone gain to 50% in some Samsung phones like Galaxy A73, Your voice cannot be heard by other users. If you set the microphone gain to 100%, your voice is still low and can hardly be heard by other. The fact is there is a bug on transmitting in the android client. Actually the problem is not from samsung side because things are going well in other recording applications.

### Application

- [ ] qtTeamTalk
- [x] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkClassic
- [ ] TeamTalkServer

### Platform

- [ ] Windows
- [ ] macOS
- [x] Android
- [ ] iOS
- [ ] Linux

### Expected behavior

When you install teamtalk on Samsung phones like galaxy a73 or a40 or s23, it should work like other phones. Thus, when you set the microphone gain to 50%, your voice should be heard correctly and clearly by other people, and when you set it to 100%, your voice should be very loud (destortion), like what we see in galaxy a01 or galaxy a54.

### Actual behavior

seems that the opus does not work correctly in some samsung phones. Though your microphone gain is 100% but your audio volume is really low for other people. When it is 50%, indeed it cannbot be heard by other people. Remember, this happens when channel sample rate is 48000 but its ok with 24000 sample rate.

### Steps to reproduce problem

Step 1: Buy galaxy a73 or s23 or a33 or a40.
Step 2: Install team talk 5.13.
Step 3: Create a channel with the following properties: Audio codec =opus, Application =vo-IP, sample rate =48000, bitrate =64000.
Step 4: With your android phone, join to that channel and try transmitting your microphone.
Step 5: first, make sure your microphone gain is set to 50%, you will see your audio volume is seriously unhearable.
Step 6: Try to set your microphone gain to 100%. You will see that your audio volume is still verry low.
Step 7: From the channel properties, Enable "Fixed audio volume for all users", and try control the audio volume from the channel properties, e.g set audio volume to 50%. Then you will see the problem is solved.
Step 8: Disable "Fixed audio volume for all users" from the channel properties, instead, switch recorder sample rate from 48000 to 24000 KHZ. You will see again that the problem is solved. This time you can control your microphone gain from your android client itself, but the fact is the 24000 KHZ sample rate, has lower audio quality when it is compared with 48000.
Step 9: Inventually, you will understand the above mentioned issue persists when: 1. "Fixed audio volume for all users" is not enabled from the channel properties. 2. Recorder sample rate is set to 48000 KHZ.
Step 10: Conclusion: Team talk contributors must find a solution to solve the lower audio volume in android client for all devices specially galaxy a73, They need to check what is the bug in opus that causes the microphone to not work properly in some phones and under certain settings and does not transmit the sound properly.

**Comment by shaghayegh1382** [comment]
@Nardol @beqabeqa473 @schulle4u @poretsky

**Comment by CoBC** [comment]
Due to same issue as #1762
