### ISSUE TITLE
Qt client: an option to automatickly hear our own voice after login in to the server so we don't have to always enable subscription voice for our self manully, also video too if possible.

### ISSUE THREAD

**Issue by amirmahdifard** [BearWare/TeamTalk5#1949]
### Description

some people are got used to always turn on the voice or video subscription for them selves so they can hear them selves while talking, an option should be added in to the teamtalk to automaticly enable voice subscription for people them selves, so they don't have to always press controle + 4 or controle + shift + 3 to start hearing them selves: this suggestion has been provided to me by one of my friends who needs such option, and i also thort it's a really cool suggestion so  i told you: please work on this if possible: thanks a lot.

### Application

- [X] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkServer

**Comment by Medusa5000** [comment]
Good suggestion

**Comment by CoBC** [comment]
@bear101 DO you think we should store status of "hear myself" and restore it at next login?

**Comment by bear101** [comment]
Yes, that would be a good idea.

**Comment by amirmahdifard** [comment]
@bear101 @CoBC the pull request have been murged today, but this issue is still not closed do you have anything to do yet with it? or do you want me to close it as completed?

**Comment by jeremyp3** [comment]
for your information, we say "merged" and not "murged".

i think the issue wasn't closed because there was no mention of it in 
the second PR that was done. that's all.
so, if you think your problem is solved, you can put the number of the 
pr that solved it and close it.
