### ISSUE TITLE
A Few Improvement Suggestion for iTeamTalk

### ISSUE THREAD

**Issue by lbk2907** [BearWare/TeamTalk5#1952]
### Description

Hey there.
Currently, we not able to know the following information when using iTeamTalk. It will be grate if we able to know these information. I not sure whether this information isn't available or is unreadable by VoiceOver.
1. User status (away, question).
2. User gender (male, female).
3. User client type.
Other suggestion.
1. When using headset button to toggle the TX, we just need to press once instead of press twice to turn on the microphone. This will have benefits to VoiceOver user to turn on the microphone using the magic tap (by default is two finger double tap).
2. When we successfully connected to server or when we join to any channel, TTS will announce our self nickname has join the channel. Maybe this can be remove.
Thanks.

### Application

- [ ] qtTeamTalk
- [ ] TeamTalkAndroid
- [X] iTeamTalk
- [ ] TeamTalkServer

**Comment by bear101** [comment]
When creating an issue only address one issue and the title must relate to what the issue is about. A title like this is not concrete.
