### ISSUE TITLE
qt client: a little bit reduce of annoying speecking too much for the screen reader

### ISSUE THREAD

**Issue by amirmahdifard** [BearWare/TeamTalk5#1963]
### Description

currently, when we open the dialog to send private messages to users, and we swich between the history and the message edit box, the screen reader always pronounces it like this.
History  grouping History  edit  read only  blank
New message  grouping New message  edit  blank
the grooping should be only one grooping and not 2 of them, so when you are swiching between the history and the edit box, it would only say like this.
History  edit  read only  blank
New message  edit  blank
like the history and edit box of the main window for the channel messages and channel history: that stops the screen reader from speecking too much and increaces the working speed for the user.

### Application

- [X] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkServer

**Comment by CoBC** [comment]
Groupings was made like this for visual reasons. I think there is a very small issue if screenreader announce history grouping and then history edit box.
I suggest to close this with wontfix label.

**Comment by amirmahdifard** [comment]
i don't understand why, but ok.
