### ISSUE TITLE
Spanish translation in teamtalk for android

### ISSUE THREAD

**Issue by manuelcortez** [BearWare/TeamTalk5#197]
How can we add a spanish translation in the android version of Teamtalk? I have seen some other translations there, but nothing about spanish. Should I copy an existent template or there is a way to create the catalog from the strings?

**Comment by bear101** [comment]
You should create a folder called values-es here:
https://github.com/BearWare/TeamTalk5/tree/master/TeamTalkAndroid/res
Afterwards copy https://github.com/BearWare/TeamTalk5/tree/master/TeamTalkAndroid/res/values/strings.xml to https://github.com/BearWare/TeamTalk5/tree/master/TeamTalkAndroid/res/values-es and translate the strings.

Thanks for the updated translation file. I've just updated the iOS translation again with the latest strings.
