### ISSUE TITLE
Change language by default system language

### ISSUE THREAD

**Issue by OzancanKaratas** [BearWare/TeamTalk5#200]
Qt TeamTalk and TeamTalk Classic should detect system language automatically.

**Comment by OzancanKaratas** [comment]
Qt TeamTalk have some problems. Please read http://wiki.qt.io/How_to_create_a_multi_language_application
Include DLL error into translation files.
Some alerts (like DLL error) still untranslatable.

**Comment by OzancanKaratas** [comment]
Qt TeamTalk have some problems. Please read http://wiki.qt.io/How_to_create_a_multi_language_application
Include untranslatable items into translation files so make translatable.
Some alerts (like DLL error) still untranslatable.

**Comment by OzancanKaratas** [comment]
Include Qt's translations

**Comment by bear101** [comment]
Out of scope. It's easy for users to change their language.
