### ISSUE TITLE
iTeamTalk: Voice Preprocessing Can't Be Disabled

### ISSUE THREAD

**Issue by Simon818** [BearWare/TeamTalk5#210]
In latest (non-beta) release of iTeamTalk, there's still obvious noise cancellation even when voice preprocessing is turned off. There's also a gigantic master volume level change when the setting is toggled (not to be confused with microphone volume): When I disable the setting, everyone else sounds quieter than they would with the setting enabled.

**Comment by stickbear2015** [comment]
I can reproduce this, note that the AGC is absolutely terrible, you 
whisper, it comes way up to the point of clipping, it takes at least 90 
seconds, then when you get loud and clip it out, or just talk norm, it 
takes at least 5 seconds to fully die down.
for the record, I'm really displeased that this made it out of beta.

**Comment by bear101** [comment]
Fix available here: http://bearware.dk/?p=663

**Comment by OzancanKaratas** [comment]
This hasn't a problem, the setting is able to disable. The issue can be closed.
