### ISSUE TITLE
can't upload , download and stream Media files

### ISSUE THREAD

**Issue by hussain4-00** [BearWare/TeamTalk5#2117]
### Description

    hello , when i try to upload or download a file or stream a media files on android it says upload or import files will be Unavailable same thing for streaming , when I click browse it doesn't show the files , I am using the programLatest version from the google play ,and my phone is samsung galaxy s23ultra

### Application

- [ ] qtTeamTalk
- [X] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkClassic
- [ ] TeamTalkServer

### Platform

- [ ] Windows
- [ ] macOS
- [X] Android
- [ ] iOS
- [ ] Linux

### Steps to reproduce problem

n/a

**Comment by bear101** [comment]
Duplicate #1182
