### ISSUE TITLE
In the qt version of teamtalk autooperator on channel cannot be removed

### ISSUE THREAD

**Issue by zstanecic** [BearWare/TeamTalk5#2120]
### Description

This is a bug, because the button is not working and it is an accessibility issue in qt. The channel is also not removed from the list.

### Application

- [X] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkClassic
- [ ] TeamTalkServer

### Platform

- [X] Windows
- [ ] macOS
- [ ] Android
- [ ] iOS
- [ ] Linux

### Expected behavior

channel operator should be removed and it should be reflected in the list

### Actual behavior

- operator channel is not removed

### Steps to reproduce problem

step1. go to the account configuration
step 2. select the account, in which you have set up the auto operator
step 3, try to remove the operator by selecting the channel and removing the operator by presing remove button

**Comment by bear101** [comment]
I cannot reproduce the issue. After you press Add or Remove to an auto-operator channel you have to press "Add/Update" button on the user account. The new auto-operator channels for the user account is not reflected until next login
