### ISSUE TITLE
bug in qt teamtalk. When channle tree is empty and has nothing in focus, pressing application on it doesn't open the context menu

### ISSUE THREAD

**Issue by HanaDadfar** [BearWare/TeamTalk5#2129]
### Description

when the channle tree is empty and/or has nothing in focus, context menu doesn't open when pressing application, but this is not the case for files tree.
reason: all applications like this that has GUI trees that has context menus, application key to open context menus always works regardless of whether the tree has options or it is empty, or something is in focuse or nothing, and also the teamtalk classic doesn't have this problem.
steps to reproduce: disconnect from any server you are currently connected to. Now that files tree and channle tree are both empty, try pressing application key on both trees to open context menus related to the trees, you will see that pressing application on files tree works and opens the context menu properly (useful when files tree is empty because you have no files, and you wish to press application to open the context menu so you can klick on upload file option), but pressing application on chanle tree doesn't work  and doesn't open the context menu
affect version/s: 5.14 and all older versions are affected by this bug as a result of my testing results

### Application

- [X] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkServer

**Comment by bear101** [comment]
What context menu should be shown when nothing is selected? The context menu for users or the one for channels?

**Comment by HanaDadfar** [comment]
@bear101 in the classic client, when nothing is selected, the channel context menu is shown. But your comment makes sence. When we have 2 type of context menus in one tree, when nothing is selected, it makes more sence to don't open any context menus raather than opening one of the context menus randomly. Thanks for your answer, i'm convinced.
