### ISSUE TITLE
a recently introduced bug for qt teamtalk. Lable of files list doesn't reset back when disconnected from a server

### ISSUE THREAD

**Issue by HanaDadfar** [BearWare/TeamTalk5#2134]
### Description

recently, a useful feature has been introduced, here's the entry.
label of files list now includes channel path
this feature is really useful, but there is a small bug with it. disconnecting from a server doesn't reset the label, and it still includes that server's channel path, even now that you aren't connected to any server at that time.
affect version/s: 5.15 only.

### Application

- [X] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkServer

**Comment by HanaDadfar** [comment]
also, the files list doesn't clear up on disconnection, here's how to reproduce it and understand it.
1: connect to a server, and then join a channel that has a fue files on it, or just focus on that channel if you are an administrator.
2: just press f2 to disconnect, now look at files list. you can still see the files even that now you aren't connected. the list should be cleared.

**Comment by CoBC** [comment]
I'll try to fix this
