### ISSUE TITLE
hability to ban IP suffix

### ISSUE THREAD

**Issue by DalisonCPU** [BearWare/TeamTalk5#2141]
### Description

I would like to see the possibility of adding a way to ban an IP suffix. For example, instead of banning the ip 189.122.123.124, ban only 189.122.

### Application

- [X] qtTeamTalk
- [X] TeamTalkAndroid
- [X] iTeamTalk
- [X] TeamTalkServer

**Comment by bear101** [comment]
To do this you ban 189.122.0.0/16

**Comment by DalisonCPU** [comment]
I didn't understand. Could you explain better?

**Comment by Medusa5000** [comment]
Just  ban the ip
189.122.0.0/16

**Comment by DalisonCPU** [comment]
I understand now. But simply banning without understanding, to me it didn't make sense
