### ISSUE TITLE
Ability to specify person's nickname and gender when creating TT file for server

### ISSUE THREAD

**Issue by trancer1994** [BearWare/TeamTalk5#2147]
### Description

Hi,

Recently I have been asked to create TT files for a server but not all of them are men, for instance (one of them is a man but the next one is a woman, etc) and they have different account details. What's worse is the server I am creating the files for is account-based, meaning you need an account to get into it. I can create the username and password for the user that I can paste into the generation boxes for those details but I can't specify the person's nickname that they will have on the server, nor their gender, and they will be using the TT files I create to log into the server every time they want to log in and won't be relying on manually-stored info, and thus won't want to change their gender every time it switches to the wrong one as soon as they log in due to how the client is set. Is there any way you could introduce the ability to specify the nickname of the user who will be logging into an account-based server and their gender when creating tt files? Currently this is not possible, unless I am missing something.

### Application

- [X] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkServer

**Comment by bear101** [comment]
Hm, yes, it looks like the gender selection is not applied when opening a .tt file.
