### ISSUE TITLE
iOS 7 support should be removed

### ISSUE THREAD

**Issue by OzancanKaratas** [BearWare/TeamTalk5#216]
iOS 7 is an absolutely old system. TeamTalk is not running well. We should remove iOS 7 support.

**Comment by bear101** [comment]
I think not running well is better than not running at all. If iOS 7 is not supported then iPhone 4 will not work.

**Comment by OzancanKaratas** [comment]
It is absolutely too bad.<br><ul><li>It isn't connecting to servers<br><li>The app is closing itself when clicking edit fields, server entries is being added<br><li>VoiceOver Rotor gestures is not working</ul><br>Etc etc... So iOS 7 does not carries TeamTalk app.

**Comment by OzancanKaratas** [comment]
Please merge to master branch the above commit.

**Comment by bear101** [comment]
Have you tested this? What about devices which run iOS 8.0? Do they still work?

**Comment by OzancanKaratas** [comment]
Anybody not using iOS 8. Because Apple is not allowing. Everybody is updated iOS 9.3.4. This patch is true. You can merge it.

**Comment by bear101** [comment]
There are still people using iOS 8. I can see that in the iTeamTalk statistics provided by Apple.

**Comment by bear101** [comment]
Same for iOS 9.2

**Comment by OzancanKaratas** [comment]
Hmmm, alright. You can label and close this issue. But Apple will disable iOS 8 coming soon.

**Comment by OzancanKaratas** [comment]
Aaaa, I have an idea. Can we localize to App Store and Google Play description and features of new versions?

**Comment by bear101** [comment]
It would delay the release of new versions if I have to wait for translation every time. But maybe the application description in App Store could be translated. I'll look into this. I cannot at the moment because TeamTalk v5.1.6 is currently in review.

**Comment by OzancanKaratas** [comment]
Please include the microphone access message on Info.plist. Translation files isn't containing a string for microphone accessing information.
