### ISSUE TITLE
wav files for yourself when recording to MP3 with separate files for each user

### ISSUE THREAD

**Issue by masonasons** [BearWare/TeamTalk5#217]
When you record as mp3, wave files are generated for your side of the conversation. This is with separate users for each file enabled.

**Comment by bear101** [comment]
It works for wav but not MP3?

**Comment by masonasons** [comment]
It records them all in .wav if I select Wav, but if I select .mp3, 
everything records in .mp3 except my side of the session.

**Comment by bear101** [comment]
Fixed in DLL 4.1.6.4610
