### ISSUE TITLE
iTeamTalk clashes with most other audio apps

### ISSUE THREAD

**Issue by Simon818** [BearWare/TeamTalk5#218]
When connected to a server in iTeamTalk, it is not possible to use most other apps which play back audio. This could be a game, a music app, or any number of other things. The recent headset tx change has not made any difference: This happens whether the option is disabled or not, and definitely still affects apps which use iOS's playback controls. Loading such an app will simply cause TeamTalk to disconnect from the current server and become unusable until the second app is closed. This probably isn't an easy thing to fix, and even from an end user perspective, iOS's audio system seems horribly convoluted. However, I do know that TeamSpeak uses a different audio profile on iOS, and this means there are a lot of other apps which will work simultaneously.

**Comment by bear101** [comment]
Discussion here: http://www.bearware.dk/phorum/read.php?1,4959
