### ISSUE TITLE
Fix building ffmpeg with binutils >= 2.41

### ISSUE THREAD

**Issue by beqabeqa473** [BearWare/TeamTalk5#2212]
Patch Here.
https://[git.videolan.org/?p=ffmpeg.git;a=patch;h=effadce6c756247ea8bae32dc13bb3e6f464f0eb](https://git.videolan.org/?p=ffmpeg.git;a=patch;h=effadce6c756247ea8bae32dc13bb3e6f464f0eb)

Helps to build ffmpeg in alpine

**Comment by bear101** [comment]
How does this affect Android, Ubuntu and iOS?

**Comment by bear101** [comment]
I think patching of FFmpeg should be done in the FFmpeg repo and not TeamTalk repo.
