### ISSUE TITLE
Sound Event Not Playing Correctly in "Default" Mode

### ISSUE THREAD

**Issue by lbk2907** [BearWare/TeamTalk5#2220]
### Description

There's an issue with the playback of sound events in the "Default" mode. The exact behavior is challenging to articulate, but generally, the correct sound isn't always triggered. Instead, the last played sound persists. For example, when User A connects to the server, the appropriate sound plays. However, subsequent events like User B sending a message to the channel result in the repeated playback of the initial connection sound rather than the expected channel message sound. This issue needs attention to ensure accurate sound playback.

### Application

- [X] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkClassic
- [ ] TeamTalkServer

### Platform

- [X] Windows
- [ ] macOS
- [ ] Android
- [ ] iOS
- [ ] Linux

### Expected behavior

I expected the sound events in the "Default" mode to play accurately and consistently according to their respective triggers. Specifically, when User A connects to the server, I anticipated hearing the designated sound associated with that event. Subsequently, when other events occur, such as User B sending a message to the channel, I expected to hear the corresponding sound without any interference from previously played sounds. Overall, I expected the sound playback to align precisely with the actions happening within the application, providing clear auditory feedback to users.

### Actual behavior

In the "Default" mode, the sound events are not playing as expected. When User A connects to the server, the designated sound associated with this event plays correctly. However, subsequent events, such as User B sending a message to the channel, do not trigger the intended sound. Instead, the sound that was played during User A's connection persists and is heard again, despite the occurrence of a different event. This results in inconsistent and inaccurate sound playback, which can lead to confusion among users regarding the actual events happening within the application.

### Steps to reproduce problem

I am unsure since which version of TeamTalk this issue has existed, but my current TeamTalk version is 5.15.2.5137 - Unreleased. All that is needed to reproduce the problem is to change the playback mode of the sound event to "Default".

**Comment by kirill-jjj** [comment]
problem is stil existing on teammtalk 5.16.0.5138

**Comment by bear101** [comment]
"Default" mode is playback using Qt's sound event.

It could also be related to the sound device. E.g. my BlueTooth headset has its own buffering mechanism, so it cannot play very short sounds.

**Comment by lbk2907** [comment]
I My sound driver has no issue for now.

**Comment by bear101** [comment]
@lbk2907 so the issue can be closed?

**Comment by beqabeqa473** [comment]
hi @bear101 the problem is not with short or long sounds. The problem is that wrong sound event is played when for example user logs in joins channel, if you press ptt key or voice activation before that user logged in.

**Comment by lbk2907** [comment]
Any way to fix this issue?

**Comment by kirill-jjj** [comment]
@bear101 the problem is still present on teamtalk 5.16 release.

**Comment by a11cf0** [comment]
This happens only when using the default sound event playback mode, not with TeamTalk Sound Device. In this case, only one sound is played for all events. This issue appeared in 5.15.2.5137 and is still present in the final 5.16 build.

**Comment by lbk2907** [comment]
Thanks for the details.

**Comment by artem59k** [comment]
The issue has persisted in the latest release. Even broadcast messages are sent with the sound of connecting to the server. Joining the channel also has the same sound as connecting to the server. Sending private messages has the same sound as well. Only the chat messages within the channel have the sound working properly.

**Comment by schulle4u** [comment]
I can also confirm the issue, it came up with the first 5.16 betas. Switching playback mode from default to overlapping in sound events tab temporarily fixes the problem.

**Comment by math65** [comment]
Hi,

I Can Reproduce this problem on Mac 

Mathieu

**Comment by stickbear2015** [comment]
I can reproduce this as well,regardless of playback mode, the issue is persistent.
I'm running
Version 5.16.0.5139.
TeamTalk 64-bit DLL version 5.16.0.5139.

**Comment by cyrmax** [comment]
Hello there!
I have tested with latest teamtalk 5.16 release for Windows and yes, the problem exists.
If you use overlapping or one by one sound event modes you have no problem and everything works perfectly. But when you set default sound event mode, the first sound is remembered and played for every event.
For example if I switch to the default mode and press ok button to apply preferences, the first sound I hear is a beep indicating that the sound system is initialized. After that if I turn on and off voice activation, receive channel and private messages, always I hear this beep instead of proper sound events.
But, it is important to note that if I remove some file from channel then I hear a proper file modification sound.
But after that this sound becomes the one which is played for every event.
If I press ptt hotkey then I hear proper ticking sound of ptt being activated, but after that this ticking sound becomes the one for all events.

I hope that my explanation helped the developers and I hope that @bear101 will fix it as soon as possible because it is terrible to see such major bugs in public release, not even in beta.

**Comment by stickbear2015** [comment]
as sad as it is, I even tried @cyrmax note about switching the playback mode, and on all of my computers it didn't work, I even tried switching the sound pack to default, with the issue still happening.
@bear101

**Comment by stickbear2015** [comment]
@cyrmax  @bear101  I was able to get @cyrmax one by one sound playing the proper sounds ot play, so that's a tleast but default should still not have broken in beta than left broken in the official release.

**Comment by bear101** [comment]
As far as I can see in the log of changes then the way sound event playback is implemented has been unchanged since v5.12.

@CoBC PlaySoundEvent was introduced in commit 88506180a2a700e582705620aad19b8a786b1ffb and hasn't changed.
```
$ git tag --contains=88506180a2a700e582705620aad19b8a786b1ffb
v5.12
v5.13
v5.13.1
v5.14
v5.14.1
v5.14.2
v5.15
v5.15.1
v5.16
```

**Comment by lbk2907** [comment]
I not sure but yeah, I haven't experience this bug before the version
mentioned.

**Comment by bear101** [comment]
@lbk2907 so if you install [v5.11](https://bearware.dk/teamtalk/v5.11/) you don't have the problem, but it exists in [v5.12](https://bearware.dk/teamtalk/v5.12/)?

**Comment by lbk2907** [comment]
I not sure which version starting have this problem. Maybe starting from
version 5.15 mentioned by someone before.

**Comment by CoBC** [comment]
I guess it's an issue with Qt 6.7, but, good luck to create an example 
and report it to Qt :(

**Comment by beqabeqa473** [comment]
@bear101 it started from v5.15.2 beta.

**Comment by kirill-jjj** [comment]
@bear101 It started from TeamTalk 5.15.2.5137

**Comment by trancer1994** [comment]
This also seems to happen when pms are sent by users as well to other users. For instance, user A sends a pm to user B, and the same thing happens as when user A sent a channel message to user B in the channel itself.

**Comment by bear101** [comment]
@lbk2907 Please try this version and see if it fixes the problem: https://bearware.dk/teamtalk/v5.16.1/TeamTalk_v5.16.1_Setup.exe

**Comment by kirill-jjj** [comment]
@bear101 for me it fixed the problem. Thank you.

**Comment by a11cf0** [comment]
The problem is now fixed! Thanks!

**Comment by lbk2907** [comment]
@bear101 It fix here. Thanks.
