### ISSUE TITLE
microphone don't work in background mode in last Teamtalk for android

### ISSUE THREAD

**Issue by grishakonzalaev** [BearWare/TeamTalk5#2237]
### Description

If I switch from Teamtalk to other app, people in channel cannot hear me.
Version: 5.15.2 build 131

### Application

- [ ] qtTeamTalk
- [X] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkClassic
- [ ] TeamTalkServer

### Platform

- [ ] Windows
- [ ] macOS
- [X] Android
- [ ] iOS
- [ ] Linux

### Expected behavior

microphone in teamtalk works in background mode.

### Actual behavior

Microphone not working in background mode. If I switch to other app or press home button, microphone not working.

### Steps to reproduce problem

1. enter to TT server.
2. press push to talk or voice activation button. Microphone will work only when Teamtalk window in foreground mode.

**Comment by SalehAcehUtara** [comment]
Wow, the desired issue. I and several other friends also experienced the
same thing, and I tried exploring the settings but nothing changed it. I
hope it gets fixed, because it's very important.

Pada Sen, 1 Apr 2024 08:08, grishakonzalaev ***@***.***>
menulis:

**Comment by bear101** [comment]
Fixed by #2236

**Comment by bear101** [comment]
A TeamTalk v5.15.2 build 132 should be available shortly that fixes this issue.
