### ISSUE TITLE
TeamTalk v. 5.17.0.5141 - Inaccessible Preferences Dialog

### ISSUE THREAD

**Issue by StormProductionsMusic** [BearWare/TeamTalk5#2257]
### Description

Hey there, so I just installed the latest beta of TeamTalk, pressed F4, seems like I can't access neither the tabs or their content at all. I just see the cancel and the ok buttons. So basically I can't control my TeamTalk's settings alltogether.

### Application

- [X] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkClassic
- [ ] TeamTalkServer

### Platform

- [X] Windows
- [ ] macOS
- [ ] Android
- [ ] iOS
- [ ] Linux

### Expected behavior

The settings window should be fully accessible as it was in previous versions so I can change anything.

### Actual behavior

Only the OK and Cancel buttons are visible in the dialog with no way to change any setting at all.

### Steps to reproduce problem

Just update to the latest beta version, press F4 and you'll notice you can't change any setting.

**Comment by CoBC** [comment]
Hi,

there is a Qt issue with Qt6.8, see here: [QTBUG-124854] Unable to focus 
tab bar using keyboard - Qt Bug Tracker 
<https://bugreports.qt.io/browse/QTBUG-124854>

I already asked @bear101 to rollback to Qt6.7 for now :) so it will 
probably be the case as soon

**Comment by StormProductionsMusic** [comment]
Understood. Closing this issue then since it'll eventually be fixed anyway.
