### ISSUE TITLE
qt teamtalk: kritical bug: Publishing a server publicly doesn't work in the new host manager

### ISSUE THREAD

**Issue by peter1384** [BearWare/TeamTalk5#2272]
### Description

when i try to publish my local server publicly with the new host manager, I get this error instantly.
Publish Server  dialog  Failed to publish server.

### Application

- [X] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkServer

**Comment by CoBC** [comment]
Can't reproduce

**Comment by CoBC** [comment]
Also, this is absolutely not a feature request but a bug report. However, as @bear101 said previously, please use discussions instead of issues, and if an issue exists we can convert discussion to issue.

**Comment by peter1384** [comment]
oh lol i was wanted to close this after a fue minutes after i opened it. the reason it didn't work for me was because i didn't login to my bearware.dk account in my client
