### ISSUE TITLE
PTT keys do not work with Qt 5 on X11

### ISSUE THREAD

**Issue by bear101** [BearWare/TeamTalk5#228]

**Comment by bear101** [comment]
http://doc.qt.io/qt-5/sourcebreaks.html

Search for QApplication::x11EventFilter() which has been removed in Qt 5

**Comment by webczat** [comment]
not sure if it's the same: for me ptt works but pressing and holding it reacts as if I repeatedly pressed the ptt key very fast. I am on x11 of course.

**Comment by bear101** [comment]
I'm not going to look further into this. Currently X11 client works as PTT-lock
