### ISSUE TITLE
Check for updates option on Windows

### ISSUE THREAD

**Issue by OzancanKaratas** [BearWare/TeamTalk5#230]
QtTeamTalk and TeamTalk Classic doesn't provides an update checker.

**Comment by schulle4u** [comment]
There is a "check for updates on startup" option under settings -> display. AFAIK this setting causes TeamTalk to display a status bar event when a new version has been released.

**Comment by bear101** [comment]
There is already an update checker

**Comment by OzancanKaratas** [comment]
Automatic update checker is not working well. Also TeamTalk doesn't has an check for updates option in Help menu.

**Comment by bear101** [comment]
Should run every 24 hours

**Comment by OzancanKaratas** [comment]
But this is not downloading and installing application automatically.

**Comment by OzancanKaratas** [comment]
Also Qt TeamTalk should use default system language on any systems.

**Comment by OzancanKaratas** [comment]
Please see issue #200 for an another bug.

**Comment by OzancanKaratas** [comment]
@bear101 Ctrl+Shift+M shortcut doesn't works on Windows 10.

Also it's not used Mute Voice setting in Mute submenu. This setting and its shortcut is not working.
I don't know anything about other systems that how it works.
