### ISSUE TITLE
crash when sending very long text message

### ISSUE THREAD

**Issue by valiant8086** [BearWare/TeamTalk5#2323]
### Description

I pasted a complete hp fanfiction book in the edit compose box in a conversation to myself. The entire contents appeared in the box, but when I pressed enter the client closed out completely.

### Application

- [X] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkClassic
- [ ] TeamTalkServer

### Platform

- [X] Windows
- [ ] macOS
- [ ] Android
- [ ] iOS
- [ ] Linux

### Expected behavior

It should either not let me paste ridiculously long text like that, or it shouldn't crash.

### Actual behavior

It pasted in just fine, but when I pushed enter, client closed out altogether

### Steps to reproduce problem

1. start a chat with yourself, double click your own name in the channel list or press enter on it.
2. since it would take a while to create a long text, find something really long, in this case it was book 3 of the Krait series HP fanfiction
3. paste that content into the chat box
4. Notice the contents is all there to review
5. Press enter
6. Notice the client immediately  closes out altogether

**Comment by valiant8086** [comment]
reproduced with tt 5.17.0.5142 actual release, and a Github-created test version for the new list views discussed in #2313.

**Comment by bear101** [comment]
I sent the entire content of this file and didn't see a crash: https://raw.githubusercontent.com/BearWare/TeamTalk5/master/Client/qtTeamTalk/mainwindow.cpp
