### ISSUE TITLE
critical bug in teamtalk server! banning an empty IP adress makes the server to ban everyone from the server and does not let anyone to login

### ISSUE THREAD

**Issue by peter1384** [BearWare/TeamTalk5#2365]
### Description

when adding a new ban with type ip but not entering anything as the Ip editbox, so having a ban like this in the server ban list
Nickname: , Username: , Ban type: IP, Ban Time: 6/12/2024 10:51 PM, Creator: admin, Channel: , IP-address:  
the server known everyone as banned and does not allow anyone to be login to the server, absolutely anyone who have user account on that server
@bear101 please take care of this and fix it in the teamtalk server, this bug makes it impossible for even admins to login in to the server and remove the ban, I was forced to shut down my server and edit the server xml file and remove the ban from it and start my server again.
Thanks!

### Application

- [ ] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [X] TeamTalkServer

**Comment by peter1384** [comment]
the same is for the channels. When an empty IP adress banned from a channel anyone cannot join that channel until that ban is removed

**Comment by bear101** [comment]
The channel ban issue should be fixed by this commit: https://github.com/BearWare/TeamTalk5/commit/1782b6defad098b333f60f08fbdc601630e97b48

**Comment by peter1384** [comment]
@bear101 yes the add button is disable, but,
in void key press event, up on pressing enter on the text box, we don't check only if the text is not empty call slot new ban
        if (ui.banEdit->hasFocus())
        {
            slotNewBan();
            ui.bannedTableView->setFocus();
        }
        which I can even fix that
        And the channel is also same, It is not related to the mainwindow.cpp which you've committed to, You can go to banned users from channel and press enter on text box to add an empty ip ban, So may be you should revert this commit
        But also, this should be fixed from the server as wel, because the empty ip ban will ban everyone, but it should have no effect
