### ISSUE TITLE
complication error after the new mytab with laytist up to date master

### ISSUE THREAD

**Issue by peter1384** [BearWare/TeamTalk5#2375]
### Description

this is all of the errors in the complication
1>mainwindow.obj : error LNK2019: unresolved external symbol "public: __cdecl MyTabWidget::MyTabWidget(class QWidget *)" (??0MyTabWidget@@QEAA@PEAVQWidget@@@Z) referenced in function "public: void __cdecl Ui_MainWindow::setupUi(class QMainWindow *)" (?setupUi@Ui_MainWindow@@QEAAXPEAVQMainWindow@@@Z)
1>preferencesdlg.obj : error LNK2001: unresolved external symbol "public: __cdecl MyTabWidget::MyTabWidget(class QWidget *)" (??0MyTabWidget@@QEAA@PEAVQWidget@@@Z)
1>useraccountdlg.obj : error LNK2001: unresolved external symbol "public: __cdecl MyTabWidget::MyTabWidget(class QWidget *)" (??0MyTabWidget@@QEAA@PEAVQWidget@@@Z)

### Application

- [X] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkServer

**Comment by amirmahdifard** [comment]
@CoBC I have the same problem, can you please fix it? thanks

**Comment by CoBC** [comment]
Do you have the same problem of yourself?
Anyway, just re-run CMake
Can't reproduce.
