### ISSUE TITLE
qt teamtalk's build problems

### ISSUE THREAD

**Issue by amirmahdifard** [BearWare/TeamTalk5#2377]
### Description

@CoBC you said that pr was not a correct place for talk about building, so I opened this to ask this. Is it no longer possible to build qt teamtalk like we did yesterday? until yesterday, like it says in readme, I used set path command to direct the folder which contanes qmake.exe, and then the command for getting project files, which is qmake tp blaablaa releace teamtalk5.pro, and then built the .exe by teamtalk5.vcx proj on vs 2019, but since my tab has been added, We get error. what to do? is the build system has changed? thanks for answering

### Application

- [X] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkServer

**Comment by amirmahdifard** [comment]
I folow the steps of file readme.md inside qt teamtalk folder provided by teamtalk's developers it self, And it was working fine from a long time since I lurnt how to build teamtalk, and it is only broken since yesterday, and vc even shows the errors, the file, and the number of line which has errors, which all of them are provided in peter's issue. so, @CoBC can you please look at the line numbers and fix compilation errors, because I get the same error and line numbers as peter, so if you fix that my issue will also be solved

**Comment by HanaDadfar** [comment]
oh yeah true, I have this problem as wel. May be corentin builds teamtalk difrently, And he can't or didn't consider other people may be building it difrently or something, so, @bear101 you should fix this issue yourself.

**Comment by amirmahdifard** [comment]
yeah, i've also reported this at contact@bearware.dk I wanted to change my qt vertion and try, but i don't think this is related, so I'm waiting to see what does @bear101 will say

**Comment by Muamalaljanahi** [comment]
Can't you just wait without spamming us with useless comments?

**Comment by Muamalaljanahi** [comment]
look at this
https://github.com/BearWare/TeamTalk5/actions/runs/9505433497/job/26200308370
Therefore, I am almost certain that they are aware of the issue

**Comment by jeremyp3** [comment]
FYI, many of us have been thinking for several days that @amirmahdifard  @HanaDadfar @peter1384 are in fact one and the same person.

**Comment by Muamalaljanahi** [comment]
Yes. It is quite clear that all these accounts are for one person; You can tell that from his distinctive writing style :)

**Comment by peter1384** [comment]
@Muamalaljanahi no, It is not related to that, my Visual Studio compilation errors files and lines and discriptions showes that it is related to the mytabwidget because other files which uses this object produces errors about it, I provided the logs in my own opened issue. and, @jeremyp3 I didn't even know that this issue also exist, until you mentioned me so I came to look and answer it
Yesterday I just opened an issue regarding the compilation problem, and when co bc said he can't reproduce, I contacted @bear101 to investigate the problem
so, lets wait what is the issue
