### ISSUE TITLE
Security enhancements for the teamTalk server

### ISSUE THREAD

**Issue by zstanecic** [BearWare/TeamTalk5#2380]
### Description

I have in a long term tracked one critical issue: the passwords shouldn't be visible in the teamTalk 5 server configuration file. Now the situation is that anyone who will optain the config file, he will be able to use this information to take over an user account on other services, because users's tendency and practices regarding setting up passwords are very bad. Also i want users to be able to request creation of the user accounts.

### Application

- [ ] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [X] TeamTalkServer

**Comment by bear101** [comment]
To have secure passwords you need to use BearWare.dk WebLogin.

**Comment by zstanecic** [comment]
Using bearware web login is not possible in the free version for the server.

**Comment by peter1384** [comment]
@zstanecic for having some abilitys, you need pro server
