### ISSUE TITLE
a nice idea for the channel share dialog

### ISSUE THREAD

**Issue by amirmahdifard** [BearWare/TeamTalk5#2386]
### Description

currently, after pressing enter on specify account dialog on channel share dialog, if the selected channel contanes a password, a new popup will appear for you to enter channel password. Please also make the channel password dialog's edit box in to the first dialog which is specify account dialog, and if a channel doesn't have a password, the channel password edit box would be disabled, or set to read only in this dialog. @CoBC would you please do this also, this idea is the last to make this dialog best

### Application

- [X] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkServer

**Comment by CoBC** [comment]
> the first dialog which is specify account dialog

You have said all, the first dialog is to specify an user account, it is not related to channel, it's confusing to have an edit field for channel password here.

**Comment by amirmahdifard** [comment]
@CoBC but we can rename it from specify account to specify information, and we have username, password, and channel password editboxes in it. what about this?
