### ISSUE TITLE
Windows QT client: TT wav sounds are always played on the default device

### ISSUE THREAD

**Issue by djgraco** [BearWare/TeamTalk5#2397]
### Description

Hello,
The problem started when I noticed that notification sounds such as when voice activation was turned on or when a user joined a channel were not always played in TeamTalk QT Windows.
After investigating the problem, it turned out that the sounds always go through the default playback device.
Example:
I have Creative SoundBlaster as my default playback device in Windows. In teamtalk, in the sound system settings, I set the output device to Realtek speakers. The call goes through Realtek, but sounds are still played by SoundBlaster. When you change Realtek to the default sound card, sounds are played through that sound card.

### Application

- [X] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkClassic
- [ ] TeamTalkServer

### Platform

- [X] Windows
- [ ] macOS
- [ ] Android
- [ ] iOS
- [ ] Linux

### Steps to reproduce problem

1. Set whatever the default sound card is in your system.
2. In preferences/sound system, set the output device to a different sound card that is not the default one. Teamtalk sounds should play through the default sound card.

**Comment by amirmahdifard** [comment]
in sound events tab, You can choos wether you want the sounds to play throo your system's default device or the teamtalk's defalt device
