### ISSUE TITLE
TeamTalk for iOS taking around 2-3 minutes to connect to server

### ISSUE THREAD

**Issue by a-singer** [BearWare/TeamTalk5#2414]
### Description

Hello,

When using Tailscale

http://www.tailscale.com

all other products connect quickly but TeamTalk, on iOS, takes several minutes to connect. I have tried this with a Windows an OSX server.

I have contacted Tailscale and, after having reviewed logs, they aren't able to determine what's going on. If I may ask, is there a server or client log I can look at to see what's happening to delay the connection? Note that the connection is fine once made.

### Application

- [ ] qtTeamTalk
- [ ] TeamTalkAndroid
- [X] iTeamTalk
- [ ] TeamTalkClassic
- [X] TeamTalkServer

### Platform

- [X] Windows
- [X] macOS
- [ ] Android
- [X] iOS
- [ ] Linux

### Expected behavior

TT should connect to the server within a few seconds.

### Actual behavior

TT takes a few minutes to connect.

### Steps to reproduce problem

1. Install Tailscale on both the iOS device and the TeamTalk server.

2.	Make a new server profile with the tailscale IP address as the address for the server.

3.	Try to connect. Connection will take anywhere from a minute and a half to three minutes. When on the local network, and the IP for the server is set to the local IP, connection is immediate.

**Comment by bear101** [comment]
I don't see this issue without TailScale installed, so the problem must be in TailScale.

**Comment by a-singer** [comment]
That is probably true, but since Tailscale seems unable to diagnose it, and since TT is the only application I know of, out of about fifteen I've tried, which makes a real connection and does not do so at once, I'm wondering if there is a log which would help diagnose the issue? As I said, there is no other application which is having this issue that I know of and it does eventually work so there is some sort of timeout going on or something like that.
