### ISSUE TITLE
Teamtalk QT on Windows does not work when VPN with UDP over TCP is in use

### ISSUE THREAD

**Issue by cyrmax** [BearWare/TeamTalk5#2423]
### Description

When some VPN is in use on the system, Teamtalk client starts very slowly, it takes over 10 seconds to open the UI.
And after that I cannot connect to any server, encrypted or plain, located in any country.
I even cannot connect to my own server so I can be sure that there are no restrictions for my VPN.

VPN itself is self-hosted too and I am sure that there are no restrictions as well.

While connected to the VPN I can connect to any teamtalk server via telnet console and even log in.
Other UDP streams also work, for example I can talk in discord, make calls in Telegram and Whatsapp.

Also the problem exists only on the Windows version, on Android with the same VPN I can normally connect to any server and talk there.

### Application

- [X] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkClassic
- [ ] TeamTalkServer

### Platform

- [X] Windows
- [ ] macOS
- [ ] Android
- [ ] iOS
- [ ] Linux

### Expected behavior

Teamtalk should work normally as other applications do.

### Actual behavior

Teamtalk refuses to connect and hangs in connecting state endlessly without even logging in to a server.

### Steps to reproduce problem

1. Install Hiddify next vpn application;
2. Set up or find any vpn with reality protocol;
3. Connect to it in VPN or VPN Service mode enabled in hiddify;
4. Try to open Teamtalk and connect to something

**Comment by jeremyp3** [comment]
what type of vpn is it?

**Comment by cyrmax** [comment]
@jeremyp3 It is xtls reality. Xray as a server and hiddify as a client app.
