### ISSUE TITLE
Revert Sound events behavior to play through default Sound Device rather than TeamTalk output device

### ISSUE THREAD

**Issue by Nick6489** [BearWare/TeamTalk5#2431]
### Description

To me, TeamTalk 5.17's behavior is not, in fact, desirable as a broadcaster who brings TeamTalk on air. I don't like my sounds and my voice traffic going to the same place. Can you please either revert that feature, or alternatively, give us a third combobox in Sound System for Sound Events output?

### Application

- [X] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkServer

**Comment by Nick6489** [comment]
Also, I apologize for my abominable typing in the subject line. I wish we could edit those...But we can't. Thanks Microsoft.

**Comment by CoBC** [comment]
> Also, I apologize for my abominable typing in the subject line. I wish we could edit those...But we can't. Thanks Microsoft.

You can edit the issue title by pressing "edit issue title" above the level 1 header with the title

**Comment by CoBC** [comment]
@bear101 Do you have a preference? Should we add a new option to choose device or revert to previous behaviour? My opinion is to add an option to choose device

**Comment by Nick6489** [comment]
> @bear101 Do you have a preference? Should we add a new option to choose device or revert to previous behaviour? My opinion is to add an option to choose device

Honestly? I'm with you. Add an option to choose the device. Make it less ad hoc. I was talking to some people on Mastodon and discovered that it wasn't always the same behavior for everyone.

**Comment by CoBC** [comment]
OK, I've added a checkbox in #2436 to use TeamTalk Sound Output Device, if this checkbox is not checked, the behaviour is equivalent to the one prior to 5.17 release
