### ISSUE TITLE
404 when getting android app

### ISSUE THREAD

**Issue by a-singer** [BearWare/TeamTalk5#2456]
### Description

Hello, 

At

https://bearware.dk/?page_id=353

there is supposed to be a download for Android, which leads to

https://bearware.dk/teamtalk/v5.8.2/TeamTalkAndroid_v5.8.2_build107.aab

That page leads to a 404, not found, error. Thank you.

### Application

- [ ] qtTeamTalk
- [X] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkClassic
- [ ] TeamTalkServer

### Platform

- [X] Windows
- [X] macOS
- [X] Android
- [X] iOS
- [X] Linux

### Expected behavior

The file should have been downloaded

### Actual behavior

404 error

### Steps to reproduce problem

Go to the site and try to download the android file.

**Comment by bear101** [comment]
Hm, there's a v5.8.1 here: https://bearware.dk/teamtalk/v5.8.1/TeamTalkAndroid_v5.8.1_build106.aab
Does it work?

**Comment by a-singer** [comment]
I'm sorry, I replied to the email but the reply did not make it here. Anyhow, thanks very much, I can download this so the original issue is resolved, but I am having a very hard time installing it on the device. Is an APK available anywhere?

**Comment by bear101** [comment]
Here's an APK: https://bearware.dk/teamtalk/v5.4/TeamTalkAndroid_v5.4.apk
