### ISSUE TITLE
Server API Callback issue

### ISSUE THREAD

**Issue by DevBDK** [BearWare/TeamTalk5#247]
UserDisconnected Callback invoked for no reason, when FileDownloaded or FileUploaded is raised.

**Comment by bear101** [comment]
It's because the file is uploaded/downloaded on a separate connection and the disconnect event is from that connection. If you check the nUserID then you'll probably see that the UserID is not one you have seen in connect or login event.

**Comment by DevBDK** [comment]
Ah, Okay. So i have to check the userid if 0 then it was a download upload event?

**Comment by bear101** [comment]
There's a user-id but the user will never log on (no logged in event). 
You will only see connect and disconnect.

--
Kind regards

Bjoern D. Rasmussen
www.bearware.dk

**Comment by bear101** [comment]
@DevBDK , can I close this one?

**Comment by DevBDK** [comment]
Moin Bjoern, 
yes u can Close this.

**Comment by bear101** [comment]
Btw, if there's more commands you would like to see in the server API then just let me know.
