### ISSUE TITLE
[Qt client] Keyboard shortcuts broken in some locales

### ISSUE THREAD

**Issue by schulle4u** [BearWare/TeamTalk5#251]
In some locales such as german, the modifier keys (CTRL, Shift etc) have different names. This causes broken keyboard shortcuts in the Qt client. In the MacOS version keyboard shortcuts probably are generally broken when used with locales, because of totally different modifier names (CMD, option...). 

Therefore we should think about removing shortcuts completely from translation files to avoid this problem or just leave them as untranslated. Or is there another possibility to fix this? I'll provide a temporary fix for the german locale this weekend. 

Steffen

**Comment by bear101** [comment]
Ah, yes, I see what you mean. I guess the keyboard shortcuts should not be translated at all.
