### ISSUE TITLE
TeamTalk Classic crashes when recording audio files for each user

### ISSUE THREAD

**Issue by tech10** [BearWare/TeamTalk5#266]
When recording audio files for each individual user, TeamTalk classic will eventually crash, sometimes quickly, sometimes within a few hours. The recording format isn't relevant, as it will crash regardless of what file format you're recording in.

To best reproduce this, go on a server of at least three people, who don't mind being recorded for a test or otherwise, all of whom are using either hotkeys, or a voice activation threshold high enough to stop their audio transmission when they aren't talking. Start recording, selecting to record an audio file for each user. Wait for some time, and the program will eventually become unresponsive, requiring a forced quit.

This bug is in TeamTalk 5.2, but was also present in 5.1.7, also.

**Comment by bear101** [comment]
Hi Blake. Is this still an issue?

**Comment by tech10** [comment]
From my limited testing, it doesn't appear to be.

Blake

**Comment by OzancanKaratas** [comment]
> This bug is in TeamTalk 5.2, but was also present in 5.1.7, also.

Please update TeamTalk to 5.2.3, and do these:

*  Use Windows Audio Session instead of DirectSound and Windows Default
*  Do not record sounds as MP3. Record as OGG or wave format and convert MP3 instead.
*  Avoid openning another instances of TeamTalk.

After do these, please share your comments.

**Comment by bear101** [comment]
I had a v5.3 client running for three days and no crashes. This was on Linux though.

**Comment by tech10** [comment]
The last time I tested this when it crashed, it was on Windows with the classic client, recording in MP3. The QT client on Mac OS doesn't seem to crash when recording files separately, and it's good that Linux doesn't crash either.

I'd suggest you try your test for at least six hours on Windows with the classic client. If it doesn't crash when recording files separately with MP3, Opus, or WAV, then I'd consider the issue resolved.

**Comment by bear101** [comment]
I found a deadlock issue which would cause the application to hang (not crash). With this fix I'll close the issue. The deadlock issue is fixed in v5.3.0.4915
