### ISSUE TITLE
Add text-to-speech in Qt client

### ISSUE THREAD

**Issue by bear101** [BearWare/TeamTalk5#275]
Use branch QtTextToSpeech.

https://doc-snapshots.qt.io/qt5-5.8/qtspeech-hello-speak-mainwindow-cpp.html
http://blog.qt.io/blog/2017/01/20/qt-speech-text-speech/

**Comment by OzancanKaratas** [comment]
Update Qt to 5.9.1 (latest version) for this issue and #200.

**Comment by math65** [comment]
Hello,
Where is the project? Will it be available on mac for the next version?

**Comment by bear101** [comment]
No, it's not planned for a release the moment.

**Comment by bear101** [comment]
Install QT TTS on Ubuntu 18 by installing: libqt5texttospeech5-dev

**Comment by beqabeqa473** [comment]
i think depending on operating system, on windows, we should add tolk
to qt client as well as in classic client.

i am using qt client for some time and it is much much faster. the
only problem is lack of announcements.

On 7/21/20, Bjørn Damstedt Rasmussen <notifications@github.com> wrote:
> Install QT TTS on Ubuntu 18 by installing: libqt5texttospeech5-dev
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/BearWare/TeamTalk5/issues/275#issuecomment-661315115


-- 
with best regards beqa

**Comment by Oreonan** [comment]
I'm completly agree with this idea and I've suggested this to Bjoern 
yesterday. I'll think try to work in the code of QTTTS branch from 
Bjoern to add this function quickly.

In my point of view, it's only this feature who it's necessary to add on 
QT in priority for accessibility because actually, blinds users of Linux 
and Mac haven't any announcement of events.

**Comment by bear101** [comment]
@Oreonan if you call m_speech->say("Hello") here then it should use TTS on your platform:
https://github.com/BearWare/TeamTalk5/blob/87dc1dde974a0683b4a94a5b932395da1b490fca/Client/qtTeamTalk/mainwindow.cpp#L178

**Comment by bear101** [comment]
The TTS events are currently in a QModel which isn't working in preferences. If you're not familiar with models in Qt then wait until I have time to look at it.

**Comment by Oreonan** [comment]
Fixed by #834

**Comment by bear101** [comment]
@Oreonan Shouldn't SETTINGS_TTS_ACTIVEEVENTS_DEFAULT be something other than TTS_NONE?
https://github.com/BearWare/TeamTalk5/blob/master/Client/qtTeamTalk/preferencesdlg.cpp#L571

**Comment by Oreonan** [comment]
Yes, I think also this, but I don't know what enable by default. Maybe:

- User logged in/out

- Channel join/left

- File added/removed

- All messages receptions

And probably nothing other for now.

**Comment by bear101** [comment]
Yes, that sounds about right. Maybe also class-room changes?

--
Kind regards

Bjørn Damstedt Rasmussen
www.bearware.dk

**Comment by Oreonan** [comment]
Yes, agree with this.
