### ISSUE TITLE
Add Push-to-Talk lock

### ISSUE THREAD

**Issue by bear101** [BearWare/TeamTalk5#278]

**Comment by tech10** [comment]
This seems like it could be a useful option, but different sounds when push to talk is enabled or disabled would enhance the usefulness of the lock. Alternatively, there could be a sound when the client is transmitting, and another sound when the client is not transmitting, but had previously been.

**Comment by bear101** [comment]
User can now lock the "push-to-talk" key for extended talk when channel has "voice activation" with the ctrl-shift-a key combination, and unlock it with the same key combo, but we need a sound for each press of this key combo to confirm the "lock" changes to visual impaired users.
