### ISSUE TITLE
Channel mode Single transmission should advertise who's in queue

### ISSUE THREAD

**Issue by bear101** [BearWare/TeamTalk5#279]
Add time-out-timer as well so no one can block a channel (issue #22)

**Comment by DevBDK** [comment]
> @bear101  also on which Position?

**Comment by bear101** [comment]
Yes, I can limit it to 16 positions and it's already FIFO ordering

**Comment by DevBDK** [comment]
> @bear101 Can you make the value of max positions accessable from outside?  thx

**Comment by DevBDK** [comment]
Hi Bjoern,

do you think you can add also UserMaxSpeechTime for singletransmissionmode? Thanks! So the User cannot block all the other user. For example the max speech time is 20 seconds. So after this time he will rejoin the queue.

**Comment by bear101** [comment]
I plan to make a time-out-timer which applies to all channel types.

--
Kind regards

Bjoern D. Rasmussen
www.bearware.dk

**Comment by bear101** [comment]
When turn comes up in queue to speak, need audible tone to alert visually impaired user

**Comment by bear101** [comment]
@DevBDK I've added the transmission queue to Channel-struct when channel is configured with CHANNEL_SOLO_TRANSMISSION. The 'transmitUsersQueue' is modifiable in the server API so you can control who is talking in a channel.

**Comment by bear101** [comment]
Use latest v5.2.2.4861 SDKs.
