### ISSUE TITLE
Option to flip video 180 degree

### ISSUE THREAD

**Issue by bear101** [BearWare/TeamTalk5#28]
Apparently some video devices output top-down bitmaps to the TT video encoder. It only supports bottom-up.

**Comment by Oire** [comment]
I was looking through all open issues to avoid duplicating the inquiries. and here it is! The need to flip the video upside down just drives us nuts a bit :). We make webinars and audio/video courses via TeamTalk, and we are in frequent need to transmit video and desktop.  
Besides that, there is something weird with sound when the video being transmitted is not in WMV format.

**Comment by bear101** [comment]
Which TeamTalk client do you see this problem? Also are they all using TT v5.2.1?

**Comment by Oire** [comment]
I use TeamTalk Classic, but it seems, with QT version the result was the same.  
We have been using 5.1 for a long time, was that fixed in 5.2.1? And also, should the server be updated? Thanks!

**Comment by bear101** [comment]
Yes, the issue should have been fixed.

**Comment by bear101** [comment]
The up-side down video issue seems to have been fixed, so there's really no need for this (Issue #71)
