### ISSUE TITLE
Allow audio codec change while users are within channel and transmitting

### ISSUE THREAD

**Issue by tech10** [BearWare/TeamTalk5#282]
Currently, while users are within a channel, and are either transmitting or not transmitting, the audio codec cannot be changed. I believe this is a limitation that could be removed with one of several ways.

1. When the codec is updated in the channel, force all clients to stop transmitting, go through whatever reset process they use when joining another channel with different audio codec settings, then resume transmitting. There would be a momentary pause in audio while this occurs, but this would be more acceptable than moving all users to another channel, simply to modify the audio codec within the channel they were in, then move them back.
2. The audio received and transmitted by the sound device of the platform running TeamTalk, would always be a specific format, and converted to whatever format the TeamTalk codec used. This would allow the TeamTalk program to internally accept the changing of audio codecs with very minimal delay in audio reception.
3. If Opus is being used, I know it can accept codec changes with no delay depending on how the program receiving the stream is configured, as I've played opus files with differing bit rates within the file, to demonstrate how smoothly opus can accept changes in bandwidth. If such a specific codec is used that allows such variations in bit rate and channel format, the TeamTalk program could allow such changes rather than limiting the changes when users are within a channel. In this case, a change from opus to speex or no audio codec wouldn't be allowed, but there would be no delay in the transmission of receiving of audio during a format change within a specific codec.

In all these cases, any recording of files would have to be restarted if they were recorded in the native format of the channel, but I imagine this wouldn't be difficult to implement.

I'd like to see TeamTalk allow audio codec changes from within a channel containing users, whether transmitting or not. When experimenting with different audio formats, or changing them based on a users bandwidth limits, it's bothersome to move them all into another channel with a different codec, only to move them back into the previous channel once the codec is changed. As this may require a change in the protocol of which I'm unaware, this may have to be a release for the next major release of TeamTalk, such as 6.0, which would be fine to me.

**Comment by bear101** [comment]
This issue will have to wait for TeamTalk v6 because audio codecs are only initialized on initial join. This would make existing TeamTalk v5 clients incompatible.
