### ISSUE TITLE
Sound events on voice activation enable/disable

### ISSUE THREAD

**Issue by bear101** [BearWare/TeamTalk5#289]

**Comment by bear101** [comment]
Fixed in v5.2.2.4861. Compiled client ready here: http://bearware.dk/beta/

**Comment by schulle4u** [comment]
Only the "voice activated" event works, "voice deactivated" is silent. Tested with 5.2.2.4861 classic under win 10 home 64 bit, and [these test files](http://www.robbenradio.de/dl/va_sounds.zip).
