### ISSUE TITLE
Sharp Clipping From Audio Transmissions on Mac OS X and Linux

### ISSUE THREAD

**Issue by tech10** [BearWare/TeamTalk5#292]
If a user on Mac OS X or Linux is transmitting audio, which goes even a little beyond a specific limit, perhaps -1 or 0DB, the audio will clip with a harsh, sharp sound rather than distort slightly. Most often, this happens on Linux or Mac OS X, and I've rarely seen it happen on Windows, and never on mobile platforms. I believe it may have something to do with converting the sample rates, as if you have an input device on Mac OS X that isn't set at 48K, this issue seems to occur. Recently, I've used a program called Loopback in an attempt to rout multiple streams of audio from different sources into TeamTalk, but even while setting the sound card to use 48K, the harsh clipping will still occur if multiple streams of audio from different sources are going into the virtual card. This is not a Loopback specific issue, as other programs recording, hearing, or using the Loopback card will not have the problem of harsh clipping.

This particular issue has been around since at least TeamTalk 4, when it first became available on Linux or Mac. I don't know if the issue has ever been touched upon, so I thought I'd get it out there.

**Comment by vlad-a-c** [comment]
i don't know why it's closed since this hasn't been resolved yet.
kind regards.

**Comment by tech10** [comment]
@vlad-a-c #840 was a duplicate and was closed, this issue is still open.

**Comment by bear101** [comment]
@CoBC Have you noticed this issue? I don't hear a difference between Windows, macOS and Linux.

**Comment by bear101** [comment]
Anyway, I suspect if there is such an issue it's somewhere inside PortAudio.

**Comment by CoBC** [comment]
The only issue I noticed is a distortion on MacOS when user speak a bit high. But probably not something we can fix in TT side.

**Comment by vlad-a-c** [comment]
you might wanna look on the qt or something. cause i've tested the ios version on mac since i have apple sillicon and on that one it doesn't clip. also, try to see if there are other sound systems to use if coreaudio has such issues. i didn't know that linux has this issue aswell, so there might be something on the qt side. i know mumble uses the same engine and has the same audio issue

**Comment by tbdalgaard** [comment]
I can confirm that Teamtalk is the only app I have seen doing this strange thing. I have tested with other applications, and I cannot reproduce the issue on WIndows or ios. But also not in apps that aren't coded in QT. How can I give some more useful feedback with logs etc. to show the issue?

**Comment by vlad-a-c** [comment]
this problem occurs also on mumble, other qt apps of this kind i don't know to suggest to see what they have in common with teamtalk.

**Comment by bear101** [comment]
TeamTalk does not use Qt for recording audio. On Windows it uses [PortAudio](https://www.portaudio.com/).

**Comment by vlad-a-c** [comment]
no, but maybe the encoder used has issues on mac. not sure what causes this, but i'm just giving suggestions.
