### ISSUE TITLE
Improve settings bundle

### ISSUE THREAD

**Issue by OzancanKaratas** [BearWare/TeamTalk5#293]
@bear101 Add iTeamTalk settings to iPhone's settings using settings bundle.
Same preferences can be set up on Settings>iTeamTalk

**Comment by OzancanKaratas** [comment]
Refer https://developer.apple.com/reference/watchkit

**Comment by bear101** [comment]
I don't see the need to duplicate preferences. Accessing preferences in the app is faster. Closing..
