### ISSUE TITLE
Error in teamtalk5: double free or corruption

### ISSUE THREAD

**Issue by schulle4u** [BearWare/TeamTalk5#296]
I'm currently testing the latest beta client (5.2.2.4886) under Debian 8 (Jessie) 64 bit. The client crashes after a few moments of successful connection with the following error message: 

```
*** Error in `/home/steffen/Programme/TeamTalk/teamtalk5': double free or corruption (fasttop): 0x0000000001cab8d0 ***
./run.sh: line 4:  5173 aborted             /home/steffen/Programme/TeamTalk/teamtalk5

```

The client also throws lots and lots of AtSpiAdaptor errors at me when using Orca, but this is not new and doesn't seem to have an effect on functionality. Furthermore I've made modifications to run.sh to allow starting of TeamTalk from the desktop (absolute library paths and so on), but this also should be no problem. 

Steffen

**Comment by OzancanKaratas** [comment]
Which are you using interface? GNOME or Unity?

**Comment by schulle4u** [comment]
I'm currently using Mate desktop environment, will test this also with GNOME.

**Comment by OzancanKaratas** [comment]
OK, a related bug is being seen on the Windows 7 32-bit Service Pack 1, the program is crashing when pressing PTT key. Bjoern must have compiled it wrongly. :)

**Comment by bear101** [comment]
What if you choose "No Sound Device" as input and output device? Does it still crash?

**Comment by bear101** [comment]
@OzancanKaratas, I tried the 32-bit version on Windows XP and it works fine. Both classic and default Qt client.

**Comment by bear101** [comment]
@schulle4u, when I tried on Debian 8 x64 then it doesn't crash. I think it's the screen reader which influences the client software.

**Comment by OzancanKaratas** [comment]
This issue related with #198. Screen reader problems may be fixed using IAccessible 2 APIs.

**Comment by schulle4u** [comment]
@bear101 Using "no sound device" as input and output seems to work, switching back to "default" or "pulse" let the client crash in mor or less time. Sometimes after seconds, sometimes after a few minutes. 

I'm not sure if this is really an Orca issue as latest stable TeamTalk version has no problems appart from the usual atspi errors. 

BTW: The linux client still uses Qt4. Would upgrading to Qt5 improve accessibility and also solve the Atspi errors? The needed dependencies should be available on recent distribution versions.

**Comment by bear101** [comment]
Qt5 works much better with accessibility as far as I've read in the documentation but I cannot make the PTT key work in Qt5 :-(

**Comment by OzancanKaratas** [comment]
PTT key was set as Alt+Ctrl :)
So Push-to-Talk is not working sometimes.

**Comment by schulle4u** [comment]
@bear101 No, still the same problem, TeamTalk crashes a few moments after connecting to a channel. Audio is being transmitted successfully, then TT crashes out of nowhere. 

```
*** Error in `/home/steffen/Programme/TeamTalk/teamtalk5': double free or corruption (fasttop): 0x0000000001372d10 ***
```

The complete console output is attached to this post, perhaps this might help to find the problem elsewhere. 

Steffen

[tt_error.txt](https://github.com/BearWare/TeamTalk5/files/972768/tt_error.txt)

**Comment by OzancanKaratas** [comment]
You should delete 5.2.2 tag, TeamTalk is not running well in Windows 7 64-bit both TeamTalk Classic and Qt TeamTalk. @schulle4u Please test it on your own Linux distribution and write a comment. @bear101 You should not hurry for releasing new versions.

**Comment by schulle4u** [comment]
Still crashes under debian jessie 64 bit. I'll stay with 5.2.1 for the moment.

**Comment by OzancanKaratas** [comment]
@bear101 Qt TeamTalk is running well on Windows 7 64-bit, but push-to-talk hotkey still not working.
@schulle4u You try the new beta on your Linux distribution.

**Comment by schulle4u** [comment]
@OzancanKaratas Latest beta for linux is 5.2.2.4887, this is older than the current 5.2.2 stable release. Both are crashing. The debug version 5.2.2.4889 is only available for windows, so can't tell anything regarding linux. The classic client in 5.2.2 was crashing very often, 4889 is more stable than the older one. No program crash since I've installed it yesterday.

**Comment by OzancanKaratas** [comment]
PTT hotkey is running now, there are no problems at this time.

**Comment by OzancanKaratas** [comment]
Both TeamTalk Classic and Qt TeamTalk is not stable on Windows 7. Latest beta was installed but not working.

**Comment by schulle4u** [comment]
Short update for 5.2.2.4891: The linux build now crashes less frequently, but it is still far from being stable. Now the "double free" error happens after approximately 5 minutes of voice TX. When connecting, the client even sometimes sends weird noises into the channel.

**Comment by bear101** [comment]
Hi Steffen

I'm pretty sure the crash issue with virtual sound device is now fixed 
in this version:
http://bearware.dk/beta/teamtalk-v5.2.2.4892-debian7-x86_64.tgz
http://bearware.dk/beta/teamtalk-v5.2.2.4892-debian7-i386.tgz

--
Kind regards

Bjoern D. Rasmussen
www.bearware.dk

**Comment by schulle4u** [comment]
@bear101 Looks good so far, 30 minutes and still no crash.

**Comment by bear101** [comment]
@schulle4u @OzancanKaratas  If you have crash issues with 5.2.2 on Windwos then can you please try this version: http://bearware.dk/beta/TeamTalk_v5.2.2.4892_Setup.exe

**Comment by OzancanKaratas** [comment]
[turkish.zip](https://github.com/BearWare/TeamTalk5/files/1049888/turkish.zip)
@bear101 My computer is not running now, please get this zip file and push its content.
