### ISSUE TITLE
Accessibility hint for PTT lock doesn't match preference

### ISSUE THREAD

**Issue by bear101** [BearWare/TeamTalk5#304]
In the preferences/general settings/“Push to talklock: double tap switch button”, voiceover reports off when the setting is actually on, and on when the setting is off. As I say, this may be a voiceover labeling issue.

**Comment by OzancanKaratas** [comment]
Change it as "Transmission Behaviour", and create selection button.
For example, it is may be "Push-to-Talk" and "Locked Transmission". Do not requires to be changed VoiceOver hint in channel list.
