### ISSUE TITLE
Adding Gender Nonbinary support

### ISSUE THREAD

**Issue by GreenGablesFan** [BearWare/TeamTalk5#308]
Hello,
As someone who identifies as a different gender from the binary, I have noticed that the area where your nickname is located that there are no other options besides male or female. Some people wish to not disclose their gender for certain reasons. Might it be possible to add a third option in a future update, such as unknown, unspecified, or other, and use they and them pronouns?
Thanks!

**Comment by bear101** [comment]
Closing... out of scope

**Comment by vlad-a-c** [comment]
well, i don't see the point. at least on team talk classic you can't see someone's gender. so there's no point of that.

**Comment by GreenGablesFan** [comment]
The point is that right next to you use your name, if you press for, to the right of your nickname there are two radio buttons that about the falls is selected as mail. No desire is made to add a third gender, perhaps else with your buttons can be removed. The iOS version of TeamTalk does not have this nuissance.

**Comment by vlad-a-c** [comment]
no, what i'm saying, is that i don't see the sence of it cause on the server you can't see someone's gender.
