### ISSUE TITLE
a problem with the debian init script

### ISSUE THREAD

**Issue by vlad-a-c** [BearWare/TeamTalk5#315]
hello.
when i got the teamtalk for linux i used to get the following error when i tried the init script. job service failed to start because the control process exited with the error code. after a bunch of retries, i figured out that the first line #!/bin/bash was missing. do you mind if you could fix that in the next version?

**Comment by bear101** [comment]
Is it this client script you're referring to? https://github.com/BearWare/TeamTalk5Setup/blob/master/Client/Linux/run.sh

**Comment by bear101** [comment]
No reply. Closing...
