### ISSUE TITLE
Pressing shift+tab skips over the message input and message history in TT5 Classic

### ISSUE THREAD

**Issue by Simon818** [BearWare/TeamTalk5#317]
Using the keyboard to tab through the TeamTalk Classic interface, I first encounter the treeview, then the main sliders, then the chat / files tab control, then the message history, and finally the message input, and finally I come back around to the treeview. Ideally, I would like to be able to hit shift+tab from the treeview and immediately get to the message input, as this would be an easy way to write a message quickly. It would also be consistent with tabbing through, as shift+tab should always go in exact reverse order from tab. However, when I press shift+tab from the treeview, I get to the tab control to switch between chat and files. This means that the quickest way to get to the message text field is actually to press shift+tab once, then tab twice.

**Comment by bear101** [comment]
It should probably be fixed somewhere in this tab-key handler:
https://github.com/BearWare/TeamTalk5/blob/master/TeamTalkClassic/gui/MyTab.cpp#L31

**Comment by bear101** [comment]
@Oreonan I tried fixing the Tab -> Shift+Tab issue described here but it's quite tricky to do. At least I didn't find an easy way.

**Comment by amirmahdifard0** [comment]
Please try to fix this problem. This is an important issue and has been reported for a long time. thanks.
