### ISSUE TITLE
Voice activation usability in the Android client

### ISSUE THREAD

**Issue by poretsky** [BearWare/TeamTalk5#319]
Now if PTT button is pressed when voice activation is on the client
obeys, but implicitly turns voice activation off despite
preferences. To have it on again it is necessary to open and close
another activity or restart the main activity by some other way. It is
not clear, but somewhat useful, since allows to turn voice activation
off quickly and easy. In some cases it is pretty helpful.

I think, it would be better to have a possibility to turn voice
activation on and off directly from the connection screen rather than
via preferences, just like mute and unmute sound. Moreover, I see
almost no reason to have this option persistent.

I'd suggest to use for this purpose the microphone icon between gain
level control buttons. It can be transformed to an ImageButton
switching voice activation mode.

If my suggestion has a reason, then I am ready to implement it, but
I'd like to get an advice what icons would fit best to indicate this
button states.

Furthermore, the PTT button seems unusable in voice activation mode
and we should indicate it somehow. Maybe gray background colour. Is it
ok or something else would be better?

Besides that, it seems reasonable to have voice activation level
control just under fingers as well. But where it could be placed?
Since PTT button in voice activation mode is superfluous, we can use
its place, but this area seems too big.

Any suggestions would be appreciated.

**Comment by bear101** [comment]
I doesn't really make sense to have PTT button on voice activation mode, so I also suggest to replace it with a voice level control.

**Comment by poretsky** [comment]
I tried such an approach, but it looked not so good and finally did not
satisfy me. So, I've elaborated another solution that hav pushed just
now.

The microphone icon has been turned into an image button that being
clicked toggles voice activation on and off and changes its look
accordingly. When voice activation is on, the microphone gain control
buttons actually affect voice activation level. Maybe, it is not
absolutely clear, but, I hope, not so difficult to discover. Voice
activation level depends on the microphone gain, so, it seems not a good
idea to change gain in this mode. It should be adjusted previously and
then we can toggle voice activation on and tune its level.

When transmission is activated by voice, the tx button changes its
 background color automatically. I think, there should be a visual
 feedback anyway. This button may be used as usual in all cases, but
 being touched it implicitly turns voice activation off. When voice
 activation is on, the headset button turns it off and then works as
 usual toggling voice transmission on and off.

Please, give a look and express your opinion. Any feedback will be
appreciated.

By the way, this version is already tested carefully and I consider it
as ready for release. So, if there are no objections then it may be
rolled out and, therefore, I'll close this issue.

**Comment by beqabeqa473** [comment]
hi igor.

i've built and tested this last version and i must say, i like this idea to quickly turn on/off voice activation and tune its level.

one thing which i don't like, it is not related to these commits, but, these are sounds for activation/deactivation.

i suggest to change these earcons or add vibration feedback when this event occures.

@bear101 @poretsky what do you think?

**Comment by poretsky** [comment]
Firstly, I think that a criticism must be constructive at least. In
other words, if you insist on changing these earcons, please, suggest an
alternative. For instance, it can be easily done via a pull
request. Though I see no real reason for the moment except your personal
taste, of course. But, I think, It's hardly possible to satisfy all
tastes even theoretically. IMHO, the existing sounds are just ok. They
are pretty distinguishable, informative and fit well the application
design style. And what else is really required? Moreover, just identical
sounds are used in TeamTalkAndroid and iTeamTalk that seems quite reasonable.

I argue against haptic feedback on voice activation events, because it
can theoretically pop up permission confirmation dialog not associated
directly with touch interactions, that seems to be not ok.

**Comment by bear101** [comment]
@poretsky I finally got around to test the new voice activation. My Android phone has died but I managed to run it in the simulator.
I like the new voice activation feature. It's very simple and makes use of the existing control.
One thing that would be a bit more informative now is that mute on speaker should show volume as 0%. That way a toggle of mute also changes the percent indicator.

**Comment by bear101** [comment]
I added the +/- buttons cancels mute and volume as 0% when mute: 3726da318ede7bd8fa9ee78062328873db06ab80

**Comment by poretsky** [comment]
Hi Bjoern,

If I understand correctly what you are talking about, it is quite easy
to implement, but, IMHO, is hardly reasonable. I think, it will do not
clarify anything. Zero volume and mute are actually different
situations. When sound is muted, the volume indicator says in which
level it will be unmuted and we can change it. Of course, we can disable
volume change when sound is muted, but in that case it is not clear for
what purpose the volume tuning buttons serve on the screen. Or they
should disappear? I don't think it would look nice.

What is really questionable for me, that is the icon used for the voice
activation mode indication. I've used the icon already existing in the
project but yet not used anywhere. I am not sure that it is the best
choice, but I found nothing better. And for the moment, unfortunately, I
have no good idea how the role change of the gain control buttons could
be made intuitively clear.

**Comment by poretsky** [comment]
Yes, Bjoern, I've taken a glance. As for me, it looks like a good
solution. Thanks.

**Comment by bear101** [comment]
Should I wrap up a new release or do you have more things in the pipeline?

**Comment by poretsky** [comment]
Yes, it's just ready for release. I have nothing more for the moment.

**Comment by bear101** [comment]
Hi Bjoern,

I found a bug in the latest TeamTalk beta for Android.
It got installed just two days ago.
When I activate sound and deactivate it again,  the microphone control is not returned to the phone properly. I cannot issue any Google commands or use voice dictation.
I'm assuming this has to do with the new voice activation button or something.
Please fix.
The workaround for now is to leave the room, then audio handling is restored aparently.

Could you please include an option not to enter the default room on a server?
There are a few servers where people play loud, disturbing noises, and one cannot possibly hear Talkback over it to find the mute button.

Also, some accessibility observations.
1. I have to doubletap twice to get the microphone to work, is this intentional?
2. When using two fingers to swipe to the next page in the main window, focus is often misplaced to the microphone or speaker sliders. This will result in the microphone jumping to 0 % at random, and cannot be corrected on the fly.
I have to close out TeamTalk, restart, and then I can restore the sliders.
It would be better if the sliders were real sliders, like the ones found when reviewing an user's properties to change the volume. Those sliders can be manipulated with the volume keys as well.
I'm assuming the standard gestures do not register correctly, and TeamTalk is the only application where this is happening.

Could you please make the appearance of Teamtalk and the room name in the notification shade optional, or at least change the behaviour in the following way?
When I close TeamTalk using the overview button, the app will remain in the notification shade. To really close the app quickly, one has to click there again, then use "up a level" to exit the room, and only then will TeamTalk disappear. It would be great if I could just close it out and the icon would disappear as well, or at least make it configurable.

You can see all comments on this post here:
http://bearware.dk/?p=747#comments

**Comment by poretsky** [comment]
Concerning microphone functionality restoring: fixed.

concerning not entering a room when connecting a server: I have no good
idea how it could be implemented. Anyway, Talkback has an option to
reduce other applications sound when it talks.

Concerning accessibility observations:

1) Yes.

2) Is not reproducible.

Concerning notification and application exiting: the Overview button
actually does not exit an application, it moves it in background
instead, so, the notification is correct. It indicates that active
connection exists. To shutdown the application you should close
connection and exit in a conventional way.

**Comment by poretsky** [comment]
Sorry, I was confused concerning the Overview button. Of course, the
service should be stopped when application is cleared out of
recents. Fixed in fa777df1.

**Comment by poretsky** [comment]
Now I've addressed all the issues I am aware of in this beta-version

**Comment by bear101** [comment]
Some more feedback from users:

Hi,

thanks for acknowledging the bugs.

When I use the gestures to go back one page, focus will be placed on the microphone control or the speaker volume, causing them to change at random. I cannot manipulate them to correct the issue. As I described earlier, I have to exit out TeamTalk, then restart, enter a room, and then I can set the sliders again. As for Talkback having an option to lower other volumes, it does not work with TeamTalk for some odd reason. I'm using Marshmallow and the latest Talkback beta.
It would be great, as  I stated earlier, if the microphone and speaker sliders were like the ones in user properties, we can manipulate those with the volume buttons.
The Windows client has an option to enter the main room as per default, that's what I mean with the option of just getting to a server, then manually choosing a room. 
As a general comment, the later versions are much more stable and do not crash sound or disconnect TeamTalk as soon as I use the phone for other tasks, so whatever you did resulted in a better overall performance at least.

http://bearware.dk/?p=747#comments

**Comment by poretsky** [comment]
As I've stated already, I did not succeed to reproduce sporadic volume
or gain change as a side effect of swiping pages. On the other hand,
to place focus on a button would not be enough to activate it, it
would be necessary to make a click as well. Anyway, it seems to be not
a very good idea relying on a beta-version of TalkBack, since it can
have some problems itself.

I strongly argue against sliders for volume and gain control. Anyway,
in this version. Existing controls provide much more gradual tuning
and are pretty convenient. Moreover, replacement of these controls by
sliders would require interface design revision. So, if you insist,
I'd suggest to discuss it as a potencial feature for the future
releases.

Concerning initial room when entering a server, Android client allows
to enable or disable remembering a channel via preferences. And if it
is disabled, you will get just in the root channel by default.

**Comment by poretsky** [comment]
I think, the topic itself is over for the moment, so the issue has no
more reason to hang around.

**Comment by bear101** [comment]
Alright! I'll put out a new beta!

**Comment by bear101** [comment]
@poretsky, Now submitted to Google Play: http://bearware.dk/?p=798

**Comment by poretsky** [comment]
Very much thanks!

**Comment by beqabeqa473** [comment]
hi @poretsky 
maybe it is not related to this issue, but, some people told me that on samsung galaxy a 2017 lines voice transmition button lockups teamtalk interface when it is released and they are getting teamtalk is not responding.
they also said, that in first beta which was on oct 28, this bug was fixed, but appeared again in release build.
i tried to narrow commits and it seems commit @8494eb9eeaacec3078b94db498cfee055863d933 broke it again.
could you lok at it if you have chance please?


thank you.

**Comment by poretsky** [comment]
Yes, I've looked at it. This commit makes TeamTalk to close audio input
device unconditionally when microphone is not in use. It is necessary to
prevent phone conversation to be eventually translated to a TeamTalk
channel. I am wondering how it could cause an effect you notice.

**Comment by beqabeqa473** [comment]
i don't know also. on my galaxy s6, j5 everything works like a charm,
but on a 2017 line, a3, a5, a7 this effect is noticable.

unfortunately, i don't have any of such devices to debug what is causing this.

On 11/18/17, Igor B. Poretsky <notifications@github.com> wrote:
> Yes, I've looked at it. This commit makes TeamTalk to close audio input
> device unconditionally when microphone is not in use. It is necessary to
> prevent phone conversation to be eventually translated to a TeamTalk
> channel. I am wondering how it could cause an effect you notice.
>
>
> --
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/BearWare/TeamTalk5/issues/319#issuecomment-345451670


-- 
with best regards beqa
