### ISSUE TITLE
Voice activation state not maintained when server connection drops on Android build 66

### ISSUE THREAD

**Issue by tech10** [BearWare/TeamTalk5#322]
On testing this, the voice activation state wasn't maintained when the connection to the server was dropped, then resumed. I tested this when the screen was off, and the state of voice activation was deactivated. If we're maintaining such things as transmit and voice activation state, it ought to remain active and resume transmission when reconnecting to the server. This would increase usability if not wishing to interact with your android device, and you're switching between WIFI or mobile networks.

**Comment by poretsky** [comment]
Can you please provide exact step-by-step instruction how to reproduce
the situation?

**Comment by tech10** [comment]
Certainly. This is what I did. I originally connected to a server with WIFI enabled, turned voice activation on and set it to 0% so it would constantly transmit, went to my home screen, turned off WIFI, then deactivated my screen. When the client connected to the server on my mobile network, it wasn't transmitting, and voice activation was deactivated, when I'd previously enabled it.

**Comment by poretsky** [comment]
Fixed in 6f4335fa

Very much thanks for comprehensive description.

**Comment by poretsky** [comment]
Solved completely, AFAIK.
