### ISSUE TITLE
TeamTalk for Mac, portible client or option to use different configuration per instance

### ISSUE THREAD

**Issue by tech10** [BearWare/TeamTalk5#326]
Sometimes, I like to connect to different servers with different settings, or would like TeamTalk to automatically connect to a particular server, with each TeamTalk containing different configuration settings. At the moment, on the Mac, this is difficult to do, as you have to set up TeamTalk to use a specific configuration manually when you launch an instance, which is somewhat time consuming with VoiceOver. Could there either be different configuration files per instance, a portible client, or some way to launch TeamTalk using a selected configuration file, perhaps through the terminal or a shell script, or even an apple script set to execute the application to use an alternate configuration file?

**Comment by bear101** [comment]
There is a command line option:

http://bearware.dk/teamtalk/v5.2.3/docs/advanced.html

Use "-cfg filename.ini" to use a different config file.

--
Kind regards

Bjoern D. Rasmussen
www.bearware.dk

**Comment by tech10** [comment]
That is useful, but it could probably use some examples for Mac, unless you use the path to the TeamTalk application in the terminal, shell script, or apple script to launch the TeamTalk client.

Also, while we have a .tt file for connections to servers, perhaps we could have a .ttcfg file for entire TeamTalk configurations that could be loaded upon opening the file, just as .tt files work now. This could be useful, also, especially to do what I described easier.

**Comment by bear101** [comment]
You launch it like this:

bdr@macbox:~> /Applications/TeamTalk5.app/Contents/MacOS/TeamTalk5 -cfg 
mycfg.ini

--
Kind regards

Bjoern D. Rasmussen
www.bearware.dk

**Comment by tech10** [comment]
Can you launch that more than once, and have multiple instances of TeamTalk running under their saved configuration files, and how might you go about adding a file association for that if that's the case?
