### ISSUE TITLE
Store for move only allows one user in queue in Classic client

### ISSUE THREAD

**Issue by bear101** [BearWare/TeamTalk5#334]

**Comment by bear101** [comment]
Also support multi selection

**Comment by Mchopra7** [comment]
Hi. Is this bug planning to be fixed in the next update? Is highly annoying, as I find it very inconvenient because on the iPhone, you can do bulk moves but on the laptop with teamtalk five classic, you can’t do it. What cause the issue? Do you have any idea what could be happening?

**Comment by bear101** [comment]
Yes, I put it in milestone v5.3

**Comment by bear101** [comment]
Fixed

**Comment by Mchopra7** [comment]
When are you planning to release the next update?

**Comment by bear101** [comment]
Please try this updated version: http://bearware.dk/beta/TeamTalk_v5.3.0.4910_Setup.exe

Note that Windows XP is no longer supported in this version.
