### ISSUE TITLE
Provide text box to set the bitrate in mobile clients

### ISSUE THREAD

**Issue by OzancanKaratas** [BearWare/TeamTalk5#336]
instead of slider

**Comment by bear101** [comment]
What is the advantage of a textbox over a slider?

**Comment by OzancanKaratas** [comment]
The text box provides correct values. Slider doesn't works as wanted.

For example, you want to set bitrate as 64000. Slider skips as 10-10, so  wanted values runs away from it.

**Comment by bear101** [comment]
Does it matter if it's 64000 or 64200? I doubt you'll be able to hear the difference.

--
Kind regards

Bjoern D. Rasmussen
www.bearware.dk

**Comment by OzancanKaratas** [comment]
%10 sets 56400. %20 sets 104000. No values such as 64000 or 64200.

**Comment by bear101** [comment]
Latest iOS client clamps max bitrate if it's exceeded.
