### ISSUE TITLE
New profile dialog doesn't runs correctly

### ISSUE THREAD

**Issue by OzancanKaratas** [BearWare/TeamTalk5#339]
In the classic client's New profile dialog displays this error message:

> The file Files\TeamTalk5\TeamTalk5Classic.exe
does not contain a valid TeamTalk 5 Classic host entry.
Error message: File: . Failed to open file. Line 0 column 0.

Windows architecture: 64-bit

I don't know that how it works on 32-bit versions of Windows..

**Comment by bear101** [comment]
Fixed by 502575edddbb685a37e52dfdbdef7d19017efeaa

**Comment by bear101** [comment]
hi @OzancanKaratas can you give this one a try to see if the error is fixed: http://bearware.dk/beta/TeamTalk_v5.3.0.4916_Setup.exe

**Comment by OzancanKaratas** [comment]
Fixed, thanks.
