### ISSUE TITLE
Announce when user logs on to server in iTeamTalk

### ISSUE THREAD

**Issue by bear101** [BearWare/TeamTalk5#342]

**Comment by vlad-a-c** [comment]
well, how can i update it? i'm actually interested about this feature.

**Comment by bear101** [comment]
when the issue is closed then it has been implemented.

**Comment by vlad-a-c** [comment]
hey. just curious, how is this enhancement going? i haven't heard of any progress regarding this one since a long time ago.

**Comment by muamal** [comment]
ITeam Talk needs more features. It is the worst compared to Windows and Android

**Comment by Mchopra7** [comment]
I really wish this would be added, it would make life easy for those of us on iOS.
