### ISSUE TITLE
Mac OS X TeamTalk 5.3, unable to change video settings

### ISSUE THREAD

**Issue by tech10** [BearWare/TeamTalk5#343]
The title of this one basically summarizes the issue. In TeamTalk 5.3 on the mac, I can't select or change any video settings, especially that have to do with selecting a camera or its display options. I'm running OS X 10.13.3, the latest, I believe. Neither me or a friend of mine, who is also on a mac, are able to change camera settings.

**Comment by wemaus** [comment]
Hello,

I have exactly the same problem with TT5. I'm also running the newest OSX 10.13.3.

**Comment by bear101** [comment]
The video camera doesn't show up right?

**Comment by bear101** [comment]
Probably fixed by this commit 1ed5e04b3ca0d014aeb0deb7cf0a44528c21c53d

**Comment by tech10** [comment]
The download to the beta you provided in issue #327 doesn't have this issue, but yes, that was the problem. No video devices were showing up, now they are, and video transmission works.
