### ISSUE TITLE
Alerts upon user account/ban addition/deletion

### ISSUE THREAD

**Issue by tech10** [BearWare/TeamTalk5#348]
I propose as a possible feature that clients receive alerts upon the events of a user account being added or deleted, and the same for user banning. The alert should contain the user who performed the action, along with the user account or IP address that has been ban or removed, added or removed for user accounts. Also, the alert should tell administrators if a user account was changed, and what was changed on the user account.

Though I'm sure some TeamTalk users will do facebook logins which may or may not be more secure due to the potential for abuse in Facebook itself, it would help administrators that don't, so they can see more activity that is happening on their servers in real time without going through a complicated procedure of writing a software program that pulls the servers list of accounts and checks its own list for changes. If the client could do such a thing, I think server administrators, including myself, would find it quite useful.

I think such things are logged now, but sometimes, a log file is too late to stop a malicious user from performing actions they could be prevented, if such alerts and monitoring happened in real time.

**Comment by bear101** [comment]
If a user's account is deleted or the user is banned then the normal operation is to kick the user afterwards. It doesn't make sense to have a user on a server who doesn't have an account.
