### ISSUE TITLE
Remove own user account and possibly change own password

### ISSUE THREAD

**Issue by tech10** [BearWare/TeamTalk5#349]
I think it would be useful for users to have the ability to remove their own TeamTalk accounts if they're not using Facebook logins, and possibly, for them to either reset their password or view what it is. If they can reset their password, they shouldn't be able to set it to an empty one, opening the server for abuse, and accounts such as those with empty passwords or the anonymous account, shouldn't have the ability to remove themselves. I think this would help server administrators maintain their servers a little easier, as users then wouldn't have to come to administrators if they wanted their accounts removed for some reason.

**Comment by bear101** [comment]
Use Facebook or BearWare.dk weblogin
