### ISSUE TITLE
LibQt5 dependencies for Linux

### ISSUE THREAD

**Issue by N8JJ** [BearWare/TeamTalk5#357]
Trying to install the Linux client and I get an error from the apt install
There are 3 packages that can't be located:
libqt5webenginewidgets5
libqt5webenginecore5
libqt5webchannel5

**Comment by beqabeqa473** [comment]
hi.

try apt install libqt5webengine5

On 5/9/18, N8JJ <notifications@github.com> wrote:
> Trying to install the Linux client and I get an error from the apt install
> There are 3 packages that can't be located:
> libqt5webenginewidgets5
> libqt5webenginecore5
> libqt5webchannel5
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/BearWare/TeamTalk5/issues/357


-- 
with best regards beqa

**Comment by N8JJ** [comment]
I did.  It's already installed.  The client will still not run due to missing packages.
It may be that I'm using Ubuntu 16.04 and 17.10 is the Debian 9 derivative

**Comment by N8JJ** [comment]
I did the upgrade to Ubuntu 17.10 and that fixed it
