### ISSUE TITLE
Give channel operators and admins the ability to remove people who abuse the operator power in teamtalk

### ISSUE THREAD

**Issue by Mchopra7** [BearWare/TeamTalk5#363]
I think it would be a good idea if other channel operators and admins had the power to remove operator power from others that abuse the privilege because I just had someone that kicked someone else from a channel for no reason.

**Comment by bear101** [comment]
Why don't you just change the operator password?

**Comment by bear101** [comment]
Then why don't you delete that account?

**Comment by bear101** [comment]
Or change the account's password...

**Comment by bear101** [comment]
Closing.. Out of scope..
