### ISSUE TITLE
Team talk windows client does not have system sound filteration

### ISSUE THREAD

**Issue by abdullah5490** [BearWare/TeamTalk5#366]
Hello there. I've my own server for my project "blind help project" and we use it as our primary medium of communication for team meeting etc. But, a problem is too much disturbing and i want to explain it here, may be, someone could understand and do something to resolve it.
I have a laptop which has a 3.5mm combo audio port where i need to plug-in a single connecter headset/handfree like the one which came with our phones having 3.5mm audio jack. The common problem with this type of connector is, the audio coming from the system, also being send back via its mike. In result, whenever we record something, the system's sound also included in the recording along with our voice.
When we use some communication software, the software filter the system sound from the voice coming via mike. But in team talk, this type of filtration is not present. So what happen is, when i am on a call, and my mike is unmuted, then everybody on the call will listen to everything is playing or producing sound on my system. For example, If i play a song on my system, the sound will be heard via my mike to the call participant. If I use a screen reader like narrator, its voice also being heard by the call participant via my mike.
This kind of problem is too annoying, I cannot stop my system sound from going through to the call, and it is also disturbing for all participants as well.
This filtration is present in other calling software. For example, I use skype for audio/video calling on the same laptop, and there, this type of issue is not present. My system sound always filtered when i am on a call, and the call participants won't listen to my system sound playback via my mike.
Note: it will not happened on dool-port laptop with dool-connector headset, or on a headset which have a separate mike (not in its wire).
Please, do something to provide this filtration in team talk, so we can easily use it for our day-to-day usage. Currently, this annoying behavior is very much disturbing for me, and for all call participants. 
If you are still not understanding the nature of the problem, then i am even ready to demonstrate it live. Kindly connect with me, i'll invite you on my team talk server, and will demonstrate the problem on a live call.

**Comment by bear101** [comment]
@tech10 is this an issue you've heard of? That the screen-readers sends it output as microphone input.

**Comment by tech10** [comment]
No, the apple Macbook Pro can use a headset in a similar manner, and this issue isn't present. It sounds like using a different headset or USB sound card would be the preferred option to mitigate a problem such as this, rather than trying to get a specific software program to filter out unwanted data. After all, the same problem would exist if someone was recording microphone input with another program. I wouldn't consider this a TeamTalk issue, but a more broadly based one centered in the manner in which the computer is using the microphone input with its single 3.5MM headset jack, and perhaps the headset itself may contribute in some manner to the difficulty described here.

**Comment by beqabeqa473** [comment]
hi.

it is more hardware problem than a software.
it is some wrong construction of jacks and headsets, even in phones,
we can listen back what is playing or if screenreader is talking.
it very depends which headset are you using.

2018-07-14 23:39 GMT+04:00, Blake G <notifications@github.com>:
> No, the apple Macbook Pro can use a headset in a similar manner, and this
> issue isn't present. It sounds like using a different headset or USB sound
> card would be the preferred option to mitigate a problem such as this,
> rather than trying to get a specific software program to filter out unwanted
> data. After all, the same problem would exist if someone was recording
> microphone input with another program. I wouldn't consider this a TeamTalk
> issue, but a more broadly based one centered in the manner in which the
> computer is using the microphone input with its single 3.5MM headset jack,
> and perhaps the headset itself may contribute in some manner to the
> difficulty described here.
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/BearWare/TeamTalk5/issues/366#issuecomment-405045222


-- 
with best regards beqa

**Comment by abdullah5490** [comment]
@tech10
 and @beqabeqa473 and others, if this is the hardware problem only, then a simple question to you. why it only happened in TeamTalk? why it doesn't be problematic on Skype? because, skype has this "sound cancelation" or "sound filteration" feature build-in to it. But why does the teamTalk does not has? or if it has, then where to configgure?

**Comment by tech10** [comment]
TeamTalk does have noise reduction, duplex mode, and echo cancellation in the sound system tab of its preferences, activated by pressing F4 from the main TeamTalk window. I don't think it will block system sound from coming through along with your microphone, though, and as there are easier and better alternatives such as a USB microphone to eliminate this issue, I personally don't see the noise canceling being modified to such a degree to block system sound as well.

Unlike TeamTalk, Skype is designed to do its best to pick up a person's voice, not other background noise. It can do this in many different ways, even going so far as to modify your sound settings on your computer for you, without asking and without notification. TeamTalk doesn't do this, leaving it up to the user to modify. Though it is for voice and video transmission, it doesn't do some things quite as well as Skype, and does some things much better than Skype, especially with its ability to transmit stereo audio as originally as possible from the sound card, something Skype can't do, and in my opinion, sacrifices audio clarity in the process. All software programs are different, though, such is the nature of them.

The difficulty you're having with TeamTalk not canceling system sound won't be limited to just TeamTalk. I would imagine most other programs that capture your audio will also have this issue, and would pick up your system sound. To stop this, you should consider the above suggestion of a USB microphone, or perhaps a USB headset. This will help you nicely.

**Comment by abdullah5490** [comment]
@tech10 if this is not a feature of windows client because that is not necessary or priority for developer, then why the same case happening with its android and iOS clients? what to do to fix this issues there?

**Comment by tech10** [comment]
The developer didn't really build system sound cancellation into the iOS or Android clients, either, just took advantage of the processing available within the operating system already. After all, if you're on a phone call, you wouldn't want to hear yourself looping back, someone's notification sounds, etc. iOS and Android are expected to run on portable devices with a speaker and microphone close together, so the operating systems for such devices already have echo cancellation for system audio, no matter what it may be, built in. Windows is designed for running on a computer where you won't have that issue or can easily deal with it yourself with a set of headphones or a different sound device of some kind, so the operating system doesn't have system sound cancellation built in. That would be the same for the Mac or Linux systems, too.

**Comment by bear101** [comment]
Closing... out of scope
