### ISSUE TITLE
Switch to WxWidgets interface

### ISSUE THREAD

**Issue by OzancanKaratas** [BearWare/TeamTalk5#368]
Some users wants to use WxWidgets interface in desktop versions of TeamTalk.

We need to code the TeamTalk application's both QtTeamTalk and TeamTalk Classic. If WxWidgets interface is used, no requirements to coding separately. Because QtTeamTalk and TeamTalk Classic can be removed/deleted in TeamTalk source. Also TeamTalk clients can be named using single name (like TTDesktop).

Note: WxWidgets is licensed under WxWidgets license, but it is free to use. Also available in all operating systems.

**Comment by bear101** [comment]
Out of scope... if someone wants to develop a new client then let me know...
