### ISSUE TITLE
TeamTalkServer.NET crashes when auto-save is true

### ISSUE THREAD

**Issue by bear101** [BearWare/TeamTalk5#369]
First, 
the server program(C# version) will be broken when I set up "ServerProperties.bAutoSave = true;" and then I doing "server.UpdateServer(ServerProperties);".
It said,
Unhandled exception: System. NullReferenceException: Object reference is not set to an instance of an object.
In C_tt. Ttprodll Tts_updateserver (IntPtr lpttsinstance, serverproperties& lpserverinfo)
In TeamTalkserver Teamtalkserver. ctor () location program. CS: Line number 39
In TeamTalkserver. program. Main ([] args) position program. CS: Line number 69
I think, it maybe some variables is null. Please check it~~

Second,
I compile the server program(C# version) and start the offacial client.
I open the "Server - > User Accounts" menu, finding the left list that called "Activated User" no anything users information whatever I do any "add user" action after I reconnect the client.
But I use the client connecting the official server program, I can see all of users information when I add user information.
So, where can I get the server program(C# version)'s "getting users information data" function's entrance?
And how can I read database with server program(C# version)?  What is the function's variable?

**Comment by DevBDK** [comment]
I will check it out in the next days

**Comment by DevBDK** [comment]
on Line 69 there is no a valid instance created. Please put the srv.bAutoSave=true after the line 70.
`           ServerProperties srv = new ServerProperties();
            srv.bAutoSave=true;
            srv.nUserTimeout = 200;
            srv.nMaxUsers = 1000;
            //Update Serverproperties
server.UpdateServer(srv)`

**Comment by bear101** [comment]
Hm, I just tried to put bAutoSave = true on line 72 and I didn't see a crash:
https://github.com/BearWare/TeamTalk5/blob/master/Server/TeamTalkServer.NET/Program.cs#L70

I wonder if this have been fixed since I heard of the issue.
