### ISSUE TITLE
Last playmarket beta version don't work

### ISSUE THREAD

**Issue by grishakonzalaev** [BearWare/TeamTalk5#376]
Hello, developers!
I have got update of TT today and it's don't work. I go to server, and login, but leave server.
app tell me, that app is fail and close.
[Bearwarelogcat.txt](https://github.com/BearWare/TeamTalk5/files/2475650/Bearwarelogcat.txt)

I testet it at android 8.1 and 7.0

**Comment by bear101** [comment]
Please try to uninstall and reinstall the app. There might be some issues with new permissions.

--
Kind regards


Bjoern D. Rasmussen
www.bearware.dk

**Comment by bear101** [comment]
I found the bug and rolled out new beta (build 74).

--
Kind regards

Bjoern D. Rasmussen
www.bearware.dk
