### ISSUE TITLE
Cannot stream any media file to a classroom channel

### ISSUE THREAD

**Issue by ivnc** [BearWare/TeamTalk5#377]
Hello.

We are right now at @nvda-es organizing our first community meeting and we have decided to use TeamTalk as the main broadcasting place.
Today a person asked us if he could stream media files to the channel and, when doing a demo of this functionality, nobody between the participants was able to stream any media to the classroom channel. We have verified that the permissions are OK (Allow All Media Files Transmission, ctrl+alt+shift+r, is checked and, when unchecked, Allow Media file Transmission checkbox, ctrl+alt+r, was turned on for each user). I joined a non-classroom channel, tried to stream and it worked fine. I can reproduce this in two servers, both running version 5.3.2.4931. My client is Teamtalk 5 Classic 5.3.2.
Can someone reproduce this? Is this a bug or does the functionality require any additional configuration?

Regards.

**Comment by bear101** [comment]
Hm, yes, I can reproduce the issue. I'll look into it.
