### ISSUE TITLE
User can still "somewhat" see other users when "view all users" is disabled

### ISSUE THREAD

**Issue by bear101** [BearWare/TeamTalk5#38]
If view all users is disabled on a user account then it's still possible to do TT_DoUnsubscribe() on a user ID which cannot be seen. E.g. by unsubscribing to one self. The server should report "user not found" error.

**Comment by Simon818** [comment]
you also still get updateuser events for any administrators or other users who have permission to see all users. Here's a telnet session on my anonymous server which shows my Desktop's information. I logged in with no username on Telnet and therefore shouldn't have been able to see users at all, and I'm logged in as a non-admin on my desktop but I did give myself permission to see all users for this experiment:

teamtalk userid=1843 servername="TTHub - Anonymous Server (No Encryption): Please join a channel to see other users." maxusers=1000 maxiplogins=0 usertimeout=120 protocol="5.4"
login
accepted userid=1843 nickname="" ipaddr="::ffff:96.54.186.77" username="" usertype=1 userdata=0 userrights=69637 note="" initchan="" opchannels=[] audiocodeclimit=0 cmdflood=[0,0]
serverupdate servername="TTHub - Anonymous Server (No Encryption): Please join a channel to see other users." maxusers=1000 maxiplogins=0 usertimeout=120 motd="Welcome.\r\nThis server has no public channels, unless you make them. If someone is in a different channel from you, you can't see that person or know they exist.\r\nIf you want your channel made permanent, send me a message while you're logged in.\r\nIn case you're worried about admin permissions, my normal account (Simon) is not an administrator. The admin account is named Root, and will log in to add users or make server changes.\r\nAn encrypted copy of this server can be found on port 10440." voicetxlimit=0 videotxlimit=0 mediafiletxlimit=0 desktoptxlimit=0totaltxlimit=0 version="5.3.2.4931"
addchannel channel="/" chanid=1 parentid=0 protected=0 topic="" operators=[] diskquota=0 maxusers=1000 type=1 userdata=0 audiocodec=[0] audiocfg=[0,0]
addchannel channel="/place/" chanid=2 parentid=1 name="place" protected=0 topic="" operators=[] diskquota=0 maxusers=1000 type=0 userdata=0 audiocodec=[3,48000,1,2048,10,1,0,32000,1,0,1920] audiocfg=[0,0] voiceusers=[4095] videousers=[4095] desktopusers=[4095] mediafileusers=[4095]
ok
updateuser userid=1842 nickname="Simon (Desktop)" statusmode=0 statusmsg="" sublocal=383 subpeer=287
