### ISSUE TITLE
Android translation question

### ISSUE THREAD

**Issue by dingpengyu** [BearWare/TeamTalk5#381]
hello Bjoern D. Rasmussen
How does TeamTalk5's androidAPP translation merge? I used 7zip to extract the app's installation package, and I don't see the following translation directories and files:
values-ar
values-ar-rIL
values-az
values-de
values-es
values-in
values-mk
values-nl
values-pl
values-ru
values-tr
thanks

**Comment by bear101** [comment]
The translations are here: https://github.com/BearWare/TeamTalk5/tree/master/Client/TeamTalkAndroid/src/main/res

**Comment by dingpengyu** [comment]
thank bear101
I know the translation is here, I was wondering why the app installer does not have a translation file.

**Comment by bear101** [comment]
App installer? Don't you install using Google Play?

**Comment by dingpengyu** [comment]
No, I am not installing from Google Play.
