### ISSUE TITLE
How to update translation strings

### ISSUE THREAD

**Issue by schulle4u** [BearWare/TeamTalk5#387]
I'm currently updating german client translations. Is there a more comfortable way to update the android string files with latest changes from the "values" folder? The only way seems to compare both files line by line to determine which line is missing in the translation. This is even getting worse when line sorting differs between the files. Any CLI magic I can use?

**Comment by bear101** [comment]
The only other way I know is to use Android Studio and open its translation editor:
https://developer.android.com/studio/write/translations-editor

Open the project in Client/TeamTalkAndroid and the look for the values-files.

**Comment by bear101** [comment]
Let me know if you found another tool
