### ISSUE TITLE
Cancel echo from the own microphone

### ISSUE THREAD

**Issue by ivnc** [BearWare/TeamTalk5#392]
When broadcasting live radio using TeamTalk, it would be specially usefull for the people we connect with to not hear the echo of his own microphone the mixer returns. Echo cancellation and noise reduction work partially, has they reduce the echo but don't cancel it as Skype, channel this station was using to connect. They are thinking right now on moving to TeamTalk for its higher sound quality but the loopback audio is a problem, because it usually confuses the speakers.

thanks. Regards.

**Comment by schulle4u** [comment]
If your mixer supports more than two outputs, you can use a second sound card for your TeamTalk participants. I'm using a Behringer Xenyx X1602 recording mixer that allows me to route the output of every channel to either the main output, subgroups or both of them. Using a second sound interface connected to sub group output of the mixer and selecting it as input in TeamTalk, I'm able to only send my microphone, music and cart wall to TeamTalk, while the TeamTalk output only is sent to the main output of the mixer. TeamTalk participants don't get any echo of their own signal.

**Comment by ivnc** [comment]
Hi.


This is not a question of echo from speakers, but from a sound mixer. If 
the audio technician configures the mixer to send TeamTalk to the 
output, and then al the output audio returns back to TeamTalk, the 
speaker hears is own voice with some lag, and that could be very confusing.

It seems that the solution proposed by @schulle4u is not possible due to 
the mixer features.

The question is that, with Skype, the other person doesn't hear is own 
voice. It would be very interesting to implement some similar feature in 
TeamTalk that tries to completely cancel the echo.


Thank you all for your answers.

**Comment by schulle4u** [comment]
Even Skype's echo cancelation is far from perfect. The more it tries to suppress noises, the worse the quality of transmitted audio. TeamTalk is known for it's good quality and should not implement these type of audio castration by default. 
So if you wanna have a minimum of professionality in your shows, try to get a better mixer or at least use a simple USB microphone as a secondary talkback channel for your co-hosts.

**Comment by ivnc** [comment]
Hello.


I'm not the technician of the station. We've bot widely commented this 
and the conclussion is that the mixer has, or should have, that feature, 
but dued to a unknown issue master2 repeats somehow master1, so that 
it's the same to send audio to master1 than to send it to master2; 
although the mixer should support the configuration you've suggested, 
it's about 20 years-old and nobody wants to touch it because that is an 
university station owned by an association without such money as to buy 
a new mixer.

However, I understand your point, maxime when the main point of TT is 
its audio quality. What do you think about implementing this as an 
optional feature? We don't need to degrade the sound quality if the user 
doesn't want to do so.


Thanks. Regards


O 07/12/2018 á(s) 17:49, Steffen Schultz escribiu:

**Comment by bear101** [comment]
The best way to eliminate echo is to enable the following options in Sound System preferences:
* Windows Audio Session (on Windows)
* Duplex mode
* Echo cancellation
* Automatic gain control
* Denoising

When creating a channel you should also enable "Fixed audio volume for all users" in the create channel dialog.


In my experience echo cancellation works far better on macOS than Windows. The audio processing is significantly faster on macOS compared to Windows and can therefore eliminate echo better.

**Comment by bear101** [comment]
Currently TeamTalk uses Speex's echo chancellor but there are better ones available, e.g. the one used by WebRTC.

**Comment by ivnc** [comment]
Thank you for all your suggestions. I'm going to test with them enabled 
to see if echo is reduced. I've a Mac so I can test also from it.


Happy new year. Regards.
