### ISSUE TITLE
Missing kTCCServiceMicrophone entitlement for TeamTalk on MacOS Mojave

### ISSUE THREAD

**Issue by Flameborn** [BearWare/TeamTalk5#393]
The MacOS version of TeamTalk does not have the _kTCCServiceMicrophone_ entitlement, which results in having blocked input devices by the system, i.e. making TeamTalk not usable. TeamTalk needs to be added to the accessibility database, in particular to the Microphone category in order to make sound devices, such as the built-in Mac microphone work. This entitlement will raise a system alert at startup, letting the user grant access to the microphone.

Entitlements can be viewed via:

`~ > codesign -d --entitlements - /Applications/TeamTalk5.app`

**Comment by bear101** [comment]
Specifically, if an application does not have the kTCCServiceMicrophone or kTCCServiceCamera values in the com.apple.private.tcc.allow entitlement, the OS will block the mic or webcam, and alert the user, requesting explicit permissions.

**Comment by Flameborn** [comment]
The problem is that even though Mojave should prompt for microphone access, it does not at the moment. In an earlier version, I think it was 5.3.2, it happened, but not ever since, even on Macs where the client is installed for the first time.

Adding this to _Info.plist_ and resigning the application should fix things, according to a similar ITerm2 issue https://gitlab.com/gnachman/iterm2/issues/7194#note_109695386:

`<key>com.apple.private.tcc.allow</key>
<array>
  <string>kTCCServiceMicrophone</string>
`</array>`

**Comment by bear101** [comment]
Hm, I tried adding an Entitlements.pinfo file but then the app crashes with an invalid signature:
```
Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1
```
Are Entitlements AppStore specific? My code is signed with a Comodo license.

**Comment by Flameborn** [comment]
They are not, as far as I know. Iterm2 is not available in the Appstore, and this was one of the solutions.

Have you tried to resign the application with the added plist?

**Comment by Flameborn** [comment]
There's some more info [here](https://www.ecamm.com/mac/callrecorderft/mojave.html) about Hardened mode, I think the entitlements file you mentioned is only used if hardened mode is enabled.

Based on the Iterm2 ticket, it is possible to add these entitlements to _Info.plist_, which should not make the app crash. I will do some investigating and let you know if I find something, but in theory this should work as a fix.

**Comment by bear101** [comment]
do you get the prompt if you install this version? http://bearware.dk/beta/TeamTalk_v5.3.5.4943_Setup.dmg

I put the permission in Info.plist and then codesign without entitlements option.

**Comment by Flameborn** [comment]
Unfortunately, I still do not get prompts with this version.

**Comment by bear101** [comment]
Hm, it's the com.apple.private.tcc.allow which is causing the crash. All other permissions work fine. As soon as the com.apple.private.tcc.allow key is added then it crashes...
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>com.apple.security.app-sandbox</key>
    <true/>
    <key>com.apple.security.device.camera</key>
    <true/>
    <key>com.apple.security.device.audio-input</key>
    <true/>
    <key>com.apple.security.network.server</key>
    <true/>
    <key>com.apple.security.network.client</key>
    <true/>
    <key>com.apple.security.inherit</key>
    <true/>
    <key>com.apple.security.files.user-selected.read-write</key>
    <true/>
    <key>com.apple.security.application-groups</key>
    <true/>
    <key>com.apple.private.tcc.allow</key>
    <array>
      <string>kTCCServiceMicrophone</string>
      <string>kTCCServiceCamera</string>
    </array>
  </dict>
</plist>

```

**Comment by bear101** [comment]
Can you try running this command on Mojave and post the output here?
`codesign -d --entitlements - /Applications/FaceTime.app`

**Comment by Flameborn** [comment]
`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>com.apple.CallHistory.sync.allow</key>
	<true/>
	<key>com.apple.CommCenter.fine-grained</key>
	<array>
		<string>spi</string>
		<string>phone</string>
		<string>voice</string>
		<string>identity</string>
	</array>
	<key>com.apple.FaceTime.NoPrompt</key>
	<true/>
	<key>com.apple.accounts.appleaccount.fullaccess</key>
	<true/>
	<key>com.apple.authkit.client.private</key>
	<true/>
	<key>com.apple.coreduetd.allow</key>
	<true/>
	<key>com.apple.coreduetd.people</key>
	<true/>
	<key>com.apple.coretelephony.Calls.allow</key>
	<true/>
	<key>com.apple.icloud.passwordreset</key>
	<true/>
	<key>com.apple.imagent</key>
	<true/>
	<key>com.apple.imagent.av</key>
	<true/>
	<key>com.apple.private.CallHistory.read-write</key>
	<true/>
	<key>com.apple.private.accounts.allaccounts</key>
	<true/>
	<key>com.apple.private.aps-client-cert-access</key>
	<true/>
	<key>com.apple.private.aps-connection-initiate</key>
	<true/>
	<key>com.apple.private.audio.notification-wake-audio</key>
	<true/>
	<key>com.apple.private.communicationsfilter</key>
	<true/>
	<key>com.apple.private.contactsui</key>
	<true/>
	<key>com.apple.private.corerecents</key>
	<true/>
	<key>com.apple.private.ids.identityservicesd</key>
	<true/>
	<key>com.apple.private.ids.idquery-cache</key>
	<true/>
	<key>com.apple.private.ids.idsquery</key>
	<true/>
	<key>com.apple.private.ids.messaging</key>
	<array>
		<string>com.apple.madrid</string>
	</array>
	<key>com.apple.private.ids.registration</key>
	<array>
		<string>com.apple.ess</string>
		<string>com.apple.private.ac</string>
	</array>
	<key>com.apple.private.imcore.imremoteurlconnection</key>
	<true/>
	<key>com.apple.private.imcore.spi.database-access</key>
	<true/>
	<key>com.apple.private.iokit.darkwake-control</key>
	<true/>
	<key>com.apple.private.launchservices.changedefaulthandlers</key>
	<array>
		<string>tel</string>
		<string>facetime</string>
		<string>facetime-audio</string>
		<string>facetime-group</string>
	</array>
	<key>com.apple.private.notificationcenterui.alerts</key>
	<true/>
	<key>com.apple.private.suggestions</key>
	<true/>
	<key>com.apple.private.suggestions.contacts</key>
	<true/>
	<key>com.apple.private.tcc.allow</key>
	<array>
		<string>kTCCServiceAddressBook</string>
		<string>kTCCServiceReminders</string>
		<string>kTCCServiceMicrophone</string>
		<string>kTCCServiceCamera</string>
	</array>
	<key>com.apple.security.app-sandbox</key>
	<true/>
	<key>com.apple.security.device.camera</key>
	<true/>
	<key>com.apple.security.device.microphone</key>
	<true/>
	<key>com.apple.security.files.bookmarks.app-scope</key>
	<true/>
	<key>com.apple.security.files.user-selected.read-write</key>
	<true/>
	<key>com.apple.security.network.client</key>
	<true/>
	<key>com.apple.security.network.server</key>
	<true/>
	<key>com.apple.security.personal-information.addressbook</key>
	<true/>
	<key>com.apple.security.personal-information.calendars</key>
	<true/>
	<key>com.apple.security.temporary-exception.files.absolute-path.read-only</key>
	<array>
		<string>/Library/Preferences/com.apple.applepushserviced.plist</string>
		<string>/AppleInternal/Library/Monaco/Environments.plist</string>
		<string>/Library/Preferences/com.apple.apsd.plist</string>
	</array>
	<key>com.apple.security.temporary-exception.files.absolute-path.read-write</key>
	<array>
		<string>/private/tmp/FaceTime/</string>
		<string>/Library/Preferences/com.apple.conference.plist</string>
	</array>
	<key>com.apple.security.temporary-exception.mach-lookup.global-name</key>
	<array>
		<string>com.apple.corerecents.recentsd</string>
		<string>com.apple.coreduetd.people</string>
		<string>com.apple.duetknowledged.activity</string>
		<string>com.apple.CallHistoryPluginHelper</string>
		<string>com.apple.imagent.desktop.Launched</string>
		<string>com.apple.imagent.desktop.auth</string>
		<string>com.apple.coreservices.appleid.authentication</string>
		<string>com.apple.soagent</string>
		<string>com.apple.notificationcenterui.alerts</string>
		<string>com.apple.identityservicesd.desktop.auth</string>
		<string>com.apple.identityservicesd.idquery.desktop.auth</string>
		<string>com.apple.dockling.server</string>
		<string>com.apple.networkd</string>
		<string>com.apple.logind</string>
		<string>com.apple.CallHistorySyncHelper</string>
		<string>com.apple.telephonyutilities.callservicesdaemon.callstatecontroller</string>
		<string>com.apple.telephonyutilities.callservicesdaemon.accountscontroller</string>
		<string>com.apple.telephonyutilities.callservicesdaemon.callprovidermanager</string>
		<string>com.apple.telephonyutilities.callservicesdaemon.momentscontroller</string>
		<string>com.apple.telephonyutilities.callservicesdaemon.conversationmanager</string>
		<string>com.apple.commcenter.xpc</string>
		<string>com.apple.audio.AUPBRegistrar</string>
		<string>com.apple.ak.auth.xpc</string>
		<string>com.apple.awdd</string>
		<string>com.apple.suggestd.suggestionmanager</string>
		<string>com.apple.suggestd.contacts</string>
		<string>com.apple.videoconference.camera</string>
		<string>com.apple.assistant.dictation</string>
		<string>com.apple.CalendarAgent.proxy</string>
		<string>com.apple.rcd.media.key.events</string>
		<string>com.apple.photolibraryd</string>
		<string>com.apple.BluetoothDOServer</string>
	</array>
	<key>com.apple.security.temporary-exception.sbpl</key>
	<array>
		<string>(allow mach-lookup (global-name-regex #"^[0-9]+$"))</string>
		<string>(allow authorization-right-obtain (right-name "com.apple.icloud.passwordreset"))</string>
	</array>
	<key>com.apple.security.temporary-exception.shared-preference.read-only</key>
	<array>
		<string>com.apple.logging</string>
		<string>com.apple.VideoConference</string>
		<string>com.apple.GVAEncoder</string>
		<string>com.apple.AppleGVA</string>
		<string>com.apple.imagent</string>
		<string>com.apple.digihub</string>
		<string>com.apple.monaco</string>
		<string>com.apple.conference</string>
		<string>com.apple.FaceTimeTests</string>
		<string>com.apple.iTunes</string>
		<string>com.apple.AVConference</string>
		<string>com.apple.TelephonyUtilities</string>
	</array>
	<key>com.apple.security.temporary-exception.shared-preference.read-write</key>
	<array>
		<string>com.apple.FaceTime</string>
		<string>com.apple.ids</string>
		<string>com.apple.id-status</string>
		<string>com.apple.facetime.bag</string>
		<string>com.apple.conference</string>
		<string>com.apple.logging</string>
		<string>com.apple.TelephonyUtilities</string>
	</array>
	<key>com.apple.system.get-alert-tone</key>
	<true/>
	<key>com.apple.system.set-alert-tone</key>
	<true/>
	<key>com.apple.telephonyutilities.callservicesd</key>
	<array>
		<string>access-calls</string>
		<string>modify-calls</string>
		<string>access-call-capabilities</string>
		<string>modify-call-capabilities</string>
		<string>access-moments</string>
		<string>modify-moments</string>
	</array>
	<key>com.apple.videoconference.allow-conferencing</key>
	<true/>
	<key>keychain-access-groups</key>
	<array>
		<string>ichat</string>
		<string>apple</string>
		<string>appleaccount</string>
		<string>InternetAccounts</string>
		<string>IMCore</string>
	</array>
</dict>
</plist>`

**Comment by bear101** [comment]
I finally got my new Mac so I can develop on Mojave. I managed to install this package and get the permission prompts when configuring sound and camera:
http://bearware.dk/beta/TeamTalk_v5.3.5.4944.pkg

**Comment by Flameborn** [comment]
This seems to have fixed it for me as well. My preferences got reset, but that is to be expected.

Thank you very much!

**Comment by bear101** [comment]
Ah, yes, I can fix the preferences issue.

**Comment by bear101** [comment]
Hm, it's seems it's Qt 5.12 that has changed the default location of config-files. Before TeamTalk5.ini was in `~/.config/BearWare.dk` now it's in `./Library/Containers/dk.bearware.TeamTalk5/Data/.config/BearWare.dk/TeamTalk5.ini`

**Comment by Flameborn** [comment]
Ah, that’s all right. I think if you mention this in the release notes, it should not cause issues.

**Comment by bear101** [comment]
I've created a beta version which uses the old config file:
http://bearware.dk/?p=905
I don't use the entitlements file for code signing but instead just added the camera and microphone prompts: 0ce80c64f221f14afb8996dac604fca4564d28d4

**Comment by bear101** [comment]
The entitlements file puts the app into a sandbox but this prevents Facebook weblogin from working so I had to create an "old fashioned" app and installer.

**Comment by Flameborn** [comment]
Thank you very much. I consider this fixed.
