### ISSUE TITLE
TT can't send large messages to channel.

### ISSUE THREAD

**Issue by grishakonzalaev** [BearWare/TeamTalk5#394]
Hello.
I found the bug in sending messages to TT channels.
If I paste cirillic message more than 256 symbols without carriage returns to edit field, all participants see one dot instead my message.
If I send latin message more than 4096 symbols without carriage return, message can't send.

**Comment by bear101** [comment]
Text messages are limited to 512 UTF-8 characters. Depending on how your characters are encoded they may take up to 4-bytes each (AFAIR).
