### ISSUE TITLE
Forced Speaker phone on android client

### ISSUE THREAD

**Issue by abdullah5490** [BearWare/TeamTalk5#398]
Hello there. The android client v5.3.4 is not handeling the speaker phone properly. It always uses the speaker phone by default as an audio output even the option is disabled in the "settings". 
what we need to do to switch to the ear speaker:
1. Go to settings after connecting to the server.
2. enable "voice preprocessing".
3. enable "speaker phone" option once and then disable it again at the same time.
4. Now, when we go back, the audio output will switch to ear speaker itself -  That doesn't make sense!
Secondly, when we close the app, the phone's default audio output remains sticked to the ear speaker and we need to restart the device in order to restore the voice back to the regular phone speaker.
It should be tweaked instantly.

**Comment by poretsky** [comment]
Addressed in 95239246.

**Comment by bear101** [comment]
@abdullah5490 If this is still an issue then please reopen.
