### ISSUE TITLE
Option to control media volume when streaming

### ISSUE THREAD

**Issue by bear101** [BearWare/TeamTalk5#405]

**Comment by beqabeqa473** [comment]
oh, yes. i've asked this numerous times

On 3/9/19, Bjørn Damstedt Rasmussen <notifications@github.com> wrote:
>
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/BearWare/TeamTalk5/issues/405


-- 
with best regards beqa
