### ISSUE TITLE
The following string is missing from the TeamTalkClassic client

### ISSUE THREAD

**Issue by dingpengyu** [BearWare/TeamTalk5#407]
Hi bjoerndrasmussen, there are some strings in the TeamTalkClassic client that are not available, the following is a list:
User Account：
User can change nickname checkbox selected (cannot be translated)
User can record voice in all channels check box unchecked (cannot be translated)
Close button Alt+l (cannot be translated)
Channel information:
OK button (cannot be translated)
Cancel button (cannot be translated)
Server statistics:
OK button (cannot be translated)
TeamTalk5Classic connection:
An error occurred while perform a requested command: Invalid user account
(cannot be translated)
Failed to connect to host "" TCP port UDP port . Check that the server is running on the specified address and that a firewall isn't preventing clients from connecting.
(cannot be translated)
thank

**Comment by dingpengyu** [comment]
cc
@bear101

**Comment by bear101** [comment]
I fixed a few of the missing in this commit: 2d986d2b17d7caa8653692748df4d5d5959f02bf

**Comment by dingpengyu** [comment]
Hi Thanks for the work of bear, the following is my statistical feed string:
Server property:
Create anonymous user account? (no translation)
User Account:
button(Untitled)
button (Untitled)
Kick out + kick out and ban:
An error occurred while perform a requested command:
Command not authorized
thank

**Comment by dingpengyu** [comment]
Hi @bear101 
I tested TeamTalk 5 Classic 5.5.0.4978
The following translation string is not in lng_classic/English.lng:
No Audio Preprocessor
Start position 滑块 0
Play 按钮 Alt+p
TeamTalk Audio Preprocessor
Setup 按钮 Alt+s
Start position 滑块 0
Play 按钮 Alt+p
Speex DSP Audio Preprocessor
Setup 按钮 Alt+s
Start position 滑块 0
Play 按钮 Alt+p
Audio preprocessor
thanks

**Comment by bear101** [comment]
I think has been fixed by @Oreonan
