### ISSUE TITLE
V4L2 support

### ISSUE THREAD

**Issue by bear101** [BearWare/TeamTalk5#41]
TeamTalk uses an old API for video capture on Linux, i.e. V4L. It should be replaced by a new video capture API.

**Comment by bear101** [comment]
https://help.ubuntu.com/community/Webcam

**Comment by sp2ong** [comment]
I can understand why you send info how to setup webcam under ubuntu ?? My webcam working very
well under ubuntu but I can not use under TT because TT don't see my webcam

**Comment by bear101** [comment]
It's because TT doesn't support V4L2.

On 17. nov. 2015, at 09.49, Waldek <notifications@github.com> wrote:

I can understand why you send info how to setup webcam under ubuntu ?? My
webcam working very
well under ubuntu but I can not use under TT because TT don't see my webcam

—
Reply to this email directly or view it on GitHub
<https://github.com/BearWare/TeamTalk5/issues/41#issuecomment-157310840>.

**Comment by sp2ong** [comment]
Ok many thanks you for clarification situation of TT. Do you have plan add possibility support webcams
in TT under Linux or I must buy MS Windows system to use TT with webcam ?

**Comment by bear101** [comment]
For now Windows and Mac have the best webcam support. Android and iOS also
currently lack webcam support.

On 17. nov. 2015, at 10.50, Waldek <notifications@github.com> wrote:

Ok many thanks you for clarification situation of TT. Do you have plan add
possibility support webcams
in TT under Linux or I must buy MS Windows system to use TT with webcam ?

—
Reply to this email directly or view it on GitHub
<https://github.com/BearWare/TeamTalk5/issues/41#issuecomment-157322742>.

**Comment by bear101** [comment]
V4L2 support in v5.2.0.4692
