### ISSUE TITLE
Feature suggestion: Add MP3-format (320 kbit)

### ISSUE THREAD

**Issue by dpy013** [BearWare/TeamTalk5#411]
hi bjoerndrasmussen
TeamTalk 5's new recording to mp3 format is a nice new feature, but without mp3 (320kbps), if possible, can you add recording to mp3 (320kbps) recording format?
thank

**Comment by dingpengyu** [comment]
cc
@bear101

**Comment by dingpengyu** [comment]
cc @bear101 and @beqabeqa473
