### ISSUE TITLE
Inform users when text message limit is exceeded

### ISSUE THREAD

**Issue by bear101** [BearWare/TeamTalk5#412]
UTF-16 strings are converted to UTF-8 and cut at 511 characters. If the string is cut then the user should be informed or indicated in the received message.

**Comment by bear101** [comment]
https://stackoverflow.com/questions/35328529/stdstring-optimal-way-to-truncate-utf-8-at-safe-place

**Comment by Oreonan** [comment]
On Windows when limit is exceeded, an empty line is send. We can probably send the 511 first characters.

**Comment by bear101** [comment]
The problem is that the string you send on Windows is encoded in 16-bit values which are then converted to UTF-8 which can be up to 32-bit values.

**Comment by bear101** [comment]
https://stackoverflow.com/questions/37623359/how-to-remove-the-last-character-of-a-utf-8-string-in-c
