### ISSUE TITLE
Allow selecting loopback input devices on Windows using WASAPI

### ISSUE THREAD

**Issue by masonasons** [BearWare/TeamTalk5#413]
Currently, selection of Loopback Input devices on windows is not possible, however WASAPI has this feature. It would be cool to see this added to tt as it makes sharing system audio easier.

**Comment by slannon97** [comment]
I'd also like to see this feature added to the Windows version. If the user could select the default playback device as an input, this would greatly simplify sharing system audio. There would be no need for hardware mixers or software workarounds that create virtual audio devices.

**Comment by burakyuksek** [comment]
Yes, I want this feature as well, please.

**Comment by ntcarver0** [comment]
Unfortunately, this would also make it much easier for spammers to spam channels with loud, looping audio. However, if this weren't such a glaring issue, I'd support this idea too.

**Comment by burakyuksek** [comment]
The one who is going to do this, is going to do this no matter what.

**Comment by bear101** [comment]
PortAudio has a pull-request that should add loopback interface: https://github.com/PortAudio/portaudio/pull/672
