### ISSUE TITLE
Bug in the teamtalk's channel ban list, Changing channel name effects the ban list

### ISSUE THREAD

**Issue by abdulrahmanessam** [BearWare/TeamTalk5#414]
When You ban someone from a channel and when You change the name of a channel the person can join but the name still in the ban list, when I tried to unban it it shows channel not found, and when I restored the name it's possible to unban him

For some reasons I can't change a channel name because of that

**Comment by bear101** [comment]
Bans are stored with channel-path. Therefore renaming a channel will invalidate existing bans:
https://github.com/BearWare/TeamTalk5/blob/master/Library/TeamTalkLib/bin/ttsrv/ServerXML.cpp#L1120

It's a bug but a bit tricky to fix

**Comment by amirmahdifard** [comment]
guys, seriously please fix this
