### ISSUE TITLE
Passwords should be stored as MD5 sum instead of plain text

### ISSUE THREAD

**Issue by bear101** [BearWare/TeamTalk5#42]
(in Pro-edition)

Maybe use the bProtected field to tell whether password should be changed. On UserAccount blank password is no change?

**Comment by Oire** [comment]
MD5 in 2017? Oh no, prefer secure hashing, something like salted PBKDF2. but I fully support the initiative :).

**Comment by bear101** [comment]
https://github.com/Anti-weakpasswords/PBKDF2-GCC-OpenSSL-library/blob/master/pbkdf2_openssl.c#L127

**Comment by bear101** [comment]
Obsoleted by BearWare.dk weblogin
