### ISSUE TITLE
classic client: change broadcast messages acceptance

### ISSUE THREAD

**Issue by beqabeqa473** [BearWare/TeamTalk5#422]
hello.

currently, broadcast messages are playing sound of private message and outputting information in chatlog.

in most cases, this sound could be deceptive.

what do you think about changing it to something from the following.

1. replace outputting to chatlog to a simple MessageBox.
2. change sounc for broadcast message.

personally, i preffer MessageBox.

if you have any other way to improve situation, please write here.

**Comment by Mchopra7** [comment]
I prefer a sound. I think that would be easier.
