### ISSUE TITLE
Support bluetooth headsets

### ISSUE THREAD

**Issue by beqabeqa473** [BearWare/TeamTalk5#426]
For now, in Teamtalk for android bluetooth headsets are not fully supported.

specifically, we cannot use headset mic in teamtalk.

**Comment by Oreonan** [comment]
I just aproove this suggest. I think it will be very interesting to use bluetooth mic headset...

**Comment by emrerencber** [comment]
Hello.  I am thinking of buying Anker SoundCore Bluetooth 5.0 headphones.  However, I have doubts about its compatibility with TeamTalk. I will generally use it in Windows environment and TeamTalk 5 Classic Client For Accessibility mode. Sometimes I can use it with iOS. Can I use Teamtalk with this headset? Do I have problems with the microphone sound?

**Comment by poretsky** [comment]
Suggested in #558. I don't think that it will work identically good
on every hardware, thus, I've implemented it as an option.
