### ISSUE TITLE
Add the possibility for users to login to a team talk server via fone call

### ISSUE THREAD

**Issue by Adriani90** [BearWare/TeamTalk5#432]
Dear all,

I am a contributor at the NVDA project where we organize every year a conference for users, developers and other stakeholders. The conference is called NVDACon. Since 2014, we host the conference every year on a Team Talk server owned by NV Access.

Background for this requested feature is that we want to reach as many NVDA stakeholders as possible, even people in developing countries, people with limited access to internet and people who are not using a smartfone.

My proposal is to build a feature where server admins can assign a fone number and specify a time slot during which the number is valid. After the time slot expires, the fone number becomes invalid.
On the other side, when a user calls that number, it must enter a pin code which has been created by the server admin and shared with the people. Then, the user must speak or type a user name and press the hash key. After that, the user is online. After the user is online, it must press the hash key to speak and hash key again to turn off its microfone. This would be a default push to talk setting to avoid echo and similar side effects.

Is it possible to create such a feature?

**Comment by dingpengyu** [comment]
cc
@bear101 
and
@beqabeqa473

**Comment by bear101** [comment]
Sorry, but it's way out of scope
