### ISSUE TITLE
Ban subnet

### ISSUE THREAD

**Issue by bear101** [BearWare/TeamTalk5#44]
Is it possible to ban an entire subnet? 
For example 88.135.233.x 
Where x can be ANY number?

**Comment by beqabeqa473** [comment]
hi.

i know this should get a new issue, but, is it possible to make a ban by mac adress or by some hardware id to ban user permanently?

**Comment by bear101** [comment]
If you can find a way to extract some unique ID from a machine (Windows, Mac, Android, etc) then you're welcome to show me.

**Comment by beqabeqa473** [comment]
on pc we can use id of ram , hard disk etc.

on android i found this.
http://www.pocketmagic.net/android-unique-device-id/
