### ISSUE TITLE
error. Can't upload file to server. Teamtalk android

### ISSUE THREAD

**Issue by grishakonzalaev** [BearWare/TeamTalk5#441]
If I press upload button teamtalk stops and show me two buttons: restart app and send review. 
Android 8.1 lineageos, Xiaomi land redmi3x, last teamtalk version 5.4. I am betatester in playmarket.
[filesendcrash2019-07-18_215558_logcat.txt](https://github.com/BearWare/TeamTalk5/files/3408100/filesendcrash2019-07-18_215558_logcat.txt)

**Comment by beqabeqa473** [comment]
yes, i think this was a cause to crash byt inspecting logcat.
