### ISSUE TITLE
iOS 13 - unable to transmit, only partially able to receive audio

### ISSUE THREAD

**Issue by cartertemm** [BearWare/TeamTalk5#448]
Running the latest beta of iOS 13 on an iPhone 8.

When joining a server, I can hear a couple (about three) seconds of audio before it promptly goes away. Transmitting doesn't seem to work either. Might be worth noting, this issue only presented itself in the fifth developer beta.

**Comment by bear101** [comment]
If you toggle the Voice Preprocessing option in Preferences does that
make the problem go away?

--
Kind regards

Bjørn Damstedt Rasmussen
www.bearware.dk

**Comment by cartertemm** [comment]
Yes, this seems to fix it at least temporarily. However, the moment someone joins or leaves the channel I'm forced to toggle again.

**Comment by jadesharp1992** [comment]
so I am running the ios 13 beta as well and this happens on bluetooth headphones, wired headphones. if you join a channel, you can hear audio for a second, but it seems to be that once voiceover speaks and you hit the transmit button, everyone's audio ducks down and you can't hear them and they can't hear you. you can get it back by bringing up siri, but the moment someone joins the channel and voiceover speaks, audio goes again. I don't know if this is affecting it, but this article might be worth a read with some changes that are being made in IOS 13. https://www.forbes.com/sites/kateoflahertyuk/2019/08/07/apple-just-dealt-a-major-blow-to-facebook-with-this-new-ios-feature/#57d28566414a

**Comment by jadesharp1992** [comment]
so, I have found a temporary solution. I tried this earlier and it works. so for now you have to go into text to speech events and turn off everything. so now if someone joins the channel and it just clicks, you do not lose audio. You can be heard, and you can hear everyone else. it seems to be that when the teamtalk tts ducks the audio it has problems.

**Comment by jadesharp1992** [comment]
Hi everyone, so just to let you know apple released ios developer beta 7 today and teamtalk is working perfectly again. you can use text to speech, you can transmit audio and you can be heard as well, so it's all good!
