### ISSUE TITLE
Allow Team Talk 5 Classic to use SAPI for messages even if a screen reader is running.

### ISSUE THREAD

**Issue by slannon97** [BearWare/TeamTalk5#449]
Currently, Team Talk 5 Classic speaks server messages using a screen reader if it is running. If no screen reader is running or the running screen reader is not supported, the client switches to SAPI 5. Please add an option to force the client to use SAPI even if a supported screen reader is running. I realize this may not be what everyone wants, but leaving the current behavior as the default while giving users the option to override it and use SAPI could be helpful.

**Comment by beqabeqa473** [comment]
agree on that.

sometimes when working on something with screenreader, it is possible to miss some chat messages.

so, we could add a checkbox in settings > text to speech to preffer sapi over screenreader.

**Comment by bear101** [comment]
@beqabeqa473 Can this be solved by calling Tolk_PreferSAPI() ?

**Comment by beqabeqa473** [comment]
Yes, exactly

**Comment by beqabeqa473** [comment]
There should be two checkboxes in tts settings. One tfor sapi5 and another to completely enable disable tts events. As I know, there is no way to do this.


I can do these on these weekends

**Comment by bear101** [comment]
"Me -> Enable TTS" can disable TTS completely.

**Comment by beqabeqa473** [comment]
yes, but it is not persistent across restarts as i can remember.

On 9/12/20, Bjørn Damstedt Rasmussen <notifications@github.com> wrote:
> "Me -> Enable TTS" can disable TTS completely.
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/BearWare/TeamTalk5/issues/449#issuecomment-691422911


-- 
with best regards beqa

**Comment by bear101** [comment]
Ok, but we can change this.

Kind regards

Bjoern Damstedt Rasmussen
www.bearware.dk

**Comment by beqabeqa473** [comment]
ok, i will add corresponding config entry and change that on menuitem change.

**Comment by Oreonan** [comment]
We can probably close this now. This option has been implemented in Qt client to which users are encourage to switch. @bear101 what about this?

**Comment by bear101** [comment]
Ok, will do.
