### ISSUE TITLE
SSL certificate verification

### ISSUE THREAD

**Issue by Simon818** [BearWare/TeamTalk5#451]
We can't really add domain verification without a client update, but how about a trusted certificates list and a prompt to trust a new certificate? That way if something changes, the user will know about it and can make an intelligent decision. Right now if someone's SSL cert changed or someone were intercepting my traffic for some reason, I would have no idea.

**Comment by bear101** [comment]
Server side verification of clients has been merged to master (ssl_verify branch). Client-side support for private-key, certificate and CA file(s) is still pending.

@Simon818 how would you prefer that clients get their private key and certificate? Should users send a client certificate request to you or do you plan to send private key and certificate to clients?

**Comment by Simon818** [comment]
Hmm, I think this should be a system a user can put in place as a login method if they wish and server owners can enforce if they want extra security (much like SSH keys). I wasn't actually thinking about client-side verification when I wrote this, though it is important and something I'd probably put in place. I think if the client could generate--or use--its own set of keys and allow the user to send theirs to an administrator, that would work. Am I misunderstanding? You also know way more about this than I do, so I would welcome your thoughts on how it should or shouldn't work. I just want to make sure it's secure but also easy for non-administrators to deal with and set up. If you can point me at the documentation in question I can also take a look and probably be way more constructive than this.

**Comment by bear101** [comment]
I've written a guide here on how you configure encryption in the tt5pro server: https://bearware.dk/test/teamtalksdk/v5.6.1.5007/docs/C-API/serversetup.html#ttsrvencrypt

As you can see it's a complicated process to do peer verification.

**Comment by bear101** [comment]
This issue will not be part of v5.7 since it has to be thought more through how it should be used.

**Comment by bear101** [comment]
@Simon818 please try out the new client/server verification in pull-request #1780

**Comment by Simon818** [comment]
I'm kind of a GitHub noob. Is there a build available? I don't have a dev environment set up and I don't see one linked there.

**Comment by CoBC** [comment]
This is probably what you have to use:
https://github.com/BearWare/TeamTalk5/suites/12323997912/artifacts/653688957

**Comment by bear101** [comment]
See #1920
