### ISSUE TITLE
TeamTalk Server API List<Useraccounts> lstAccounts empty 

### ISSUE THREAD

**Issue by DevBDK** [BearWare/TeamTalk5#453]
Hello Bjoern,

tts doesnt save the created Useraccounts internally.

Is this a bug or a feature?

**Comment by bear101** [comment]
It's intentional. User accounts should be save in a database or
configuration file.

Kind regards

Bjørn Damstedt Rasmussen
www.bearware.dk

**Comment by DevBDK** [comment]
Thanks for the Answer, but how to management the Client get the Useraccount list? Its possible to make an callback to get an array of Useraccounts and send it to the client? When the client DoListUserAccounts ?

**Comment by bear101** [comment]
Handling of DoListUserAccounts() is currently not support by the TTS
API. You can only authenticate at the moment (DoLogin()).

Kind regards

Bjørn Damstedt Rasmussen
www.bearware.dk
