### ISSUE TITLE
Client crash because of Filepicker exception

### ISSUE THREAD

**Issue by beqabeqa473** [BearWare/TeamTalk5#454]
hi.

a crash occurres when trying to launch file picker class after removing saved path in shared preferences.

this results in non workable state of stream media files, import servers from file and file uploading.

**Comment by beqabeqa473** [comment]
fixed in 5821db25f98dee1a2bb7501abe094182db00b053#

**Comment by beqabeqa473** [comment]
@bear101 is it possible to release a hotfix release for this?

i am asking because after introducing stream media files on android, it is possible to have specific file/directory on user's device now but it could be removed in the future and user will get crash.

**Comment by bear101** [comment]
I've created a new beta release (v5.4.1). It's being processed by Google now.

**Comment by bear101** [comment]
Is this the same issue #441 ?

**Comment by beqabeqa473** [comment]
i think so.

anyway, logcat pointed to the same line of code.

so #441 should be fixed now.
