### ISSUE TITLE
no simultaneous voice transmission UpdateChannel event

### ISSUE THREAD

**Issue by DevBDK** [BearWare/TeamTalk5#455]
Hello Bjoern,

when someone already are in voicetx mode, the UpdateChannel event doesnt update new queued voice user. Only when the current voice user release, then the queue send the UpdateChannel event.
But the new User need to know who is waiting in the queue, to update there icon state in the Userlist. 
Can you update the queue (with UpdateChannel) always, when a user release or add to the queue.

And when A User Joinedchannel send an UpdateChannel event with the TransmitUserQueue

Thanks.

**Comment by bear101** [comment]
Will be fixed along with #321
