### ISSUE TITLE
TeamTalk Server 5 Window Application

### ISSUE THREAD

**Issue by DevBDK** [BearWare/TeamTalk5#456]
Hello Bjoern,

i have almost finished the server application. Do you think we can upload it to the website?

**Comment by bear101** [comment]
What is the different in this server and the existing Windows server application?

**Comment by DevBDK** [comment]
Multiple Server Creation.
Save Config in XML file.
User Management
Room Management

![1](https://user-images.githubusercontent.com/24915755/63615687-37278e80-c5e6-11e9-90f6-f144de81faa7.gif)
![2](https://user-images.githubusercontent.com/24915755/63615693-3a227f00-c5e6-11e9-9398-a94d3ddcf120.gif)


Which Window Server app u mean? I know only the Console Application!

**Comment by bear101** [comment]
You're welcome to submit the the project in the Server-folder as a TeamTalk server example.
