### ISSUE TITLE
Add additional admin and channel configuration settings to the client and server.

### ISSUE THREAD

**Issue by slannon97** [BearWare/TeamTalk5#457]
The broadcast message feature should be expanded to support sending voice data as well as text. Broadcasting your voice to all users in the server might be more effective as opposed to sending out a global text message.

Please add the ability to disable streaming audio and/or video files when creating a channel. Currently, this can only be controlled at the user level. The ability to disable streaming of audio and video files on a channel by channel basis will prevent people from coming onto servers and spamming others, especially in public channels.

**Comment by slannon97** [comment]
Here is another idea. Allow an administrator to specify how many times someone can connect using a specific user account. For example, a person can only connect twice. If a third attempt to connect to the server using the same credentials is detected, it simply does not connect. Currently, the only choice you have is to either allow one connection or multiple, which can be as many as you want. Basically, I want more exact control over this setting. This should be in addition to the current setting that determines how many logins can be used per IP address.

**Comment by bear101** [comment]
Press F9 in Classic or Qt Client and locate "Server Abuse". Here you have the option to ban after failed login attempts.

**Comment by bear101** [comment]
Sending out a "voiced" broadcast message would be quite difficult with the way TeamTalk configures its channels. All channels can have different audio codecs, so the voice message would have to be encoded multiple times.
