### ISSUE TITLE
add flag for block prior client versions

### ISSUE THREAD

**Issue by nunotfc** [BearWare/TeamTalk5#462]
Hello! Can you add a flag in the server? for example: minversion=5.4 with this value, all client versions that not match the value in the server flag, can't conect to the server. for security reasons. I suspect that exists persons in public servers that are using outdated versions to slow the conection of all the server, or for hacking.

**Comment by ntcarver0** [comment]
I believe this is already doable by changing a line in your server's XML file like so:

<teamtalk version="5.1">

Just change the version number in quotes to the lowest client version that you want your users to have before they can connect. Note that I am unable to test this on my end, so you'll have to try this out and report back.

**Comment by bear101** [comment]
You cannot slow the connection to the server by using an old client.
