### ISSUE TITLE
Pack prebuilt file in Windows

### ISSUE THREAD

**Issue by huanghe2015** [BearWare/TeamTalk5#463]
Is it necessary to pack prebuilt files as an installer? If not, pack binary files on Windows as an archive in future versions.
By the way, modify location of the server configuration file. the best suggestion is in the subfolder of the server's root directory, it will be lost easily after reinstall OS.

**Comment by bear101** [comment]
There's a portable version of TeamTalk Classic. There's also a Windows Store version.
http://bearware.dk/teamtalk/v5.5.1/TeamTalkClassic_v5.5.1_Portable.zip
