### ISSUE TITLE
Ability to change client's keep-alive settings

### ISSUE THREAD

**Issue by bear101** [BearWare/TeamTalk5#465]
UDP and TCP keep alive interfaces are currently entirely controlled by the client instance. It should be possible for developers to set their own keep alive intervals.

**Comment by Simon818** [comment]
I would likewise appreciate seeing this in the existing client instance. I frequently drop from TeamTalk servers only to immediately reconnect. This is almost always the client's fault as I have pretty generous timeout intervals on my servers. This is of course my internet's fault, but being able to account for this in the client would be excellent.
