### ISSUE TITLE
Web Interface For Team Talk

### ISSUE THREAD

**Issue by Elshara** [BearWare/TeamTalk5#469]
As someone who has used team talk since 2007, This is a feature request.
Tea Talk needs a web interface so that people don't need a client to connect to the server.
Web interface could allow people to register themselves on the server. Web interface could support message storage and the ability to manage server roles if you are an admin. Web interface could support SSL encryption.
Why does team talk need a web interface? Eight main reasons to consider:
1. voice and text forum with file attachment support and media play back. This could be expanded as a professional feature as well. I know people would pay for in a heart beat.
2. Ability to expand on a per instance basis. Turn channels into categories and you'd be able to get a search engine presence.
3. Having the ability to post into multiple channels using multiple inputs and outputs would make notifications a breeze and configurable. It could be used as a streaming service that is interactable rather than a broadcast server.
Having web access for both Debian and Cent OS would make Team Talk compatible with Cron for updates as well, so that people don't have to spend too much time with server admins and updates to server installations. especially if a Git reposatory was there to manage the file instances, one could essentially run it on master for ever using git version controls without needing to adapt to GDK.
4. More time spent on developing features rather than client compatibility accept for apps which could use Iframes from the web client to manage browser simulations. Using WebRTC and configurable options for Opus, this is possible using default sound settings on your computer or device.
5. Low footprint saving memory resource usage. You could get listed in Softaculous as a conferencing application as well, giving the platform more of a direct boost. You could also charge for add ons to the platform if you wanted individually and make it a marketplace which could help fund more research. This would also make more contributors happy to develop forks in return because it's all open source and powered by the web.
6. Server decentralization. With web access, one could theoretically communicate with other web servers so that you could using team talk on multiple domains, connect with channels and users away from a centralized server instance or platform. This way people could freely go to a social web without limitations and therefore bring popularity to the project. Making communication valued as a direct protocol expansion. Similar to Mastodon.
7. Having web access means you could host files remotely so people could host their own instances and files on shared hosting, but have a public port for bandwidth to start out for domain connectivity until you know you can host your own. This way official public servers could have many channels, but b more customized by direct use rather than tying up server members in and of itself as it could use localized databases for the hosted versions to connect to just by using optional remote port access. Similar to CDN.
8. No limitations on features. Anything you'd want, from voice transcriptions to emogis could be available. It would also decentralize Skype and Discord for their interference in web calls that I started noticing is happening more and more as data censorship increases.
I hope this happens.

**Comment by bear101** [comment]
Out of scope for now
