### ISSUE TITLE
TeamTalk Classic: Use line feed instead of carriage return

### ISSUE THREAD

**Issue by OzancanKaratas** [BearWare/TeamTalk5#470]
Generally, TeamTalk Classic uses the standard Windows line ending (CR). However, LF is better than CR in chats.
- Screen readers acts users better with LF,
- LF looks fine in the screen,
- In fact, CR is not a new line mark. It is just ends the current line.

**Comment by bear101** [comment]
Isn't this a screen reader issue and not related to TT? From this discussion it seems to be a configurable option in the screen reader: https://nvda.groups.io/g/nvda/topic/carriage_return/5159902?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,40,5159902
