### ISSUE TITLE
Add encryption to the server

### ISSUE THREAD

**Issue by slannon97** [BearWare/TeamTalk5#471]
Team Talk servers are not encrypted by default. The only way to do this is to purchase the SDK, which is prohibitively expensive and not necessary for most users. Please add encryption to the server by default. Encryption is a standard now, so it is silly to run unencrypted anything on the Internet anymore.

**Comment by Simon818** [comment]
I had heard there would be an easy way to license the server that has encryption without paying for the SDK, however I'm not aware of whether this idea ever took off or what the price would be. I agree that for someone who simply wants to have secure communication, the pro SDK is prohibitively expensive, and that in 2019 security should be a must, not an add-on that costs thousands of dollars. once I hear more about the licensing system I'm happy to enable encryption on all TTHub servers for free if that option is available to me.

**Comment by slannon97** [comment]
Why isn't encryption enabled right out of the box? If I can encrypt my web servers for free and TeamTalk servers are offered free of charge, why isn't this available? I can understand charging for the SDK, but why encryption? As I said, it is a standard that's widely used on the Internet now.

**Comment by ntcarver0** [comment]
Agreed. Encryption is a no-brainer in 2020.

**Comment by slannon97** [comment]
I Completely agree with the last comment. Please add encryption as a standard feature in the next server version. Running anything on the Internet these days without encryption is a bad idea, especially something like this where many users are communicating back and forth. It should not cost $1000 for this necessary feature.

**Comment by dingpengyu** [comment]
cc @bear101

**Comment by bear101** [comment]
I've created a commercial TeamTalk server with encryption and BearWare.dk Web-Login: https://bearware.dk/?page_id=976

**Comment by PatrykMis** [comment]
But why I must purchase SDK to have encryption. These times encryption is standard. Even websites without encryption are more and more disqualifying from Google.

**Comment by KevanGP** [comment]
I hate to say it but I have to agree with comments above.
I think encryption should be put into the free version of TeamTalk as well.
