### ISSUE TITLE
Require the user moving other users with the move command to enter a password if moving to a password protected channel.

### ISSUE THREAD

**Issue by slannon97** [BearWare/TeamTalk5#473]
Currently, using the move user command allows the user(s) to be moved anywhere, even into channels that require passwords. This is done without asking the user moving the other users to supply the password. This should be changed so that people with this user right cannot move people to any channel on the server without first knowing the password and being required to type it in before the move command is executed.

**Comment by OzancanKaratas** [comment]
Why must an authorized user such as an administrator enter a password?

**Comment by slannon97** [comment]
This would be useful for users that are not full administrators, but rather have a few admin commands. For example, a moderator who can kick and move people between channels versus a full administrator. I agree that administrators shouldn't need to have to type a password, but a regular user with the move right should.This would be useful for users that are not full administrators, but rather have a few admin commands. For example, a moderator who can kick and move people between channels versus a full administrator. I agree that administrators shouldn't need to have to type a password, but a regular user with the move right should.

**Comment by bear101** [comment]
If the user is currently in a password protected channel then the user should also enter the password of this channel. It seems this feature would complicate the move feature quite a lot.

**Comment by bear101** [comment]
Yet another move-user-command would complicate setting up user accounts.

**Comment by tbdalgaard** [comment]
@bear101  there is however a bigger problem here:

If a user is allowed to move other users into a channel this can be done without knowing the password, so you can in fact "hack" around a protected channel by moving yourself or other users into this, so I think this issue shall be reopened and we may have to discuss some user experience and possible security strategies.
If not I will create a new issue about this situation.
