### ISSUE TITLE
Frequent client crashes in TeamTalk 5.5.0.4985

### ISSUE THREAD

**Issue by schulle4u** [BearWare/TeamTalk5#479]
Hello, 

my setup: TeamTalk 5.5.0.4985 (windows 10, Ubunto server build). 

Me and also other users on the same server running the current beta version experience client crashes from time to time. When this happens, the client closes without an error message. Unfortunately I cannot reproduce this behaviour. Sometimes there are no crashes during a few days, sometimes our clients crash two or more times in a row. This seems to be a client-related problem, users running the stable 5.4 version don't crash at all. Tried with both Qt and classic client. 

Steffen

**Comment by bear101** [comment]
Do you use OPUS codec with the new frame size selection?

--
Kind regards

Bjørn Damstedt Rasmussen
www.bearware.dk

**Comment by schulle4u** [comment]
No, all settings should be the same like in the previous version. The channel in we are experiencing the crashes is at Opus stereo, 64 KBps (VoIP profile), frame size and transmit interval are both at 60 msec. 

Steffen

**Comment by bear101** [comment]
Can you try this debug version: http://bearware.dk/test/TeamTalkClassic_v5.5.0.4987_Portable.zip
Then send .dmp files to me when it crashes.

**Comment by schulle4u** [comment]
Thank you, I'll report if a new crash happens.

**Comment by schulle4u** [comment]
Unfortunately the version doesn't create a dmp file. When a crash happens, it trows an exception error with retry, ignore and cancel buttons, but no file is being generated.

**Comment by bear101** [comment]
Can you take a screenshot of the error message dialog (Alt+PrintScreen)
and put it in an email?

--
Kind regards

Bjørn Damstedt Rasmussen
www.bearware.dk

**Comment by bear101** [comment]
@schulle4u Can you try this version (without debug) and see if the crash issues are gone: http://bearware.dk/beta/TeamTalkClassic_v5.5.0.4988_Portable.zip

**Comment by schulle4u** [comment]
Thanks, so far no crash with this version. In previous beta versions I also noticed tiny dropouts in voice transmissions, they also appear to be gone.

**Comment by schulle4u** [comment]
I think the problem has been fixed, no more crashes in 5.5.0.4988 during the last week.
