### ISSUE TITLE
Implement Info.plist translations into project.pbxproj

### ISSUE THREAD

**Issue by OzancanKaratas** [BearWare/TeamTalk5#484]
iOS doesn't handle the InfoPlist.strings correctly. The strings files should be defined in the project.pbxproj file.

**Comment by bear101** [comment]
how do you set up multiple InfoPlist.strings in Xcode?

**Comment by OzancanKaratas** [comment]
Ok, I found! Someone told [here](https://www.raywenderlich.com/250-internationalizing-your-ios-app-getting-started).

**Comment by bear101** [comment]
I dont see information on how to localize Info.plist. I tried using Xcode's way of creating localized string files but this results in duplicate Info.plist files and when running the app the screen was blank.

**Comment by OzancanKaratas** [comment]
[The first answer here](https://stackoverflow.com/questions/25736700/how-to-localise-a-string-inside-the-ios-info-plist-file).

**Comment by bear101** [comment]
I'm closing this issue until someone finds a way on how it should be implemented.

**Comment by OzancanKaratas** [comment]
No, that didn't work. In order for the existing file to be recognized by iOS, InfoPlist localization must be selected from the new localization file menu. I don't know how to do it.
