### ISSUE TITLE
Multilingual documentation

### ISSUE THREAD

**Issue by winman3000** [BearWare/TeamTalk5#486]
Currently the documentation is only available in English. However, there are users whose English is not sufficient for the documentation. For this reason the documentation should be available in several languages.

To avoid collisions it would be advisable to create a folder named "Docs" and a subfolder with a three-letter country code e.g. "ENU".

**Comment by bear101** [comment]
You are welcome to translate the documentation. Then I'll create the subfolder and make an initial index with language selection.

**Comment by bear101** [comment]
The TeamTalk documentation is located here: https://github.com/BearWare/TeamTalk5/tree/master/Documentation/TeamTalk

**Comment by bear101** [comment]
All *.md file will then be put into "English" subfolder.

**Comment by bear101** [comment]
Reopen issue if there's progress with multilingual docs
