### ISSUE TITLE
Classic client: Some strings are not translatable

### ISSUE THREAD

**Issue by Oreonan** [BearWare/TeamTalk5#492]
In classic client for accessibility on Windows, some strings aren't translatable.
For example:
-On ctrl-s dialogbox: "start position, audio preprocessor and cancel button" are not translatable.
-About dialog is not translatable.
Can you add the ability to translate absolutly allt parts of interface ?
Very thanks.

**Comment by bear101** [comment]
Some of the items in the about-dialog are auto-generated. Therefore they are not translatable

**Comment by bear101** [comment]
I've added the other missing items
