### ISSUE TITLE
Store passwords in encrypted format

### ISSUE THREAD

**Issue by Nardol** [BearWare/TeamTalk5#495]
For security reasons, it could be reasonable to be able to store encrypted passwords.
letting the choice to user or avoid breakage can be possible if encrypted passwords were specified using a prefix in the configuration file.
In a first time, doing it on the server side seams to be the more importent even if ideally, passwords should always be storred in an encrypted format.

**Comment by slannon97** [comment]
I completely agree with this. The server should be encrypted as a whole, but encrypting passwords is definitely necessary for security. Currently they are stored in plain text and are visible to anyone listening to the connnection because the entire server is unencrypted. Please add encryption for all users, no matter if they are using the SDK or not.

**Comment by bear101** [comment]
Use Facebook or BearWare.dk weblogin. Then users control their own passwords

**Comment by Nardol** [comment]
So only passwords are storred if we use FaceBook/Bearware.
It is not really safe to store admin password in plein text. In case of server intrusion, TeamTalk password is leaked.

**Comment by bear101** [comment]
Try looking in your TT client's config-file. No password is stored.

**Comment by Nardol** [comment]
I agree, in the case of FaceBook/Bearware login the password is not storred.
But administrator cannot use a FaceBook/Bearware login.
So, administrator password is storred in the server config file and in the client one, in plein-text format.
Or I miss-understood you?

**Comment by bear101** [comment]
Please read the Facebook section in the manual:
http://www.bearware.dk/teamtalk/v5.5/docs/userinterface.html#fbuseraccount

If you use BearWare.dk WebLogin you can create an administrator with
username: mee344@bearware.dk where "mee344" is your BearWare.dk weblogin
name.

--
Kind regards

Bjørn Damstedt Rasmussen
www.bearware.dk
