### ISSUE TITLE
Some strings are not translatable in the QT client

### ISSUE THREAD

**Issue by Nardol** [BearWare/TeamTalk5#498]
The new French translator sent me an updated translation of the QT client.
I have not checked every dialogs but in the chanel creation and in preferences dialog, it looks like the "Cancel" button cannot be translated.
@Oreonan told me he checked and didn't find it in translatable strings.
Could it be added or is there a reason why it is not translatable?

**Comment by bear101** [comment]
"Cancel", "OK", etc. use system's default text for buttons

**Comment by Oreonan** [comment]
I not uderstand. In certains dialog boxes, I was able to translate these buttons. Why not in all dialog ?

**Comment by Nardol** [comment]
Is there a QT Debian package I could have forgotten to install to have correctly localized buttons?

**Comment by bear101** [comment]
@Oreonan isn't the issue due to use of QDialogButtonBox and normal buttons? QDialogButtonBox will show system defaults whereas the other does not.

**Comment by Oreonan** [comment]
Yes, it's the issue, currently QT haven't languages files up to date for 
all languages.

**Comment by bear101** [comment]
Ok, then it's a UI framework issue and not related to TeamTalk. Then I'll close the issue.

**Comment by Oreonan** [comment]
I'm currently working on it. Like QT doesn't update translations, I'll force translation of standards buttons.
