### ISSUE TITLE
Stream volume and voice activation level have not the same values on Linux and Windows

### ISSUE THREAD

**Issue by Nardol** [BearWare/TeamTalk5#508]
On Windows, values are logically from 0 to 100 for stream level and from 0 to 10 for voice activation level.
On linux, we have the double : 0 to 200 for streams and 0 to 20 for voice activation level.

**Comment by bear101** [comment]
On Windows you mean Classic client or Qt Client?

**Comment by Nardol** [comment]
I mean the Qt one.

**Comment by bear101** [comment]
Then Qt must somehow change it. The code is the same on Windows and Linux: https://github.com/BearWare/TeamTalk5/blob/master/Client/qtTeamTalk/mainwindow.cpp#L180

**Comment by bear101** [comment]
Closing issue. Must be related to UI framework and not TeamTalk
