### ISSUE TITLE
Add others way to log in to TeamTalk

### ISSUE THREAD

**Issue by Nardol** [BearWare/TeamTalk5#509]
Could it be possible to add some other login method?
Other social medias as Twitter, or using a Google or Microsoft account.
And for non-centralized ways, adding Open-ID compatibility could allow users to control even better their information. It could also allow server administratore to store Open-ID on the same server, with password storred as they wish.
OAuth is another idea I think about.

**Comment by bear101** [comment]
BearWare.dk WebLogin and Facebook are supported now. If you need more authentication types then I suggest you look into TeamTalk 5 SDK for developing your own client.
