### ISSUE TITLE
Issue with video capture streams.

### ISSUE THREAD

**Issue by c-smile** [BearWare/TeamTalk5#510]
TeamTalk.dll 5.5.0.4993 , Windows 10.

When remote user stops sharing camera neither `CLIENTEVENT_USER_VIDEOCAPTURE` nor `CLIENTEVENT_USER_STATECHANGE` are sent.  

This makes impossible to detect "user stops sharing camera"  event completely.

Presumably `CLIENTEVENT_USER_VIDEOCAPTURE` shall be sent with `msg.nStreamID == 0` but no such message is generated. Yet it should be `CLIENTEVENT_USER_STATECHANGE` notification for the user but no this one either.

**Comment by bear101** [comment]
The TeamTalk client applications use the status-mode property to see when someone closes their video stream: https://github.com/BearWare/TeamTalk5/blob/master/Client/qtTeamTalk/common.h#L212

There is no "end-of-stream" indicator for voice or video in TT.
