### ISSUE TITLE
Message logs on server side and other wishes. 

### ISSUE THREAD

**Issue by c-smile** [BearWare/TeamTalk5#511]
First a bit about the context: I am creating [Sciter](https://github.com/c-smile/sciter-sdk#some-screenshots-of-real-life-applications-that-use-sciter-ui) based TeamTalk client (preliminary ETA end of May) and got these wishes:

There is a need of having message logs on server side, at least for persistent channels:

1.  User A can send message to a channel. User B when he/she will connect to the channel should be able to see prior messages in the channel to be in context of discussion. This could be made by storing message logs in a file with predefined name and associated with the channel. So client will be able to load that messages.log (or whatever) file to present conversation history to the user.

2. It is highly desired to have persistent UID for messages. So User A should be able to edit his/her message sent before. Pretty much any chat allows that. Yet, unique ID will help to sync local and remote message stores.

Thanks in advance.

**Comment by bear101** [comment]
Duplicate #659
