### ISSUE TITLE
Add ability to personalize nickname by server on iOS clients

### ISSUE THREAD

**Issue by Oreonan** [BearWare/TeamTalk5#513]
On Android client, We have ability to change our nickname by serveur in server's properties. Can you this option in others clients ?

**Comment by Simon818** [comment]
+1000000 to this. I didn't even know this was possible on Android, but have thought for years that I would love to see a nickname field in all server profiles and only have the default nickname take effect if the server one is left blank. On desktop, f5 could also change the nickname only for the current session, or a checkbox could decide whether to change it permanently or not. That way there would actually be a difference between the nickname field in preferences and the one you get when you press f5.

**Comment by Simon818** [comment]
Not sure if this is known, but iOS also lacks this feature, so the desktop clients are not the only missing pieces.

**Comment by Oreonan** [comment]
Ah, yes, it's me who has renamed this and made #940 to close this. I forgot iOS client. Sorry.
