### ISSUE TITLE
Sort option for user account names

### ISSUE THREAD

**Issue by bear101** [BearWare/TeamTalk5#514]
It's hard to find a user account with a screen reader when usernames are not sorted.

**Comment by Simon818** [comment]
I've always thought it would be great if accounts were sorted alphabetically or at least if we had multi-letter navigation in the list. On large servers with over 100 users, this is more than just a screen-reader annoyance. What about a tree view of "admins" and "users"?

**Comment by Simon818** [comment]
To clarify, what I mean by multi-leltter navigation is that one can quickly press more than one letter to jump to something containing those letters. For instance, I could quickly type l-o-b into the main channel tree to get to a channel called "lobby". If I quickly type "s-i-m" into the user accounts list, I'd jump to individual users starting with s, i, and m. A tree view by default does not have this problem.
