### ISSUE TITLE
Optionally allow server to re-encode audio streams

### ISSUE THREAD

**Issue by tech10** [BearWare/TeamTalk5#518]
This could have multiple uses, but would place more demand on the CPU of the server hosting, thus, it could be optionally used or not used. This would probably be something to be done for a later major version of TeamTalk, perhaps version 6. Here are some examples for its use.

1. Transmit a single audio stream to mobile clients at a configurable bit rate, just like configuring a channel, but on a user specific level, or marked for mobile clients only. Receive the same audio stream, and encode it to match any channel settings that the channel is using. This would allow for decreased data use on mobile clients that may have limited data on cellular networks.
2. Create a channel that user specific audio codec settings can be used in, which could allow for clients to set their own audio codecs, if allowed. If someone always wanted to transmit in stereo, receive in stereo, or both.
3. Implement #457 for global voice broadcasts across the entire server.

**Comment by bear101** [comment]
Since this issue is not in scope for the near future I'll close the issue.
