### ISSUE TITLE
The chat and files tabs can not be navigated accessibly

### ISSUE THREAD

**Issue by bear101** [BearWare/TeamTalk5#52]
The chat and files tabs can not be navigated accessibly. TalkBack reads Chat/Files/Desktop but these items can not be clicked. It would be nice if the app has a few separate tabs such as chat, files, desktop, history etc. 

Reported here: http://bearware.dk/?p=279

**Comment by poretsky** [comment]
Hello Bjoern,

In fact, all the tabs are pretty navigable and accessible with
Talkback. Of course, their headers are not clickable, but tabs can be
easily switched by sweeping gesture. In the accessibility mode this
gesture should be done by two fingers. As usual in such cases, nothing
special. And proper speech feedback will follow.

I've answered in the forum as well.

Best regards,
Igor.

>>>>> "Bjoern" == Bjoern D Rasmussen <notifications@github.com> writes:

    Bjoern> The chat and files tabs can not be navigated
    Bjoern> accessibly. TalkBack reads Chat/Files/Desktop but these
    Bjoern> items can not be clicked. It would be nice if the app has a
    Bjoern> few separate tabs such as chat, files, desktop, history etc.

    Bjoern> Reported here: http://bearware.dk/?p=279

    Bjoern> — Reply to this email directly or view it on GitHub.*
