### ISSUE TITLE
Text message origin cannot be seen

### ISSUE THREAD

**Issue by bear101** [BearWare/TeamTalk5#53]
The incoming messages does not start a new window, so we can not understand whom the message was recieved from.

Reported here: http://bearware.dk/?p=279

**Comment by poretsky** [comment]
Hello Bjoern,

It is intentionally. A new message doesn't start a new window to not
disturb a current interaction, but it produces sound and leaves proper
shortcut in the notification panel.

I've answered in the forum as well.

Best regards,
Igor.

>>>>> "Bjoern" == Bjoern D Rasmussen <notifications@github.com> writes:

    Bjoern> The incoming messages does not start a new window, so we can
    Bjoern> not understand whom the message was recieved from.  Reported
    Bjoern> here: http://bearware.dk/?p=279

    Bjoern> — Reply to this email directly or view it on GitHub.*

**Comment by bear101** [comment]
Igor's way is preferred so end-user is not interrupted.
