### ISSUE TITLE
Channels not sorted on IOS

### ISSUE THREAD

**Issue by wandogau** [BearWare/TeamTalk5#533]
On IOS the list of Channels is not sorted alphabetically, even "ascending" is selected in settings Tap.

**Comment by bear101** [comment]
Is there a public server that has this issue?

**Comment by beqabeqa473** [comment]
hi bjoern.

no, it started to happen after latest iTeamtalk update.
i wrote about that to you earlier.

channels are sorted randomly.

On 6/18/20, Bjørn Damstedt Rasmussen <notifications@github.com> wrote:
> Is there a public server that has this issue?
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/BearWare/TeamTalk5/issues/533#issuecomment-645609463


-- 
with best regards beqa

**Comment by wandogau** [comment]
Hello,
Can be seen on the official TT5-Server
tt5eu.bearware.dk
too.

**Comment by bear101** [comment]
6244e143436cb64beff0be16049fc22071d4623b
