### ISSUE TITLE
Quick command like some Standard mail handler

### ISSUE THREAD

**Issue by matiz1965** [BearWare/TeamTalk5#534]
Hi Sir or Madam,
I'm newbe on GitHub, si I surely miss to post my question on a proper space. Sorry.
In fact this my request is not an issue but a question.

I'm a french teamtalk's user. I'm developping a small app to work with TeamTalk and I would like to know if TeamTalm has some quick command like some Standard mail handler use to work:

mailto:abc@example.com?SUBJECT=Test&BODY=azertyuiop&FILE=c:\filename.txt

dedicated to TeamTalk app.

Many thanks for your answers.
MTZ

**Comment by bear101** [comment]
Have a look at tt-URLs in the manual.
https://bearware.dk/teamtalk/v5.5/docs/ttfiles.html#tturl

**Comment by bear101** [comment]
Did that sort your issue?

**Comment by matiz1965** [comment]
Hi Sir,

Many thanks for your email and attention.
The link you gave me doesn't match with my request. Surely due to my lack of explaination.
So please accept my appologise for this lack of explaination.

Most of the time from a webpage there is "word" or a "picture" which has some effect (i.e. a link to contact some body).
When you click on this "word" or a "picture" on your web page it opens automaticaly your Standard Email handler and automaticaly prepares your email with the "TO" (feild) pre-filled like "techdept@free.fr"; the Subject filed as "Resquest from Matiz" and also the text filed as "Hi Sir, I need you help for this...blablablabla...."

(please check attached)


So my need it to know if there is some extra Commands Code to "inject" into TeamTalk a text message or attached file to your application.

In order to try to give you more explaination: My target is as follow.
If I click on my application button, my application could send some commands like:

teamtalk5.exe /room=[matiz_with_bearware] /text=[Hi Sir, I need you help for this...blablablabla....] /file=[c:\user\matiz\text.zip]

so, it could autatically launch the room matiz_with_bearware and automaticaly fill the text area with Hi Sir, I need you help for this...blablablabla....
and also has an attachement c:\user\matiz\text.zip

Please let me know if my explainations are clear.
All the very best.

Matiz

----- Mail original -----
De: "Bjørn Damstedt Rasmussen" <notifications@github.com>
À: "BearWare/TeamTalk5" <TeamTalk5@noreply.github.com>
Cc: "matiz1965" <techdept@free.fr>, "Author" <author@noreply.github.com>
Envoyé: Jeudi 18 Juin 2020 19:38:30
Objet: Re: [BearWare/TeamTalk5] Quick command like some Standard mail handler (#534)





Did that sort your issue?

**Comment by bear101** [comment]
You can use both .tt files and tt:// URLs as arguments to teamtalk5.exe. You can also "inject" user settings in a .tt file.

If you need something more specific than this then I suggest you look into the TeamTall 5 SDK for developing your own client.
