### ISSUE TITLE
Probleme send file with teamtalk classic

### ISSUE THREAD

**Issue by math65** [BearWare/TeamTalk5#535]
When we send a file to the server, the pseudonym is not ours but a random one and always the same.

**Comment by bear101** [comment]
You mean the owner of the file? The owner of the file will be your username.

--
Kind regards

Bjørn Damstedt Rasmussen
www.bearware.dk

**Comment by bear101** [comment]
No response. Closing...

**Comment by Oreonan** [comment]
I've reproduced this issue, shis only present on a server who have no user. I've found cause of this issue and I'm trying to fix it.
