### ISSUE TITLE
TT5Classic - show Channel Topics

### ISSUE THREAD

**Issue by wandogau** [BearWare/TeamTalk5#540]
Hi Bjoern,
When browsing the Channel-Tree on IOS, VoiceOver reads the name of a channel followed by the topic of the channel. 
Could this be implemented in the Windows-Versions too? Either by appending the channels topic to the channel's name, or just reading it out via TTS?
Best
Wandogau (Mo)

**Comment by bear101** [comment]
This commit 7bb47c4b826e133834f01f88eaa4081f22992b6d allow the user of Ctrl+G to hear the channel topic (requires TTS enabled).
