### ISSUE TITLE
TT5Classic - move all user in a channel

### ISSUE THREAD

**Issue by wandogau** [BearWare/TeamTalk5#542]
Hello,
Lets say you start teaching a group of people. Everybody in the channel can hear everybody, to say hello and so on.
Now, as the teaching starts, it would be great to have a function like
move all users in channel
to another channel, where only the operator can talk.
I know, this can be done via mark user for move and then move them, but its a little heavy to do this, especially, if there are lets say 50 users.
I think this would be a great option for TT5Classic, because for a visually impaired Admin or OP it is not so easy to first mark all users and then move them.
Internally, this function just marks all users for move and then open the move-users-dialog.
Best
Wandogau (mo)

**Comment by bear101** [comment]
This is not a typical scenario. Most servers have people in multiple channels and not all in a single channel.

**Comment by wandogau** [comment]
You're welcome to open the issue again but as you can see there's 80
others issues. So I doubt anyone will ever look into it.

Kind regards

Bjoern Damstedt Rasmussen
www.bearware.dk
