### ISSUE TITLE
possible stereo input on ios 14 and above

### ISSUE THREAD

**Issue by beqabeqa473** [BearWare/TeamTalk5#546]
A new feature in AVAudioSession allows clients to request stereo polar patterns from the built-in mic. Clients choosing a stereo polar pattern must call a new method of AVAudioSession to specify the stereo input orientation. For more information, see AVAudioSession (58584572)

**Comment by beqabeqa473** [comment]
https://developer.apple.com/documentation/avfoundation/avaudiosession/capturing_stereo_audio_from_built-in_microphones

**Comment by math65** [comment]
Yes! It’s a good idea !

**Comment by ChrisDuffley** [comment]
Several recording apps have made the rounds for stereo recording, so this is definitely possible!

Christopher Duffley
Host of Mission Possible Podcast: http://www.missionpossiblepodcast.com
Cell: +1 (603) 851-6971

**Comment by math65** [comment]
That's what I tell myself :)

 

On teamtalk the audio quality is very high, it would be of great interest

 

De : ChrisDuffley <notifications@github.com> 
Envoyé : mardi 3 novembre 2020 00:19
À : BearWare/TeamTalk5 <TeamTalk5@noreply.github.com>
Cc : math65 <mathieumartin65@icloud.com>; Comment <comment@noreply.github.com>
Objet : Re: [BearWare/TeamTalk5] possible stereo input on ios 14 and above (#546)

 

Several recording apps have made the rounds for stereo recording, so this is definitely possible!

Christopher Duffley
Host of Mission Possible Podcast: http://www.missionpossiblepodcast.com
Cell: +1 (603) 851-6971

**Comment by pitermach** [comment]
I'd love to see this as well, though if this is added I also think there should be a switch to toggle it on and off. I can think of instances when I'd like to have both access to stereo and mono transmition.
