### ISSUE TITLE
ITeamTalk: two little errors in settings-display

### ISSUE THREAD

**Issue by wandogau** [BearWare/TeamTalk5#551]
In ITeamTalk under settings
When navigating to
Text to Speech Events,
VoiceOver says
"the volume of the speaking voice is 0.5" instead of
"The Volume of the speaking voice is 50 %"
Same for
Rate of speaking voice
Best
Wandogau

**Comment by bear101** [comment]
To avoid updating all the translations we'll keep it at 0-1 instead of a percentage.
