### ISSUE TITLE
Server system requirements

### ISSUE THREAD

**Issue by VladTru20** [BearWare/TeamTalk5#555]
Tell me, please, what are the hardware and software requirements of the server in the latest TeamTalk version with a maximum number of chat users of about 30-50? Is an old office PC with a 2-core processor (AMD deAthlon II or A4-5300), 2-4 GB RAM and a 500 GB hard drive suitable as a server?

**Comment by bear101** [comment]
It's plenty. I run a TeamTalk server on a Raspberry Pi with 256 MB RAM,
800 MHz and 4 GB SD card.

Kind regards

Bjørn Damstedt Rasmussen
www.bearware.dk

**Comment by VladTru20** [comment]
Thanks, Björn. We are now deciding whether to use our server or virtual hosting. Apparently, we will choose the second option - it is still cheaper and easier;)Sincerely, Vladimir-------- Исходное сообщение --------От: Bjørn Damstedt Rasmussen <notifications@github.com>Дата: пт, 26 июн. 2020 г., 20:54Кому: BearWare/TeamTalk5 <TeamTalk5@noreply.github.com>Копия: VladTru20 <Vtr2005@mail.ru>, Author <author@noreply.github.com>Тема: Re: [BearWare/TeamTalk5] Server system requirements (#555)

It's plenty. I run a TeamTalk server on a Raspberry Pi with 256 MB RAM,

800 MHz and 4 GB SD card.



Kind regards



Bjørn Damstedt Rasmussen

www.bearware.dk
