### ISSUE TITLE
Fix Bluetooth audio quality on iOS

### ISSUE THREAD

**Issue by ip410** [BearWare/TeamTalk5#564]
Hello is wondering if you fix the Bluetooth audio quality on iOS. When connecting to TeamTalk with BluetoothThe sound quality is very low. And uses Bluetooth headset microphone. Please update this

**Comment by MarcoZehe** [comment]
Confirmed. Even with AirPods, which have higher quality audio normally, see FaceTime audio, the quality TeamTalk uses is quite low.
