### ISSUE TITLE
media volume shoud be 50% of voice volume initially

### ISSUE THREAD

**Issue by bear101** [BearWare/TeamTalk5#58]

**Comment by bear101** [comment]
Partly fixed in 05627f15c1171901ab57bfe3c800a2d978323830.
Would be nice not having to reconnect.

**Comment by bear101** [comment]
iOS use refVolume() instead of percentage 0-1.0

**Comment by bear101** [comment]
@beqabeqa473 is there a "slider preference" type for Android? Or something like a UIStepper? I would like to make the slider to control media file vs. voice volume in the Android preferences.

**Comment by beqabeqa473** [comment]
hi bjoern.

i've emailled you an example how it can be done.

i am sorry that can't do it right now, i have a lot of work at my job.

**Comment by bear101** [comment]
@beqabeqa473 when you have the time can you check whether media file volume is less than voice volume with these two last commits?
