### ISSUE TITLE
TT-Links not working with channel-parameter

### ISSUE THREAD

**Issue by wandogau** [BearWare/TeamTalk5#580]
Hello,
The following link does'nt work on TT5Classic and iTeamTalk too:
tt://teamtalk.blindzeln.net/?&tcpport=10333&udpport=10333&username=gast&channel=BeckerHof
"BeckerHof" is the name of an existing channel.
The Server is up and running, so you can test this with the link if you like.
Is there someting wrong in my link or does TT not support them?
Best
Wandogau

**Comment by bear101** [comment]
Should be:
tt://teamtalk.blindzeln.net?tcpport=10333&udpport=10333&username=gast&channel=BeckerHof
