### ISSUE TITLE
Software requirements for TeamTalk 5 Ubuntu server

### ISSUE THREAD

**Issue by VladTru20** [BearWare/TeamTalk5#583]
Please tell me what TeamTalk Server requirements for the software part of a virtual server based on Ubuntu 18 are - do I need Apache, etc. (e.g. LAMP kit)?

**Comment by bear101** [comment]
Only requirement is that it's 64-bit Intel.

Kind regards

Bjørn Damstedt Rasmussen
www.bearware.dk
