### ISSUE TITLE
QT client: Wrong behavior when starting to stream the most recently played file

### ISSUE THREAD

**Issue by Nardol** [BearWare/TeamTalk5#595]
Looks like reproducible only with media files which have an image inside.
1. Stream one of these files;
2. Wayt until the end or stop it;
3. Open again the streaming media file dialog and press OK directly.

Expected behavior: the stream should begin.
Actual behavior: nothing happens. We have to change the file and re-select the desired one in the list of recent streams to be able to stream the file.

**Comment by bear101** [comment]
This is on Linux or macOS, right?

**Comment by Nardol** [comment]
Yes, on Linux.

**Comment by bear101** [comment]
Ok, this has been fixed in #517

**Comment by Nardol** [comment]
Not exactly.
Before #517 it was not possible at all to stream them.
Now, it is possible but if I want to re-stream the same file a second time latter, I cannot open the dialog, and press OK directly.
I have to re-select the file, from the recent files list or press brows and re-select it.
For other audio files, if I open the stream media file and press OK directly, the file is streamed.
It is only when we want to stream the last streamed file.

I hop I explained better.
