### ISSUE TITLE
Stream media files

### ISSUE THREAD

**Issue by bear101** [BearWare/TeamTalk5#6]
TeamTalk JNI DLL currently doesn't support this.

**Comment by bear101** [comment]
Android client doesn't support streaming media files at the moment

**Comment by beqabeqa473** [comment]
hi @bear101 
i've implemented java part of streaming.

please look at it in android_stream_media branch

**Comment by bear101** [comment]
@beqabeqa473 I merged your branch to sdks/dev and added steaming status mode  (doChangeStatus): c87014c3ff4215223f44186c5681f2a15fc6efa6

Shouldn't the stream media file text box show the previously used URL (for fast access)?

**Comment by bear101** [comment]
Duplicate #167
