### ISSUE TITLE
audio recording allowed

### ISSUE THREAD

**Issue by wandogau** [BearWare/TeamTalk5#600]
If you have a channel, and check 
no audio recording allowed
you can still access the corresponding dialog in client menu. It works fine, because the file just contains nothing, but would'nt it be better to inactivate the whole menu entry, or dialog, if you do not have the possibility to record?

**Comment by bear101** [comment]
Audio recording is not linked to a specific channel so you can enable it prior to joining a channel with "no audio recording" option.

**Comment by bear101** [comment]
I take it the issue can be closed now.
