### ISSUE TITLE
contrast of ptt-key in ITeamTalk

### ISSUE THREAD

**Issue by wandogau** [BearWare/TeamTalk5#601]
Some of our friends, who are not completely blind, find it hard to recognize the status of push-to-talk. Is there a chance to make the contrast higher, so that a person, who's visually impaired, can better recognize if ptt is on or off? Or other colors, which are more different?

**Comment by bear101** [comment]
On iOS the TX button turns red when it's transmitting and otherwise green

**Comment by bear101** [comment]
@wandogau can you think of colors that are more recognisable?

**Comment by bear101** [comment]
Also on Android and iOS the color of TX button is opposite. iOS shows red for transmitting and Android shows green for transmitting. We should probably align this. @poretsky do you have an opinion of which is more logical?

**Comment by poretsky** [comment]
As soon as personally I use Android, I've got used to it, and it seems
to me pretty logical: The button reads "Tx" and green color means that
transmission is on. But I assume that there can be another treatment:
red color draws attention to the fact that transmission is on.
