### ISSUE TITLE
Channel-Password doesn't protect corresponding sub-channels

### ISSUE THREAD

**Issue by Michael1972** [BearWare/TeamTalk5#616]
After creating a password-protected channel with 1 or more corresponding sub-channels, it is possible to  enter a sub-channel without typing in the main-channel-password. Steps for reproduction: Create a channel and assign a password. Create a sub-channel within the password-protected channel. Enter the main-channel, team-talk is behaving correctly and asks for the main-channel-password. Now, leave the main-channel, navigate to the sub-channel and enter it. No password-requirement. For teaching-purpose, it would be better, to have main-channel and all corresponding sub-channels protected by the main-channel-password, to make it impossible for unauthorized visitors to enter a sub-channel of the protected main-channel.

**Comment by tbdalgaard** [comment]
@Michael1972  I see your point! Perhaps there could be a setting somewhere about a classroom-channel like this:

If classroom-option is turned on: Treat Protect all subchannels with the same password as classroom-channel. That could be cool as well for preserving other settings like audio codec, allow record etc.

This would require the credentials for the main classroom-channel for all subchannels. I like this idea, but wonder how this could be implemented.
I guess in order for this to work the main classroom-channel should be permanent on the server until the class is over.

**Comment by bear101** [comment]
I'm closing this issue because it will lead to a more complicated usage.
