### ISSUE TITLE
Translation workflow for all TeamTalk clients

### ISSUE THREAD

**Issue by jmdaweb** [BearWare/TeamTalk5#623]
Yesterday I updated my TeamTalk classic to version 5.6 and noticed a couple of mistakes in the client menu related to shortcuts (spanish translation). I was surprised, because when I tested the translation from pull request #516 these errors didn't exist. When I visited the About dialog in the help menu, I didn't see my name in the translation credits. Instead, I saw another person. After talking to him, we concluded we did exactly the same work in parallel, ignoring each other was working in the same thing. I sent my translation via a pull request, and he did it via e-mail.
This situation makes me feel very disappointed, offended and, of course, angry. I have wasted a lot of time updating the classic client spanish translation for... nothing?
I suggest you to define a reliable, structured, documented and well-designed translation workflow to avoid these kind of situations in the future, with a coordinator for each language which maintains their respective translation team, reviews and accepts or rejects contributions from the community, among other things. A tool which generates translation files for all clients from a single translation should be also considered, although I understand it might be difficult to create.

**Comment by bear101** [comment]
When I receive an updated translation I typically simply replace the existing one if everything looks good in the new translation. 

You are welcome to add two translators to translator item. If there's not enough room in the About box then I can extend it so everyone can be listed.

Some translations are taken over by others if the previous translation is no longer available. Of course it would be best to keep everyone listed.

**Comment by dingpengyu** [comment]
hi @bear101 
As a translation hosting tool, I recommend [weblate](https://github.com/WeblateOrg/weblate.git).
First, this tool can edit translations online. Second, this tool is very friendly to screen readers. Finally, this tool is 100%  open source.
thanks

**Comment by bear101** [comment]
Isn't weblate a commercial tool that requires a license?

**Comment by dingpengyu** [comment]
> Isn't weblate a commercial tool that requires a license?
The following is weblate's description of the license:
License
-------

Copyright © 2012–2020 Michal Čihař michal@cihar.com

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation, either version 3 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program. If not, see https://www.gnu.org/licenses/.
thanks

**Comment by bear101** [comment]
@jmdaweb To best way to ensure a translation is up-to-date and includes the correct people is to monitor commits to the TeamTalk5 Git repository.

**Comment by bear101** [comment]
I'll close the issue. It seems the Spanish translation includes your name again.
