### ISSUE TITLE
Add a third gender option for non-binary people

### ISSUE THREAD

**Issue by MarcoZehe** [BearWare/TeamTalk5#649]
Right now, TeamTalk only gives a choice between traditional male and female genders. However, this excludes people who are non-binary, gender-fluid or otherwise don't identify with the classic male/female genders.

I therefore propose to add a third option "Diverse" (wording to be finalized), and also add a gender emoji for that, following #645 .

**Comment by jage9** [comment]
To expand on this a bit, now that genders are being displayed in the tree, an option to not choose to share gender would be helpful in case someone doesn't want the emoji by their name.

**Comment by bear101** [comment]
TeamTalk v5.6.3 has just been released which doesn't announce gender when "Male" is selected.

**Comment by Oreonan** [comment]
V5.6.3 does not meet this request, @MarcoZehe's initial request is to add more gender options, not just show female. V5.6.3, on the other hand, temporarily fixes the problem of mobile clients which do not allow specifying the gender. So I suggest allowing sex selection on mobile clients, and adding an additional gender option for people who identify as neither male nor female.

**Comment by jage9** [comment]
Alternatively, is the gender option needed at all? People can choose to 
specify gender or any other characteristic using emoji in their username 
currently, and this may help to streamline the solution.

**Comment by ChrisDuffley** [comment]
This is true. However, we also should think of the other scenario (myself included) where people will only have accounts for admin access. The other participants who don't need admin access or who don't care for an account at all can use the <anonymous> user in the User Accounts list. If we can leave the gender selection as an option for this particular scenario, that would be good.

Also, with my particular server and others who have < 100 channels, NVDA pics it up right away, so I've had no issues there.

Christopher Duffley

Host of Mission Possible Podcast <http://www.missionpossiblepodcast.com/>

LINKS TO SUBSCRIBE:

iTunes <https://itunes.apple.com/us/podcast/mission-possible-christopher/id1103092109?mt=2> | Stitcher <http://www.stitcher.com/s?fid=88094&refid=stpr> | Google Play <https://goo.gl/app/playmusic?ibi=com.google.PlayMusic&isi=691797987&ius=googleplaymusic&link=https://play.google.com/music/m/Ik76dexklcprwnpuxbdr2s6bm3y?t=Mission_Possible_with_Christopher_Duffley> | Follow Podcast On TuneIn And Listen To Latest Episode <http://tunein.com/radio/Mission-Possible-With-Christopher-Duffley-p892505/>

LIKE/FOLLOW Me:

Facebook <http://facebook.com/christopherduffley> | Twitter <http://twitter.com/chrisduffley> | YouTube <http://youtube.com/christopherduffley> | Instagram <http://instagram.com/christopherduffley>

On Sep 21, 2020, at 11:46, jage9 <notifications@github.com> wrote:


Alternatively, is the gender option needed at all? People can choose to 
specify gender or any other characteristic using emoji in their username 
currently, and this may help to streamline the solution.

**Comment by Oreonan** [comment]
We are working on it. Follow #745 to see progress

**Comment by beqabeqa473** [comment]
what does non-binary people mean at all?

first of all, i don't understand why this is needed at all?
secondly, i don't understand why make identification was removed?
if we'll look from law point of view, it can be interpreted as gender
dissbalance.
no one can say which gender is default, so for example we won't show
make, because it is by default or are there some other reason of
removing that?

i am saying that because people are asking lots of questions about
that and there are no clear explanation or explanation doesn't exist
at all why this measure was taken.

On 1/28/21, Oreonan <notifications@github.com> wrote:
> We are working on it. Follow #745 to see progress
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/BearWare/TeamTalk5/issues/649#issuecomment-768795687


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: beqaprogger@gmail.com
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by beqabeqa473** [comment]
i agree that not third gender but Non-specified option should be added, so it means if i don't want to set my gender i'll select that.

**Comment by Oreonan** [comment]
What did you mean when you say: "why identification has been removed", I 
not understand what is "identification" in this case.

**Comment by beqabeqa473** [comment]
it is not possible to identify if user's gender is male.

if third option will be added, it'll be necessary to re-add announcing male gender as well.
