### ISSUE TITLE
Incorrect nickname when reopened private messages dialog on classic

### ISSUE THREAD

**Issue by Oreonan** [BearWare/TeamTalk5#657]
On classic client, when you send a MP to an user, before first window close, nicknames are correctly reported. But, when we close and reopen private messages window, all messages are set to same nickname...

**Comment by bear101** [comment]
Hm, I don't see this issue. What do you do to reproduce?

I connected two client instances which send private messages to each other and nicknames are correct when reopening the message window

**Comment by Oreonan** [comment]
I'm afraid this outcome is still a bit random, normally just send a 
message to a user, let them respond, close the dialog box, then reopen 
it a bit later to reproduce. But, that does not work everytime...

**Comment by Oreonan** [comment]
Not reproduced for now

**Comment by Oreonan** [comment]
Similar problem appears with MP timestamp.
Step to reproduce:
- Send a MP to an user and see timestamp
- Close and reopen MP dialog for same user
- See timestamp, instead of first MP timestamp, timestamp is now the same as when you reopen MP dialog

**Comment by Oreonan** [comment]
Same issue in QT client.
I think problem which cause because timestamp is retrieved when dialog is opened. Maybe a solution can be to create an array with all timestamps and replace it in all messages when dialog is reopen.
@bear101 Have you another idea? And if no, are you agree with my idea? If yes, could you do it?

**Comment by bear101** [comment]
@Oreonan time-stamp issue should be fixed now

**Comment by Oreonan** [comment]
Yes, just confirm :), Thanks
