### ISSUE TITLE
Probleme accessibility team talk 5.6.1 in Mac OS 

### ISSUE THREAD

**Issue by math65** [BearWare/TeamTalk5#661]
Hello !

I know Teamtalk is not too accessible and you don't have time, however in the latest version VoiceOver does not detect any interface element.

Can you fixe this in a future version?

Kind regard,

**Comment by bear101** [comment]
Hm, I updated Qt to v5.14 for TeamTalk v5.6.1 but it seems accessibility
is more broken than it usually is.

I tried updating to Qt v5.15.1 and it seems to be back to "usual" again.
I'll make a v.5.6.2 version for macOS where this is fixed.

--
Kind regards

Bjørn Damstedt Rasmussen
www.bearware.dk

**Comment by math65** [comment]
Ok, thank you so much !

**Comment by bear101** [comment]
Please try this version: https://bearware.dk/teamtalk/v5.6.2/TeamTalk_v5.6.2_Setup.pkg

**Comment by bear101** [comment]
Had to use Qt 5.15.0 because Qt 5.15.1 cannot sign Qt Webengine

**Comment by math65** [comment]
Hi !

Thank, it’s work ! :)
