### ISSUE TITLE
Possible crashes in classic client with latest update. 5.6.1

### ISSUE THREAD

**Issue by beqabeqa473** [BearWare/TeamTalk5#665]
hello all.

there were made serious changes in translation strings, that caused teamtalk to crash in some languages which have not updated their translation files.
specifically, file adding/removing strings were swapped, updated old strings to not include username and added new strings with the identical information.
also menu actions, specificaly announcing selected users were moved to channel %s was put instead of phrase away, and away moved to another place.

that is not good, as it makes direct impact to stability of an app.

i think, critical update should be posted with these fixes as it causes crashes when uploading files for example for languages which was not updated.

**Comment by bear101** [comment]
Ok, but I don't have time to look at it until the weekend. We should probably do a "git diff v5.5.1..HEAD -- Client/TeamTalkClassic/lng_classic/English.lng" to see what strings have %-something in the diff.

**Comment by bear101** [comment]
@beqabeqa473 I'm preparing v5.6.3 release of the classic client on branch teamtalk_v5.6.3. I've corrected the errors I've found so far. https://github.com/BearWare/TeamTalk5/tree/teamtalk_v5.6.3

**Comment by bear101** [comment]
@beqabeqa473 I've made the following changes to the Russian translation: 723b6afd2bad0d66eb141a5c2d45f75b1666b26d

**Comment by bear101** [comment]
@Oreonan I've also replaced a bunch of apostrophe with &apos; in the French translation: 723b6afd2bad0d66eb141a5c2d45f75b1666b26d I hope it doesn't give merge conflicts

**Comment by Oreonan** [comment]
I've just tested now to merge master in my personal branch, no error found.

**Comment by beqabeqa473** [comment]
i've already updated russian translation in master so it had no errors

On 9/19/20, Oreonan <notifications@github.com> wrote:
> I've just tested now to merge master in my personal branch, no error found.
>
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/BearWare/TeamTalk5/issues/665#issuecomment-695174985


-- 
with best regards beqa

**Comment by beqabeqa473** [comment]
ok, it looks good.

**Comment by bear101** [comment]
I've publish v5.6.3
