### ISSUE TITLE
ITeamTalk and VoiceOver

### ISSUE THREAD

**Issue by wandogau** [BearWare/TeamTalk5#670]
With the latest ITeamTalk and IOs 13.xx, the following sometimes occures - VoiceOver with speech is active:
If you start TeamTalk and click "connecgt" the volume of the iPhone-Speaker is very, very low. This did'nt happen all times, but 4 times of 10 logins.
If you need more input - just let me know!

**Comment by bear101** [comment]
@wandogau is this issue still applicable in v5.7 Build #2?

**Comment by bear101** [comment]
No response. Closing issue.
