### ISSUE TITLE
Auto reconnect if first connection attempt fails

### ISSUE THREAD

**Issue by patmu** [BearWare/TeamTalk5#676]
Enabling "Reconnect on connection dropped" is working if an already existing connection is dropped (like the name says).

I would like to see the same logic for the first connection attempt. So if the connection to the server fails, the client tries to establish the connection again until it's connected.

This helps when the client is started with command line parameters (eg. hostname to connect) and the server is not already up and running.

Thank you for considering.

**Comment by Oreonan** [comment]
I believe that has been dealt with, right? CC @bear101
