### ISSUE TITLE
Feature request: Add feature for streaming current audio

### ISSUE THREAD

**Issue by adkurz** [BearWare/TeamTalk5#683]
Hello,
it would be a great feature to stream the current audio to a channel. With this audio, I don't mean a sound file, but the current audio from the sound card. For example, it would be a great enhancement for desktop streaming that it's possible to hear the audio from the shared desktop too.

**Comment by dingpengyu** [comment]
cc @Oreonan

**Comment by bear101** [comment]
Duplicate #413
