### ISSUE TITLE
It is suggested to add the function of sending a mandatory pop-up broadcast to the whole service.

### ISSUE THREAD

**Issue by olsen-zhang** [BearWare/TeamTalk5#685]
### This is set in order to allow users who have missed the normal broadcast to see the more important messages. The broadcast message will be displayed in the form of a pop-up dialog box, and there is a close button at the bottom of the message to close the message.

**Comment by bear101** [comment]
In my view the server should not be able to force behaviour in client applications. Whatever is configured in the client application should overrule what the server is posting.

**Comment by olsen-zhang** [comment]
It makes sense, the user-selectable is the most user-friendly.

**Comment by olsen-zhang** [comment]
It&nbsp;makes&nbsp;sense,&nbsp;the&nbsp;user-selectable&nbsp;is&nbsp;the&nbsp;most&nbsp;user-friendly.
------&nbsp;原始邮件&nbsp;------
发件人:&quot;Bjørn&amp;nbsp;Damstedt&amp;nbsp;Rasmussen&quot;<notifications@github.com&gt;;
发送时间:2020年12月26日(星期六)&nbsp;凌晨5:26
收件人:&quot;BearWare/TeamTalk5&quot;<TeamTalk5@noreply.github.com&gt;;
抄送人:&quot;olsen-zhang&quot;<745801160@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:Re:&nbsp;[BearWare/TeamTalk5]&nbsp;It&nbsp;is&nbsp;suggested&nbsp;to&nbsp;add&nbsp;the&nbsp;function&nbsp;of&nbsp;sending&nbsp;a&nbsp;mandatory&nbsp;pop-up&nbsp;broadcast&nbsp;to&nbsp;the&nbsp;whole&nbsp;service.&nbsp;(#685)



 
In my view the server should not be able to force behaviour in client applications. Whatever is configured in the client application should overrule what the server is posting.
 
&mdash;

**Comment by ChrisDuffley** [comment]
I would believe that, like we've done with private messages, that could be an option in the Display tab of Preferences which could be on by default.

Does that make more sense in this context?

Christopher Duffley
Host of Mission Possible Podcast: http://www.missionpossiblepodcast.com
Cell: +1 (603) 851-6971
