### ISSUE TITLE
Kick and ban users missing in mobile clients

### ISSUE THREAD

**Issue by bear101** [BearWare/TeamTalk5#69]

**Comment by beqabeqa473** [comment]
hi.

kick/ban actions were added on android. 

bjoern: please review, if something should be changed.

**Comment by bear101** [comment]
In relation to d5d8e005ad86ac0daffe953ddd7f54e37f990f25.

The way I thought of moving users in the iOS client was to make a menu-item (or accessible action) called "Select user for move operation". You can then do this on several users and each time add the user-IDs to a list. Then we you press a channel you will then have a menu-item saying "Move user here".

**Comment by bear101** [comment]
There should probably also be a cancel move operation to clear the list of user-IDs.

**Comment by beqabeqa473** [comment]
hi bjoern.

i added move users operation as you suggested.

please review if you can and tell if something should be changed/improved.

**Comment by bear101** [comment]
I've just tested the move operation and it works fine!

**Comment by beqabeqa473** [comment]
is something related to this issue else or it can be closed?

**Comment by bear101** [comment]
we can close it

**Comment by marksplace** [comment]
sorry unless i am missing some thing there are no Kick and ban   or move on  android

**Comment by marksplace** [comment]
move and Kick and ban

**Comment by beqabeqa473** [comment]
please read this topic from bginning to end.

On 6/6/16, marksplace <notifications@github.com> wrote:
> move and Kick and ban
>
> ---
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/BearWare/TeamTalk5/issues/69#issuecomment-223958387


-- 
with best regards beqa

**Comment by marksplace** [comment]
Hi sorry still not getting this i have TeamTalk on my tablet and s5 and there is no kick or move any where i have been thugh all menus and settings
also asked a friend who is on iPhone and still no move or kick am i missing some thing
Mark
Member of the accessible friends network 
www.tafn.org.uk

**Comment by bear101** [comment]
I added the ability to kick people also if channel-operator in this commit b798bd83bd600f0b48bd515f3576a6415f86c51b
