### ISSUE TITLE
WebRTC audio preprocessor

### ISSUE THREAD

**Issue by bear101** [BearWare/TeamTalk5#699]
C# API missing: everything
Clients: Put copyright notice for WebRTC

**Comment by beqabeqa473** [comment]
Hi bjoern.

Happy new year to you and all of our community.

could you please make a build for testing?

thanks.

On 12/31/20, Bjørn Damstedt Rasmussen <notifications@github.com> wrote:
> Java API missing: 'echocanceller' 'adaptivedigital'
> C# API missing: everything
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/BearWare/TeamTalk5/issues/699


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: beqaprogger@gmail.com
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by bear101** [comment]
http://www.bearware.dk/test/teamtalksdk/v5.7.0.5015/

Happy New Year to you too!
