### ISSUE TITLE
ability to join the hidden channel when on the server

### ISSUE THREAD

**Issue by zstanecic** [BearWare/TeamTalk5#708]
Currently in the latest beta, it is not possible to join the hidden channel when connected on the server. One who wants to connect needs to specify the channel in the server properties.
What i propose is to add the dialog box to join the channel by typing the known by user channel name. for now it is not possible.

**Comment by bear101** [comment]
I've added some additional information to the manual regarding hidden channels:

_Hidden channel

- Create a hidden channel that can only be seen by users with User Right [User can see hidden channels](@ref useraccountsdlg). Creating a hidden channel requires User Right [User can create/modify all channels](@ref useraccountsdlg). To join a hidden channel that cannot be seen use the Create Channel Dialog and type the name of the channel, its password and press OK. Ensure to be in the parent channel of the hidden channel while doing this.
- A hidden channel must be a sub channel with no other sub channels, i.e. a leaf node.
- Note that it is not possible to update an existing channel to a hidden channel, and vice versa._

**Comment by bear101** [comment]
@zstanecic did you manage to make it work?

**Comment by zstanecic** [comment]
Yes, but i still think as the administrator of the several teamtalk servers,

That this feature needs a small rewrite i.e there should be  a separate dialog for joining the chanel, and I should have an ability to transform normal channel to the hidden ones. 

If it cannot be done, it should bring up another error message, not this message about the server incompatibility.

Best,

Zvonimir
