### ISSUE TITLE
Failed to initialize video device on macOS

### ISSUE THREAD

**Issue by wemaus** [BearWare/TeamTalk5#711]
TeamTalk Vers. 5.7.0.5017 and 5.6.2 for Mac
Video will not be initialized on Mac Book and iMac with OS X "Big Sur". In Preferences it isn't possible to configure the (internal) video device properly.
All other Apps like FaceTime... working fine with the camera.
Is there any solution?
Thanks!

**Comment by bear101** [comment]
I can reproduce the issue. It seems the problem starter when I switched to Big Sur. I get some weird timestamps on video frames from webcams, so TT gets confused

**Comment by bear101** [comment]
Hm, I just updated to macOS 11.2 and now the video is working again.
In macOS 11.1 the timestamp on video frames were incorrect and therefore TT got confused and rejected the frames.

So workaround... upgrade to 11.2.

**Comment by bear101** [comment]
Hm, it seems the error is due to sleep-mode in macOS. When your Mac comes back from sleep then the video is not displayed. If you restart your Mac then the video will appear. I'll see if I can find a workaround.

**Comment by bear101** [comment]
@wemaus please try this version and see if it fixes the video issue: http://bearware.dk/beta/TeamTalk_v5.7.0.5025_Setup.pkg
