### ISSUE TITLE
TeamTalk 5.7 sounds are worse

### ISSUE THREAD

**Issue by pitermach** [BearWare/TeamTalk5#713]
The new sounds proposed in TeamTalk 5.7 are in my opinion  a downgrade. While I really like that we now have extra events for users logging in and out, the sounds to go with them could be better. The new sounds are much louder, don't blend with each other very well, and many of them have extra silence at the beginning (the voice activation on/off sounds are the most obvious)

If you want to overhaul the sounds, and I can definitely see why this is a good idea even before the new ones in 5.7, I'd like to propose an alternative set. A group friends and myself have created an alternative set of TeamTalk sounds a few months ago which is used by a number of people which you can find [at this link](https://currentlyuntitled.design/downloads/Majorly-G-TT5.zip). It doesn't include any sounds for users logging in and out because the pack was created before these were available, but if you want to include these in a future TeamTalk version we'd be happy to make a log in and log out sound in the same style.

**Comment by bear101** [comment]
I like them better. They are much better quality.

**Comment by Oreonan** [comment]
Personally I think this sounds are more longs, and less recognizables. I 
think some sounds of this pack are good to use (like question mode and 
hotkey) but not all.

**Comment by Oreonan** [comment]
maybe we can keep these sounds on hand and integrate in the future a 
sound pack system, we'll can include olders sounds, sound of 5.7 and 
this sounds and user can choose bitween all packs.

**Comment by beqabeqa473** [comment]
current sounds are too long for my opinion and connection lost sound
is very unpleasent.

i think these new sounds should be included as they are not so long
ands loud and they don't disturb while working.

On 1/11/21, Oreonan <notifications@github.com> wrote:
> maybe we can keep these sounds on hand and integrate in the future a
> sound pack system, we'll can include olders sounds, sound of 5.7 and
> this sounds and user can choose bitween all packs.
>
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/BearWare/TeamTalk5/issues/713#issuecomment-757544557


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: beqaprogger@gmail.com
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by pitermach** [comment]
I can see how the join and leave sounds I proposed might be a little long. I just trimmed them a bit to make them shorter, think these should work even better ☺️ 
[Uploading alternate_join_leave_sounds.zip…]()

**Comment by jeremyp3** [comment]
I like the new sounds installed in teamtalk 5.7. it is true that we could modify some of them, but the great majority are good. I think it's a matter of habit

**Comment by bear101** [comment]
@Oreonan should I remove the silence period from the sound files?

**Comment by Oreonan** [comment]
If you talk about new sounds currently includes in V5.7, I don't hear 
any silence period. But maybe we can found a litle silence with an audio 
editor, in this case yes you can remove this without problem :)

**Comment by bear101** [comment]
@Oreonan I've uploaded latest test-version v5.7.0.5023 and also SDKs

**Comment by Oreonan** [comment]
@bear101 We should also integrate sounds you have cut in mobile clients, right?

**Comment by bear101** [comment]
@Oreonan can we close this now?

**Comment by Oreonan** [comment]
If you agree I'll just include sounds without silence in mobile clients, 
and close it just after.

**Comment by bear101** [comment]
I can remove the silence.

**Comment by Oreonan** [comment]
OK, nice :), so you can do it and close it I think.
