### ISSUE TITLE
Add ability to move users to operator-controlled channels

### ISSUE THREAD

**Issue by Michael1972** [BearWare/TeamTalk5#716]
On servers, used for teaching-purpose, it would be good, if a channel-operator could move users from anywhere on the server to his own channel. So if I created or joined a channel and got operator-access with the help of an operator-password, I could go to the main-channel and pick up my technical-unexperienced students there and move them to my channel with the corresponding menu-command. Currently, moving users only is possible by setting the property in the user-accounts and works globally for the complete server instead of channel-dependent.

**Comment by bear101** [comment]
On public servers this feature would cause a lot of trouble. A channel
operator could take complete control of other channels.

You might as well use the existing user right to move users.

--
Kind regards

Bjørn Damstedt Rasmussen
www.bearware.dk
