### ISSUE TITLE
Optional sound when sent a channel or an user message

### ISSUE THREAD

**Issue by adns44** [BearWare/TeamTalk5#720]
Hi!

In TeamTalk 5.7 beta classic version there are new sounds that are very good, and as a new feature, TTS says when a private or channel message sent.

Can you add options to enable sound on channel and user message sent? Channel message sent sound was very good in earlier clients to detect lags in TCP connection, and easier to hear the message sent instead of TTS says it.

**Comment by Oreonan** [comment]
Hi,

I'm currently working on it. A checkbox will add soon, please wait a few 
moment :)
