### ISSUE TITLE
Load preferences file from user profile firstly instead from the teamtalk executable directory

### ISSUE THREAD

**Issue by Nardol** [BearWare/TeamTalk5#723]
Loading the TeamTalk preferences file from the user directory firstly could avoid overriding it when updating TeamTalk from an archive, in the case of the Debian version for example.
The archive contains a default ini file so we have to extract the archive selectively instead of simply extract and run when updating.
The actual behavior makes TeamTalk more portable by default but could make the update more risky.

**Comment by bear101** [comment]
I believe the current order of configuration file is more logical and
very useful for error handling. Many cannot find the user-profile directory.

Kind regards

Bjørn Damstedt Rasmussen
www.bearware.dk

**Comment by Nardol** [comment]
In this case, how about renaming the ini file provided in the downloaded archive?
In this situation the user profile file will be used when updating as there would not be any configuration file which already exist and the default ini file could be renamed if no preferences file could be loaded.
The actual behavior make the update more risky if the user does not extract the archive carefully.

**Comment by bear101** [comment]
The idea having the ini-file in the portable archive is that it comes with a working configuration. E.g. if it loads the profile ini-file then it will use the sounds in some other directory instead of those included with the portable archive.
