### ISSUE TITLE
Android client build problem

### ISSUE THREAD

**Issue by poretsky** [BearWare/TeamTalk5#725]
Build from master branch with test SDK v5.7.0.5015 fails. Error
messages like "dk/bearware/backend/TeamTalkService.java:652: error:
AudioPreprocessor() is not public in AudioPreprocessor; cannot be
accessed from outside package" hint that something is wrong with jar
library. How the problem should be overcome?

**Comment by bear101** [comment]
Please download this latest SDK: http://www.bearware.dk/test/teamtalksdk/v5.7.0.5018/
