### ISSUE TITLE
Audio/Video sync

### ISSUE THREAD

**Issue by wolme** [BearWare/TeamTalk5#727]
Have an issue with audio/video sync. At least 1-2 seconds latency.
Tested on german server and own server on different days.
What can I do ?

Regards Wolfram

**Comment by amirmahdifard** [comment]
haa? bear101? can you please close this, can't understand anything of that if you chek.

**Comment by amirmahdifard** [comment]
@bear101

**Comment by bear101** [comment]
It would be annoying to delay audio playback to sync with video.
