### ISSUE TITLE
clicking sound when enabling transmission

### ISSUE THREAD

**Issue by beqabeqa473** [BearWare/TeamTalk5#729]
i think starting with teamtalk5.5, when any of users in the channel is enabling transmission, even if voice activation is on, and at the same time ptt is used, some unpleasent clicking sound is appearing.

You can test it with subscribing to your own voice and quickly pressing push to talk key.

@bear101 do you have an idea why it is happening?

**Comment by bear101** [comment]
What client and OS?

**Comment by bear101** [comment]
I cannot reproduce the issue. I tried on Windows with Classic client.
