### ISSUE TITLE
Problems joining hidden channels as a non-admin

### ISSUE THREAD

**Issue by Simon818** [BearWare/TeamTalk5#733]
#### Method 1: From the Connect Dialog

Steps:

1. As an admin, create a hidden channel (I named mine "test" and gave it a password of "test")
2. Disconnect from the server (or bring up a second instance of TeamTalk)
3. Connect using a non-admin account, and fill in the "join channel" section with the new hidden channel.

When I press connect, I get a syntax error and am not joined to the channel.

#### method 2: Re-creating the channel as a non-admin

Steps:

1. As an admin, create a hidden channel (I named mine "test" and gave it a password of "test")
2. While the first instance is in this new channel, load a second instance.
3. Log in as a non-admin, but do not fill in the "join channel" section
4. On the non-admin instance, try to create the same channel with the same password.

For me, the creation process appears to work, and I join the new channel on the non-admin instance. My admin instance can see both users, but the non-admin can only see itself.

I can test this some more and maybe look behind the scenes to see if the channel ID is the same across both; just let me know if you need anything.

**Comment by bear101** [comment]
@Simon818 thanks for the thorough bug report. Do you use Debian 9 binary for server and Classic client? Then I can try and send you an updated version.

**Comment by Simon818** [comment]
Sorry if you get this twice; for some reason I can't reply via e-mail.

I'm using Debian 10 for the (pro) server and Windows 10 for the client. I'd definitely be interested in testing it.

**Comment by bear101** [comment]
@Simon818 please try these:
http://bearware.dk/beta/TeamTalkClassic_v5.7.0.5020_Portable.zip
http://bearware.dk/beta/teamtalkpro-v5.7.0.5020-debian9-x86_64.tgz

**Comment by bear101** [comment]
@Simon818 did you manage to test?

**Comment by Simon818** [comment]
Hi,

Sorry, I only managed to test this today; it's been a busy week. Unfortunately much the same thing happens with hidden channels, only this time when I try to log in with a non-admin account and enter the channel info in the connect window, I get an error that says "channel not found." Re-creating the channel as a non-admin will still show me as the only user in that channel, even if other users are there. The connect dialog method works fine if the account being used is an admin.

**Comment by Oreonan** [comment]
Hmmmm, for me it's working correctly now, server and client 5023.
