### ISSUE TITLE
URL Decode tt:// Links

### ISSUE THREAD

**Issue by Simon818** [BearWare/TeamTalk5#735]
In TeamTalk Classic and perhaps other versions, it's not possible to use encoded characters in a tt: URL, such as %20 for a space. If you pass the space through in the command-line parameters, it works; but that's not always possible. My suggestion for fixing this is to do a URL decode on the username, password, channel name, and channel password fields.

**Comment by ChrisDuffley** [comment]
Definitely agree with you on this, especially if you want to link to specific channels on websites or inside documents etc as it does not currently work pretty much anywhere at the moment. Just channels that have dashes or no spacing will work.

Christopher Duffley
Host of Mission Possible Podcast: http://www.missionpossiblepodcast.com
Cell: +1 (603) 851-6971

**Comment by StrikerDS** [comment]
I absolutely agree! I spent quite a few hours trying, to get PHP to decode and pass the information into the client with spaces in the username. Without spaces in the URL it logs in fine, but I've tried '%20' and '+'. But, with the PHP urldecode function its giving me a 403 Forbidden HTTP error with my test URL and in troubleshooting this error it says that Cookies passing login credentials may or may not resolve this issue depending on the hosted domain's server security settings. So, I'd really wouldn't want to pursue this further down this avenue (not being sure if it will work or not.)

**Comment by Oliver2213** [comment]
I too have encountered this issue, and second what @Simon818 said above. URL decoding those fields should fix this, as right now as far as I can tell it's impossible to construct URLs with special characters (specifically spaces for me) in any of the mentioned fields.

**Comment by bear101** [comment]
@tech10 Can you confirm it's working in v5.7.1.5032 ?

**Comment by tech10** [comment]
@bear101 This does seem to be working. I was able to successfully enter a server using a link with an encoded space as `%20` in my browser, but was also able to enter the space character directly without encoding it into the browser's address field. If anyone has any other ideas on how I can test this, I'm willing to do so.

**Comment by bear101** [comment]
Android and iOS beta clients have been submitted which also fixes the issue.
