### ISSUE TITLE
Possibility to use new Noise reduction

### ISSUE THREAD

**Issue by beqabeqa473** [BearWare/TeamTalk5#750]
hello bjoern.

did you think about this?
https://github.com/xiph/rnnoise

is it something that can be used in teamtalk, of course if there is better quality than it is now in teamtalk noise reduction?

**Comment by bear101** [comment]
It seems that WebRTC is already using rnnoise library when using AGC: https://webrtc.googlesource.com/src/+/refs/heads/master/modules/audio_processing/agc2/rnn_vad/BUILD.gn#39

Name: Recurrent neural network for audio noise reduction
Short Name: rnnoise
URL: https://github.com/xiph/rnnoise
Version: 91ef401
Date: Oct 10, 2017
Revision:
License: BSD 3-Clause
License File: COPYING
Security Critical: no
License Android Compatible:

Description:
RNNoise is a noise suppression library based on a recurrent neural network.
The library is used for speech processing in WebRTC.
