### ISSUE TITLE
ALSA is slow to start up initially

### ISSUE THREAD

**Issue by bear101** [BearWare/TeamTalk5#752]
When TT shared library loads it queries all sample rates on the available sound devices. This is, for some reason, very slow on ALSA.

This listed commit will make TT shared library load instantly but will only list one available sample rate. This means that echo cancellation cannot be used if input/output device doesn't support the same sample rate. However, the same sound device will most likely have the same sample rate for input/output device. At least I have never seen it's not the case.

I've also notice that on my Ubuntu 18 and Raspberry Pi the sound devices seems to be screwed up when sample rates are queried multiple times. This means that you constantly will have to reconfigured the sound device in preferences.

**Comment by bear101** [comment]
@Oreonan should I merge this to master?

**Comment by Oreonan** [comment]
Yes, I think it's a good idea.

Maybe we can add an alert if input and output devices haven't same 
samplerate?

**Comment by bear101** [comment]
@Oreonan echo cancellation checkbox will be disabled. That's the alert :)

**Comment by Oreonan** [comment]
Oh, yes, right, OK :)
