### ISSUE TITLE
I found a bug in TeamTalk 5.7

### ISSUE THREAD

**Issue by MuhammadGagah** [BearWare/TeamTalk5#754]
Hi, I'm using TeamTalkClassic_v5.7.0.5023 Portable, and found lots of bugs.
1. When I press control+shift+a to enable Voice Activation, the file "vox_me_enable.wav", and voiceact_on.wav played at the same time, unlike TeamTalk previous versions, where the sound is played alternately.
2. I press alt+control+t to allow transmit channel messages, but screen reader do not say can no longer transmit channel messages or can now transmit channel messages, but it's working, it's just that the screen reader doesn't say anything.
3. I try to enable Sound Event "Everyone in channel has stopped talking ", and choose the sound I want. But sometimes the sound I use played itself, this happens usually after someone login or logout to server.
4. Please add option "disable history login and logout", because for us screen reader users it's very annoying. We have a hard time reading channel message and broadcast message, because the login and logout are on the same buffer with chat history.

**Comment by Oreonan** [comment]
Hi,
1. Yes, we have changed sounds play mode, but I think we'll add an option to choose bitween older and newer behavior.
2. I've added a TTS event for this, go to preferences/text to speech events and activate checkbox for "channel messages transmission allowed"
3. Same answer like problem number one.
4. I let @bear101 respond to this, it's me who have added this on chat history to make same behavior bitween classic and QT, but we can also remove this if it's problematic, personaly I'm on server with small number users so I'm not disturb with this.

**Comment by jeremyp3** [comment]
for the hitem 4, rather than removing it, it could be configurable and not enabled by default. people who wish could activate it in preferences.

**Comment by MuhammadGagah** [comment]
Thanks @Oreonan
I think, the new sound is already very good, but just fix it a little.
Problem number 2 is resolved, but there seems to be an error with String translation, because the screen reader only reads checked / not checked.
![TT](https://user-images.githubusercontent.com/35881211/107461221-870c6380-6b94-11eb-8a3b-c862b03b14a5.png)

**Comment by Oreonan** [comment]
Which language are you using @MuhammadGagah ?

**Comment by Oreonan** [comment]
I've made PR #756 which add an option to disable users logs in/out display in chat history...
I think this will be merge as soon, so this option will be part of 5.7.

**Comment by MuhammadGagah** [comment]
> Which language are you using @MuhammadGagah ?

I am using language default, English.

**Comment by Oreonan** [comment]
@MuhammadGagah I've fixed the problem, fix will be integrate in next beta

**Comment by Oreonan** [comment]
- 1 and 3: An option has been added that allows you to choose your prefered playback mode for sound events
- 4: This option has been also added.
All new options will be presents in final version of course
