### ISSUE TITLE
no stereo in qt-teamtalk

### ISSUE THREAD

**Issue by jeremyp3** [BearWare/TeamTalk5#755]
since the commit on alsa (commit 1ff8bc4be7c85342c5ac5a6e1e8558df932329ca) we no longer have stereo in the teamtalk qt. it is true that alsa no longer has latency, but suddenly i hear people and mono streams
I tested with opus and the other codec.

**Comment by bear101** [comment]
I don't see why this commit would cause a limitation to mono.

--
Kind regards

Bjørn Damstedt Rasmussen
www.bearware.dk

**Comment by jeremyp3** [comment]
when i compile before i commit i am in stereo, and as soon as i compile after this commit i am in mono. I can't say more ...

**Comment by bear101** [comment]
I found the bug. Thanks for the input :)

--
Kind regards

Bjørn Damstedt Rasmussen
www.bearware.dk

**Comment by jeremyp3** [comment]
fixed. thanks !
