### ISSUE TITLE
Teamtalk classic cannot switch sound cards in some circumstances

### ISSUE THREAD

**Issue by burakyuksek** [BearWare/TeamTalk5#759]
I have a USB headset which I usually use as default sound card. Sometimes this headset stops working so I have to plug it out and plug it back in. When this happens, my voice stops getting transmitted and I cannot hear the other side. I have to restart Teamtalk Classic.

**Comment by MuhammadGagah** [comment]
yaps, same problem to me.

**Comment by ChrisDuffley** [comment]
This has been in Classic for a long time now. I hope this will be resolved soon.

**Comment by dingpengyu** [comment]
cc @bear101

**Comment by bear101** [comment]
Duplicate of #712
