### ISSUE TITLE
Server Config

### ISSUE THREAD

**Issue by Brotherred** [BearWare/TeamTalk5#763]
I have TeamTalk installed on Peppermint which is a another mod of Lubuntu and Mint. I have Team Talk server running but I can not seem to find my own server from and other PC or my phone.

I tried following instructions and put the daemon here `/etc/init.d/tt5server `

I do not have the daemon working so there is that issue, that I do not know much about. But also I can not find the server as I say. Lastly I wonder if the client can be run or installed in a more useful way on a desktop.

Regards

**Comment by bear101** [comment]
Hi, I would suggest you first make the TeamTalk server run in non-daemon before you start a more complicated setup.

**Comment by Brotherred** [comment]
I did not know that I had not set it as a daemon. That is why I mentioned the daemon. Your telling me about it pretty much all I know.

Regards.

**Comment by Brotherred** [comment]
I believe that I followed instructions.

"The TeamTalk server for Linux can run both in daemon mode and as a regular console application. A daemon script is also included which can be put in /etc/init.d."
