### ISSUE TITLE
Problem sound devices after connection lost in classic client

### ISSUE THREAD

**Issue by Oreonan** [BearWare/TeamTalk5#771]
In client classic, when connection is loast, when we are kicked, or also when we disconnect from a server and reconnect to another one, sound devices doesn't work.
To make sound system working again, we must have to change one of our devices in preferences, and after that switch again to previous one.
This issue is present after commit 6fe2783

**Comment by bear101** [comment]
Ah, these three lines should be removed:
https://github.com/BearWare/TeamTalk5/blob/de4d7981efe8960fa73f83e6374e8f419dcdfd2a/Client/TeamTalkClassic/TeamTalkDlg.cpp#L243

**Comment by Oreonan** [comment]
Do you want I make test and remove this in master if it's OK, or you do it?

**Comment by bear101** [comment]
Can you remove and test? I'm working on new jitter-buffer at the moment.

Kind regards

Bjørn Damstedt Rasmussen
www.bearware.dk
