### ISSUE TITLE
Support for OBS Virtual Camera (OBS Studio 26.x)

### ISSUE THREAD

**Issue by iEvgn** [BearWare/TeamTalk5#779]
Hello Bjorn,

Please add support for OBS Virtual Camera for TeamTalk 5.7.x windows version.
Currently in Zoom, Skype the OBS Virtual Camera is listed in sources and can be selected for output. In TeamTalk (in same time) OBS Virtual Camera is not listed in Video Capture > Video Capture Device.

P.S. Looks like in OBS 26.x the tool "Virtual Camera" is already built-in and there is no need to install it additionally from separate installer.

**Comment by bear101** [comment]
#584
