### ISSUE TITLE
Support for 16x9 high resolution cameras

### ISSUE THREAD

**Issue by iEvgn** [BearWare/TeamTalk5#780]
Hello Bjorn,

I've noticed that on MS Surface, MacBook (in BootCamp) built-in high resolution cameras not work with TeamTalk. For these cameras TeamTalk gives in RGB32/I420/YUY2 modes only one option for recognized video resolution - "Custom video format". If the "Custom video format" is the only listed mode and no other modes like 640x360 are recognized, TeamTalk shows on test "failed to initialize video device" but if with the same camera will be listed any other default modes (through ManyCam), same camera will work. Also noted that if press "Default" for non working camera and then "Test", camera will work. If press "Default", then "Ok", then icon "Enable video transmission", camera will not work.

Please add list of default resolutions 4:3, 16:9 (in addition to "Custom video format") for new unknown cameras

**Comment by bear101** [comment]
#584
