### ISSUE TITLE
when trying to change settings when connected on the server, team talk crashes

### ISSUE THREAD

**Issue by zstanecic** [BearWare/TeamTalk5#781]
steps to reproduce:
1. connect to the whatever server,
2. press f4 and try to change for example nickname or soundcard: microphone, imput device etc...
you will notice a crash of the client.
This is happening on the classic client, last version

**Comment by bear101** [comment]
is this still occurring in v5.7?

**Comment by zstanecic** [comment]
Yep, it’s occurring in 5.7

**Comment by bear101** [comment]
I cannot reproduce the issue.
