### ISSUE TITLE
Sound events for "mute all" in Classic client

### ISSUE THREAD

**Issue by bear101** [BearWare/TeamTalk5#782]
Second, we found there are no hint tones for open and recover mute all during our use. Could you please add hint tones for these two, just like the ones for open and close voice activated? Many people have no awareness when they keep mute all on during their use, especially visually impaired, for they can`t see, they use this software totally on hint tones.

@Oreonan maybe one you can easily do and have some sound files available.

**Comment by Oreonan** [comment]
Shoud I add this events only in classic? Or also in QT?
