### ISSUE TITLE
Probleme upload disk usage

### ISSUE THREAD

**Issue by math65** [BearWare/TeamTalk5#783]
Hi !

In my XML file, when I put 0 for the maximum disk size in the file upload, I get an error message. Shouldn't you put 0 to have unlimited disk usage?
The other parameters are done like this :)

**Comment by Oreonan** [comment]
Have you tried to put -1 instead of 0 in your config?

**Comment by math65** [comment]
Yes, don’t work ...

**Comment by ChrisDuffley** [comment]
What I'd do is 10 9's which equates to 10 TB of storage.

Hope this helps.

Christopher Duffley

Host of Mission Possible Podcast <http://www.missionpossiblepodcast.com/>

LINKS TO SUBSCRIBE:

iTunes <https://itunes.apple.com/us/podcast/mission-possible-christopher/id1103092109?mt=2> | Stitcher <http://www.stitcher.com/s?fid=88094&refid=stpr> | Google Play <https://goo.gl/app/playmusic?ibi=com.google.PlayMusic&isi=691797987&ius=googleplaymusic&link=https://play.google.com/music/m/Ik76dexklcprwnpuxbdr2s6bm3y?t=Mission_Possible_with_Christopher_Duffley> | Follow Podcast On TuneIn And Listen To Latest Episode <http://tunein.com/radio/Mission-Possible-With-Christopher-Duffley-p892505/>

LIKE/FOLLOW Me:

Facebook <http://facebook.com/christopherduffley> | Twitter <http://twitter.com/chrisduffley> | YouTube <http://youtube.com/christopherduffley> | Instagram <http://instagram.com/christopherduffley>

On Feb 26, 2021, at 07:35, math65 <notifications@github.com> wrote:


Yes, don’t work ...

**Comment by math65** [comment]
Yes, thank you, it’s work !

**Comment by bear101** [comment]
You have to put a number for bytes of file storage. If you use the setup Wizard then I believe you put in KBytes.
