### ISSUE TITLE
iOS 14.5 bug and informations TeamTalk.

### ISSUE THREAD

**Issue by ghost** [BearWare/TeamTalk5#790]
I use an apple device iPhone X with the last version of iOS 14.

How can we view the user's informations ?

When I use braille input to write a channel message, it doesn't work. Recalibration of points doesn't happen, just like writing.

When I'm on the cellular network and I'm disconnected when I lost network, the transmiting is inactive. Is it wanted?

**Comment by bear101** [comment]
In TeamTalk v5.8.3 build 3 which is currently begin beta-tested I've modified how the text message input is displayed. Does this fix the issue you're having with channel messaging?

https://testflight.apple.com/join/ZPILmexZ
