### ISSUE TITLE
Can't modify channel visibility

### ISSUE THREAD

**Issue by adns44** [BearWare/TeamTalk5#793]
Dear Development Team!

I use the latest 5.7.0.5024 classic client on my Windows 10 PC, and I host my own server on my Debian VPS in docker.

I can't update channels visibility. If I press SHIFT+f7, and try to change the hidden channel checkbox state, the client says:
"An unknown error occurred. Check that the action you
performed is supported by the server. This error is most
likely caused by an incompability issue between the server
and your client.Cannot apply hidden property to channel"
I got this error when I try to modify a visible channel or a hidden channel. I tried to modify a channel that created on earlier server version, and on a new channel.

**Comment by bear101** [comment]
You cannot change an existing channel into a hidden channel and vice versa.
