### ISSUE TITLE
Abuse of anonymous accounts

### ISSUE THREAD

**Issue by Nick6489** [BearWare/TeamTalk5#796]
Attached is a log demonstrating server activity from 2021-03-07 02:57:34.156923 to 2021-03-07 03:08:50.037995. It contains 2 MB worth of spam, from entry and exit spam, to constant single message typing into a channel, and media file spam (if it's logged). It is audible denial of service. The anonymous account was open, as this is a public TeamTalk server and TeamTalk has no overt sign-up process, other than Bear Web Login. ...We badly, badly need a method of combatting this, if it doesn't already exist.
[tt5spam.log](https://github.com/BearWare/TeamTalk5/files/6096539/tt5spam.log)

**Comment by bear101** [comment]
Have you tried to use "Abuse Prevension" in User Accounts dialog? Also limit logins per IP-address in Server Properties dialog?

**Comment by Nick6489** [comment]
@bear101 How would abuse prevention help? As I understand it, it limits maximum failed logons. In this case, the user is logging in, successfully, then logging out, at rapid intervals, many times per second. Or, he's joining a channel and leaving it many times per second. or, he's sending a single message many times per second. In old IRC terms, he would've been kicked and banned for flooding. As I understand it, TeamTalk is not equipped to handle a flood attack of *successful* commands.

**Comment by Nick6489** [comment]
> @bear101 How would abuse prevention help? As I understand it, it limits maximum failed logons. In this case, the user is logging in, successfully, then logging out, at rapid intervals, many times per second. Or, he's joining a channel and leaving it many times per second. or, he's sending a single message many times per second. In old IRC terms, he would've been kicked and banned for flooding. As I understand it, TeamTalk is not equipped to handle a flood attack of _successful_ commands.

...Oops! I think I didn't read properly what you were saying. No, I didn't know this feature existed. In any case, does a command, in the abuse prevention's case, mean logging in and out?

**Comment by bear101** [comment]
To prevent fast login/logout you should use Server Properties dialog where you can specify a timeout per IP-address

**Comment by Nick6489** [comment]
@bear101 Thank you! Although exactly how does the user timeout work, and what are the consequence's for violating it? I'm sorry if these are obvious questions, I'm not even sure where to find the documentation on running the actual server so I can read it.

**Comment by bear101** [comment]
The timeout is the duration before the same IP-address can try and log on again.

**Comment by bear101** [comment]
I'm closing this issue. I hope you managed to find some more features for combating spammers
