### ISSUE TITLE
Unable to Switch Audio Devices While logged In in 5.7 Builds on Classic

### ISSUE THREAD

**Issue by ChrisDuffley** [BearWare/TeamTalk5#801]
I don't know if anyone else has experienced this with TT5 Classic from 5.7 (5017 or so) onwards, but it appears that when I now switch devices, whether it's Windows Audio Session or DirectSound, neither of them will want to switch for me from one device to another after clicking OK. This affects both input and output devices. I don't know if it's the difference in sample rates or what, as mentioned in previous issues, but this bug is not found in 5.6.3. I have to be logged out of a server in order for it to work, otherwise TeamTalk will be unresponsive and I have to force close it.

**Comment by bear101** [comment]
Is this still an issue in v5.7 release?

**Comment by bear101** [comment]
Duplicate #809
