### ISSUE TITLE
Possibility to transfer the sound card signal

### ISSUE THREAD

**Issue by winman3000** [BearWare/TeamTalk5#802]
In some applications it is possible to send the audio signal of the sound card. Teamtalk should also offer this possibility. If possible it should be prevented that the participants hear themselves.

In addition, it should be possible to select which sound card is enabled for transmission.

**Comment by bear101** [comment]
Is this the same issue as #413?

**Comment by winman3000** [comment]
That seems to be similar, yes. But I am not 100% sure.

**Comment by bear101** [comment]
But you want to transmit what Windows is playing to your current channel in TeamTalk, right?

**Comment by winman3000** [comment]
@bear101:
> But you want to transmit what Windows is playing to your current channel in TeamTalk, right?

Right. Exactly what Zoom does with "Share audio", for example.
