### ISSUE TITLE
Unable to hear sound events in Teamtalk v5.7 in Windows7

### ISSUE THREAD

**Issue by Exink** [BearWare/TeamTalk5#804]
Hello,

I'm new to github and this is the first time I create a new issue, so hopefully I'm not doing things wrong. But without much ado ahead, I would like to report that my girlfriend has downloaded the update for Teamtalk, which corresponds to v5.7 running Windows 7.

However, she tells me that it's not possible to hear any sound event, such as when someone has joined to a channel or the private message notification. We've tried to fix this isue by checking the soundcards volume and setup as well as the checkboxes for the desired sound events, even we verified that all the sounds are placed in their appropriate folders.

However, she's still unable to hear any sound event like she did before.

I'll try to update TeamTalk to the latest version tomorrow, although I don't think it won't affect me since I'm using Windows 10. I'll keep you informed if something different happens.

I'm thinking this is about some sort of compatibility issue between TT and W7, but I'm not completely sure of that. Can someone tell us what we can do to solve out this please?

Thanks in advance!

**Comment by Oreonan** [comment]
Can you please try to change "playback mode" in sound events tab of preferences?

**Comment by Exink** [comment]
It seems that by changing the playback to one by one the issue is fixed, however I haven’t Heard of this new setting somewhere else, though I’m not a big fan of the beta versions.

Thanks for your help!

De: ***@***.***>
Enviado: jueves, 11 de marzo de 2021 12:24 a. m.
Para: ***@***.***>
CC: ***@***.***>; ***@***.***>
Asunto: Re: [BearWare/TeamTalk5] Unable to hear sound events in Teamtalk v5.7 in Windows7 (#804)


Can you please try to change "playback mode" in sound events tab of preferences?

**Comment by bear101** [comment]
@Oreonan should we change default playback mode to [PLAYBACKMODE_SYNC](https://github.com/BearWare/TeamTalk5/blob/36a760dafc3b53a98086f35d4852b53014c9d40a/Client/TeamTalkClassic/PlaySoundThread.h#L31)?

**Comment by Oreonan** [comment]
Yes, I think it would be better to avoid this kind of problem
