### ISSUE TITLE
TeamTalk5.7 Classic: issues when switching sound devices

### ISSUE THREAD

**Issue by beqabeqa473** [BearWare/TeamTalk5#809]
Helo all.

discovered a serious regression.

when trying to switch sound devices in classic client, when connected to the server, client freezes and then crashes.
but if somehow you switch device, it will be active only after client restart.

**Comment by bear101** [comment]
@beqabeqa473 This commit should fix it: 082f2d73c73fbf81740373443be0220c0bacf8af

**Comment by bear101** [comment]
Please check if the version fixes the problem: http://bearware.dk/beta/TeamTalkClassic_v5.7.1.5029_Portable.zip

**Comment by beqabeqa473** [comment]
Hello Bjoern.

Yes, issue doesn't persist in this build.

thanks.

On 3/24/21, Bjørn Damstedt Rasmussen ***@***.***> wrote:
> Please check if the version fixes the problem:
> http://bearware.dk/beta/TeamTalkClassic_v5.7.1.5029_Portable.zip
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/BearWare/TeamTalk5/issues/809#issuecomment-806069207


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili
