### ISSUE TITLE
Possibility to import and export XML file with client

### ISSUE THREAD

**Issue by adns44** [BearWare/TeamTalk5#816]
Hello!

If the TeamTalk Classic downloaded from the Windows Store, it doesn't store the settings in appdata, it uses a hidden location where users don't have privilege by default, so they can't access settings file for backup or move to a new computer.

Is it possible to add a function to client to import and export the XML file?

**Comment by bear101** [comment]
The issue is the same for AppStore and Google Play. If you want full access then use the standard Windows installer
