### ISSUE TITLE
Feature Request : LDAP auth support

### ISSUE THREAD

**Issue by xJMV** [BearWare/TeamTalk5#817]
Hi,

I am looking to officially use TeamTalk to facilitate certain communications over over our volunteer emergency communication network. TT5 is doing a good job so far and it is really appreciated by the ones who tested it.

Our biggest problem is the user management that needs to be done by hand with yet another password to remember. All other tools that we currently use had in common to allow LDAP auth. So we now have an LDAP server allowing users to use the same username and password all over the network and tools. Using one simple interface we can manage all aspects of a user profile for general access and then configure specific needs on a per software base (if the software do not support LDAP groups).

Having a simple LDAP auth mecanism would be awesome for many organizations. I see it that way:

1. User try to log in with its LDAP credentials (Username/Password)
2. The TT5 server ping the LDAP server to check if auth can be established (LDAP have mechanism to disable users so it need to be checked everytime (ex: pwdAccountLockedTime)). Anonymous login should still be accepted at that point if activated.
3. Once the LDAP server confirm the AUTH, TT5 add the user into the internal DB if it is not existing or not anonymous.
4. Allows connection and normal operation. Admins will then give permissions internally to users when required.
5. Admin username/password remains outside of LDAP so in case of outage, the TT5 server is not lost.

So, I am opening a request to add LDAP auth support.

**Comment by bear101** [comment]
Out of scope. Use BearWare.dk WebLogin for now.
