### ISSUE TITLE
Where is teamtalk5pro.lib? Is it's source code here?

### ISSUE THREAD

**Issue by technop** [BearWare/TeamTalk5#83]
I read a tag in dll's part:
"Place import library TeamTalk5.lib or TeamTalk5Pro.lib from TeamTalk 5 SDK here."
1) Where is this lib's source code?
2) can i change it's source?
3) TeamTalk5Pro.lib is not open source?
4) How can i compile that to an dll?
5) How can i link this DLL to the project easily?
6) Is this source package an full featured and with plugins source?

**Comment by bear101** [comment]
The TeamTalk SDK is not open source. You can download the SDKs here: http://bearware.dk/?page_id=419

**Comment by technop** [comment]
1) How can i make a dll for users of my team freely?
2) Is this system a spoof free?
3) Is this system without online license chekers?
What is limited in this free source?
(The TeamTalk 5 SDK downloads are trial versions which will expire after 30 days. To use the TeamTalk 5 SDKs in an end-user application you must purchase a license.)

**Comment by bear101** [comment]
You must purchase a TeamTalk SDK license if you want to develop your own application:
http://bearware.dk/?page_id=316

**Comment by technop** [comment]
Please answer to my questions

**Comment by technop** [comment]
Dont use bear !!

**Comment by technop** [comment]
Dont use bear
;)
