### ISSUE TITLE
5.7 can't install, dependencies "not available"

### ISSUE THREAD

**Issue by gjzs** [BearWare/TeamTalk5#832]
Here is the message I am receiving:
$ sudo apt install libqt5x11extras5 libqt5webenginewidgets5 \
> libqt5webenginecore5 libqt5quick5 libqt5widgets5 \
> libqt5multimedia5 libqt5gui5 libqt5webchannel5 \
> libqt5qml5 libqt5network5 libqt5xml5 libqt5core5a libasound2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libqt5webenginecore5 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Unable to locate package libqt5webenginewidgets5
E: Package 'libqt5webenginecore5' has no installation candidate

**Comment by bear101** [comment]
In TeamTalk v5.7 you can skip:

- libqt5webenginewidgets5
- libqt5webenginecore5
- libqt5quick5
- libqt5webchannel5
- libqt5qml5

I've updated the documentation.
