### ISSUE TITLE
Channels and users not saved on reboot

### ISSUE THREAD

**Issue by patrickdickey52761** [BearWare/TeamTalk5#835]
I set up TeamTalk on a virtual machine with 60GB of disk space. No problem there, except I didn't specify a disk quota, so we weren't able to upload files. We created about thirty users and eight channels on the server. The channels were all designated as permanent... Fast forward to today.

I decided to fix the XML file and set the disk quota. I went into the virtual machine and used nano to update the XML file that is referenced in the service (/etc/teamtalk/tt5srv.xml). The only change I made was to change the disk quota from 0 to 99999999 (as per an issue on their GitHub repository). I used sudo systemctl restart tt5srv.service and restarted it...

I'm the only user listed in the accounts, and the only channel that survived is the one I was in. And that's because I had reconnected to my last channel enabled. Everyone and everything is gone.

So, my questions are these:
1. What did I do wrong?
2. Earlier today, I clicked the "Save Server Configuration" option in the windows client. Did that not save it? Or did it save it somewhere else?
3. What do I have to do to make sure all our changes last through a restart of the server?

I just checked the XML file after clicking the Save Server Configuration and none of the users that I added are listed there. So, they aren't being saved--even with clicking the Save Server Configuration in the Windows Client.

Thanks, and have a great night. :)
Patrick.

**Comment by jeremyp3** [comment]
hello,
please check the permissions of your .xml file. it must be owned by the
same user as the teamtalk server so that it can write to it.

**Comment by Oreonan** [comment]
@bear101 maybe we can add a verification to check if xml have correct rights and add an alert if it's not the case. What do you think?

**Comment by bear101** [comment]
I guess the issue is related to #50.

If you edit the tt5srv.xml file then it's a good idea to run "xmllint tt5srv.xml" to see that you didn't do any mistakes.

**Comment by patrickdickey52761** [comment]
It ended up being a permissions issue. The problem is, I have the teamtalk:teamtalk user running the server and I placed the XML file in /etc/teamtalk. I thought I had added teamtalk to the root group so it could access it, but that didn't work. The workaround that I'm using is that I have the XML file and the log file in /home/teamtalk now. If I use chown and set the XML file to teamtalk in /etc/teamtalk, will it have access (directory permissions above won't block it, I mean)?

**Comment by tech10** [comment]
@patrickdickey52761  Adding a standard user to the root group is not a good idea. I wouldn't recommend doing this, it may provide your server with all sorts of vulnerable security problems that you wouldn't want.

To answer your question, if you're going to store your TeamTalk files in /etc/teamtalk and run the server as the teamtalk user and group, chown the /etc/teamtalk directory recursively so that it, and all files within it, are owned by teamtalk:teamtalk. This should work as well as storing them within the teamtalk users home directory.
