### ISSUE TITLE
Ability to choose sound events playback mode in QT client

### ISSUE THREAD

**Issue by CoBC** [BearWare/TeamTalk5#839]
We can currently choose sound events playback in classic client. We should add also this feature to QT client.

**Comment by CoBC** [comment]
@bear101 Do you have any idea on how to implement a queue for playing all sounds entirely using QSoundEffect?

**Comment by bear101** [comment]
Maybe the playingChanged() signal can be used: https://doc.qt.io/qt-6/qsoundeffect.html#playingChanged. I, however, don't know if the underlaying implementation guarantees that the file is fully played.

**Comment by CoBC** [comment]
Yes, I thought to the same idea, but in we have to refactor something because currently we can't use the QObject::connect() function in utilsound.cpp.

**Comment by amirmahdifard** [comment]
this is one reezen y i don't use sound events for qt client, at least if you can't add all at once,  please add one by one.
