### ISSUE TITLE
Distortion audio on Mac

### ISSUE THREAD

**Issue by math65** [BearWare/TeamTalk5#840]
Hello,

I notice audio distortion when talking to my Mac. My microphone is saturated whereas if I make a recording via Quicktime or any other application, I have no saturation. I don't understand why this only happens in Teamtalk.

Kind regard,

Mathieu

**Comment by bear101** [comment]
What is your microphone level? It should be 50 to be unprocessed. Also try disabling AGC in preferences.

**Comment by math65** [comment]
It is at 50, and all TeamTalk enhancement effects are disabled ... I don't understand why this is happening ...

**Comment by tech10** [comment]
I have had some luck with setting my input device bitrate to 48000KHZ in the Audio Middy Setup Utility. Also, take a look at #292 which was open about 4 years ago, I explain what I've noticed about this here.

It does seem to only be present in TeamTalk compared to other applications. I don't know why, but TeamTalk does seem to do things a bit more inefficiently with audio processing than other applications do. Hopefully, setting your bitrate will help.

Also, in your sound preferences, check your microphone's audio level in the input tab. Try turning it down some. If you can, turn off any noise reduction or audio effect processing as well, not just in TeamTalk, but within the operating system itself.

**Comment by bear101** [comment]
Duplicate #292
