### ISSUE TITLE
An option to sort the username alphabetically or by latest update

### ISSUE THREAD

**Issue by Ramon-Salazar** [BearWare/TeamTalk5#845]
Hi @bear101

please add an option to choose the username sorting to either alphabettically or by latest update.

Some people like me for example don't prefer alphabetically, instead by latest changes so that'll be cool if there is an option to change sorting.

In this way that'll be easier to know if some accounts changed and so on in the server.

**Comment by bear101** [comment]
#654

**Comment by Ramon-Salazar** [comment]
Hello

I guess this has nothing to do with the server version, cause when I reverted back to earlier versions I can get the list by latest changes, while the newer versions the list is by alphabetticlly.
