### ISSUE TITLE
Failure to sort channels in latest version

### ISSUE THREAD

**Issue by emrerencber** [BearWare/TeamTalk5#846]
Hello there. I'm using Teamtalk 5.7. When I try to move a channel above other channels, I add a space in front of the channel name, but TeamTalk removes the space. Therefore, I cannot change the location of channels. Thank you.

**Comment by bear101** [comment]
#654

**Comment by bear101** [comment]
It is on purpose that the client applications remove spaces and tabs in channel names. Spaces and tabs often cause problems. I suggest you use _ or 1, 2, 3 as prefix.
