### ISSUE TITLE
Problem with sound events

### ISSUE THREAD

**Issue by amirmahdifard0** [BearWare/TeamTalk5#861]
When we go to the teamtalk settings and click on the tab sound events, in this section we can no longer hear the sound of that option by unchecking any of these options. It is good when we want to uncheck an option, but if we want to uncheck that option again, it will be a headache and we will have to add the corresponding sound to the folder again. This is bad for two reasons. 1: It is very painful and time consuming. 2: The user is more likely to save the sound associated with each option by mistake. It is not better to set it so that, like the other parts, the one-click mark will remove the option and click again, the mark will be added again.

**Comment by bear101** [comment]
Please state client, platform and version.

**Comment by amirmahdifard0** [comment]
teamtalk5 Classic Client for accessibility

Version: 5.7

 Windows platform.
