### ISSUE TITLE
Implement reload or SIGHUP for Teamtalk server

### ISSUE THREAD

**Issue by Nardol** [BearWare/TeamTalk5#864]
To configure log rotate, the `reload` operation has to be performed to avoid restarting the service and interrupt eventual conference.
Could it be possible to make the Teamtalk server catch sigup or to add a command line parameter to reload the configuration of the running instance?

**Comment by adns44** [comment]
Hi @Nardol, I have a working logrotate config for this problem. It works when TT5SRV runs on the host system or in Docker (in second case the logrotate runs on host system and the entire tt5srv folder mounted as a volume).

```
/var/log/tt5srv/tt5srv.log
{
daily
missingok
rotate 360
delaycompress
notifempty
copytruncate
create 640 tt5srv tt5srv
}

```

Create a file in /etc/logrotate.d/tt5srv. Every midnight it creates the new file, rotates others and cleans up the tt5srv.log file. Do not forget to create an user and a group with tt5srv or change the config.

You can try the config after the copy with the logrotate -d /etc/logrotate.d/tt5srv command.
