### ISSUE TITLE
5.7.1 Classic: Queue Position is Lost in Half-duplex Channels

### ISSUE THREAD

**Issue by Simon818** [BearWare/TeamTalk5#868]
It seems that when more than one person is in a half-duplex channel, and one person starts talking, the queue position is almost instantly lost. The longest I was able to transmit in my testing was around 1 second of audio.

One thing I notice is that when I transmit in any channel, there's a small burst of audio, followed by silence, followed by constant audio. i'm not sure what changed in the audio system, but this strikes me as something which might be related. Also, as I'll mention in another issue, the sound system changes are still not saving on my system--in fact, now I just can't adjust them at all, so I can't tell whether this happens with other settings. However, iv'e reproduced it between myself (on more than one device) and others.

**Comment by Simon818** [comment]
Thanks to a 5.8 beta build referenced in #869, I can now confirm that this only happens for me if sound events are set to play all at once. I couldn't remember which setting I had before, and wasn't able to set preferences in 5.7.1. Now, while connected to a server, I can switch between both and witness the transmit delay when I set the option to "all at once."

**Comment by Oreonan** [comment]
Yes, another user has also reported this delay when "all at once" 
playback mode is selected. This also appears when you play a mediafile 
locally using CTRL+S dialog, but it's probably logical because "all at 
once" playback mode use the same feature of playing a mediafile locally.

@bear101 do you think it's something we can fix? It's probably due to a 
buffer that create a delay, right?

**Comment by bear101** [comment]
@Oreonan So when we use TT_InitLocalPlayback() there's a longer delay before initial playback compared to PlayWaveFile() ?

**Comment by bear101** [comment]
TeamTalk v5.8.0.5039 has improved latency so this should no longer be an issue:
http://bearware.dk/beta/TeamTalk_v5.8.0.5039_Setup.exe
Reopen if it's still an issue.
