### ISSUE TITLE
qt-TeamTalk: Currently it is not possible to use shortcuts to hide the main interface

### ISSUE THREAD

**Issue by xingkong0113** [BearWare/TeamTalk5#876]
Problem description：
Currently, when using qt-TeamTalk, you cannot use shortcuts to hide the main interface.
I have used TeamTalk5.exe
and
TeamTalk5Classic.exe
Did the test.
In TeamTalk 5 Classic/Shortcut settings there is this setting item:Minimize/restore
After setting this shortcut, you can hide and display the main screen of TeamTalk.
Minimize/restore in qt-TeamTalk: is not available.
Solution:
It is recommended to port the Minimize/restore shortcut function to qt-TeamTalk

**Comment by bear101** [comment]
WINKEY + DOWN ARROW
