### ISSUE TITLE
Hotkeys are not available in the 64-bit version of QT-TeamTalk

### ISSUE THREAD

**Issue by hejiadong0608** [BearWare/TeamTalk5#877]
System version: Windows 10 Professional 10.0.19043.964
In the 64-bit version of QT-TeamTalk, the hotkeys set in the preferences are not available. 32-bit version does not have this problem.

**Comment by Oreonan** [comment]
Yes, I confirm this. It's only present on Windows, Linux don't have this issue.

**Comment by bear101** [comment]
What hotkeys are not working? PTT works with 64-bit Windows 10 on my PC. So does the hotkeys configured in Preferences -> Shortcuts.

**Comment by bear101** [comment]
Is it the "Show/restore window" feature that is available in the Classic client but not in Qt Client?

**Comment by Oreonan** [comment]
Not exactly, this is one problem, but problem describe here is that all 
shortcuts configured in shortcuts tab in preferences doesn't work. For 
example here I configured a shortcut to toggle voice transmission, but 
when I pressed it client do nothing.

**Comment by Oreonan** [comment]
However it's working in the beta you created this morning, but it's a 32 
bits version apparently.

**Comment by bear101** [comment]
@Oreonan I've just tested in 64-bit Qt and here the shortcuts for volume up and voice activation are working. Also when application is not "active window".

**Comment by Oreonan** [comment]
I tested again on my computer just now and it's still not working. What 
version are you used to test this?

**Comment by bear101** [comment]
I use v5.7.1 64-bit on Windows. I use F12 for voice activation.

**Comment by Oreonan** [comment]
Ah yes, it's working with F12. My initial shortcut is CTRL+Alt+Shift+A, 
and it's not working.

**Comment by Oreonan** [comment]
@bear101 do you think this is a Qt issue? Or it could be due to some type of conversion?

**Comment by bear101** [comment]
Hm, I really have no clue. Hotkey events from Shortcuts-tab should work the same as PTT.

**Comment by Oreonan** [comment]
Just tested now, and the shortcut for PTT is also not working on 64 bits Qt.
