### ISSUE TITLE
Conference recordings: streamed media are not recorded as well

### ISSUE THREAD

**Issue by winman3000** [BearWare/TeamTalk5#887]
If media files are streamed in a recorded conference, they are currently not recorded as well. If this behavior is by design, there should be an option to record the streamed content. I can imagine that it is difficult to implement this for audiovisual media such as videos. Here (if possible) only the audio should be recorded. It also doesn't make sense for recordings with separate files. In this case the option should not be available.

**Comment by ChrisDuffley** [comment]
I would not suggest removing the multitrack recordings. However, if there was an option where it would not make a new file every time voice activation or push-to-talk was disabled, that would be hugely appreciated.

I do agree with mixing in the media file stream as an option.

Christopher Duffley
Host of Mission Possible Podcast: http://www.missionpossiblepodcast.com
Cell: +1 (603) 851-6971

**Comment by bear101** [comment]
@winman3000 TeamTalk v5.8 can record both voice and media files. Please try the latest beta.
