### ISSUE TITLE
Android: support for Push-to-talk button

### ISSUE THREAD

**Issue by winman3000** [BearWare/TeamTalk5#890]
There are Android phones that have a "real" hardware Push-To-Talk buttons. Unfortunately, it is currently not possible to define a Push-To-Talk key with TeamTalk. It would be nice if this would be possible soon.

**Comment by bear101** [comment]
@beqabeqa473 Does your media button changes also fix this issue?

**Comment by beqabeqa473** [comment]
I don't know such phones, if they behave as media buttons, then yes,
in other case, it is needed to catch keyevents i think in onKeyDown
method

On 1/16/22, Bjørn Damstedt Rasmussen ***@***.***> wrote:
> @beqabeqa473 Does your media button changes also fix this issue?
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/BearWare/TeamTalk5/issues/890#issuecomment-1013878508
> You are receiving this because you were mentioned.
>
> Message ID: ***@***.***>


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by winman3000** [comment]
There are some Android devices that work similar to radios. If it helps, I can find some models and list them here.

**Comment by bear101** [comment]
I'll close this issue since we don't have such hardware. If you're willing to sponsor the devices then reopen the issue.

**Comment by winman3000** [comment]
Couldn't this be done so that a Push-To-Talk key can be assigned itself? The key press is then sent to TeamTalk and assigned as a key combination. When the key is then pressed, the microphone channel is opened, when the key is released, the microphone channel is closed again.
