### ISSUE TITLE
Include TeamTalk5.ini in Portable archive

### ISSUE THREAD

**Issue by bear101** [BearWare/TeamTalk5#895]
Include this file in TeamTalk Portable: https://github.com/BearWare/TeamTalk5/blob/master/Setup/Client/Windows/TeamTalk5.ini
Same way as for TeamTalkClassic.xml

**Comment by bear101** [comment]
@Oreonan I guess your latest changes obsoletes this issue?

**Comment by Oreonan** [comment]
I think TeamTalk5.ini.default should be include to allow "Reset to 
default settings". But TeamTalk5.ini doesn't have to be include.
