### ISSUE TITLE
[iOS] Korean language translation is not applied completely

### ISSUE THREAD

**Issue by ungjinPark** [BearWare/TeamTalk5#907]
Hi, I'm Ungjin Park who translated the TeamTalk Android English version to Korean. Before talking about an issue, Thanks for applying our Korean translation to Android TeamTalk very well. And, I'm not to good at English, please understand.

I wrote this issue thread because we found an issue from iOS TeamTalk recently. 

Last 26 March, My colleague, @ajackpot uploaded a Pull-Request for iOS, Windows classic client and it's accepted to merged by @bear101. We were happy we got a TeamTalk Android that's very cool translated to Korean, and the iOS version was released to us finally, too.

At the 5.7 version of the iOS TeamTalk, We saw our translation has applied. By the way, It's not applied completely. 

the not translated strings were shown all over the place. But, We sure remember we translated all it working manual typing ​and we sure we saved it completely and then we sent the Merge Request. 

the link of request record is [here](https://github.com/BearWare/TeamTalk5/pull/811#issue-600852519).

Would you review with me what issue occured?

Kind Regard,

**Comment by Oreonan** [comment]
Can you provide an example of not translated string?

**Comment by ungjinPark** [comment]
The most strings have not translated.

Screenshots ​her
![1621792907687-1](https://user-images.githubusercontent.com/58059043/119271478-b3785700-bc3c-11eb-9623-684bae72e7a5.jpg)
![1621792907687-0](https://user-images.githubusercontent.com/58059043/119271482-b4a98400-bc3c-11eb-9f0a-0f3f2cdfa654.jpg)

**Comment by bear101** [comment]
I solved the issue. The Localizable.strings file was not specified in the Xcode project.
