### ISSUE TITLE
Problem with Espeak tts on android

### ISSUE THREAD

**Issue by amirramezani79** [BearWare/TeamTalk5#934]
There is a problem with espeak tts on android in teamtalk5.8.
Espeak tts is installed but it's not listed in tts engines.
almost all of the iranian use espeak tts for reading persian language.
so please fix the problem for this TTS.
thank you.
i don't know about other tts engines, i only have espeak installed on my android device.

**Comment by Oreonan** [comment]
I reproduce this. I have Google TTS, Vocalizer, eSpeak and Acapela TTS installed but none of them are listed in TT preferences.

**Comment by beqabeqa473** [comment]
they are listed.

a problem is that they are not initialized on startup.
try to connect to server and then select tts engine

On 6/10/21, Oreonan ***@***.***> wrote:
> I reproduce this. I have Google TTS, Vocalizer, eSpeak and Acapela TTS
> installed but none of them are listed in TT preferences.
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/BearWare/TeamTalk5/issues/934#issuecomment-858401429


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by Oreonan** [comment]
Ah yes, exactly. All engines are listed when connected...

**Comment by bear101** [comment]
@beqabeqa473 Is this part of the commit you did recently? Can you add the changes to ChangeLog.txt in project root?

**Comment by beqabeqa473** [comment]
fixed in #a3b51d73cc33c52d0064f243b174c181db42c994
