### ISSUE TITLE
Separate rights for server and channel kick/ban

### ISSUE THREAD

**Issue by amirmahdifard0** [BearWare/TeamTalk5#937]
Please add two options to the user access section. There are currently two options called user can kick users from server. If this option is enabled, the user can kick other users from both the channel and the server. And the second option user can ban users from server. If this option is enabled, the user can ban users from both the channel and the server. Please add user can kick users from channel and user can ban users from channel to this section. Because maybe I want to access my target user in such a way that he can kick or ban other people from the channel, but he can not kick or ban them from the server. This feature is especially suitable for when we have a robot on the server and if the user kicks it from the server, we have to do a lot of gold to bring that robot to the server. Anyway, this is very useful and I hope 5.8.0 will be added in the stable version.

Windows platform

classic client for accessibility

5.8.0 beta

**Comment by Oreonan** [comment]
To make easier work on issues, please choose a title more explicit for your next issues. I think a title should explain a litle bit what happened (in case of a bug) or what you want (in case of a feature request). I've renamed this issue. Thanks.

**Comment by bear101** [comment]
If a user should only be allowed to kick/ban from a channel then you should use the channel operator feature. When you're channel operator of one or more channels then you can kick/ban from these channels.
The kick/ban from "User Accounts" dialog applies to server and all channels.
