### ISSUE TITLE
unable to use operator password

### ISSUE THREAD

**Issue by webczat** [BearWare/TeamTalk5#94]
Hello.
I am using teamtalk 5 classic.
I am unable to use the operator password. It can be set, but I cannot use it, like pressing the op item in the users menu gives command not authorized instead of asking for a password.
Verified that it works in qt client version.

**Comment by bear101** [comment]
Ready, not pushed

**Comment by bear101** [comment]
Fixed in 0ebf35218ac4ef4a1c4c0b37cad421e74eb37fe6
