### ISSUE TITLE
A very bad and annoying breakdown in 5.8

### ISSUE THREAD

**Issue by amirmahdifard0** [BearWare/TeamTalk5#943]
When we log in to the server and join one of the channels, sometimes the program does not respond and closes. And even when we enter a channel, every few seconds, the program crashes and we hear bad sounds. For example, if someone says hello we hear it hello llo llo llo llo llo llo llo llo llo llo llo. I do not know if this is a problem with my system or the program, but I did not have this problem in version 5.7.1.

Windows platform
classic client for accessibility. This bug has rendered version 5.8 unusable for me. I hope this problem is fixed because one of the bugs I reported is fixed in version 5.8 and I would love to use it. For now, hoping that you fix these bugs in a new build and I update the program to that version, I will not go back to version 5.7.1 to have to re-configure the program and with the bugs in version 5 8. I had resolved to grapple again.

**Comment by jeremyp3** [comment]
Hello.

have you tried the qt client? accessibility is very good now.

**Comment by bear101** [comment]
I cannot reproduce this issue on my PC. Please provide a way to reproduce this issue and then reopen the issue.
