### ISSUE TITLE
The moov users option is in the wrong place

### ISSUE THREAD

**Issue by amirmahdifard0** [BearWare/TeamTalk5#949]
The ability to move users between channels can only be done from the shortcut key trick and can not be done from the option trick because the option is in the wrong place. For example, I want to move 5 users to a new channel. I open the context menu on the names of all people and select the stor for moov option from the advanced submenu, and then open the context menu on the desired channel, but I do not find the moov users option because this option is wrong instead of Channel menu is located in the users menu, so I have to use only shortcut keys to do this. Someone may want to do this from the options section. Creating shortcuts for a feature is logical provided that the user can access and use the option as well, unless the program intends to hide that option, which here was not your goal. You have placed the option in the wrong place which makes it impossible to use, which I will report this bug for you to fix. Contrary to what I have long explained, the solution to this problem is very simple. Move the moov users option from the users menu to the channel menu so that the user selects all the users selected for moov to the desired channel by selecting this option.

Windows platform

classic client for accessibility

5.8

**Comment by amirmahdifard0** [comment]
pleas fix this issue. thanks

**Comment by bear101** [comment]
I think it creates more confusion to have "Move User" in Channels-menu. The "Store for Move" and "Move User" are tightly connected.

**Comment by amirmahdifard0** [comment]
But in this case, no one can use it. This does not make sense. Please open this.

**Comment by Oreonan** [comment]
You can move an user using the CTRL+Alt+V shortcut or the menu bar. I don't really understand the issue in this case.
