### ISSUE TITLE
Implement Shift+F10 for context menus

### ISSUE THREAD

**Issue by Nardol** [BearWare/TeamTalk5#954]
Hello,

Some keyboards have no "application" key so it is not possible to use context menus using keyboard.
Shift+F10 is an often used keyboard shortcut as an alternative to the Application key.

**Comment by Oreonan** [comment]
Probably a Qt issue, fixed in Qt5.6 for Windows:
https://bugreports.qt.io/browse/QTBUG-40085
I found nothing for Linux.

**Comment by Oreonan** [comment]
Following comments from Qt devs on my bug report, X11 provide a way to make this configurable:
xmodmap -e 'keycode 76 = F10 Menu'

**Comment by Nardol** [comment]
It works for Teamtalk, but not for all applications it worked before.

Look like they provided a solution which causes a big regression ;)

**Comment by bear101** [comment]
I'll close this issue since it's related to the UI framework
