### ISSUE TITLE
Suggest for new feature for TeamTalk

### ISSUE THREAD

**Issue by aimanlinux180203** [BearWare/TeamTalk5#956]
Hi. I'm verry interesting for the 5.8 update but I have some
suggestion like can you add more category of user account such as
default, disabled, administrater and master. The benefit for master
can look any administrater account go interseption to any user. This
feature can prevent the administrater account wrong to use any feature
to disturb any user privacy. This  feature can make user mor
confertable at any server. Next, I would like to suggest to you for
give this feature to master account like the master can block any
benefit from administrater account. I hope you can understanding what
I have explain to you. I hope this suggestion can help this aplication
more better than now. Thank you.

**Comment by bear101** [comment]
The only reason to log in as administrator is either to be able to create user accounts or intercept streams. So basically there's no reason to be logged in as administrator once you've finished one of these two tasks.
