### ISSUE TITLE
TeamTalk not showing user count on anonymous servers

### ISSUE THREAD

**Issue by KevGP** [BearWare/TeamTalk5#959]
Hi,

I have a server, and when I'm not logged in (using an anonymous account), I cannot see who's in what channel because they all say 0 users, at least in the channel list.

I'm using the Classic TeamTalk client for accessibility, if that helps.

Can you please investigate?

thanks!

**Comment by bear101** [comment]
If you're not logged in you cannot see users and channels.
Alternatively check that you have user-right: "User can see all users".
