### ISSUE TITLE
iOS TeamTalk crashes if it cannot reach the public server list on BearWare.dk, regardless of whether "show public servers" is checked.

### ISSUE THREAD

**Issue by Simon818** [BearWare/TeamTalk5#975]
This means that if bearware.dk is down or unreachable for any reason, TeamTalk will not load. Specifically, the interface appears for one or two seconds and then becomes unresponsive and eventually crashes.

**Comment by ctoth** [comment]
Experiencing this same issue.

**Comment by bear101** [comment]
When I test the TeamTalk client doesn't crash but becomes unresponsive for quite some time. If you wait a minute or so it resumes again.

Does your TeamTalk client restart?

**Comment by Simon818** [comment]
I wasn't able to get a response from it at all, even if I waited. So eventually I pressed the home button, whereupon iOS told me the app had crashed (which it does if you're running a beta build.) It's possible iOS considers an unresponsive app to have crashed though, and maybe fixing the responsiveness in whatever way you think is best would also fix the crash.

**Comment by bear101** [comment]
probably related to this issue https://stackoverflow.com/questions/16579297/sendsynchronousrequest-crashes-on-slow-net-connection

**Comment by bear101** [comment]
Can you confirm if the crash issue is fixed in v5.9 Build 3?

**Comment by bear101** [comment]
[TestFlight link](https://github.com/BearWare/TeamTalk5/wiki/TeamTalk-BETA-Testing)
