### ISSUE TITLE
Ability to disable logging messages

### ISSUE THREAD

**Issue by webczat** [BearWare/TeamTalk5#98]
I would kindly request you to add a server configuration parameter that would allow disabling private and/or public message logging on a teamtalk server if basic level of privacy is required.

**Comment by bear101** [comment]
Logging is a configurable option in the server. The server administrator should decide if logging is enabled/disabled. Not the clients...

**Comment by webczat** [comment]
My request is an ability for administrators of servers to disable
private chat logging, but leave public message logging enabled. It would
be doable from the wizard, for example.

**Comment by bear101** [comment]
There's not a user-right to enable/disable ability to send text messages. At the moment there's four types of text messages so it would add quite a few more options in the user account dialog.
If more request the feature then I can reopen the issue.
