### ISSUE TITLE
memory problem

### ISSUE THREAD

**Issue by kirill-jjj** [BearWare/TeamTalk5#984]
hi, i am Experiencing memory leaking problem on tt5server, for example, my systemd unit status, Memory: 1.3M but when i wait something about 3 days, it allredy 596 mb, can you try solv the problem?

**Comment by bear101** [comment]
On the two public servers I haven't noticed any increase in memory usage.

**Comment by bear101** [comment]
What is the output of "ps aux | grep tt5srv"?
