### ISSUE TITLE
when connecting to the new teamtalk, client crashes

### ISSUE THREAD

**Issue by zstanecic** [BearWare/TeamTalk5#986]
Try to connect to any new server 5.8.5045 instance with the new client.
It crashes.

**Comment by bear101** [comment]
I've fixed the issue. It will be available in a BETA2.

**Comment by bear101** [comment]
@zstanecic Can you confirm the crash issue is gone using this version: http://bearware.dk/beta/TeamTalk_v5.8.1.5046_Setup.exe

**Comment by zstanecic** [comment]
Fixed in this version! Thanks!
