### ISSUE TITLE
Proposition: Sort user accounds by date

### ISSUE THREAD

**Issue by NightPurrer** [BearWare/TeamTalk5#989]
In the newest beta appears the possibility to check the last user accound modification date.
For me option to sorting the accounds by modification date will be also wery good think.
If you have few administrators on the server with this option you can faster check which user accound was recently changed.

**Comment by ZDSRInternational** [comment]
I agree. I am an admin of a moderately large TT server and I find it cumbersome to locate user accounts.

**Comment by bear101** [comment]
In TeamTalk v5.8.1 the Qt client has an option to sort by modification date.
