### ISSUE TITLE
Add ability to disable any kind of interception subscriptions per server

### ISSUE THREAD

**Issue by webczat** [BearWare/TeamTalk5#99]
Because at least for some people ability to intercept messages or audio (or other things) from other user is a serious privacy violation, I would like to ask you to add configuration parameters that can completely disable this feature if someone has privacy concerns about it.

**Comment by bear101** [comment]
If you want privacy then you should run your own server and configure it the way you like it.

**Comment by webczat** [comment]
I am just requesting the ability to configure the server so that
interception is not allowed. It is probably not possible, is it?

**Comment by bear101** [comment]
If you don't create administrator accounts then it's not possible to intercept data streams. Only administrators can intercept data.
