### ISSUE TITLE
Qt client: Support Room name as variable in join/leave channel TTS events

### ISSUE THREAD

**Issue by schulle4u** [BearWare/TeamTalk5#992]
Currently the Qt client uses the string "%1 joined/left channel (+ optional channel name)" to report when a user joins or leaves. This however causes gramatical issues in languages such as german. Can you add another event string which gives the possibility to use room name as vaariable? E. g. "%1 joined channel %2"?

**Comment by Oreonan** [comment]
Hmmm, lot of translations has been already updated for the 5.8.1 version...
@bear101 should I make this change now, or wait the next version.
